<div>
    <header>
        <h1>Bienvenido a Encuestas</h1>
    </header>
    <hr />
    <div>
        <ul class="list-buttons-vertical">
            <li>
                <a class="mebutton mebutton-green mebutton-md" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"home","action"=>"login"),null,true) ?>">
                    <span class="fa fa-sign-in"></span>  Login
                </a>
            </li>
            <li>
                <a class="mebutton mebutton-red mebutton-md" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"home","action"=>"require"),null,true) ?>">
                    <i class="fa fa-check"></i>  Responder Encuesta
                </a>
            </li>
            <li>
                <a class="mebutton mebutton-black mebutton-md" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"home","action"=>"results"),null,true) ?>">
                    <i class="fa fa-search"></i>  Resultados de Encuesta
                </a>
            </li>
            <li>
                <a class="mebutton mebutton-blue mebutton-md" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"home","action"=>"join"),null,true) ?>">
                    <i class="fa fa-group"></i>  Unirse
                </a> 
            </li>
        </ul>
    </div>
</div>