<?php
    $loginResultMessages = $this->loginResultMessages;
    $loginErrorMessages = $this->loginErrorMessages;
?>
<script src="<?php echo $this->baseUrl() ?>/public/lib/cryptojs/rollups/sha1.js"></script>
<div id="loginbox">            
    <form id="loginform" class="form-vertical" 
    method="post" enctype="application/x-www-form-urlencoded" 
    action="<?php echo $this->url(array("module"=>"encuesta","controller"=>"home","action"=>"login"),null,true); ?>">
    
        <div class="control-group normal_text">
            <h3>
                <img src="<?php echo $this->baseUrl(); ?>/public/ext/modules/encuesta/images/LogoEncuestas2.png" alt="Logo" />
            </h3>
        </div>
        <div class="control-group">
            <div class="controls">
                <div class="main_input_box">
                    <span class="add-on bg_lr"><i class="icon-font"></i></span>
                    <input type="text" name="claveOrganizacion" required="required" placeholder="Clave organizacion" />
                </div>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <div class="main_input_box">
                    <span class="add-on bg_lg"><i class="icon-user"></i></span> 
                    <input type="text" name="usuario" required="required" placeholder="Usuario" />
                </div>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <div class="main_input_box">
                    <span class="add-on bg_ly"><i class="icon-lock"></i></span>
                    <input type="password" name="password" required="required" placeholder="Password" />
                </div>
            </div>
        </div>
        <div class="form-actions">
            <span class="pull-left">
                <a href="<?php echo $this->url(array("module"=>"encuesta", "controller"=>"home", "action"=>"index"),null,true) ?>" class="btn btn-info">
                    <span class="icon icon-home"></span> Back to Home
                </a>
            </span>
            <span class="pull-right">
                <input type="submit" class="btn btn-success" />
            </span>
        </div>
    </form>
</div>
<?php if(!is_null($loginResultMessages)){ ?>
    <div class="container">
        <ul>
            <?php foreach ($loginResultMessages as $message) : ?>
                <li><?php echo $message; ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php } ?>
<script type="text/javascript">
</script>
