<?php 
	$divisa = $this->divisa;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"contabilidad", "controller"=>"divisa","action"=>"editar", "idDivisa"=>$divisa->getIdDivisa()),null,true));
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Detalle Divisa.
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Clave Divisa</th>
						<th>Descripcion</th>
						<th>Tipo Cambio</th>
					</tr>
				</thead>
				<tbody>
	
					<tr>
						<td><?php echo $divisa->getClaveDivisa() ?></td>
						<td><?php echo $divisa->getDescripcion() ?></td>
						<td><?php echo $banco->getTipoCambio() ?></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Divisa
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $formulario; ?>
		</div>
	</div>
</section>