<?php $encuestas = $this->encuestas; ?>
<section class="row-fluid">
    <div class="span3">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-copy"></i>
                </span>
                <h5>Encuestas</h5>
            </div>
            <div class="widget-content">
                <table class="table table-bordered table-striped">
                    <tbody>
                        <tr>
                            <td>
                                <a type="button" class="btn btn-block btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"encuestas", "action"=>"alta"), null, true) ?>">
                                    <span class="icon icon-plus"></span> Nueva
                                </a>
                            </td>
                        </tr>
                        <?php foreach ($encuestas as $encuesta) : ?>
                        <tr>
                            <td>
                                <button type="button" class="btn btn-block btn-default" tipo="encuesta" claveEncuesta="<?php echo $encuesta->getIdEncuesta(); ?>" 
                                   data-toggle="modal" data-target="#msgDetails">
                                    <?php echo $encuesta->getNombreClave(); ?>
                                </button>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
    <div class="span3">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-reorder"></i>
                </span>
                <h5>Secciones</h5>
            </div>
            <div id="contenedorSecciones" class="widget-content">
                
            </div>
        </div>
    </div>
    
    <div class="span3">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-th-large"></i>
                </span>
                <h5>Grupos</h5>
            </div>
            <div id="contenedorGrupos" class="widget-content">
                
            </div>
        </div>
    </div>
    
    <div class="span3">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-question-sign"></i>
                </span>
                <h5>Preguntas</h5>
            </div>
            <div id="contenedorPreguntas" class="widget-content">
                
            </div>
        </div>
    </div>
    
</section>

<hr />

<section class="row-fluid">
    <div id="contentDet" class="widget-box span12">
        <div class="widget-title">
            <span class="icon">
                <i class="icon-search"></i>
            </span>
            <h5>Detalles</h5>
        </div>
        <div id="detalles" class="widget-content" tipo="" claveContenedor="">
        </div>
    </div>
</section>

<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/ext/modules/encuesta/js/mainEncuesta.js"></script>
