<?php 	$estados = $this->estados; 
		$formulario = $this->formulario;
		$formulario->setAction($this->url(array("module"=>"sistema", "controller"=>"estados", "action" => "alta"), null, true));
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Estados en el Sistema.
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"estados","action"=>"alta")) ?>">
				<span class="glyphicon glyphicon-plus"></span> Nuevo Estado
			</a>
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Numero Estado</th>
						<th>Estado</th>
						<th>Capital</th>
						<th>Administrar</th>
						<th>Municipios</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($estados as $estado) : ?>
					<tr>
						<td><?php echo $estado->getIdEstado() ?></td>
						<td><?php echo $estado->getEstado() ?></td>
						<td><?php echo $estado->getCapital() ?></td>
						<td>
							<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"sistema", "controller"=>"estados", "action" => "admin", "idEstado" => $estado->getIdEstado()), null, true); ?>">
								<span class="glyphicon glyphicon-cog"></span> Administrar
							</a>
						</td>
						<td>
							<a class="btn btn-warning" href="<?php echo $this->url(array("module"=>"sistema", "controller"=>"municipios", "action" => "index", "idEstado" => $estado->getIdEstado()), null, true); ?>">
								Municipios
							</a>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</section>




