<?php 
	$formulario = $this->formulario;
	// Mensajes de Error / Exito
	$messageFail = $this->messageFail;
	$messageSuccess = $this->messageSuccess;
?>
<section class="rol">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">Alta de Nuevo Rol en el Sistema</h3>
		</div>
		<div class="panel-body">
			<div class="col-xs-6 col-md-6">
				<?php if(!is_null($messageSuccess)){ ?>
					<div class="alert alert-success" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						  <span aria-hidden="true">&times;</span>
						</button>
						<?php echo $messageSuccess; ?>
					</div>
				<?php }elseif(!is_null($messageFail)){ ?>
				<div class="alert alert-danger" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					  <span aria-hidden="true">&times;</span>
					</button>
					<?php echo $messageFail; ?>
				</div>
				<?php } ?><br />
				<?php echo $formulario ?>
			</div>
			
		</div>
	</div>
</section>