<?php 
	$roles = $this->roles;
?>
<section class="row">
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">Roles y Usuarios en el Sistema</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"rol","action"=>"alta"),null,true) ?>">
				<span class="glyphicon glyphicon-plus"></span> Nuevo Rol
			</a>
			<table class="table table-condensed table-striped">
				<thead>
					<th>Rol</th>
					<th>Creación</th>
					<th>Usuarios</th>
				</thead>
				<tbody>
					<?php foreach ($roles as $rol) : ?>
					<tr>
						<td>
							<a class="btn btn-warning">
								<span class="glyphicon glyphicon-cog"></span> <?php echo $rol->getRol() ?>
							</a>
						</td>
						<td><?php echo $rol->getFecha() ?></td>
						<td>
							<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"usuario","action"=>"usuarios","idRol"=>$rol->getIdRol()),null,true) ?>">
								<span class="glyphicon glyphicon-user"></span> Ver Usuarios
							</a>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</section>