<section class="row">
	<table class="table table-striped table-condensed">
		<thead>
			<th>Elemento</th>
			<th>Action</th>
		</thead>
		<tbody>
			<tr>
				<td>Reporte Base Vertical</td>
				<td>
					<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"util","action"=>"repvertical"),null,true) ?>">
						<span class="glyphicon glyphicon-save-file"></span> Generar Reporte Base Vertical
					</a>
				</td>
			</tr>
			<tr>
				<td>Reporte Base Horizontal</td>
				<td></td>
			</tr>
		</tbody>
	</table>
</section>