<?php
	$nombreArchivo = "reporteMuestraMargenes.pdf";
	$pdfBase = new My_Pdf_Document($nombreArchivo, PDF_PATH . '/reports/bases/');
	$pdfBase->properties["Title"] = "Main Test Letter Vertical Margin Template";
	$pdfBase->properties["Author"] = "Zazil Consultores S.A. de C.V.";
	
	$page = new My_Pdf_Page(Zend_Pdf_Page::SIZE_LETTER);
	//$page = $pdfBase->createPage();
	
	$imgEncabezado = Zend_Pdf_Image::imageWithPath(IMAGES_PATH . '/Logo.png');
	$page->drawImage($imgEncabezado, 40, 40, 123, 76);
	//$page->drawImage($imgEncabezado, 20, 25, 510.3, 108.3);
	//$page->drawLine(0, 10, $page->getWidth(), 10);
	//$page->drawLine(10, 0, 10, $page->getHeight());
	
	//$page->drawLine(0, 10, $page->getWidth(), 10);
	//$page->drawLine($page->getWidth() - 10, 0, $page->getWidth() - 10, $page->getHeight());
	/*
	$step = 10;
	$contador = 0;
	while ($contador <= $page->getWidth()) {
		$contador += $step;
		
		$page->drawLine($contador, 0, $contador, $page->getHeight());
		//$page->drawLine(0, $contador, $page->getWidth(), $contador);
	}
	$step = 10;
	$contador = 0;
	while ($contador <= $page->getHeight()) {
		$contador += $step;
		
		//$page->drawLine($contador, 0, $contador, $page->getHeight());
		$page->drawLine(0, $contador, $page->getWidth(), $contador);
	}
	*/
	// Headers
	// Horizontales
	$page->drawLine(30, 20, $page->getWidth()-20, 20);
	$page->drawLine(30, 160, $page->getWidth()-20, 160);
	// Verticales
	$page->drawLine(30, 20, 30, 160);
	$page->drawLine(170, 20, 170, 160);
	$page->drawLine($page->getWidth()-20, 20, $page->getWidth()-20, 160);
	
	// Footer
	// Horizontales
	$page->drawLine(30, $page->getHeight()-60, $page->getWidth()-20, $page->getHeight()-60);
	$page->drawLine(30, $page->getHeight()-10, $page->getWidth()-20, $page->getHeight()-10);
	// Verticales
	//$page->drawLine(30, $page->getHeight()-60, $page->getWidth()-20, $page->getHeight()-60);
	
	$page->drawLine(30, $page->getHeight()-60, 30, $page->getHeight()-10);
	$page->drawLine($page->getWidth()-20, $page->getHeight()-60, $page->getWidth()-20, $page->getHeight()-10);
	
	//$page->drawLine(30, 60, $page->getWidth()-20, 160);
	
	
	//$pdfBase->set
	
?>
<section class="row">
	Plantilla de Reporte Creada.
</section>
<?php
	$pdfBase->addPage($page);
	
	$pdfBase->save();
	//$pdfBase->save(PDF_PATH . '/reports/bases/' . $nombreArchivo,false);
?>