<?php
    $docentes = $this->docentes;
?>
<div class="row-fluid">
    <div class="span12 widget-box">
        <div class="widget-title">
            
        </div>
        <div class="widget-content">
            <div>
                <a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"docente","action"=>"alta"),null,true) ?>">
                    <span class="icon icon-plus"></span> Agregar Docente
                </a>
            </div>
            <hr />
            <div>
                <table class="table table-bordered table-striped table-condensed">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Apellidos</th>
                            <th>Creación</th>
                            <th>Evaluaciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($docentes as $docente) : ?>
                        <tr>
                            <td><?php echo $docente->getNombres() ?></td>
                            <td><?php echo $docente->getApellidos() ?></td>
                            <td><?php echo $docente->getFecha() ?></td>
                            <td>
                                <a class="btn btn-info btn-block" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"docente","action"=>"evaluaciones","idDocente"=>$docente->getIdRegistro()),null,true); ?>">
                                    <span class="icon icon-search"></span> Evaluaciones
                                </a>
                            </td>
                        </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>