<?php 
	$encuesta = $this->encuesta; 
	$estatus = Zend_Registry::get("estatus");
?>
<div>
	<strong>Encuesta:</strong> <span style="font-style: italic;"><?php echo $encuesta->getNombre() ?></span><br />
	<strong>Objetivo Encuesta:</strong>  <span style="font-style: italic;"><?php echo $encuesta->getDescripcion(); ?></span><br /><hr />
</div>
<div>
	<table class="table table-bordered table-striped">
		<thead>
		    <tr>
		        <th>Nombre Clave</th>
                <th>Creación</th>
                <th>Estatus</th>
                <th>Configurar</th>
		    </tr>
		</thead>
		<tbody>
			<tr>
				<td><?php echo $encuesta->getNombreClave(); ?></td>
				<td><?php echo $encuesta->getFecha(); ?></td>
				<td><?php echo $estatus[$encuesta->getEstatus()]; ?></td>
				<td>
					<a class="btn btn-warning btn-block" 
					   href="<?php echo $this->url(array("module"=>"encuesta","controller" => "encuestas", "action" => "config", "id" => $encuesta->getIdEncuesta()), null, true) ?>" >
						<span class="icon icon-cog"></span> Configurar
					</a>
				</td>
			</tr>
		</tbody>
	</table>
</div>
