<?php 
	$seccion = $this->seccion;
	$grupos = $this->grupos; 
?>
<table class="table table-condensed">
	<tbody>
		<tr>
			<td>
				<a class="btn btn-block btn-success" href="<?php echo $this->url(array("controller" => "grupo", "action" => "alta", "idSeccion" => $seccion->getIdSeccion()), null, true) ?>">
					<span class="glyphicon glyphicon-plus"></span> Nueva
				</a>
			</td>
		</tr>
		<?php foreach ($grupos as $grupo) : ?>
		<tr>
			<td>
				<button type="button" class="btn btn-block btn-default" tipo="grupo" numero="<?php echo $grupo->getIdGrupo(); ?>" padre="<?php echo $seccion->getIdSeccion(); ?>" hash="<?php echo $grupo->getIdGrupo(); ?>" >
					<span class="glyphicon glyphicon-th-large"></span> <?php echo $grupo->getNombre(); ?>
				</button>
			</td>
		</tr>
		<?php endforeach?>
	</tbody>
</table>
