<?php 
	$seccion = $this->seccion;
	$encuesta = $this->encuesta;
	
	$estatus = Zend_Registry::get("estatus");
	$tipo = Zend_Registry::get("tipo");
	//print_r($seccion);
	if(! is_null($seccion)){ ?>
<div>
	<strong>Encuesta: </strong> <span style="font-style: italic;"><?php echo $encuesta->getNombre(); ?></span> <br />
	<strong>Seccion:</strong> <span style="font-style: italic;"><?php echo $seccion->getNombre(); ?></span><br /><hr />
</div>
<div>
	<table class="table table-striped table-condensed">
		<tbody>
			<thead>
				<th>Creación</th>
				<th>Orden</th>
				<th>Elementos</th>
				<th>Configurar</th>
			</thead>
			<tr>
				<td><?php echo $seccion->getFecha(); ?></td>
				<td><?php echo $seccion->getOrden(); ?></td>
				<td><?php echo $seccion->getElementos(); ?></td>
				<td>
					<a class="btn btn-warning" href="<?php echo $this->url(array("module"=>"encuesta", "controller"=>"seccion", "action"=>"admin", "idSeccion"=>$seccion->getIdSeccionEncuesta()), null, true) ?>">
						<span class="glyphicon glyphicon-cog"></span> Configurar
					</a>
				</td>
			</tr>
		</tbody>
	</table>
</div>
<?php }?>