<?php 
	$seccion = $this->seccion;
	$encuesta = $this->encuesta;
	
	$estatus = Zend_Registry::get("estatus");
	$tipo = Zend_Registry::get("tipo");
	//print_r($seccion);
	if(! is_null($seccion)){ ?>
	<section class="col-xs-12">
		<header>
			<h3>Seccion: <?php echo $seccion->getNombre(); ?>
				<a href="<?php echo $this->url(array("module"=>"encuesta", "controller"=>"seccion", "action"=>"admin", "idSeccion"=>$seccion->getIdSeccion()), null, true) ?>" class="btn btn-default">
					Administrar
					<span class="glyphicon glyphicon-cog"></span>
				</a>
				<a href="<?php echo $this->url(array("module"=>"encuesta", "controller"=>"seccion", "action"=>"baja", "idSeccion"=>$seccion->getIdSeccion()), null, true) ?>" class="btn btn-default">
					Eliminar
					<span class="glyphicon glyphicon-remove"></span>
				</a>
			</h3>
		</header>
		<table class="table table-striped">
			<tbody>
				<tr>
					<td>Encuesta: </td>
					<td><?php echo $encuesta->getNombreClave(); ?></td>
					<td>Orden: </td>
					<td><?php echo $seccion->getOrden(); ?></td>
					<td>Elementos: </td>
					<td><?php echo $seccion->getElementos(); ?></td>
				</tr>
			</tbody>
		</table>
	</section>
<?php }?>