<?php 
	$registros = $this->registros;
	$tUsuario = Zend_Registry::get("tUsuario");
?>
<section class="row">
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">
				Usuarios Registrados
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"registro","action"=>"alta"), null, true); ?>">
				Registrar Usuario
			</a>
			<table class="table table-striped table-condensed">
				<thead>
					<th>Nombres</th>
					<th>Apellidos</th>
					<th>Tipo Usuario</th>
					<th>Fecha</th>
					<th>Referencia</th>
				</thead>
				<tbody>
					<?php foreach ($registros as $registro) : ?>
					<tr>
						<td><?php echo $registro->getNombres() ?></td>
						<td><?php echo $registro->getApellidos() ?></td>
						<td><?php echo $tUsuario[$registro->getTipo()] ?></td>
						<td><?php echo $registro->getFecha() ?></td>
						<td><?php echo $registro->getReferencia() ?></td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</div>
</section>