<?php 	$telefono = $this->telefono; 
		$formulario = $this->formulario;
		$formulario->setAction($this->url(array("module"=>"sistema", "controller"=>"telefono", "action" => "edita", "idTelefono"=>$telefono->getIdTelefono()), null, true));
?>
<section class="row">
	<article>
		<header>
			<h3>
				Detalle Telefono: <?php echo $telefono->getTelefono(); ?>
			</h3>
		</header>
		
		<table class="table table-striped table-condensed">
			<thead>
				<tr>
					<th>Numero Estado/th>
					<th>Tipo</th>
					<th>Lada</th>
					<th>Telefono</th>
					<th>Extensiones</th>
					<th>Descripcion</th>
				</tr>
			</thead>
			<tbody>

				<tr>
					<td><?php echo $estado->getIdEstado() ?></td>
					<td><?php echo $estado->getTipo() ?></td>
					<td><?php echo $estado->getLada() ?></td>
					<td><?php echo $estado->getTelefono() ?></td>
					<td><?php echo $estado->getExtensiones() ?></td>
					<td><?php echo $estado->getDescripcion() ?></td>

					
				</tr>
			</tbody>
		</table>
	</article>
</section>
<section class="row">
	<article class="col-md-6" style="background-color: #87CEEB">
		<header>
			<h3>Editar</h3>
		</header>
		<?php echo $formulario; ?>
	</article>
	<article class="col-md-6" style="background-color: #FF6347">
		<header>
			<h3>Eliminar</h3>
		</header>
		<a class="btn btn-danger" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"telefono", "action"=>"baja", "idTelefono"=>$telefono->getIdTelefono()), null, true) ?>">
			Eliminar Telefono
		</a>
		<br /><br />
	</article>
</section>