<?php
	$fiscales = $this->fiscales;
	$formulario = $this->formulario;
	$telefonos = $this->telefonos;
	$tipoTelefono = Zend_Registry::get("tipoTelefono");
?>
<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"empresas","action"=>"admin","idFiscales"=>$fiscales->getIdFiscales())) ?>">
	<span class="glyphicon glyphicon-chevron-left"></span> Regresar a Empresa
</a>
<br /><br />
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Telefonos de: <strong><?php echo $fiscales->getRazonSocial() ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<th>Tipo</th>
					<th>Creación</th>
					<th>Lada</th>
					<th>Telefono</th>
					<th>Extensiones</th>
					<th>Descripcion</th>
				</thead>
				<tbody>
					<?php foreach ($telefonos as $telefono) : ?>
					<tr>
						<td><?php echo $tipoTelefono[$telefono->getTipo()]; ?></td>
						<td><?php echo $telefono->getFecha(); ?></td>
						<td><?php echo $telefono->getLada(); ?></td>
						<td><?php echo $telefono->getTelefono(); ?></td>
						<td><?php echo $telefono->getExtensiones(); ?></td>
						<td><?php echo $telefono->getDescripcion(); ?></td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
	
</section>

