<?php 	$telefonos = $this->telefonos; 
		//print_r($telefonos);
		$formulario = $this->formulario;
		$formulario->setAction($this->url(array("module"=>"sistema", "controller"=>"telefono", "action" => "alta"), null, true));
?>
<section class="row">
	<article>
		<header>
			<h3>
				Telefonos datos de alta en el sistema.
			</h3>
		</header>
		<?php echo $formulario; ?>
		<table class="table table-striped table-condensed">
			<thead>
				<tr>
					<th>Numero Telefono</th>
					<th>Lada</th>
					<th>Telefono</th>
					<th>Extensiones</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($telefonos as $telefono) : ?>
				<tr>
					<td><?php echo $telefono->getIdTelefono() ?></td>
					<td><?php echo $telefono->getLada() ?></td>
					<td><?php echo $telefono->getTelefono() ?></td>
					<td><?php echo $telefono->getExtensiones() ?></td>
					
					<td>
						<a class="btn btn-block btn-warning" href="<?php echo $this->url(array("module"=>"sistema", "controller"=>"telefono", "action" => "admin", "idTelefono" => $telefono->getIdTelefono()), null, true); ?>">
							Administrar
						</a>
					</td>
				</tr>	
				<?php endforeach; ?>
			</tbody>
		</table>
	</article>
</section>




