<?php
	$multiplo = $this->multiplo;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"inventario", "controller"=>"multiplos", "action" => "edita", "idMultiplos"=>$multiplo->getIdMultiplos()),null,true));
	
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Detalle Multiplo: <?php echo $multiplo->getUnidad() ?>.
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Cantidad</th>
						<th>Unidad</th>
						<th>Abreviatura</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><?php echo $multiplo->getCantidad() ?></td>
						<td><?php echo $multiplo->getUnidad() ?></td>
						<td><?php echo $multiplo->getAbreviatura() ?></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Multiplo
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $formulario; ?>
		</div>
	</div>
	
	