<?php 
	$producto = $this->producto;
	$multiplos = $this->multiplos; 
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"inventario", "controller"=>"multiplos", "action" => "alta"), null, true));
	
?>
<section class="row">
	<article>
		<header>
			<h3>Multiplos:  <?php echo $producto->getProducto() ?></h3>
		</header>
		<div>
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"inventario","controller"=>"multiplos","action"=>"alta","idProducto"=>$producto->getIdProducto()),null,true); ?>">
				<span class="glyphicon glyphicon-plus"></span> Nuevo Multiplo
			</a>
			<table class="table table-condensed table-striped">
				<thead>
					<th>idMultiplos</th>
					<th>idProducto</th>
					<th>idUnidad</th>
					<th>Cantidad</th>
					
				</thead>
				<tbody>
					<?php foreach ($multiplos as $multiplo) : ?>
					<?php print_r($multiplo->toArray()) ?>
					<?php print_r("<br />") ?>
					<tr>
						<td><?php echo $multiplo->getIdMultiplos() ?></td>
						<td><?php echo $producto->getProducto() ?></td>
						
						
						<td><?php echo $multiplo->getIdUnidad() ?></td>
						<td><?php echo $multiplo->getCantidad() ?></td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</article>
</section>
