<div class="row-fluid">
    <div class="span12 widget-box">
        <div class="widget-title">
            <h5>Normalizaciones disponibles</h5>
        </div>
        <div class="widget-content">
            <table class="table table-bordered table-condensed table-striped">
                <thead>
                    <th>Descripción</th>
                    <th>Acción</th>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            N. Valor Máximo de Todos los Grupos de Preguntas.
                        </td>
                        <td>
                            <a class="btn btn-info btn-block" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"normalize","action"=>"nmaxvalgrupo"),null,true) ?>">
                                <span class="icon icon-asterisk"></span> Normalizar Valores Máximos
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            N. Valor Mínimo de Todos los Grupos de Preguntas.
                        </td>
                        <td>
                            <a class="btn btn-info btn-block" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"normalize","action"=>"nminvalgrupo"),null,true) ?>">
                                <span class="icon icon-asterisk"></span> Normalizar Valores Mínimos
                            </a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>