<div class="row-fluid">
    <div class="span12 widget-box">
        <div class="widget-title">
            <h5>Resultados de la Normalizacion</h5>
        </div>
        <div class="widget-content">
            <a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"normalize","action"=>"index",),null,true) ?>">
                <span class="icon icon-arrow-left"></span> Regresar a Normalización
            </a><br /><br />
            <?php echo $this->mensaje ?>
        </div>
    </div>
</div>