<?php 	$unidad = $this->unidad; 
		$formulario = $this->formulario;
		$formulario->setAction($this->url(array("module"=>"inventario", "controller"=>"unidad", "action" => "edita", "idUnidad"=>$unidad->getIdUnidad()), null, true));
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Detalle Unidad: <?php echo $unidad->getUnidad(); ?>
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Unidad</th>
						<th>Abreviatura</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><?php echo $unidad->getUnidad() ?></td>
						<td><?php echo $unidad->getAbreviatura() ?></td>
						
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Unidad
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $formulario; ?>
		</div>
	</div>
	
	<div class="panel panel-danger">
		<div class="panel-heading">
			<h3 class="panel-title">
				Eliminar Unidad
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-danger" href="<?php echo $this->url(array("module"=>"inventario","controller"=>"unidad", "action"=>"baja", "idUnidad"=>$unidad->getIdUnidad()), null, true) ?>">
				Eliminar Unidad
			</a>
		</div>
	</div>
</section>