<?php 	$unidad = $this->unidad; 
		$formulario = $this->formulario;
		$formulario->setAction($this->url(array("module"=>"inventario", "controller"=>"unidad", "action" => "edita"), null, true));
?>
<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
				Unidades para productos del sistema.
		</h3>
	</div>
		<div class="panel-body">
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"inventario","controller"=>"unidad","action"=>"alta")) ?>">
				<span class="glyphicon glyphicon-plus"></span> Nueva Unidad
			</a>
		
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Unidad</th>
						<th>Abreviatura</th>
						<th>SAT</th>
						<th>Administrar</th>
						
					</tr>
				</thead>
				<tbody>
					<?php foreach ($unidad as $unidad) : ?>
					<tr>
						<td><?php echo $unidad->getUnidad() ?></td>
						<td><?php echo $unidad->getAbreviatura() ?> </td>
						<td><?php echo $unidad->getSat3() ?> </td>
					
						<td>
							<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"inventario", "controller"=>"unidad", "action" => "admin", "idUnidad" => $unidad->getIdUnidad()), null, true); ?>">
								<span class="glyphicon glyphicon-cog"></span> Administrar
							</a>
						</td>
						
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	
</section>
