<?php
	$formulario = $this->formulario;
	$datosFactura = $this->datosFactura;
	$clientesFac = $this->clientesFac;
	$sucursalFac = $this->sucursalFac;
	$messageFail = $this->messageFail;
	$messageSuccess = $this->messageSuccess;
?>
<!--Tabla eniva datos -->
<section class="panel panel-warning">
	<div class="panel-heading">
		<h5>Realiza cobro remision cafetería cliente.</h5>
	</div>
	<div class="panel-body">
		<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
			<!--Datos -->
			
			<div class="form-group hidden">
				<label for="datos" class="col-md-1">Datos: </label>
				<div class="col-md-4">
					<input id="datos" name="datos" type="text" class="form-control" />
				</div>
			</div>
			<!--Clave producto 
			<div class="form-group">
				<label for="clave" class="col-md-1">Clave Producto: </label>
				<div class="col-md-4">
					<input id="idClaveProducto" name="clave" type="text" class="form-control" />
				</div>
			</div>-->
			<!-- Fecha -->
			<div class="form-group">
    			<label for="fecha" class="control-label col-md-2">Fecha de Pago: </label>
        		<div class="col-md-10">
        			<input id="fecha" name="fecha" type="text" class="form-control" />
        		</div>
    		</div>
		    <!-- Pago -->
			<div class="form-group">
				<label for="pago" class="control-label col-md-2">Monto: </label>
				<div class="col-md-10">
					<input id="pago" name="pago" type="text" class="form-control" />
				</div>
			</div>
		    <!-- Divisa -->
			<div class="form-group">
    			<label for="divisa" class="control-label col-md-2">Divisa: </label>
    			<div class="col-md-10">
        			<select id="idDivisa" name="divisa" class="form-control">
        			<?php foreach ($divisas as $divisa) : ?>
        				<option value="<?php echo $divisa->getIdDivisa(); ?>"><?php echo $divisa->getDescripcion(); ?></option>
        			<?php endforeach; ?>
    				</select>
    			</div>
			</div>
		    <!-- Concepto -->
			<div class="form-group">
				<label for="concepto" class="control-label col-md-2">Concepto: </label>
				<div class="col-md-10">
					<select id="conceptoPago" name="concepto" class="form-control">
						<?php foreach ($conceptoPagos as $key =>$value): ?>
							<option value="<?php echo $key; ?>"><?php echo $value; ?></option>
						<?php endforeach; ?>	
					</select>
				</div>
			</div>
			<!-- FormaPago -->
			<div class="form-group">
				<label for="formaPago" class="control-label col-md-2">Forma de Pago</label>
				<div class="col-md-10">
					<select id="formaPago" name="formaPago" class="form-control">
						<?php foreach ($formasPago as $key => $value): ?>
							<option value="<?php echo $key; ?>"><?php echo $value; ?></option>
						<?php endforeach ?>	
					</select>
				</div>
			</div>
			<!-- Banco -->
			<div class="form-group">
				<label for="banco" class="control-label col-md-2">Banco: </label>
				<div class="col-md-10">
					<select id="idBanco" name="banco" class="form-control">
						<?php foreach ($bancos as $banco) :?>
							<option value="<?php echo $banco->getIdBanco(); ?>"> <?php echo $banco->getBanco(); ?></option>
						<?php endforeach?>
					</select>
				</div>
			</div>
			<!-- Referencia -->
			<div class="form-group">
				<label for="referencia" class="control-label col-md-2">Referencia: </label>
				<div class="col-md-10">
					<input id="referencia" name="referencia" type="text" class="form-control" placeholder="(Opcional)..." />
				</div>
			</div>
			<!-- Boton consulta -->
			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<button id="query" type="submit" class="btn btn-success">
						<i class="fa fa-search"></i> Agregar
					</button>
				</div>
			</div>
		</form>
	</div>
</section>
<script>
$().ready(function(){
	
		
});
</script>
