<?php 
	$formulario = $this->formulario; echo $formulario;
	$facturac = $this->facturac; 
?>
<!-- Muesta el resultado de la busqueda -->
<?php if(!is_null($facturac)){ ?>
	<div id="facturac" class="row hidden">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Detalle Número Factura.</h5>
			</div>
			<div class="panel-body">
				<div>
					<table  class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Movimiento</th>
								<th>Número Factura</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td><?php echo $facturac["idTipoMovimiento"]; ?></td>
								<td><?php echo $facturac["idSucursal"]; ?></td>
								
							</tr>	
						</tbody>
					</table>
				</div>
			</div>
			
		</div>
	</div>
</div>	
<?php } ?>

<script>
	$(document).ready(function(){
		
		console.log("ready");
		var url = window.location.origin + "/General/";
		//Sucursal
		$("select#idEmpresas").on('change', function(){
			var idEmpresa = $(this).val();
			if (idEmpresa !=0){
				var urlSucursal = url + "sistema/json/sucursales/idFiscales/" + this.value;
				console.log(urlSucursal);
				$.ajax({
					url: urlSucursal,
					dataType: "json",
					success: function (data){
						//$("select#idSucursal").empty();
						$.each(data, function (i,item){
							$("select#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal));
						});
					}
				});
			}
		});
		
		//Tabla
		$("#submit").on('click', function(){
			console.log("hola");
			$("#facturac").removeClass("hidden");
			
		});	
	});
</script>