<?php 
	$datosFacturas = $this->datosFacturas;
?>
<section class="row">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">
				Facrtura.
			</h3>
		</div>
		<div class="panel-body">
			
			<table cellpadding="0" cellspacing="0" border="0" class="display" id="example" width="100%">
				<thead>
					<tr>
						<th></th>
						<th>Configurar</th>
						<th>Clave Producto</th>
						<th>Descripción</th>
						<th>Codigo de Barras</th>
						<th>Multiplos</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($datosFacturas as $datosFactura) : ?>
					<tr>
						<td><?php echo $datosFactura["idFactura"] ?></td>
						<td><?php echo $datosFactura["idSucursal"] ?></td>
						<td><?php echo $datosFactura["idCoP"] ?></td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</section>

<script>
$(document).ready(function (){

});
</script>