<?php 
	 echo $this->formulario;
?>
<section class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Agregar Productos para Factura Salida.</h3>
		</div>
		<div class="panel-body">
			<br />
			<button id="addRow" class="btn btn-success" >
				<span class="glyphicon glyphicon-plus" ></span> Nuevo
			</button>
			<a id="generarJsonArray" class="btn btn-warning">
				<span class="glyphicon glyphicon-cog" ></span> Cargar
			</a>
			<table id="productos" class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Cantidad</th>
						<th>Clave Producto</th>
						<th>Seleccione Unidad</th>
						<th>Codigo de Barras</th>
						<th>Descripcion</th>
						<th>Precio Unitario</th>
						<th>Importe</th>
						<th>Eliminar</th>
					</tr>
				</thead>
				<tbody>
				</tbody>
				<tfoot>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>Total:</td>
						<td><input id="total" class="form-control" /></td>
					</tr>
					
				</tfoot>
			</table>
		</div>
	</div>
</section>

<script>
	$(document).ready(function(){
		
		console.log( "ready!" );
		var jsonProductos = <?php echo $this->jsonProductos; ?>;
		var jsonUnidad = <?php echo $this->jsonUnidad; ?>;
		//var jsonImpuestos = <?php echo $this->jsonImpuestos; ?>;
		
		//console.dir(jsonImpuestos);
		
		// cuando se presione el boton con id=addRow, se inserta una nueva fila en la tabla de productos
		$("button#addRow").on("click",function(){
			var filasTabla = $("table#productos tbody > tr").length;
			//console.log(filasTabla);
			// si filasTabla = 0 continuar
			// si filasTabla <> 0 checar fila actual
			filasTabla ++;
			// generamos elementos de nueva fila
			// cantidad
			var inputCantidad = $('<input />').attr({'id': 'idCantidad_' + filasTabla}).attr({'class':'form-control'}).attr({'value':"0"}).attr({'required':"La cantidad no puede quedar vacia"});
			// idProducto
			var inputProducto = $('<input />').attr({'id': 'idProducto_' + filasTabla}).attr({'class':'form-control'});

			// idUnidad
			var inputUnidad = $('<select />').attr({'id': 'idUnidad_' + filasTabla}).attr({'class':'form-control'});
			$.each(jsonUnidad,function(i,item){
				inputUnidad.append('<option value="'+jsonUnidad[i].idUnidad+'">'+jsonUnidad[i].unidad+'</option>');
			});
			// codigoBarras
			var inputCodigoBarras = $('<input />').attr({'id': 'codigoBarras_' + filasTabla}).attr({'class':'form-control'});
			// descripcion
			//var inputdescripcion = $('<input />').attr({'id': 'descripcion_' + filasTabla}).attr({'class':'form-control'});
			var selectdescripcion = $('<select />').attr({'id': 'descripcion_' + filasTabla}).attr({'class':'form-control'});
			$.each(jsonProductos,function(i,item){
				selectdescripcion.append('<option value="'+jsonProductos[i].idProducto+'">'+jsonProductos[i].producto+'</option>');
			});
			// precioUnitario
			var inputCostoUnitario = $('<input />').attr({'id': 'costoUnitario_' + filasTabla}).attr({'class':'form-control'});
			// precioImporte
			var inputCostoTotal = $('<input />').attr({'id': 'costoTotal_' + filasTabla}).attr({'class':'form-control'}).attr({'name':'costoTotal_'});
			
			// botonLimpiar
			var buttonLimpiar = $('<button />').attr({'id': 'btnLimpiar_' + filasTabla}).attr({'class':'btn btn-danger'});
			buttonLimpiar.html('<span class="glyphicon glyphicon-remove-circle"></span> Eliminar Producto')

			var tbody = $("table#productos").find('tbody');
			tbody.append($('<tr>').
				append($('<td>').append(inputCantidad)).
				append($('<td>').append(inputProducto)).
				append($('<td>').append(inputUnidad)).
				append($('<td>').append(inputCodigoBarras)).
				append($('<td>').append(selectdescripcion)).
				append($('<td>').append(inputCostoUnitario)).
				append($('<td>').append(inputCostoTotal)).
				append($('<td>').append(buttonLimpiar))
				
			);
		});//cierra el addRow
		
		$("a#generarJsonArray").on("click",function(){
 			
 			var tabla = $("table#productos > tbody  > tr");
 		
 			//Array Json de productos
 			var productos = [];
 			
 			tabla.each(function(){
 				
 				var row = $(this);
 				var cantidad = row.find("input[id^='idCantidad_']").val()
 				if ($("input#idCantidad_").val() == "0"){
 					console.log("La cantidad no puede quedar en 0")
 				}else{
 				 cantidad = row.find("input[id^='idCantidad_']").val();
 				}
 				var unidad = row.find("select[id^='idUnidad_']").val();
 				var codigoBarras = row.find("input[id^='codigoBarras_']").val();
 				var descripcion = row.find("select[id^='descripcion_']").val();
 				
 				var precioUnitario = row.find("input[id^='costoUnitario_']").val();
 				var importe = row.find("input[id^='costoTotal_']").val();
 				
 				//var subTotal = row.find("input[id^='subTotal']").val();
 				//var total = row.find("input[id^='total']").val();
 				
 				console.log("Cantidad:"+cantidad);
 				console.log("unidad:"+unidad);
 				console.log("codigoBarras:"+codigoBarras);
 				console.log("descripcion:"+descripcion);
 				console.log("precioUnitario:"+precioUnitario);
 				console.log("costoTotal:"+importe);
 				//console.log("total:"+total);
 				
 				
 				//var subTotal = $("input[id^='subTotal']").val();
 				//var total = $("input[id^='total']").val();
 				//var descuento = $("input[id^='descuento']").val();
 	
 			
 				//console.log("total:"+total);
 				productos.push(new Producto(cantidad, unidad, codigoBarras, descripcion, precioUnitario, importe)); 
 			});
 			console.dir(productos);
 			var myString = JSON.stringify(productos);
 			
 			console.log(myString);
 			if ($("input#productos").val(myString)){
 				
 			};
 	
 		});
		/*Importes
		 //===================================
		 $("a#generarJsonArray").on("click",function(){
 			
 			var tabla = $("table#productos > tbody  > tr");
 		
 			//Array Json de productos
 			var importes = [];
 			
 			tabla.each(function(){
 				
 				
 				var subtotal = $("#subtotal").val();
 				var descuento = $("#descuento").val();
 				var total = $("#total").val();
 				
 				var iva = $("#iva").val();
 				var ieps = $("#ieps").val();
 				var ish = $("#ish").val();
 				var isr = $("#isr").val();
 				
 				
 				console.log("subtotal:"+subtotal);
 				console.log("descuento:"+descuento);
 				console.log("total:"+total);
 				
 				console.log("iva:"+iva);
 				console.log("ieps:"+ieps);
 				console.log("ish:"+ish);
 				console.log("isr:"+isr);
 				
 		
 				importes.push(new Importe(subtotal, descuento, total,iva,ieps,ish,isr)); 
 			});
 			console.dir(importes);
 			var myString = JSON.stringify(importes);
 			
 			console.log(myString);
 			if ($("#1-importes").val(myString)){
 				
 			};
 	
 		});
		 ===================================//
		  */
		//==========================================Obtenemos el valor en la tabla del producto
		$("a#generarJsonArray").on("click",function(){
 			var tabla = $("table#productos > tbody  > tr");
 			//Array Json de productos
 			var producto = [];
 			
 			tabla.each(function(){
 				var row = $(this);
 				var  idProducto= row.find("select[id^='descripcion_']").val();
 				console.log("idProducto:"+idProducto); 
 				producto.push(new Producto(idProducto)); 
 				
 				if ($("input#idProducto").val(idProducto)){
 				
 				};
		
 			});
 		});
		//===========================================
		
 		function Producto(cantidad, unidad, codigoBarras, descripcion, precioUnitario, importe) {
		  
		  this.cantidad = cantidad;
		  /*if(cantidad == 0){
		  	console.log("La cantidad no puede quedar en 0");
		  }*/
		  //this.claveProducto = claveProducto;
		  this.unidad = unidad;
		  this.codigoBarras = codigoBarras;
		  this.descripcion = descripcion;
		  this.precioUnitario = precioUnitario;
		  this.importe = importe;
		  //this.unidad = unidad;
		  
		}
		/*
		 //=======================================================================//
		 
		function Importe(subtotal, descuento, total,iva,ieps,ish,isr) {
		  this.subtotal = subtotal;
		  //this.claveProducto = claveProducto;
		  this.descuento = descuento;
		  this.total = total;
		  
		  this.iva = iva;
		  this.ieps = ieps;
		  this.ish = ish;
		  this.isr = isr;
		}
		=======================================================================//
		*/
		$("select#idEmpresas").on('change', function(){
			var url = window.location.origin + "/General/public/sistema/json/sucursales/idFiscales/" + this.value;
			$.ajax({
				url: url,
				dataType: "json",
				success: function(data){
					$("select#idSucursal").empty();
					$.each(data, function(i,item){	
						$("select#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal)); 
					});
				}
			});
		});
		
		$("select#idSucursal").on('click', function(){
			var url = window.location.origin + "/General/public/sistema/json/proyectos/idSucursal/" + this.value;
			console.log(url);
			$.ajax({
				url:url,
				dataType: "json",
				success: function(data){
					console.dir(data);
					$("select#idProyecto").empty();
					$.each(data, function(i,item){
						$("select#idProyecto").append($("<option></option>").attr("value",data[i].idProyecto).text(data[i].descripcion));
					});
				}
			});
		});
		
		//Funcion Eliminar #btnLimpiar_2
 		$("table#productos").on("click", "button[id^='btnLimpiar_']", function(){
  			if ($("table#productos tbody > tr").length >1)
  			{
  				$("table#productos  tbody > tr:last").remove();
  			}
  			
 		});//cierra funcion eliminar
 		
 		//Funcion buscar descripcion del producto
 		$("table#productos").on("change", "select[id^='descripcion_']", function(){
 			var descripcion = $(this).attr("id");
			var arr = descripcion.split('_');
			var id = $(this).val();
			var numFila =  arr[1];
 			
 			$.each(jsonProductos,function(i,item){
 				if(jsonProductos[i].idProducto == id){
 					$("input#idProducto_"+numFila).val(jsonProductos[i].claveProducto);
 				}
 				
			});
 		});
 		
 		$("a#generarJsonArray").on("click",function(){
 			/*//$("table#productos").on("change","input[id^='idCantidad_']" ,function() {
 			var idCantidad = $("idCantidad_").attr("id");
 			//var arr = idCantidad.split('_');
 			//var numFila = idCantidad[1];
 			
 			if($("input#idCantidad_").val() == ""){
 				console.log("La cantidad mno puede quedar vacia");
 			}
 		});
 		//});*/
 		var $inputs = $('#productos :input'); // Obtenemos los inputs de nuestro formulario
		var formvalido = true; // Para saber si el form esta vacio 
 
		$inputs.each(function() {  // Recorremos los inputs del formulario (uno a uno)
		if(!($("table#productos").val().isEmpty)){ // Verificamos que el input este vacio 
			$(this).css('background','red'); // Agregamos un fondo rojo si este esta vacio
			formvalido = false;
		}else{
		$(this).css('background',''); // quitamos el fondo rojo si este esta lleno
		}
		return formvalido; // retornamos segun corresponda
	});
	});
	});
</script>