<?php
	$empresas = $this->empresas;
	$proyectos = $this->proyectos;
?>
<section>
	<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h4 class="panel-title">Búsqueda de Factura por Cobrar<strong></strong></h4>
			</div>
			<div class="panel-body">
				<div>
					
				</div>
				<hr />
				<div>
					<!--<div class="form-horizontal">-->
						<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
						<!-- Empresas -->
						<div class="form-group">
							<label for="empresa" class="col-md-2">Empresas: </label>
							<div class="col-md-10">
								<select name="empresa" id="idFiscales" class="form-control">
									<option value="0">Seleccione Empresa</option>
									<?php foreach ($empresas as $empresa) : ?>
									<option value="<?php echo $empresa["idFiscales"] ?>"><?php echo $empresa["razonSocial"] ?></option>
									<?php endforeach ?>
								</select>
							</div>
						</div>
						<!-- Sucursales -->
						<div class="form-group">
							<label for="sucursal" class="col-md-2">Sucursal: </label>
							<div class="col-md-10">
								<select required name="sucursal" id="idSucursal" class="form-control" >
								</select>
							</div>
						</div>
						<!--Clientes -->
						<div class="form-group">
							<label for="idProyecto" class="col-md-2">Proyecto: </label>
							<div class="col-md-10">
								<select required name="idProyecto" id="idProyecto" class="form-control">
								</select>
							</div>
						</div>
						<!-- Boton consulta -->
						<div class="form-group">
							<div class="col-md-offset-2 col-md-10">
								<button id="queryProyecto" type="button" class="btn btn-success">
									<i class="fa fa-search"></i> Consultar Proyecto.
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
</section>
<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Proyecto Por Factura Cliente.</h4>
		</div>
		<table id="detalleProyectoxfc" class="table table-striped table-condensed">
			<thead>
				<th>Tipo Movimiento</th>
				<th>CoP</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>
<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Proyecto Por Factura Proveedor.</h4>
		</div>
		<table id="detalleProyectoxfp" class="table table-striped table-condensed">
			<thead>
				<th>Tipo Movimiento</th>
				<th>CoP</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>
<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Proyecto Por Remision Entrada.</h4>
		</div>
		<table id="detalleRemisonC" class="table table-striped table-condensed">
			<thead>
				<th>Tipo Movimiento</th>
				<th>CoP</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>
<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Proyecto Por Remision Salida.</h4>
		</div>
		<table id="detalleRemisonP" class="table table-striped table-condensed">
			<thead>
				<th>Tipo Movimiento</th>
				<th>CoP</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>
<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Proyecto Por Nómina.</h4>
		</div>
		<table id="detalleProyectoNomina" class="table table-striped table-condensed">
			<thead>
				<th>Tipo Movimiento</th>
				<th>CoP</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>

<script>
	$().ready(function(){
		var url = window.location.origin + "/General/";
		
		$("#idFiscales").on('change',function(){
			//console.log($(this).val());
			var idFiscal = $(this).val();
			if(idFiscal != 0){
				var urlQuerySucursales = url + 'contabilidad/json/sucursalese/idFiscales/'+idFiscal;
				console.log(urlQuerySucursales);
				$.ajax({
					url: urlQuerySucursales,
					dataType: "json",
					success: function(data){
						console.dir(data);
						$("#idSucursal").empty();
						$("#idSucursal").append($("<option></option>").attr("value","0").text("Seleccione Sucursal..."));
						$.each(data, function (i,item){
							$("#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal));
						});
					}
				});
			}
		});
		
		
		$("select#idSucursal").on('click', function(){
			var url = window.location.origin + "/General/sistema/json/proyectos/idSucursal/" + this.value;
			//console.log("$url");
			$.ajax({
				url: url,
				dataType: "json",	
				success: function(data){
					$("select#idProyecto").empty();
					$.each(data, function(i,item){	
						$("select#idProyecto").append($("<option></option>").attr("value",data[i].idProyecto).text(data[i].descripcion)); 
					});
					
				}
			});
			
		});
		function AddRow(){
			$('#detalleProyectoxfc tbody').append('<tr><td></td><td></td><td style="text-align:right"><b>Total $:</b></td><td><input id="totalfc"class="form-control" style="width:120px"></input></td></tr>');
    	}
    	function calculaTotal(){
			var total = 0;
			var nFilas = $("#detalleProyectoxfc tr").length;
			$("table#detalleProyectoxfc").find("td[id^='importe']").each(function(){
			   	console.log($(this).text());
			   	total += +$(this).text(); 
			   	console.log(total);
			   	$("#totalfc").val(total.toFixed(2));
			 });
				
		}
		function AddRowFP(){
			$('#detalleProyectoxfp tbody').append('<tr><td></td><td></td><td style="text-align:right"><b>Total $:</b></td><td><input id="totalfp"class="form-control" style="width:120px"></input></td></tr>');
    	}
    	function calculaTotalFP(){
			var total = 0;
			var nFilas = $("#detalleProyectoxfp tr").length;
			$("table#detalleProyectoxfp").find("td[id^='importe']").each(function(){
			   	console.log($(this).text());
			   	total += +$(this).text(); 
			   	console.log(total);
			   	$("#totalfp").val(total.toFixed(2));
			 });
				
		}
		function AddRowRE(){
			$('#detalleRemisonC tbody').append('<tr><td></td><td></td><td style="text-align:right"><b>Total $:</b></td><td><input id="totalRE"class="form-control" style="width:120px"></input></td></tr>');
    	}
    	function calculaTotalRE(){
			var total = 0;
			var nFilas = $("#detalleRemisonC tr").length;
			$("table#detalleRemisonC").find("td[id^='importe']").each(function(){
			   	console.log($(this).text());
			   	total += +$(this).text(); 
			   	console.log(total);
			   	$("#totalRE").val(total.toFixed(2));
			 });
				
		}
		
		function AddRowRS(){
			$('#detalleRemisonP tbody').append('<tr><td></td><td></td><td style="text-align:right"><b>Total $:</b></td><td><input id="totalRS"class="form-control" style="width:120px"></input></td></tr>');
    	}
    	function calculaTotalRS(){
			var total = 0;
			var nFilas = $("#detalleRemisonP tr").length;
			$("table#detalleRemisonP").find("td[id^='importe']").each(function(){
			   	console.log($(this).text());
			   	total += +$(this).text(); 
			   	console.log(total);
			   	$("#totalRS").val(total.toFixed(2));
			 });
				
		}
		
		function AddRowPN(){
			$('#detalleProyectoNomina tbody').append('<tr><td></td><td></td><td style="text-align:right"><b>Total $:</b></td><td><input id="totalPN"class="form-control" style="width:120px"></input></td></tr>');
    	}
    	function calculaTotalPN(){
			var total = 0;
			var nFilas = $("#detalleProyectoNomina tr").length;
			$("table#detalleProyectoNomina").find("td[id^='importe']").each(function(){
			   	console.log($(this).text());
			   	total += +$(this).text(); 
			   	console.log(total);
			   	$("#totalPN").val(total.toFixed(2));
			 });
				
		}
		
		$("button#queryProyecto").on("click", function(){
		 	var idProyecto = $("select#idProyecto").val();
			var urlProyecto = window.location.origin + "/General/contabilidad/json/totalproyecto/idProyecto/" + idProyecto;
			console.log(urlProyecto);
			$.ajax({
				url: urlProyecto,
				dataType: "json",
				success: function(data){
					var tbody = $("table#detalleProyectoxfc").find('tbody');
					tbody.empty();
					$.each(data, function(i,item){
						
						var idTipoMovimiento = data[i].idTipoMovimiento;
						var tipo  =  window.location.origin + "/General/contabilidad/json/getdescripciontipomovto/idTipoMovimiento/" + idTipoMovimiento;
						console.log(tipo);
						
						if(idTipoMovimiento == 2){
							console.log("El tipo es factura Cliente");
							tbody.append($('<tr>').
							append($('<td>').append("FACTURA CLIENTE")).
							append($('<td>').append(data[i].idCoP)).	
							append($('<td>').append(data[i].numeroFactura)).
							append($('<td>').append(data[i].total).attr("id", "importe"))
							
							);
							
						}
					});
					AddRow();
					calculaTotal();
				}
			});
		});
		$("button#queryProyecto").on("click", function(){
			var idProyecto = $("select#idProyecto").val();
			var urlProyecto = window.location.origin + "/General/contabilidad/json/totalproyecto/idProyecto/" + idProyecto;
			console.log(urlProyecto);
			//====================================================================>>Factura Proveedor
			$.ajax({
				url: urlProyecto,
				dataType: "json",
				success: function(data){
					var tbody = $("table#detalleProyectoxfp").find('tbody');
					tbody.empty();
					$.each(data, function(i,item){
						
						var idTipoMovimiento = data[i].idTipoMovimiento;
						var tipo  =  window.location.origin + "/General/contabilidad/json/getdescripciontipomovto/idTipoMovimiento/" + idTipoMovimiento;
						console.log(tipo);
						
						if(idTipoMovimiento == 4 ){
							console.log("El tipo es factura Proveedor");
							tbody.append($('<tr>').
							append($('<td>').append("FACTURA PROVEEDOR")).
							append($('<td>').append(data[i].idCoP)).	
							append($('<td>').append(data[i].numeroFactura)).
							append($('<td>').append(data[i].total).attr("id", "importe"))
							
							);
							
						}
					});
					AddRowFP();
					calculaTotalFP();
				}
			});
		});
		$("button#queryProyecto").on("click", function(){
			var idProyecto = $("select#idProyecto").val();
			var urlProyecto = window.location.origin + "/General/contabilidad/json/proyectoremision/idProyecto/" + idProyecto;
			console.log(urlProyecto);
			//====================================================================>>Remision Cliente
			$.ajax({
				url: urlProyecto,
				dataType: "json",
				success: function(data){
					var tbody = $("table#detalleRemisonC").find('tbody');
					tbody.empty();
					$.each(data, function(i,item){
						
						var idTipoMovimiento = data[i].idTipoMovimiento;
						var tipo  =  window.location.origin + "/General/contabilidad/json/getdescripciontipomovto/idTipoMovimiento/" + idTipoMovimiento;
						console.log(tipo);
						
						if(idTipoMovimiento == 12 ){
							console.log("El tipo es factura Proveedor");
							tbody.append($('<tr>').
							append($('<td>').append("REMISION CLIENTE")).
							append($('<td>').append(data[i].idCoP)).	
							append($('<td>').append(data[i].numeroFolio)).
							append($('<td>').append(data[i].totalImporte).attr("id", "importe"))
							
							);
						}
					});
					AddRowRE();
					calculaTotalRE();
				}
			});
		});
		
		$("button#queryProyecto").on("click", function(){
			var idProyecto = $("select#idProyecto").val();
			var urlProyecto = window.location.origin + "/General/contabilidad/json/proyectoremision/idProyecto/" + idProyecto;
			console.log(urlProyecto);
			//====================================================================>>Remision Cliente
			$.ajax({
				url: urlProyecto,
				dataType: "json",
				success: function(data){
					var tbody = $("table#detalleRemisonP").find('tbody');
					tbody.empty();
					$.each(data, function(i,item){
						
						var idTipoMovimiento = data[i].idTipoMovimiento;
						var tipo  =  window.location.origin + "/General/contabilidad/json/getdescripciontipomovto/idTipoMovimiento/" + idTipoMovimiento;
						console.log(tipo);
						
						if(idTipoMovimiento == 13 ){
							console.log("El tipo es factura Proveedor");
							tbody.append($('<tr>').
							append($('<td>').append("REMISION PROVEEDOR")).
							append($('<td>').append(data[i].idCoP)).	
							append($('<td>').append(data[i].numeroFolio)).
							append($('<td>').append(data[i].totalImporte).attr("id", "importe"))
							
							);
						}
					});
					AddRowRS();
					calculaTotalRS();
				}
			});
		});
		
		$("button#queryProyecto").on("click", function(){
			var idProyecto = $("select#idProyecto").val();
			var urlProyecto = window.location.origin + "/General/contabilidad/json/proyectoremision/idProyecto/" + idProyecto;
			console.log(urlProyecto);
			//====================================================================>>Remision Cliente
			$.ajax({
				url: urlProyecto,
				dataType: "json",
				success: function(data){
					var tbody = $("table#detalleProyectoNomina").find('tbody');
					tbody.empty();
					$.each(data, function(i,item){
						
						var idTipoMovimiento = data[i].idTipoMovimiento;
						var tipo  =  window.location.origin + "/General/contabilidad/json/getdescripciontipomovto/idTipoMovimiento/" + idTipoMovimiento;
						console.log(tipo);
						
						if(idTipoMovimiento == 20 ){
							console.log("El tipo es factura Proveedor");
							tbody.append($('<tr>').
							append($('<td>').append("PAGO NOMINA")).
							append($('<td>').append(data[i].idCoP)).	
							append($('<td>').append(data[i].numeroFolio)).
							append($('<td>').append(data[i].totalImporte).attr("id", "importe"))
							
							);
						}
					});
					AddRowPN();
					calculaTotalPN();
				}
			});
		});
	});//document ready
	
</script>