<?php
	$empresas = $this->empresas;
	$proyectos = $this->proyectos;
?>
<section>
	<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h4 class="panel-title">Búsqueda de Factura por Cobrar<strong></strong></h4>
			</div>
			<div class="panel-body">
				<div>
					
				</div>
				<hr />
				<div>
					<!--<div class="form-horizontal">-->
						<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
						<!-- Empresas -->
						<div class="form-group">
							<label for="empresa" class="col-md-2">Empresas: </label>
							<div class="col-md-10">
								<select name="empresa" id="idFiscales" class="form-control">
									<option value="0">Seleccione Empresa</option>
									<?php foreach ($empresas as $empresa) : ?>
									<option value="<?php echo $empresa["idFiscales"] ?>"><?php echo $empresa["razonSocial"] ?></option>
									<?php endforeach ?>
								</select>
							</div>
						</div>
						<!-- Sucursales -->
						<div class="form-group">
							<label for="sucursal" class="col-md-2">Sucursal: </label>
							<div class="col-md-10">
								<select required name="sucursal" id="idSucursal" class="form-control" >
								</select>
							</div>
						</div>
						<!--Clientes -->
						<div class="form-group">
							<label for="idProyecto" class="col-md-2">Proyecto: </label>
							<div class="col-md-10">
								<select required name="idProyecto" id="idProyecto" class="form-control">
								</select>
							</div>
						</div>
						<!-- Boton consulta -->
						<div class="form-group">
							<div class="col-md-offset-2 col-md-10">
								<button id="queryProyecto" type="button" class="btn btn-success">
									<i class="fa fa-search"></i> Consultar Proyecto.
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
</section>

	<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Detalle de Facturas</h5>
			</div>
			<div class="panel-body">
				<div>
					<table id="proyectos" class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Tipo Movimiento</th>
								<th>CoP</th>
								<th>Número Factura</th>
								<th>Importe</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
						<tfoot>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
							
						</tfoot>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>	

<script>
	$().ready(function(){
		var url = window.location.origin + "/General/";
		
		$("#idFiscales").on('change',function(){
			//console.log($(this).val());
			var idFiscal = $(this).val();
			if(idFiscal != 0){
				var urlQuerySucursales = url + 'contabilidad/json/sucursalese/idFiscales/'+idFiscal;
				console.log(urlQuerySucursales);
				$.ajax({
					url: urlQuerySucursales,
					dataType: "json",
					success: function(data){
						console.dir(data);
						$("#idSucursal").empty();
						$("#idSucursal").append($("<option></option>").attr("value","0").text("Seleccione Sucursal..."));
						$.each(data, function (i,item){
							$("#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal));
						});
					}
				});
			}
		});
		
		
		$("select#idSucursal").on('click', function(){
			var url = window.location.origin + "/General/sistema/json/proyectos/idSucursal/" + this.value;
			//console.log("$url");
			$.ajax({
				url: url,
				dataType: "json",	
				success: function(data){
					$("select#idProyecto").empty();
					$.each(data, function(i,item){	
						$("select#idProyecto").append($("<option></option>").attr("value",data[i].idProyecto).text(data[i].descripcion)); 
					});
					
				}
			});
			
		});
		function AddRow(){
			$('#proyectos tbody').append('<tr><td></td><td></td><td style="text-align:right"><b>Total $:</b></td><td><input id="total"class="form-control" style="width:120px"></input></td></tr>');
    	}
    	function calculaTotal(){
			var total = 0;
			 $('#proyectos .importe').each(function(){
			   total += +$(this).text(); 
				$("#total").val(total); 
			 });
		}
		/*function calculaTotal(row){
			var importe = +row.find('input[id^="importe"]').val();
			total += +$(importe).text();
			console.log(total);
			$("#total").val(total); 
		}*/
		$("button#queryProyecto").on("click", function(){
		 	var idProyecto = $("select#idProyecto").val();
			var urlProyecto = window.location.origin + "/General/contabilidad/json/totalproyecto/idProyecto/" + idProyecto;
			console.log(urlProyecto);
			$.ajax({
				url: urlProyecto,
				dataType: "json",
				success: function(data){
					var tbody = $("table#proyectos").find('tbody');
					tbody.empty();
					$.each(data, function(i,item){
						
						var idTipoMovimiento = data[i].idTipoMovimiento;
						var tipo  =  window.location.origin + "/General/contabilidad/json/getdescripciontipomovto/idTipoMovimiento/" + idTipoMovimiento;
						console.log(tipo);
						
						if(idTipoMovimiento == 2){
							console.log("El tipo es factura Cliente");
							tbody.append($('<tr>').
							append($('<td>').append("FACTURA CLIENTE")).
							append($('<td>').append(data[i].idCoP)).	
							append($('<td>').append(data[i].numeroFactura)).
							append($('<td>').append(data[i].total).attr("id", "importe"))
							
							);
							
						}
					});
					AddRow();
					calculaTotal();
					
					$.each(data, function(i,item){
						
						var idTipoMovimiento = data[i].idTipoMovimiento;
						var tipo  =  window.location.origin + "/General/contabilidad/json/getdescripciontipomovto/idTipoMovimiento/" + idTipoMovimiento;
						console.log(tipo);
						var des = tipo.descripcion;
						//console.log(des);
						/*
						tbody.append($('<tr>').
							append($('<td>').append(data[i].idTipoMovimiento)).
							append($('<td>').append(data[i].idCoP)).	
							append($('<td>').append(data[i].numeroFactura)).
							append($('<td>').append(data[i].total).attr("id", "importe"))
							);*/
						if(idTipoMovimiento == 4){
							console.log("El tipo es factura Cliente");
							tbody.append($('<tr>').
							append($('<td>').append("FACTURA PROVEEDOR")).
							append($('<td>').append(data[i].idCoP)).	
							append($('<td>').append(data[i].numeroFactura)).
							append($('<td>').append(data[i].total).attr("id", "importe"))
							
							);
							
						}
					});
					AddRow();
					//calculaTotal();
				}
			});
			
			
		});
		
	});//document ready
	
</script>