<?php
	$formulario = $this->formulario;
	$descuentoDAO = new Contabilidad_DAO_Descuentos;
	$descuentos = $descuentoDAO->obtenerDescuentos();
	$messageFail = $this->messageFail;
	$messageSuccess = $this->messageSuccess;
?>
<section class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Nueva Remisión Cliente.</h3>
		</div>
		<div class="panel-body">
				<?php if(!is_null($messageSuccess)){ ?>
					<div class="alert alert-success" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						  <span aria-hidden="true">&times;</span>
						</button>
						<?php echo $messageSuccess; ?>
					</div>
				<?php }elseif(!is_null($messageFail)){ ?>
				<div class="alert alert-danger" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					  <span aria-hidden="true">&times;</span>
					</button>
					<?php echo $messageFail; ?>
				</div>
				<?php } ?><br />
				<?php echo $formulario; ?>
		</div>
	</div>
</section>

<section class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">
				Agregar Productos.
			</h3>
		</div>
		<div class="panel-body">
			<button id="addRow" class="btn btn-success" >
				<span class="glyphicon glyphicon-plus" ></span> Nuevo
			</button>
			<a id="generarJsonArray" class="btn btn-warning">
				<span class="glyphicon glyphicon-cog" ></span> Cargar
			</a>
			<table id="remisionSalida" class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Desechable Desayuno</th>
						<th>Desechable Comida</th>
						<th>Mesa</th>
						<th>Cantidad</th>
						<th>Clave Producto</th>
						<th>Seleccione Unidad</th>
						<th>Codigo de Barras</th>
						<th>Descripcion</th>
						<th>Precio Unitario</th>
						<th>Importe</th>
						<th>Eliminar</th>
					</tr>
				
				</thead>
				<tbody>
				</tbody>
				<tfoot>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>Descuento:</td>
    					<td>
    						<select id="descuento"  class="form-control">
    						<option value="0">Seleccione Descuento</option>
    							<?php foreach ($descuentos as $descuento) : ?>
    								<option value="<?php echo $descuento["idDescuentos"] ?>"><?php echo $descuento["descripcion"]; ?></option>
    							<?php endforeach; ?>
    						</select>
    					</td>		
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>Total:</td>
						<td><input id="total" class="form-control" disabled="true" /></td>				
					</tr>
				</tfoot>
			</table>
			<br />
		</div>
	</div>
</section>

<script>
	$(document).ready(function(){
		
		console.log( "ready!" );
		$("select#idEmpresas").on('click', function(){
			var url = window.location.origin + "/General/sistema/json/sucursales/idFiscales/" + this.value;
			console.log(url);
			$.ajax({
				url: url,
				dataType: "json",
				success: function(data){
					$("select#idSucursal").empty();
					$.each(data, function(i,item){	
						if(data[i].idFiscales == 6 ){
							$("select#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal)); 
						}
					});
				}
			});
		});

		
		
		$("select#idSucursal").on('click', function(){
		var url = window.location.origin + "/General/sistema/json/proyectos/idSucursal/" + this.value;
			//console.log("$url");
			$.ajax({
				url: url,
				dataType: "json",	
				success: function(data){
					$("select#idProyecto").empty();
					$.each(data, function(i,item){	
						if(data[i].idProyecto ==42){
							$("select#idProyecto").append($("<option></option>").attr("value","0").text("Seleccione Sucursal...").attr("value",data[i].idProyecto).text(data[i].descripcion)); 
							}
						
					});
					
				}
			});
			
		});
		
		var jsonDesProductos = <?php echo $this->jsonDesProductos; ?>;
		var cont=0;
		var filaSeleccionada;
		function agregar(){
			cont++;
			// cuando se presione el boton con id=addRow, se inserta una nueva fila en la tabla de productos
			//$("button#addRow").on("click",function(){
				var filasTabla = $("table#remisionSalida tbody > tr").length;
				//console.log(filasTabla);
				// si filasTabla = 0 continuar
				// si filasTabla <> 0 checar fila actual
				filasTabla ++;
				// generamos elementos de nueva fila
				// cantidad
				var chkDesechabeDes = $('<input />').attr({'id': 'desayuno' + filasTabla }).attr({'type':'checkbox'}).attr({'class':'chk'}).attr({'name':'empaque'}).attr({'value':'desayuno'});
				var chkDesechabCom = $('<input />').attr({'id': 'comida' + filasTabla}).attr({'type':'checkbox'}).attr({'class':'chk'}).attr({'name':'empaque'}).attr({'value':'comida'});
				var checkTrastes = $('<input />').attr({'id': 'traste' + filasTabla}).attr({'type':'checkbox'}).attr({'class':'chk'}).attr({'name':'empaque'}).attr({'value':'traste'});
				// cantidad
				var inputCantidad = $('<input />').attr({'id': 'idCantidad_' + filasTabla}).attr({'class':'form-control'}).attr({'required':"La cantidad no puede quedar vacia"});
				// idProducto
				var inputProducto = $('<input />').attr({'id': 'idProducto_' + filasTabla}).attr({'class':'form-control'});
				// idUnidad
				var inputUnidad	 = $('<select />').attr({'id': 'idUnidad_' + filasTabla}).attr({'class':'form-control'});
				/*$.each(jsonUnidad,function(i,item){
					inputUnidad.append('<option value="'+jsonUnidad[i].idUnidad+'">'+jsonUnidad[i].unidad+'</option>');
				});*/
				// codigoBarras
				var inputCodigoBarras = $('<input />').attr({'id': 'codigoBarras_' + filasTabla}).attr({'class':'form-control'});
				// descripcion
				//var inputDescripcion = $('<input />').attr({'id': 'descripcion_' + filasTabla}).attr({'class':'form-control'});
				var selectDescripcion = $('<select />').attr({'id': 'descripcion_' + filasTabla}).attr({'class':'form-control'});
				$.each(jsonDesProductos,function(i,item){
					selectDescripcion.append('<option value="'+jsonDesProductos[i].idProducto+'">'+jsonDesProductos[i].producto+'</option>');
				});	
				// precioUnitario
				var inputCostoUnitario = $('<input />').attr({'id': 'costoUnitario_' + filasTabla}).attr({'class':'form-control'});
				// precioImporte
				var inputCostoTotal = $('<input />').attr({'id': 'costoTotal_' + filasTabla}).attr({'class':'form-control'}).attr({'name':'costoTotal_'});	
				// botonLimpiar
				var buttonLimpiar = $('<button />').attr({'id': 'btnLimpiar_' + filasTabla}).attr({'class':'btn btn-danger'});
				buttonLimpiar.html('<span class="glyphicon glyphicon-remove-circle"></span> Eliminar Producto')
				console.log(cont);
				var tbody = $("table#remisionSalida").find('tbody');
				tbody.append($('<tr>').attr({'class':'fila'}).attr({'id':'numFila' + cont}).
					append($('<td>').append(chkDesechabeDes)).
					append($('<td>').append(chkDesechabCom)).
					append($('<td>').append(checkTrastes)).
					append($('<td>').append(inputCantidad)).
					append($('<td>').append(inputProducto)).
					append($('<td>').append(inputUnidad)).
					append($('<td>').append(inputCodigoBarras)).
					append($('<td>').append(selectDescripcion)).
					append($('<td>').append(inputCostoUnitario)).
					append($('<td>').append(inputCostoTotal)).
					append($('<td>').append(buttonLimpiar))		
				);
				
			//});//cierra el addRow
			
		}
		
		// cuando se presione el boton con id=addRow, se inserta una nueva fila en la tabla de productos
		$("button#addRow").on("click",function(){
			agregar();
			console.log("checked"); 
			$("#traste:checked").val()==1;
		});//cierra el addRow
		
		//Funcion Eliminar #btnLimpiar_2
 		$("table#remisionSalida").on("click", "button[id^='btnLimpiar_']", function(){
 			 $(this).closest('tr').remove();
 			calculaGrandTotal();
 		});//cierra funcion eliminar*/
 		
 		//Funcion buscar descripcion del producto
 		$("table#remisionSalida").on("change", "select[id^='descripcion_']", function(){
 			var descripcion= $(this).attr("id");
			var arr = descripcion.split('_');
			var id = $(this).val();
			//console.log(id);
			var numFila =  arr[1];
 			
 			$.each(jsonDesProductos,function(i,item){
 				if(jsonDesProductos[i].idProducto == id){
 					$("input#idProducto_"+numFila).val(jsonDesProductos[i].claveProducto);
 				}
			});
 			
 		});//cierra funcion buscar descripcion del producto
 		
 		//Funcion buscar Multiplo del producto
 		$("table#remisionSalida").on("change", "select[id^='descripcion_']", function(){
 			var claveProd= $(this).attr("id");
			var arr = claveProd.split('_');
			console.log(arr);
			var id = $(this).val();
			var numFila =  arr[1];

			var $url = window.location.origin + "/General/inventario/json/multiplos/idProducto/" + id ;
			//console.log($url);
			$.ajax({
				url: $url,
				dataType: "json",
				success: function(data){	
					$("select#idUnidad_"+numFila).empty();
					$.each(data, function(i,item){
						if(data[i].idProducto == id){
							//$("select#idUnidad_"+numFila).filter(jsonMultiplos[i].idUnidad);
							$("select#idUnidad_"+numFila).append($("<option></option>").attr("value",data[i].idUnidad).text(data[i].unidad));
						}	
					});
				}
			});
 		});//cierra funcion Multiplo del producto

 		$("a#generarJsonArray").on("click",function(){
 	 	});
 		

		//==================================================================== Calcular JsonArray
 		$("a#generarJsonArray").on("click",function(){
 			var tabla = $("table#remisionSalida > tbody  > tr");
 			var tipoEmpaque;
 			//Array Json de productos
 			var productos = [];
 			var empaque = [];
 			
 			tabla.each(function(){
 				var row = $(this);
 				var cantidad = row.find("input[id^='idCantidad_']").val();
 				var unidad = row.find("select[id^='idUnidad_']").val();
 				var codigoBarras = row.find("input[id^='codigoBarras_']").val();
 				var descripcion = row.find("select[id^='descripcion_']").val();
 				var precioUnitario = row.find("input[id^='costoUnitario_']").val();
 				var importe = row.find("input[id^='costoTotal_']").val();
 				var tipoDes = row.find("input[id^='desayuno']");
 				var tipoCom = row.find("input[id^='comida']");
 				var tipoMes = row.find("input[id^='traste']");

 				if (tipoDes.is(':checked')) {
 					tipoEmpaque = 'D';
 	 				console.log(tipoEmpaque);
 	 			}else if(tipoCom.is(':checked')){
 	 				tipoEmpaque = 'C';
 	 	 			console.log(tipoEmpaque);
 	 	 		}else{
 	 	 			tipoEmpaque = 'T';
 	 	 			console.log(tipoEmpaque);
 	 	 	 	}
 				
 				productos.push(new Producto(cantidad, unidad, codigoBarras, descripcion, precioUnitario, importe, tipoEmpaque));
 				if(cantidad.length < 1 || unidad == null|| descripcion.length < 1 || precioUnitario.length < 1 || importe.length < 1 ) {  
        			$('input[type="submit"]').attr('disabled', 'disabled');
        		}else{ 
        			$('input[type="submit"]').removeAttr('disabled');
        		} 
 			});
 			//console.dir(productos);
 			var myString = JSON.stringify(productos);
 			if ($("input#productos").val(myString)){	
 			};

 			
 			
 		});
 		
 		function Emp(tipoEmpaque) {
		  this.tipoEmpaque = tipoEmpaque;
		}
 		function Producto(cantidad, unidad, codigoBarras, descripcion, precioUnitario, importe, tipoEmpaque) {
		  this.cantidad = cantidad;
		  this.unidad = unidad;
		  this.codigoBarras = codigoBarras;
		  this.descripcion = descripcion;
		  this.precioUnitario = precioUnitario;
		  this.importe = importe;
		  this.tipoEmpaque = tipoEmpaque;
	
		}
	
        $("table#remisionSalida").on("change", 'input[id^="idCantidad_"], input[id^="costoUnitario_"]', function (event) {
        	calculaRow($(this).closest("tr"));
        	calculaGrandTotal();
        
    	});
    	
    	function calculaRow(row) {
   			var  precioUnitario= +row.find('input[id^="costoUnitario_"]').val();
    		var cantidad = +row.find('input[id^="idCantidad_"]').val();
    		row.find('input[id^="costoTotal_"]').val((cantidad * precioUnitario).toFixed(2));
		}
		
		function calculaGrandTotal() {	
    	var grandTotal = 0;
    	$("table#remisionSalida").find('input[id^="costoTotal_"]').each(function () {
        	grandTotal += +$(this).val(); 
    	});
    	
    	 $("input#total").val(grandTotal.toFixed(2));
    	 $("input#1-importePago").val(grandTotal.toFixed(2)); 
   		}
   		
		$("#1-pagada").on("change", function(){
			var total = $("#total").val();

			if ($("#1-pagada:checked").val()==1){
				$("#1-pagos").attr('disabled', 'disabled');
				$("#1-pagos").val(total);
			}else{
				$("#1-pagos").removeAttr("disabled");
				$("#1-pagos").val(0);
			}
		});

		$("#descuento").on("change", function(){
			var des = $("#descuento").val();
			var t = $("#total").val();
			var porcentaje;
			var tp;
			var td;

			var urlD = window.location.origin + "/General/inventario/json/obtenerdescuento/de/"+des;
			console.log(urlD);
			$.ajax({
				url: urlD,
				dataType: "json",
				success: function(data){
					if(data.idDescuentos == des){
						porcentaje = data.porcentaje;
						tp = porcentaje * t/100;
						td = t -tp;
						$('input#total').val(td);
					}
				}
			});
			calculaGrandTotal();
		});
		
		var idFila;
		//Funcion Eliminar Fila
		function eliminar(idFila){
			idFila = cont
			$('#numFila'+ idFila).remove();
		}

		
		//Funcion Eliminar Fila
 		$("table#remisionSalida").on("click", "button[id^='btnLimpiar_']", function(){
 			 
 		});
 		
	});//cierra document ready
</script>
