<?php 
	$pregunta = $this->pregunta;
	$opciones = $this->opciones;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"encuesta","controller"=>"pregunta","action"=>"edita","idPregunta"=>$pregunta->getIdPregunta())));
	$tipo = Zend_Registry::get("tipo");
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Detalle Pregunta
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-condensed">
				<thead>
					<tr>
						<th>Pregunta</th>
						<th>Tipo Pregunta</th>
						<th>Creación</th>
						<th>Contenedor</th>
						<th>Orden en Contenedor</th>
						<th>Navegar</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><?php echo $pregunta->getPregunta() ?></td>
						<td><?php echo $tipo[$pregunta->getTipo()] ?></td>
						<td><?php echo $pregunta->getFecha() ?></td>
						<td><?php echo $contenedor = ($pregunta->getOrigen() == "S") ? "Sección" : "Grupo" ; ?></td>
						<td><?php echo $pregunta->getOrden() ?></td>
						<td>
							<?php 
								$controller = ($pregunta->getOrigen() == "G") ? "grupo" : "seccion" ;
								$idDestino = ($pregunta->getOrigen() == "G") ? "idGrupo" : "idSeccion" ;; 
							?>
							<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>$controller,"action"=>"admin",$idDestino=>$pregunta->getIdOrigen()),null,true) ?>">
								Ir al Contenedor
							</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	
	<?php if($pregunta->getTipo() != "AB"){ ?>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">
				Opciones de la Pregunta
			</h3>
		</div>
		<div class="panel-body">
			<?php if($pregunta->getTipo() != "AB" && $pregunta->getOrigen() != "G"){ ?>
			<p>
				Las opciones de esta pregunta se pueden modificar.  
			</p>
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"pregunta","action"=>"opciones","idPregunta"=>$pregunta->getIdPregunta()), null, true); ?>">
				Agregar Opciones
			</a>
			<a class="btn btn-warning">
				Editar Opciones
			</a>
			<a class="btn btn-danger">
				Eliminar Opciones
			</a>
			<?php }else{ ?>
			<p>
				Las opciones de esta pregunta se modifican desde el grupo al que pertenece.  
			</p>
			<a class="btn btn-info">
				Ir al grupo
			</a>
			<?php } ?>
			<table class="table table-striped table-condensed">
				<thead>
					<th>Opción</th>
					<th>Creación</th>
				</thead>
				<tbody>
					<?php foreach ($opciones as $opcion) : ?>
					<tr>
						<td><?php echo $opcion->getOpcion() ?></td>
						<td><?php echo $opcion->getFecha() ?></td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</div>
	<?php } ?>
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Pregunta
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $formulario; ?>
		</div>
	</div>
	
	<div class="panel panel-danger">
		<div class="panel-heading">
			<h3 class="panel-title">
				Eliminar Pregunta
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-danger" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"pregunta","action"=>"baja","idPregunta"=>$pregunta->getIdPregunta()), null, TRUE); ?>">
				Eliminar Pregunta
			</a>
		</div>
	</div>
</section>