<?php 
	$pregunta = $this->pregunta;
	$formulario = $this->formulario;
?>
<section class="row">
	<article>
		<header>
			<h3>Detalle de la pregunta: <?php echo $pregunta->getPregunta() ?></h3>
		</header>
		<div>
			<table class="table table-striped table-condensed">
				<thead>
					<th>Pregunta</th>
					<th>Creación</th>
					<th>Tipo</th>
					<th>Orden</th>
					<th>Contenedor</th>
				</thead>
				<tbody>
					<tr>
						<td><?php echo $pregunta->getPregunta() ?></td>
						<td><?php echo $pregunta->getFecha() ?></td>
						<td><?php echo $pregunta->getTipo() ?></td>
						<td><?php echo $pregunta->getOrden() ?></td>
						<td><?php echo $origen = ($pregunta->getOrigen() == "S") ? "SECCION" : "GRUPO" ; ?></td>
						
					</tr>
				</tbody>
			</table>
		</div>
	</article>
	<article class="col-md-6">
		<header>
			<h3>Editar Pregunta</h3>
		</header>
		<div>
			<?php echo $formulario; ?>
		</div>
	</article>
	<article class="col-md-6">
		<header>
			<h3>Eliminar Pregunta</h3>
		</header>
		<div>
			<a class="btn btn-danger" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"pregunta","action"=>"baja","idPregunta"=>$pregunta->getIdPregunta(),), null, true) ?>">
				Eliminar Pregunta
			</a>
			<br /><br />
		</div>
	</article>
</section>