<?php 
	$formulario = $this->formulario;
    $tiposPregunta = Zend_Registry::get("tipo");
?>
<div class="row-fluid">
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <h5>Alta de Pregunta en <strong><?php echo $this->mensaje; ?></strong></h5>
            </div>
            <div class="widget-content">
                <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
                    <div class="control-group">
                        <label class="control-label" for="pregunta">Pregunta: </label>
                        <div class="controls">
                            <input class="span10" type="text" name="pregunta" />
                        </div>
                    </div>
                    
                    <div class="control-group">
                        <label class="control-label" for="tipoPregunta">Tipo Pregunta: </label>
                        <div class="controls">
                            <select class="span10" name="tipoPregunta">
                                <?php foreach ($tiposPregunta as $index => $value) : ?>
                                <option value="<?php echo $index ?>"><?php echo $value ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    
                    <div class="form-actions">
                        <div class="pull-right">
                            <button class="btn btn-success" type="submit">
                                <span class="icon"><i class="icon-plus"></i></span> Agregar Pregunta
                            </button>
                        </div>
                    </div>
                </form>
                <?php if(!is_null($this->opciones)){ $opciones = $this->opciones; ?>
                <article class="col-md-3">
                    <header>
                        <h3>
                            Opciones de la Pregunta:
                        </h3>
                    </header>
                    <div>
                        <table class="table table-striped table-condensed">
                            <tbody>
                                <?php foreach ($opciones as $key => $value) : ?>
                                <tr>
                                    <td><?php echo $value; ?></td>
                                </tr>   
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </article>
                <?php }  ?>
            </div>
        </div>
    </div>
</div>
