<section class="row">
	<article class="col-xs-9">
		<header>
			<h3>
				Nueva Pregunta en <?php echo $this->mensaje; ?>
			</h3>
		</header>
		<div>
			<?php echo $this->formulario; ?>
		</div>
	</article>
	<?php if(!is_null($this->opciones)){ $opciones = $this->opciones; ?>
	<article class="col-md-3">
		<header>
			<h3>
				Opciones de la Pregunta:
			</h3>
		</header>
		<div>
			<table class="table table-striped table-condensed">
				<tbody>
					<?php foreach ($opciones as $key => $value) : ?>
					<tr>
						<td><?php echo $value; ?></td>
					</tr>	
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</article>
	<?php }  ?>
</section>
