<?php
	$preferencias = $this->preferencias;	
	$opcionDAO = new Encuesta_DAO_Opcion;
	$docente = $this->docente;
	$pregunta = $this->pregunta;
	$grupo = $this->grupo;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Resultados de la pregunta
			</h3>
		</div>
		<div class="panel-body">
			<h4>Grupo: <strong><?php echo $grupo->getGrupo() ?></strong></h4>
			<h4>Docente: <strong><?php echo $docente->getApellidos().", ".$docente->getNombres() ?></strong></h4>
			<h4>Pregunta: <strong><?php echo $pregunta->getNombre() ?></strong></h4>
			
			<canvas width="550" height="330" id="myChart"></canvas>
		</div>
	</div>
</section>
<script>
	var options = {
		scaleBeginAtZero: true,
		scaleShowGridLines: true,
		scaleGridLineColor: "rgba(0,0,0,0.5)",
		scaleGridLineWidth: 1,
		scaleShowHorizontalLines: true,
		scaleShowVerticalLines: true,
		barShowStroke: true,
		barStrokeWidth: 1,
		barValueSpacing: 10,
		barDatasetSpacing: 1
	}
	
	var data = {
	    labels: [
	    	<?php foreach ($preferencias as $preferencia) {
	    		$opcion = $opcionDAO->obtenerOpcion($preferencia["idOpcionCategoria"]);
	    		echo "'".$opcion->getNombreOpcion() . "',";
			} ?>
			],
	    datasets: [
	        {
	            //label: "My First dataset",
	            fillColor: "rgba(135,206,250,0.5)",
	            strokeColor: "rgba(220,220,220,0.8)",
	            highlightFill: "rgba(30,144,255,0.75)",
	            highlightStroke: "rgba(220,220,220,1)",
	            //data: [65, 59, 80, 81, 56, 55, 40],
	            data: [
	            	<?php foreach ($preferencias as $preferencia) {
						echo $preferencia["preferencia"] . ",";
					} ?>]
	            //65, 59, 80, 81, 56, 55, 40]
	        }
	    ]
	};

	var ctx = $("#myChart").get(0).getContext("2d");
	var myNewChart = new Chart(ctx).Bar(data,options);
</script>