<?php 
	$pregunta = $this->pregunta;
	$formulario = $this->formulario;
?>
<section class="row">
	<article class="col-md-12">
		<header>
			<h3>Seleccion de  Opciones a Pregunta<br />
				Pregunta: <?php echo $pregunta->getPregunta(); ?>
			</h3>
		</header>
		<div>
			
			<form method="post" enctype="application/x-www-form-urlencoded" action="<?php echo $this->url(array(""=>""), null, true) ?>">
				<label></label><input type="text" />
			</form>
		</div>
		<div>
			<?php echo $formulario; ?>
		</div>
	</article>
</section>