<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

		<title>General Application</title>
		<meta name="description" content="">
		<meta name="author" content="Hector Rodriguez">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<!-- Replace favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
		<link rel="shortcut icon" href="<?php echo $this->baseUrl() ?>/public/images/icono.png">
		<link rel="apple-touch-icon" href="<?php echo $this->baseUrl() ?>/public/images/engranes.jpg">
		<!-- jQuery -->
        <script src="<?php echo $this->baseUrl() ?>/public/lib/jquery/jquery.min.js"></script>
        <!-- Bootstrap -->
        <link rel="stylesheet" charset="UTF-8" href="<?php echo $this->baseUrl() ?>/public/lib/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" charset="UTF-8" href="<?php echo $this->baseUrl() ?>/public/lib/bootstrap/css/bootstrap-theme.min.css" />
        <script src="<?php echo $this->baseUrl() ?>/public/lib/bootstrap/js/bootstrap.min.js"></script>
        <!-- Font-Awesome -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/public/lib/font-awesome/css/font-awesome.min.css" />
        <!-- jQuery UI -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/lib/jquery-ui/css/jquery-ui.min.css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/lib/jquery-ui/css/jquery-ui.structure.css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/lib/jquery-ui/css/jquery-ui.theme.css" />
        <script src="<?php echo $this->baseUrl(); ?>/public/lib/jquery-ui/js/jquery-ui.min.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/public/lib/jquery-ui/js/datepicker-es.js"></script>
        <!-- jQuery Validate -->
        <script src="<?php echo $this->baseUrl(); ?>/public/lib/jquery-validate/js/jquery.validate.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/public/lib/jquery-validate/js/additional-methods.js"></script>
        <!-- jQuery DataTables -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/lib/jquery-datatables/css/jquery.dataTables.min.css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/lib/jquery-datatables/css/responsive.bootstrap.min.css" />
        <script src="<?php echo $this->baseUrl(); ?>/public/lib/jquery-datatables/js/dataTables.bootstrap.min.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/public/lib/jquery-datatables/js/dataTables.responsive.min.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/public/lib/jquery-datatables/js/responsive.bootstrap.min.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/public/lib/jquery-datatables/js/jquery.dataTables.min.js"></script>
        <!-- Charts.js -->
        <script src="<?php echo $this->baseUrl(); ?>/public/lib/chartsjs/Chart.js"></script>
        <!-- Otros -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/public/ext/site/css/buttons.css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/public/ext/site/css/structure.css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/public/ext/site/css/graficas.css" />
        <script src="<?php echo $this->baseUrl(); ?>/public/ext/site/js/generartabla.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/public/ext/site/js/jQueryValidateConf.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/public/ext/site/js/jQueryDataTablesConf.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/public/ext/site/js/jQueryDataTablesConf.js"></script>
        
	</head>

	<body>
		<!-- Menu principal -->
		<?php echo $this->partial("partials/menus/principal.phtml"); ?>
		<?php
			$anchoLateral = "col-md-2";
			$anchoPrincipal = "col-md-10";
			$anchoTotal = "col-md-12";
		 ?>
		<br />
		<div class="container">
			<section class="main row">
				<aside class="<?php echo $clase = (is_null($this->links)) ? "hidden" : $anchoLateral ; ?>">
					<header>
						<h3></h3>
					</header>
					<?php if (!is_null($this->links)){?>
						<?php echo $this->partial("partials/menus/menuAside.phtml", array("links" => $this->links)); ?>
					<?php } ?>
				</aside>
				<!-- Contenido Web -->
				<article class="<?php echo $clase = (is_null($this->links)) ? $anchoTotal : $anchoPrincipal ; ?>">
					<?php echo $this->layout()->content; ?>
				</article>
			</section>
		</div>
	</body>
</html>

