<?php
	$grupo = $this->grupo;
	$capas = $this->capas;
	$formulario = $this->formulario;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Nueva Capa de Evaluación en el grupo: <strong><?php echo $grupo->getGrupo() ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $formulario ?>
		</div>
	</div>
	
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">
				Capas del grupo: <strong><?php echo $grupo->getGrupo() ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<tbody>
					<?php foreach ($capas as $capa) : ?>
					<tr>
						<td><?php echo $capa["nombreCapa"] ?></td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</section>