<?php
	$formulario = $this->formulario;
?>
<section class="row">
	<?php echo $formulario; ?>
</section>
<script>
	$().ready(function(){
		// Traemos los grados del server
		$("select#idNivel").on('change', function(){
			console.log(this.value);
			//Borro el contenido del select municipio
			//Obtengo los municipios del estado
			$url = "/General/public/encuesta/json/grados/idNivel/" + this.value;
			console.log($url);
			$.ajax({
				url: $url,
				dataType: "json",
				success: function(data){
					console.log($url);
					//console.dir(data);
					$("select#idGrado").empty();
					$.each(data, function(i,item){//function(key,value)		
						$("select#idGrado").append($("<option></option>").attr("value",data[i].idGrado).text(data[i].grado));
						//$("select#1-idMunicipio").append($("<option></option>").attr("value",key).text(value)); 
					});
					
				}
			});
		});
		// Traemos los grupos del server
		$("select#idGrado").on('change', function(){
			console.log(this.value);
			$idCiclo = $("select#idCicloEscolar").val();
			//Borro el contenido del select municipio
			//Obtengo los municipios del estado
			$url = "/General/public/encuesta/json/grupos/idGrado/" + this.value+"/idCiclo/"+$idCiclo;
			console.log($url);
			$.ajax({
				url: $url,
				dataType: "json",
				success: function(data){
					console.log($url);
					//console.dir(data);
					$("select#idGrupo").empty();
					$.each(data, function(i,item){//function(key,value)		
						$("select#idGrupo").append($("<option></option>").attr("value",data[i].idGrupo).text(data[i].grupo));
						//$("select#1-idMunicipio").append($("<option></option>").attr("value",key).text(value)); 
					});
					
				}
			});
		});
		
	});
</script>