<?php
	// ==============================================================================
	$nivelDAO = new Encuesta_DAO_Nivel;
	$gradoDAO = new Encuesta_DAO_Grado;
	$gruposDAO = new Encuesta_DAO_Grupos;
	$cicloDAO = new Encuesta_DAO_Ciclo;
	// ==============================================================================
	$niveles = $nivelDAO->obtenerNiveles();
	$ciclo = $cicloDAO->obtenerCicloActual();
?>
<section class="row">
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">
				Evaluaciones de Grupos
			</h3>
		</div>
		<div class="panel-body">
			<h4>4020</h4>
			<table class="table table-striped table-condensed">
				<tbody>
					<tr>
						<td>Capa A</td>
						<td>
							<a href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"4020","action"=>"A"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Serie Evaluaciones
							</a>
						</td>
					</tr>
					<tr>
						<td>Capa B</td>
						<td>
							<a href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"4020","action"=>"B"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Serie Evaluaciones
							</a>
						</td>
					</tr>
					<tr>
						<td>Capa C</td>
						<td>
							<a href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"4020","action"=>"C"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Serie Evaluaciones
							</a>
						</td>
					</tr>
					<tr>
						<td>Capa D</td>
						<td>
							<a href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"4020","action"=>"D"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Serie Evaluaciones
							</a>
						</td>
					</tr>
				</tbody>
			</table>
			<h4>5030</h4>
			<table class="table table-striped table-condensed">
				<tbody>
					<tr>
						<td>Capa A</td>
						<td>
							<a href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"5030","action"=>"A"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Serie Evaluaciones
							</a>
						</td>
					</tr>
					<tr>
						<td>Capa B</td>
						<td>
							<a href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"5030","action"=>"B"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Serie Evaluaciones
							</a>
						</td>
					</tr>
					<tr>
						<td>Capa C</td>
						<td>
							<a href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"5030","action"=>"C"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Serie Evaluaciones
							</a>
						</td>
					</tr>
					<tr>
						<td>Capa D</td>
						<td>
							<a href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"5030","action"=>"D"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Serie Evaluaciones
							</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</section>
