<section class="row">
	<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"materia","action"=>"consulta"),null,true) ?>">
		<span class="glyphicon glyphicon-search"></span> Consulta de Materias 
	</a>
	<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"materia","action"=>"alta"),null,true) ?>">
		<span class="glyphicon glyphicon-plus"></span> Alta de Materias
	</a>
</section>