<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Secundaria :: Tercer Grado :: Grupo A :: Capa D
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<th>Materia</th>
					<th>Profesor</th>
					<th>Evaluación</th>
				</thead>
				<tbody>
					<tr>
						<td>Soc. Studies</td>
						<td>Olvera, Dulce</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"323"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Computación</td>
						<td>Armida Verea, Ana Paula</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"324"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Matemáticas B</td>
						<td>Garrido Rangel, Marianella</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"386"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Taller de Costura</td>
						<td>Fonseca De la Rosa, María del Carmen</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"325"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Taller Danza</td>
						<td>Gonzalez Cid, Carlos Augusto</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"326"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Taller Diseño Interiores</td>
						<td>Landarte Limon, Gabriela</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"327"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Taller Diseño Arquitectónico</td>
						<td>Vartougian Carrillo, Shaque</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"328"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Taller de Arte</td>
						<td>Mijares Fernández, María</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"329"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Taller de Cocina</td>
						<td>Gallastegui Brambilla, Mónica</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"330"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Taller de Teatro</td>
						<td>Barber Silva, Denisse</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"331"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</section>