<?php 
	$encuesta = $this->encuesta;
?>
<section class="row">
	<article>
		<header>
			<h3>Resultados de la Encuesta:<?php echo $encuesta->getNombre() ?></h3> 
		</header>
		<div>
			<div id="canvas-holder">
		        <canvas id="chart-area2" width="300" height="300" />
		    </div>
		
		    <div id="chartjs-tooltip"></div>
		</div>
		
	</article>	
</section>
<script>
	Chart.defaults.global.customTooltips = function(tooltip) {

    	// Tooltip Element
        var tooltipEl = $('#chartjs-tooltip');

        // Hide if no tooltip
        if (!tooltip) {
            tooltipEl.css({
                opacity: 0
            });
            return;
        }

        // Set caret Position
        tooltipEl.removeClass('above below');
        tooltipEl.addClass(tooltip.yAlign);

        // Set Text
        tooltipEl.html(tooltip.text);

        // Find Y Location on page
        var top;
        if (tooltip.yAlign == 'above') {
            top = tooltip.y - tooltip.caretHeight - tooltip.caretPadding;
        } else {
            top = tooltip.y + tooltip.caretHeight + tooltip.caretPadding;
        }

        // Display, position, and set styles for font
        tooltipEl.css({
            opacity: 1,
            left: tooltip.chart.canvas.offsetLeft + tooltip.x + 'px',
            top: tooltip.chart.canvas.offsetTop + top + 'px',
            fontFamily: tooltip.fontFamily,
            fontSize: tooltip.fontSize,
            fontStyle: tooltip.fontStyle,
        });
    };

    var pieData = [{
        value: 20,
        color: "#F7464A",
        highlight: "#FF5A5E",
        label: "No"
    }, {
        value: 3,
        color: "#46BFBD",
        highlight: "#5AD3D1",
        label: "Si"
    }, {
        value: 100,
        color: "#FDB45C",
        highlight: "#FFC870",
        label: "Yellow"
    }];

    window.onload = function() {
        //var ctx1 = document.getElementById("chart-area1").getContext("2d");
        //window.myPie = new Chart(ctx1).Pie(pieData);

        var ctx2 = document.getElementById("chart-area2").getContext("2d");
        window.myPie = new Chart(ctx2).Pie(pieData);
    };
</script>