
<div>
    <header>
        <h3>Bienvenidos</h3>
    </header>
    <hr />
    <ul class="list-buttons-vertical">
        <li>
            <a class="mebutton mebutton-black mebutton-md" href="<?php echo $this->url(array('module'=>'inventario','controller'=>'inventario','action'=>'index'),null,true) ?>">
                <span class="fa fa-edit fa-lg"></span> Inventario
            </a>
        </li>
        <li>
            <a class="mebutton mebutton-blue mebutton-md" href="<?php echo $this->url(array('module'=>'contabilidad','controller'=>'empresas','action'=>'index'),null,true) ?>">
                <span class="fa fa-cogs fa-lg"></span> Contabilidad
            </a>
        </li>
        <li>
            <a class="mebutton mebutton-green mebutton-md" href="<?php echo $this->url(array('module'=>'Biblioteca','controller'=>'libro','action'=>'index'),null,true) ?>">
                <span class="fa fa-book fa-lg"></span> Biblioteca
            </a>
        </li>
        <li>
            <a class="mebutton mebutton-red mebutton-md" href="<?php echo $this->url(array('module'=>'encuesta','controller'=>'home','action'=>'index'),null,true) ?>">
                <span class="fa fa-bar-chart fa-lg"></span> Encuestas
            </a>
        </li>
    </ul>
</div>
