<section class="row">
	<article>
		<header>
			<h3>
				Empresas, Clientes y Proveedores en el Sistema.  
			</h3>
		</header>
		<div>
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"sistema","controller"=> "empresas","action" =>"index"),null,true) ?>">
				Empresas
			</a>
			<a class="btn btn-warning" href="<?php echo $this->url(array("module"=>"sistema","controller"=> "clientes","action" =>"index"),null,true) ?>">
				Clientes
			</a>
			<a class="btn btn-danger" href="<?php echo $this->url(array("module"=>"sistema","controller"=> "proveedores","action" =>"index"),null,true) ?>">
				Proveedores
			</a>
		</div>
	</article>
</section>