<?php 
	$fiscales = $this->fiscales;
	$empresaDAO = new Sistema_DAO_Empresa;
?>
<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Proveedores en el Sistema
		</h3>
	</div>
	<div class="panel-body">
		<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"proveedores","action"=>"alta",),null,true) ?>">
			<span class="glyphicon glyphicon-plus"></span> Nuevo Proveedor
		</a>
		<br /><br />
		<table class="table table-striped table-condensed">
			<thead>
				<th>R.F.C.</th>
				<th>Razon Social</th>
				<th>Administrar</th>
			</thead>
			<tbody>
				<?php foreach ($fiscales as $fiscal) : ?>
				<tr>
					<td><?php echo $fiscal->getRfc() ?></td>
					<td><?php echo $fiscal->getRazonSocial() ?></td>
					<td>
						<a class="btn btn-warning" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"proveedores","action"=>"proveedor","idFiscales"=>$fiscal->getIdFiscales()),null,true) ?>">
							<span class="glyphicon glyphicon-cog"></span> Administrar Proveedor
						</a>
					</td>
				</tr>
				<?php endforeach ?>
			</tbody>
		</table>
	</div>
</section>
<script>
	$(document).ready(function() {
		//===================================================================================
	    $('table.table').dataTable( {
	       "pagingType": "full_numbers",
	        "language": {
	        	"url": "//cdn.datatables.net/plug-ins/1.10.10/i18n/Spanish.json"
	        }
	    } );
	} );
</script>