<?php
	$idFiscales = $this->idFiscales;
	$tipoSucursal = $this->tipoSucursal;
	
	$empresaDAO = $this->empresaDAO;
	$fiscalesDAO = $this->fiscalesDAO;
	
	$empresa = $empresaDAO->obtenerEmpresaPorIdFiscales($idFiscales);
	$fiscal = $fiscalesDAO->obtenerFiscales($empresa["idFiscales"]);
	$sucursales = $empresaDAO->obtenerSucursales($idFiscales);
	$tiposSucursales = Zend_Registry::get("tipoSucursal");
	//print_r($sucursales);
	//print_r($empresa);
?>
<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Sucursales de la empresa: <strong><?php echo $fiscal->getRazonSocial() ?></strong>
		</h3>
	</div>
	<div class="panel-body">
		<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"sucursal","action"=>"alta","idFiscales"=>$idFiscales,"tipoSucursal"=>$tipoSucursal),null,true) ?>">
			<span class="glyphicon glyphicon-plus"></span> Agregar Sucursal
		</a>
		<table class="table table-striped table-condensed">
			<thead>
				<th>Configurar</th>
				<th>Sucursal</th>
				<th>Tipo</th>
			</thead>
			<tbody>
				<?php if(!is_null($sucursales)){
					foreach ($sucursales as $sucursal) : ?>
				<tr>
					<td>
						<a class="btn btn-info" href="<?php echo $this->url(array(),null,true) ?>">
							<span class="glyphicon glyphicon-cog"></span> Configurar
						</a>
					</td>
					<td>
						<a class="btn btn-link" idSucursal="<?php echo $sucursal["idSucursal"] ?>">
							<?php echo $sucursal["nombreSucursal"] ?></td>
						</a>
					<td><?php echo $tiposSucursales[$tipoSucursal]; ?></td>
				</tr>
				<?php endforeach; } ?>
			</tbody>
		</table>
	</div>
</section>

<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Domicilio
		</h3>
	</div>
	<div class="panel-body">
		<table id="tDomicilioSucursal" class="table table-striped table-condensed">
			<thead>
				<th>Configurar</th>
				<th>Estado</th>
				<th>Municipio</th>
				<th>C.P.</th>
				<th>Colonia</th>
				<th>Calle</th>
				<th>N.I.</th>
				<th>N.E.</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>

<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Telefonos
		</h3>
	</div>
	<div class="panel-body">
		<table id="tTelefonosSucursal" class="table table-striped table-condensed">
			<thead>
				<th>Configurar</th>
				<th>Lada</th>
				<th>Telefono</th>
				<th>Extensiones</th>
				<th>Descripción</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>

<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Emails
		</h3>
	</div>
	<div class="panel-body">
		<table class="table table-striped table-condensed">
			<thead>
				<th>Configurar</th>
				<th>Email</th>
				<th>Descripción</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>

<script>
	$().ready(function(){
		var base = "/General/public/"
		
		// ========================================================= Seleccion de sucursal
		$("a[idSucursal]").on('click',function(){
			console.log($(this).attr("idSucursal"));
			var idSucursal = $(this).attr("idSucursal");
			$url = "/General/public/sistema/json/sdomicilio/idSucursal/" + idSucursal;
			//console.log($url);
			// ======================================================= Carga de domicilio
			$.ajax({
				url: $url,
				dataType: "json",
				success: function(data){
					//console.log($url);
					//console.dir(data);
					//console.dir(data["calle"]);
					//console.dir(data["codigoPostal"]);
					//console.dir(data["colonia"]);
					// =======================================================
					
					var anchorConfigDomicilio = $('<a>').attr({'id': 'btnConfigDomicilio'}).attr({'class':'btn btn-info'}).attr({'href':base +"sistema/domicilio/edita/idDomicilio/"+data["idDomicilio"]}).append($('<span>').attr({'class':'glyphicon glyphicon-cog'})).text("Configurar");
					//var inputCostoTotal = $('<input />').attr({'id': 'costoTotal_' + filasTabla}).attr({'class':'form-control'}).attr({'name':'costoTotal_'});
					var tbody = $("table#tDomicilioSucursal").find('tbody');
					tbody.empty();
					tbody.append($('<tr>').
							append($('<td>').append(anchorConfigDomicilio)).
							append($('<td>').append(data["estado"]["estado"])).
							append($('<td>').append(data["municipio"]["municipio"])).
							append($('<td>').append(data["codigoPostal"])).
							append($('<td>').append(data["colonia"])).
							append($('<td>').append(data["calle"])).
							append($('<td>').append(data["numeroInterior"])).
							append($('<td>').append(data["numeroExterior"]))
						);
				}
			});
			
			// ======================================================= Carga de telefonos
			$url = base + "sistema/json/stelefonos/idSucursal/" + idSucursal;
			console.log($url);
			$.ajax({
				url: $url,
				dataType: "json",
				success: function(data){
					//console.log($url);
					//console.dir(data);
					//console.dir(data["calle"]);
					//console.dir(data["codigoPostal"]);
					//console.dir(data["colonia"]);
					// =======================================================
					var tbody = $("table#tTelefonosSucursal").find('tbody');
					tbody.empty();
					$.each(data,function(i,item){
						//selectDescripcion.append('<option value="'+jsonProductos[i].idProducto+'">'+jsonProductos[i].producto+'</option>');
						var anchorConfigTel = $('<a>').attr({'class':'btn btn-info'}).attr({'href':base +"sistema/domicilio/edita/idDomicilio/"+data[i]["idTelefono"]}).text("Configurar");
						tbody.append($('<tr>').
							append($('<td>').append(anchorConfigDomicilio)).
							append($('<td>').append(data["estado"]["estado"])).
							append($('<td>').append(data["municipio"]["municipio"])).
							append($('<td>').append(data["codigoPostal"])).
							append($('<td>').append(data["colonia"])).
							append($('<td>').append(data["calle"])).
							append($('<td>').append(data["numeroInterior"])).
							append($('<td>').append(data["numeroExterior"]))
						);
						
						
					});
					
					
					//var inputCostoTotal = $('<input />').attr({'id': 'costoTotal_' + filasTabla}).attr({'class':'form-control'}).attr({'name':'costoTotal_'});
					var tbody = $("table#tTelefonosSucursal").find('tbody');
					tbody.empty();
					tbody.append($('<tr>').
							append($('<td>').append(anchorConfigDomicilio)).
							append($('<td>').append(data["estado"]["estado"])).
							append($('<td>').append(data["municipio"]["municipio"])).
							append($('<td>').append(data["codigoPostal"])).
							append($('<td>').append(data["colonia"])).
							append($('<td>').append(data["calle"])).
							append($('<td>').append(data["numeroInterior"])).
							append($('<td>').append(data["numeroExterior"]))
						);
				}
			});
			
			/*
			// ======================================================= Carga de emails
			$.ajax({
				url: $url,
				dataType: "json",
				success: function(data){
					//console.log($url);
					//console.dir(data);
					//console.dir(data["calle"]);
					//console.dir(data["codigoPostal"]);
					//console.dir(data["colonia"]);
					// =======================================================
					
					var anchorConfigDomicilio = $('<a>').attr({'id': 'btnConfigDomicilio'}).attr({'class':'btn btn-info'}).attr({'href':base +"sistema/domicilio/edita/idDomicilio/"+data["idDomicilio"]}).text("Configurar");
					//var inputCostoTotal = $('<input />').attr({'id': 'costoTotal_' + filasTabla}).attr({'class':'form-control'}).attr({'name':'costoTotal_'});
					var tbody = $("table#tDomicilioSucursal").find('tbody');
					tbody.empty();
					tbody.append($('<tr>').
							append($('<td>').append(anchorConfigDomicilio)).
							append($('<td>').append(data["estado"]["estado"])).
							append($('<td>').append(data["municipio"]["municipio"])).
							append($('<td>').append(data["codigoPostal"])).
							append($('<td>').append(data["colonia"])).
							append($('<td>').append(data["calle"])).
							append($('<td>').append(data["numeroInterior"])).
							append($('<td>').append(data["numeroExterior"]))
						);
				}
			});
			
			*/
		});
		
		
	});	
</script>
