<?php
	$idFiscales = $this->idFiscales;
	$tipoSucursal = $this->tipoSucursal;
	
	$empresaDAO = $this->empresaDAO;
	$fiscalesDAO = $this->fiscalesDAO;
	
	$empresa = $empresaDAO->obtenerEmpresaPorIdFiscales($idFiscales);
	$fiscal = $fiscalesDAO->obtenerFiscales($empresa["idFiscales"]);
	$sucursales = $empresaDAO->obtenerSucursales($idFiscales);
	print_r($sucursales);
	//print_r($empresa);
?>
<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Sucursales de la empresa: <strong><?php echo $fiscal->getRazonSocial() ?></strong>
		</h3>
	</div>
	<div class="panel-body">
		<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"sucursal","action"=>"alta","idFiscales"=>$idFiscales,"tipoSucursal"=>$tipoSucursal),null,true) ?>">
			<span class="glyphicon glyphicon-plus"></span> Agregar Sucursal
		</a>
		<table class="table table-striped table-condensed">
			<thead>
				<th>Configurar</th>
				<th>Sucursal</th>
				<th>Tipo</th>
			</thead>
			<tbody>
				<?php if(!is_null($sucursales)){
					foreach ($sucursales as $sucursal) :
						
						
					?>
				<td></td>
				<td></td>
				<td></td>
				<?php endforeach; } ?>
			</tbody>
		</table>
	</div>
</section>

<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Domicilio
		</h3>
	</div>
	<div class="panel-body">
		<table class="table table-striped table-condensed">
			<thead>
				<th>Configurar</th>
				<th>Estado</th>
				<th>Municipio</th>
				<th>C.P.</th>
				<th>Colonia</th>
				<th>Calle</th>
				<th>N.I.</th>
				<th>N.E.</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>

<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Telefonos
		</h3>
	</div>
	<div class="panel-body">
		<table class="table table-striped table-condensed">
			<thead>
				<th>Configurar</th>
				<th>Lada</th>
				<th>Telefono</th>
				<th>Extensiones</th>
				<th>Descripción</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>

<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Emails
		</h3>
	</div>
	<div class="panel-body">
		<table class="table table-striped table-condensed">
			<thead>
				<th>Configurar</th>
				<th>Email</th>
				<th>Descripción</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>