<?php 
	$ciclo = $this->ciclo;
	$formulario = $this->formulario;
	//print_r($ciclo->toArray());
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Ciclo Escolar: <strong><?php echo $ciclo->getCiclo(); ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"ciclo","action"=>"index","idPlan"=>$ciclo->getIdPlanE()), null, true); ?>">
				<span class="glyphicon glyphicon-chevron-left"></span> Regresar a Ciclos Escolares.
			</a><br /><br />
			<table class="table table-striped table-condensed">
				<thead>
					<th>Ciclo</th>
					<th>Inicio</th>
					<th>Término</th>
					<th>Actual</th>
					<th>Descripción</th>
				</thead>
				<tbody>
					<tr>
						<td><?php echo $ciclo->getCiclo() ?></td>
						<td><?php echo $ciclo->getInicio() ?></td>
						<td><?php echo $ciclo->getTermino() ?></td>
						<td><?php echo $ciclo->getActual() ?></td>
						<td><?php echo $ciclo->getDescripcion() ?></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Ciclo Escolar: <strong><?php echo $ciclo->getCiclo(); ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $formulario ?>
		</div>
	</div>
</section>