<?php 
	$ciclo = $this->ciclo;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"encuesta","controller"=>"ciclo","action"=>"edita","idCiclo"=>$ciclo->getIdCiclo()),null,true));
?>
<section class="panel panel-warning">
	<div class="panel-heading">
		<h3 class="panel-title">
			Editar Ciclo Escolar: <strong><?php echo $ciclo->getCiclo(); ?></strong>
		</h3>
	</div>
	<div class="panel-body">
		<div>
			<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"ciclo","action"=>"index","idPlan"=>$ciclo->getIdPlan()), null, true); ?>">
				<span class="glyphicon glyphicon-chevron-left"></span> Regresar a Ciclos Escolares.
			</a>
		</div>
		<hr />
		<div>
			<?php echo $formulario ?>
		</div>
	</div>
</section>