<?php
	$empresa = $this->empresa;
	
	$empresaDAO = $this->empresaDAO;
	$fiscalesDAO = $this->fiscalesDAO;
	//  =============================================================
	$fiscal = $fiscalesDAO->obtenerFiscales($empresa["idFiscales"]);
	$sucursales = $empresaDAO->obtenerSucursales($empresa["idFiscales"]);
	$tipoSucursal = Zend_Registry::get('tipoSucursal');
	
?>
<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Proveedor: <strong><?php echo $fiscal->getRazonSocial() ?></strong>
		</h3>
	</div>
	<div class="panel-body">
		<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"proveedores","action"=>"proveedor","idFiscales"=>$fiscal->getIdFiscales()),null,true) ?>">
			<span class="glyphicon glyphicon-chevron-left"></span> Regresar a proveedor
		</a>
		<table class="table table-striped table-condensed">
			<thead>
				<th>Tipo Sucursal</th>
				<th>Sucursal</th>
			</thead>
			<tbody>
				<?php foreach ($sucursales as $sucursal) : ?>
				<tr>
					<td>
						
					</td>
					<td>
						
					</td>
				</tr>
				<?php endforeach ?>
			</tbody>
		</table>
	</div>
</section>

<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			
		</h3>
	</div>
	<div class="panel-body">
		<table class="table table-striped table-condensed">
			<thead>
				<th>Configurar</th>
				<th>Es sucursal</th>
				<th>Estado</th>
				<th>Municipio</th>
				<th>C.P.</th>
				<th>Colonia</th>
				<th>Calle</th>
				<th>N.I.</th>
				<th>N.E.</th>
			</thead>
			<tbody>
				
			</tbody>
		</table>
	</div>
</section>

<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			
		</h3>
	</div>
	<div class="panel-body">
		<table class="table table-striped table-condensed">
			<thead>
				<th>Configurar</th>
				<th>Lada</th>
				<th>Telefono</th>
				<th>Extensiones</th>
				<th>Descripción</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>

<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			
		</h3>
	</div>
	<div class="panel-body">
		<table class="table table-striped table-condensed">
			<thead>
				<th>Configurar</th>
				<th>Email</th>
				<th>Descripción</th>
			</thead>
			<tbody>
				
			</tbody>
		</table>
	</div>
</section>