<?php 
	$formulario = $this->formulario;
	$this->messageSuccess;
	$messageSuccess = $this->messageSuccess;
	$messageFail = $this->messageFail;
?>
<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Alta de Proveedor
		</h3>
	</div>
	<div class="panel-body">
		<?php if(!is_null($messageSuccess)){ ?>
			<div class="alert alert-success" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				  <span aria-hidden="true">&times;</span>
				</button>
				<?php echo $messageSuccess; ?>
			</div>
			<?php }elseif(!is_null($messageFail)){ ?>
			<div class="alert alert-danger" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				  <span aria-hidden="true">&times;</span>
				</button>
				<?php echo $messageFail; ?>
			</div>
			<?php } ?>
		<?php echo $formulario; ?>
	</div>
</section>

<script>
	$().ready(function(){
		$("select#1-idEstado").on('change', function(){
			console.log(this.value);
			//Borro el contenido del select municipio
			//Obtengo los municipios del estado
			$url = "/General/public/sistema/json/municipios/idEstado/" + this.value;
			console.log($url);
			$.ajax({
				url: $url,
				dataType: "json",
				success: function(data){
					console.log($url);
					console.dir(data);
					$("select#1-idMunicipio").empty();
					$.each(data, function(i,item){//function(key,value)		
						$("select#1-idMunicipio").append($("<option></option>").attr("value",data[i].idMunicipio).text(data[i].municipio));
						//$("select#1-idMunicipio").append($("<option></option>").attr("value",key).text(value)); 
					});
					
				}
			});
		});
		
	});
</script>