<?php 
	$eproveedor = $this->empresa;
	
	$fiscalesDAO = new Sistema_DAO_Fiscales;
	$fiscal = $fiscalesDAO->obtenerFiscales($eproveedor["idFiscales"]);
	$domiciliosFiscales = $fiscalesDAO->obtenerDomiciliosPorIdFiscal($eproveedor["idFiscales"]);
	$fiscalesTelefonos = $fiscalesDAO->obtenerTelefonosFiscales($eproveedor["idFiscales"]);
	$fiscalesEmails = $fiscalesDAO->obtenerEmailsFiscales($eproveedor["idFiscales"]);
	//print_r($fiscalesTelefonos);
	$estadoDAO = new Sistema_DAO_Estado;
	$municipioDAO = new Sistema_DAO_Municipio;
?>
<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Proveedor: <strong><?php echo $fiscal->getRazonSocial() ?></strong>
		</h3>
	</div>
	<div class="panel-body">
		<table class="table table-striped table-condensed">
			<thead>
				<th>Configuración</th>
				<th>Sucursales</th>
				<th>R.F.C.</th>
				<th>Razon Social</th>
			</thead>
			<tbody>
				<tr>
					<td>
						<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"fiscales","action"=>"edita","idFiscales"=>$fiscal->getIdFiscales()),null,TRUE); ?>">
							<span class="glyphicon glyphicon-cog"></span> Configurar
						</a>
					</td>
					<td>
						<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"proveedor","action"=>"sucursales","idFiscales"=>$fiscal->getIdFiscales(),"tipoSucursal"=>"SP",),null,true) ?>">
							<span class="glyphicon glyphicon-home"></span> Sucursales
						</a>
					</td>
					<td><?php echo $fiscal->getRfc() ?></td>
					<td><?php echo $fiscal->getRazonSocial() ?></td>
				</tr>
			</tbody>
		</table>
	</div>
</section>

<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Domicilios del Cliente: <strong><?php echo $fiscal->getRazonSocial() ?></strong>
		</h3>
	</div>
	<div class="panel-body">
		<table class="table table-striped table-condensed">
			<thead>
				<th>Administración</th>
				<th>Es sucursal</th>
				<th>Estado</th>
				<th>Municipio</th>
				<th>C.P.</th>
				<th>Colonia</th>
				<th>N.I.</th>
				<th>N.E.</th>
			</thead>
			<tbody>
				<?php foreach ($domiciliosFiscales as $domicilioFiscal) : 
					$municipio = $municipioDAO->obtenerMunicipio($domicilioFiscal->getIdMunicipio());
					$estado = $estadoDAO->obtenerEstado($municipio->getIdEstado());
					?>
					<tr>
						<td>
							<a class="btn btn-warning" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"domicilio","action"=>"edita","idDomicilio"=>$domicilioFiscal->getIdDomicilio()),null,true) ?>">
								<span class="glyphicon glyphicon-cog"></span> Administrar
							</a>
						</td>
						<td><?php echo ($fiscalesDAO->esSucursal($domicilioFiscal->getIdDomicilio(), $eproveedor["idFiscales"])) ? "Si" : "No" ;  ?></td>
						<td><?php echo $estado->getEstado(); ?></td>
						<td><?php echo $municipio->getMunicipio(); ?></td>
						<td><?php echo $domicilioFiscal->getCodigoPostal(); ?></td>
						<td><?php echo $domicilioFiscal->getColonia(); ?></td>
						<td><?php echo $domicilioFiscal->getNumeroInterior(); ?></td>
						<td><?php echo $domicilioFiscal->getNumeroExterior(); ?></td>
					</tr>
					<tr>
						<td><strong>Calle</strong></td>
						<td colspan="7"><?php echo $domicilioFiscal->getCalle(); ?></td>
					</tr>
				<?php endforeach ?>
			</tbody>
		</table>
	</div>
</section>

<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Telefonos
		</h3>
	</div>
	<div class="panel-body">
		<table class="table table-striped table-condensed">
			<thead>
				<th>Administrar</th>
				<th>Lada</th>
				<th>Telefono</th>
				<th>Extensiones</th>
				<th>Descripción</th>
			</thead>
			<tbody>
				<?php foreach ($fiscalesTelefonos as $fiscalTelefono) : ?>
				<tr>
					<td>
						<a class="btn btn-warning" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"telefono","action"=>"edita","idTelefono"=>$fiscalTelefono->getIdTelefono()),null,true) ?>">
							<span class="glyphicon glyphicon-cog"></span> Administrar
						</a>
					</td>
					<td><?php echo $fiscalTelefono->getLada() ?></td>
					<td><?php echo $fiscalTelefono->getTelefono() ?></td>
					<td><?php echo $fiscalTelefono->getExtensiones() ?></td>
					<td><?php echo $fiscalTelefono->getDescripcion() ?></td>
				</tr>
				<?php endforeach ?>
			</tbody>
		</table>
	</div>
</section>

<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Emails
		</h3>
	</div>
	<div class="panel-body">
		<table class="table table-striped table-condensed">
			<thead>
				<th>Administrar</th>
				<th>Email</th>
				<th>Descripción</th>
			</thead>
			<tbody>
				<?php foreach ($fiscalesEmails as $fiscalEmail) : ?>
					<tr>
						<td>
							<a class="btn btn-warning" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"email","action"=>"edita","idEmail"=>$fiscalEmail->getIdEmail()),null,TRUE) ?>">
								<span class="glyphicon glyphicon-cog"></span> Administrar
							</a>
						</td>
						<td><?php echo $fiscalEmail->getEmail() ?></td>
						<td><?php echo $fiscalEmail->getDescripcion() ?></td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</section>