<?php 
	$fiscalesDAO = $this->fiscalesDAO;
	$fiscales = $this->fiscales;
	$fiscalesCuentaContable = $this->fiscalesCuentaContable;
	//$empresaDAO = new Sistema_DAO_Empresa;
	$tiposProveedor = $fiscalesDAO->obtenerFiscalesTipoProveedor($fiscales->getIdFiscales());	
	$domiciliosFiscales = $fiscalesDAO->obtenerDomiciliosPorIdFiscal($fiscales->getIdFiscales());
	$fiscalesTelefonos = $fiscalesDAO->obtenerTelefonosFiscales($fiscales->getIdFiscales());
	$fiscalesEmails = $fiscalesDAO->obtenerEmailsFiscales($fiscales->getIdFiscales());
	
	$estadoDAO = new Sistema_DAO_Estado;
	$municipioDAO = new Sistema_DAO_Municipio;
	$tipoDAO = new Sistema_DAO_Empresa;
?>
<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Proveedor: <strong><?php echo $fiscales->getRazonSocial() ?></strong>
		</h3>
	</div>
	<div class="panel-body">
		<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"empresa","action"=>"proveedores"),null,true) ?>">
			<span class="glyphicon glyphicon-chevron-left"></span> Regresar a Proveedores
		</a>
		<table class="table table-striped table-condensed">
			<thead>
				<th>Configuración</th>
				<th>Sucursales</th>
				<th>R.F.C.</th>
				<th>Razon Social</th>
				<th>Tipo Proveedor</th>
				<th>Cuenta Contable</th>
				<th>Saldo</th>
			</thead>
			<tbody>
				<?php foreach ($tiposProveedor as $tipoProveedor) : 
					
					
				?>
				<tr>
					<td>
						<a class="btn btn-warning" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"proveedores","action"=>"edita","idFiscales"=>$fiscales->getIdFiscales()),null,TRUE); ?>">
							<span class="glyphicon glyphicon-cog"></span> Configurar
						</a>
					</td>
					<td>
						<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"proveedor","action"=>"sucursales","idFiscales"=>$fiscales->getIdFiscales(),"tipoSucursal"=>"SP",),null,true) ?>">
							<span class="glyphicon glyphicon-home"></span> Sucursales
						</a>
					</td>
					
					<td><?php echo $fiscales->getRfc() ?></td>
					<td><?php echo $fiscales->getRazonSocial() ?></td>
					<td><?php echo $tipoProveedor->getDescripcion() ?></td>
					<td><?php echo $fiscalesCuentaContable["cuenta"] ?>
					<td><?php echo $fiscalesCuentaContable["saldo"] ?>	
				</tr>
				<?php endforeach ?>
			</tbody>
		</table>
	</div>
</section>

<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Domicilio Fiscal del Proveedor: <strong><?php echo $fiscales->getRazonSocial() ?></strong>
		</h3>
	</div>
	<div class="panel-body">
		<table class="table table-striped table-condensed">
			<thead>
				<th>Configurar</th>
				<th>Es sucursal</th>
				<th>Estado</th>
				<th>Municipio</th>
				<th>C.P.</th>
				<th>Colonia</th>
				<th>Calle</th>
				<th>N.I.</th>
				<th>N.E.</th>
			</thead>
			<tbody>
				<?php foreach ($domiciliosFiscales as $domicilioFiscal) : 
					$municipio = $municipioDAO->obtenerMunicipio($domicilioFiscal->getIdMunicipio());
					$estado = $estadoDAO->obtenerEstado($municipio->getIdEstado());
					?>
					<tr>
						<td>
							<a class="btn btn-warning" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"domicilio","action"=>"edita","idDomicilio"=>$domicilioFiscal->getIdDomicilio()),null,true) ?>">
								<span class="glyphicon glyphicon-cog"></span> Configurar
							</a>
						</td>
						<td><?php echo ($fiscalesDAO->esSucursal($domicilioFiscal->getIdDomicilio(), $fiscales->getIdFiscales())) ? "Si" : "No" ;  ?></td>
						<td><?php echo $estado->getEstado(); ?></td>
						<td><?php echo $municipio->getMunicipio(); ?></td>
						<td><?php echo $domicilioFiscal->getCodigoPostal(); ?></td>
						<td><?php echo $domicilioFiscal->getColonia(); ?></td>
						<td><?php echo $domicilioFiscal->getCalle(); ?></td>
						<td><?php echo $domicilioFiscal->getNumeroInterior(); ?></td>
						<td><?php echo $domicilioFiscal->getNumeroExterior(); ?></td>
					</tr>
				<?php endforeach ?>
			</tbody>
		</table>
	</div>
</section>

<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Telefonos Fiscales del Proveedor: <strong><?php echo $fiscales->getRazonSocial() ?></strong>
		</h3>
	</div>
	<div class="panel-body">
		<table class="table table-striped table-condensed">
			<thead>
				<th>Configurar</th>
				<th>Lada</th>
				<th>Telefono</th>
				<th>Extensiones</th>
				<th>Descripción</th>
			</thead>
			<tbody>
				<?php foreach ($fiscalesTelefonos as $fiscalTelefono) : ?>
				<tr>
					<td>
						<a class="btn btn-warning" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"telefono","action"=>"edita","idTelefono"=>$fiscalTelefono->getIdTelefono()),null,true) ?>">
							<span class="glyphicon glyphicon-cog"></span> Configurar
						</a>
					</td>
					<td><?php echo $fiscalTelefono->getLada() ?></td>
					<td><?php echo $fiscalTelefono->getTelefono() ?></td>
					<td><?php echo $fiscalTelefono->getExtensiones() ?></td>
					<td><?php echo $fiscalTelefono->getDescripcion() ?></td>
				</tr>
				<?php endforeach ?>
			</tbody>
		</table>
	</div>
</section>

<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Emails Fiscales del Proveedor: <strong><?php echo $fiscales->getRazonSocial() ?></strong>
		</h3>
	</div>
	<div class="panel-body">
		<table class="table table-striped table-condensed">
			<thead>
				<th>Configurar</th>
				<th>Email</th>
				<th>Descripción</th>
			</thead>
			<tbody>
				<?php foreach ($fiscalesEmails as $fiscalEmail) : ?>
					<tr>
						<td>
							<a class="btn btn-warning" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"email","action"=>"edita","idEmail"=>$fiscalEmail->getIdEmail()),null,TRUE) ?>">
								<span class="glyphicon glyphicon-cog"></span> Configurar
							</a>
						</td>
						<td><?php echo $fiscalEmail->getEmail() ?></td>
						<td><?php echo $fiscalEmail->getDescripcion() ?></td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</section>