<?php
    $auth = $this->auth;
    $temas = $this->temas;
    $colecciones = $this->colecciones;
    $clasificaciones = $this->clasificaciones;
?>

<?php if (!is_null($auth) && $auth->hasIdentity()) { 
    $identity = $auth->getIdentity();
    
    ?>
<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-info">
          <div class="panel-heading">
              <h5 class="panel-title">Consulta Rápida de Recursos</h5>
          </div>
          <div class="panel-body">
              <a class="btn btn-danger" href="<?php echo $this->url(array("module"=>"biblioteca","controller"=>"home","action"=>"logout"),null,true) ?>">
                  <span class="glyphicon glyphicon-off"></span> Terminar Consultas
              </a>
              <hr />
              <div class="form-horizontal">
                  
                  <div class="form-group">
                      <label class="col-xs-2 control-label" for="clasificacion">Clasificación: </label>
                      <div class="col-xs-10">
                          <select id="idClasificacion" class="form-control" name="clasificacion">
                              <option value="0">Sin Clasificación</option>
                              <?php foreach ($clasificaciones as $clasificacion) : ?>
                              <option value="<?php echo $clasificacion["idClasificacion"] ?>"><?php echo utf8_encode($clasificacion["clasificacion"]) ?></option>
                              <?php endforeach ?>
                          </select>
                      </div>
                  </div>
                  
                  <div class="form-group">
                      <label class="col-xs-2 control-label" for="coleccion">Colección: </label>
                      <div class="col-xs-10">
                          <select id="idColeccion" class="form-control" name="coleccion">
                              <option value="0">Sin Colección</option>
                              <?php foreach ($colecciones as $coleccion) : ?>
                              <option value="<?php echo $coleccion["idColeccion"] ?>"><?php echo utf8_encode($coleccion["descripcion"]) ?></option>
                              <?php endforeach ?>
                          </select>
                      </div>
                  </div>
                  
                  <div class="form-group">
                      <label class="col-xs-2 control-label" for="titulo">Titulo: </label>
                      <div class="col-xs-10">
                          <input id="iTitulo" name="titulo" class="form-control" placeholder="Titulo Recurso..." required="required" />
                      </div>
                  </div>
                  
                  <div class="form-group">
                      <label class="col-xs-2 control-label" for="autor">Autor: </label>
                      <div class="col-xs-10">
                          <input id="iAutor" name="autor" class="form-control" placeholder="Autor Recurso..." required="required" />
                      </div>
                  </div>
                  
                  <div class="form-group">
                      <label class="col-xs-2 control-label" for="editorial">Editorial: </label>
                      <div class="col-xs-10">
                          <input id="iEditorial" name="editorial" class="form-control" placeholder="Editorial Recurso..." required="required" />
                      </div>
                  </div>
                  
                  <div class="form-group">
                      <div class="col-xs-offset-2 col-xs-10">
                          <button id="btnConsult" type="button" class="btn btn-success">
                              <span class="glyphicon glyphicon-flash"></span> Consultar
                          </button>
                      </div>
                  </div>
              </div>
          </div>
        </div>
        <!-- Resultados -->
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h5 class="panel-title">Resultados de la búsqueda</h5>
            </div>
            <div class="panel-body">
                <table id="tResults" class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>Titulo</th>
                            <th>Autor</th>
                            <th>Editorial</th>
                            <th>Pais</th>
                            <th>Temas</th>
                            <th>Detalles</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<?php } else { ?>
    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h5 class="panel-title"> Consulta Rapida de Recursos </h5>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
                        <div class="form-group">
                            <label class="col-xs-2 control-label">Clave Organización:</label>
                            <div class="col-xs-10">
                                <input name="claveOrganizacion" class="form-control" type="text" placeholder="Clave_Organizacion..." required="required" autofocus="" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-offset-2 col-xs-10">
                                <button type="submit" class="btn btn-success">
                                    <span class="glyphicon glyphicon-flash"></span> Acceso
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
<?php } ?>

<script>
    $().ready(function(){
        var url = window.location.origin + "/General/";
       console.log(url); 
       
       $("button#btnConsult").on('click',function(){
           console.log("Consulta solicitada");
           var idClasificacion = $("select#idClasificacion").val();
           var idColeccion = $("select#idColeccion").val();
           //var idTema = $("select#idTema").val();
           var iAutor = $("#iAutor").val();
           var iTitulo = $("#iTitulo").val();
           var iEditorial = $("#iEditorial").val();
           
           var pieceClasificacion = "";
           var pieceColeccion = "";
           //var pieceTema = "";
           var pieceAutor = "";
           var pieceTitulo = "";
           var pieceEditorial = "";
           
           if(idClasificacion != "0") pieceClasificacion = "idClasificacion/"+idClasificacion+"/";
           if(idColeccion != "0") pieceColeccion = "idColeccion/"+idColeccion+"/";
           //if(idTema != "0") pieceTema = "idTema/"+idTema+"/";
           if(iAutor != "") pieceAutor = "autor/"+iAutor+"/";
           if(iTitulo != "") pieceTitulo = "titulo/"+iTitulo+"/";
           if(iEditorial != "") pieceEditorial = "editorial/"+iEditorial+"/";
           
           var urlModule = url+"biblioteca/json/consultabasica/";
           var params = pieceClasificacion+pieceColeccion+pieceAutor+pieceTitulo+pieceEditorial;
           
           if(params != ""){
               var urlQuery = urlModule+params;
               console.log(urlQuery);
               
               $.ajax({
                    url: urlQuery,
                    dataType: "json",
                    success: function(data){
                        //console.log("Respuesta del server");
                        console.dir(data);
                        var tbody = $("table#tResults").find('tbody');
                        tbody.empty();
                        $.each(data, function(i, item){
                           console.log(item);
                           tbody.append($('<tr>').
                                append($('<td>').append(item["titulo"])).
                                append($('<td>').append(item["autor"])).
                                append($('<td>').append(item["editorial"])).
                                append($('<td>').append(item["idPaisPub"])).
                                append($('<td>').append("sinTemas")).
                                append($('<td>').append("detalles!"))
                           );
                        });
                    }
                });
               
           }else{
               console.log("No se ejecuta query!!");
           }
           
       });
    });
</script>