<div>
    <header>
        <h1>Bienvenido a Biblioteca</h1>
    </header>
    <hr />
    <div>
        <ul class="list-buttons-vertical">
            <li>
                <a class="mebutton mebutton-green mebutton-md" href="<?php echo $this->url(array("module"=>"biblioteca","controller"=>"home","action"=>"login"),null,true) ?>">
                    <span class="fa fa-sign-in"></span>  Login
                </a>
            </li>
            <li>
                <a class="mebutton mebutton-red mebutton-md" href="<?php echo $this->url(array("module"=>"biblioteca","controller"=>"home","action"=>"consulta"),null,true) ?>">
                    <i class="fa fa-check"></i>  Consulta Rapida
                </a>
            </li>
        </ul>
    </div>
</div>