<?php 	$proyectos = $this->proyectos;
	$sucursal = $this->sucursal;
	$cliente = $this->cliente;
	$fiscales = $this->fiscales;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"contabilidad", "controller"=>"proyectos", "action" => "alta"), null, true));
	$sucursalDAO = new Sistema_DAO_Sucursal;
	
	//$fiscalesDAO->obtenerFiscales($ecliente["idFiscales"]);
?>

<section class="row">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">
				Proyectos.
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"contabilidad","controller"=>"proyectos","action"=>"alta")) ?>">
				<span class="glyphicon glyphicon-plus"></span> Nuevo Proyecto
			</a>
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Numero Folio</th>
						<th>Sucursal</th>
						<th>Cliente</th>
						<th>Descripción</th>
						<th>Fecha Apertura</th>
						<th>Fecha Cierre</th>
						<th>Costo Inicial</th>
						<th>Costo Final</th>
						<th>Ganancia</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($proyectos as $proyecto) :
						$sucursal = $sucursalDAO->obtenerSucursal($proyecto->getIdSucursal());
						//print_r($fiscal);
					?>
					<tr>
						<td><?php echo $proyecto->getNumeroFolio() ?></td>
						<td><?php echo $sucursal->getNombreSucursal() ?></td>
						<td><?php echo $proyecto->getIdCliente() ?></td>
						<td><?php echo $proyecto->getDescripcion() ?></td>
						<td><?php echo $proyecto->getFechaApertura() ?></td>
						<td><?php echo $proyecto->getFechaCierre() ?></td>
						<td><?php echo $proyecto->getCostoInicial() ?></td>
						<td><?php echo $proyecto->getCostoFinal() ?></td>
						<td><?php echo $proyecto->getGanancia() ?></td>
						
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</section>