<?php $proyectos = $this->proyectos;
	$sucursal = $this->sucursal;
	$fiscales = $this->fiscales;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"contabilidad", "controller"=>"proyectos", "action" => "alta"), null, true));
	$sucursalDAO = new Sistema_DAO_Sucursal;
	$fiscalesDAO = new Sistema_DAO_Fiscales;
?>

<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Proyectos.
			</h3>	
		</div>
		<div class="panel-body">
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"contabilidad","controller"=>"proyectos","action"=>"alta")) ?>">
				<span class="glyphicon glyphicon-plus"></span> Nuevo Proyecto
			</a>
			
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Número</th>
						<th>Sucursal</th>
						<th>Cliente</th>
						<th>Descripción</th>
						<th>Fecha Apertura</th>
						<th>Fecha Cierre</th>
						<th>Costo Inicial</th>
						<th>Costo Final</th>
						<th>Ganancia</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($proyectos as $proyecto) :
						$sucursal = $sucursalDAO->obtenerSucursal($proyecto->getIdSucursal());
						//$fiscales = $fiscalesDAO->obtenerFiscales($proyecto->getIdCoP());
						//print_r($fiscal);
					?>
					<tr>
						<td><?php echo $proyecto->getNumeroFolio() ?></td>
						<td><?php echo $sucursal->getNombreSucursal() ?></td>
						<td><?php echo $proyecto->getDescripcion() ?></td>
						<td><?php echo $proyecto->getFechaApertura() ?></td>
						<td><?php echo $proyecto->getFechaCierre() ?></td>
						<td><?php echo $proyecto->getCostoInicial() ?></td>
						<td><?php echo $proyecto->getCostoFinal() ?></td>
						<td><?php echo $proyecto->getGanancia() ?></td>
						
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</section>
<script>
	$(document).ready(function() {
		//===================================================================================
	    $('table.table').dataTable( {
	       "pagingType": "full_numbers",
	        "language": {
	        	"url": "//cdn.datatables.net/plug-ins/1.10.10/i18n/Spanish.json"
	        }
	    } );
	});
</script>