<?php
	$formulario = $this->formulario;
?>
<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Gran Cafe del Centro: Proyecto por Fecha.
		</h3>
	</div>
	<div class="panel-body">
		<div class="container">
			<div class="col-md-6">
				<?php echo $formulario; ?>
			</div>
		</div>
	</div>
</section>
<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Proyecto Por Remision Cliente Liquidada.</h4>
		</div>
		<table id="detalleRemisonCafeL" class="table table-striped table-condensed">
			<thead>
				<th>Tipo Movimiento</th>
				<th>CoP</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>
<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Proyecto Por Remision Cliente Pendiente por Liquidar.</h4>
		</div>
		<table id="detalleRemisonCafeP" class="table table-striped table-condensed">
			<thead>
				<th>Tipo Movimiento</th>
				<th>CoP</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>

<script>
	$().ready(function(){
		var url = window.location.origin + "/General/";
			
		$("#idEmpresas").on('change',function(){
			//console.log($(this).val());
			var idEmp = $(this).val();
			if(idEmp != 0){
				var urlQuerySucursales = url + 'contabilidad/json/sucursalese/idFiscales/'+idEmp;
				//console.log(urlQuerySucursales);
				$.ajax({
					url: urlQuerySucursales,
					dataType: "json",
					success: function(data){
						console.dir(data);
						$("#idSucursal").empty();
						$("#idSucursal").append($("<option></option>").attr("value","0").text("Seleccione Sucursal..."));
						$.each(data, function (i,item){
							$("#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal));
						});
					}
				});
			}
		});
		
		
		$("select#idSucursal").on('click', function(){
			var url = window.location.origin + "/General/sistema/json/proyectos/idSucursal/" + this.value;
			$.ajax({
				url: url,
				dataType: "json",	
				success: function(data){
					$("select#idProyecto").empty();
					$.each(data, function(i,item){	
						$("select#idProyecto").append($("<option></option>").attr("value",data[i].idProyecto).text(data[i].descripcion)); 
					});
					
				}
			});
			
		});

		function AddRowRSCafe(){
			$('#detalleRemisonCafeL tbody').append('<tr><td><b>Total de registros</b></td><td><input id="totalRegRSCafe"class="form-control" style="width:120px"></input></td><td style="text-align:right"><b>Total:</b></td><td><input id="totalRSCafe"class="form-control" style="width:120px"></input></td></tr>');
    	}
    	function calculaTotalRSCafe(){
			var total = 0;
			var nFilas = $("#detalleRemisonCafeL tbody tr").length -1;
			$("table#detalleRemisonCafeL").find("td[id^='importe']").each(function(){
			   	total += +$(this).text(); 
			   	$("#totalRSCafe").val("$" + total.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ","));
			   	$("#totalRegRSCafe").val(nFilas);
			});
				
		}
		
    	function AddRowRSCafePendienteLiq(){
			$('#detalleRemisonCafeP tbody').append('<tr><td><b>Total de registros</b></td><td><input id="totalRegRSCafeP"class="form-control" style="width:120px"></input></td><td style="text-align:right"><b>Total:</b></td><td><input id="totalRSCafeP"class="form-control" style="width:120px"></input></td></tr>');
    	}
    	function calculaTotalRSCafePendienteLiq(){
			var total = 0;
			var nFilas = $("#detalleRemisonCafeP tbody tr").length -1;
			$("table#detalleRemisonCafeP").find("td[id^='importe']").each(function(){
			   	total += +$(this).text(); 
			   	$("#totalRSCafeP").val("$" + total.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ","));
			   	$("#totalRegRSCafeP").val(nFilas);
			});
				
		}
    	$("button#button").on("click", function(){
			var fechaI  = $("#fechaInicial").val();
			var fechaIn = fechaI.replace(/(\d\d)\/(\d\d)\/(\d{4})/, "$3-$2-$1");
			var fechaF  = $("#fechaFinal").val();
			var fechaFN  = fechaF.replace(/(\d\d)\/(\d\d)\/(\d{4})/, "$3-$2-$1");
			var idProyecto = $("select#idProyecto").val();
			var urlProyecto = window.location.origin + "/General/contabilidad/json/remisioncafel/idProyecto/" + idProyecto + "/fechaI/" + fechaIn + "/fechaF/" + fechaFN;
			//console.log(urlProyecto);
			//====================================================================>>
			$.ajax({
				url: urlProyecto,
				dataType: "json",
				success: function(data){
					var tbody = $("table#detalleRemisonCafeL").find('tbody');
					tbody.empty();
					$.each(data, function(i,item){
						
						var idTipoMovimiento = data[i].idTipoMovimiento;
						var tipo  =  window.location.origin + "/General/contabilidad/json/getdescripciontipomovto/idTipoMovimiento/" + idTipoMovimiento;
						console.log(tipo);
						
						if(idTipoMovimiento == 13){
							console.log("El tipo es factura Proveedor");
							tbody.append($('<tr>').
							append($('<td>').append("REMISION CLIENTE")).
							append($('<td>').append(data[i].razonSocial)).	
							append($('<td>').append(data[i].numeroFolio)).
							append($('<td>').append(data[i].totalImporte).attr("id", "importe"))
							
							);
						}
					});
					AddRowRSCafe();
					calculaTotalRSCafe();
				}
			});
		});

    	$("button#button").on("click", function(){
			var fechaI  = $("#fechaInicial").val();
			var fechaIn = fechaI.replace(/(\d\d)\/(\d\d)\/(\d{4})/, "$3-$2-$1");
			var fechaF  = $("#fechaFinal").val();
			var fechaFN  = fechaF.replace(/(\d\d)\/(\d\d)\/(\d{4})/, "$3-$2-$1");
			var idProyecto = $("select#idProyecto").val();
			var urlProyecto = window.location.origin + "/General/contabilidad/json/remisioncafep/idProyecto/" + idProyecto + "/fechaI/" + fechaIn + "/fechaF/" + fechaFN;
			//console.log(urlProyecto);
			//====================================================================>>
			$.ajax({
				url: urlProyecto,
				dataType: "json",
				success: function(data){
					var tbody = $("table#detalleRemisonCafeP").find('tbody');
					tbody.empty();
					$.each(data, function(i,item){
						
						var idTipoMovimiento = data[i].idTipoMovimiento;
						var tipo  =  window.location.origin + "/General/contabilidad/json/getdescripciontipomovto/idTipoMovimiento/" + idTipoMovimiento;
						console.log(tipo);
						
						if(idTipoMovimiento == 13){
							console.log("El tipo es factura Proveedor");
							tbody.append($('<tr>').
							append($('<td>').append("REMISION CLIENTE")).
							append($('<td>').append(data[i].razonSocial)).	
							append($('<td>').append(data[i].numeroFolio)).
							append($('<td>').append(data[i].totalImporte).attr("id", "importe"))
							
							);
						}
					});
					AddRowRSCafePendienteLiq();
					calculaTotalRSCafePendienteLiq();
				}
			});
		});
	});//document ready
</script>