<?php
	$empresas = $this->empresas;
	$formulario = $this->formulario;
?>
<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Busca Proyecto.
		</h3>
	</div>
	<div class="panel-body">
		<div class="container">
			<div class="col-md-6">
				<?php echo $formulario; ?>
			</div>
		</div>
	</div>
</section>
<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Proyecto Por Factura Cliente.</h4>
		</div>
		<table id="detalleProyectoxfc" class="table table-striped table-condensed" >
			<thead>
				<th>Tipo Movimiento</th>
				<th>CoP</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>

<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Proyecto Por Factura Proveedor.</h4>
		</div>
		<table id="detalleProyectoxfp" class="table table-striped table-condensed">
			<thead>
				<th>Tipo Movimiento</th>
				<th>CoP</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>

<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Proyecto Por Remision Entrada.</h4>
		</div>
		<table id="detalleRemisonC" class="table table-striped table-condensed">
			<thead>
				<th>Tipo Movimiento</th>
				<th>CoP</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>

<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Proyecto Por Remision Salida.</h4>
		</div>
		<table id="detalleRemisonP" class="table table-striped table-condensed">
			<thead>
				<th>Tipo Movimiento</th>
				<th>CoP</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>

<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Proyecto Por Nómina.</h4>
		</div>
		<table id="detalleProyectoNomina" class="table table-striped table-condensed">
			<thead>
				<th>Tipo Movimiento</th>
				<th>CoP</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
			<tfoot>
				
			</tfoot>
		</table>
	</div>
</section>
<script>
	$().ready(function(){
		var url = window.location.origin + "/General/";
		
		$("#idFiscales").on('change',function(){
			//console.log($(this).val());
			var idFiscal = $(this).val();
			if(idFiscal != 0){
				var urlQuerySucursales = url + 'contabilidad/json/sucursalese/idFiscales/'+idFiscal;
				console.log(urlQuerySucursales);
				$.ajax({
					url: urlQuerySucursales,
					dataType: "json",
					success: function(data){
						console.dir(data);
						$("#idSucursal").empty();
						$("#idSucursal").append($("<option></option>").attr("value","0").text("Seleccione Sucursal..."));
						$.each(data, function (i,item){
							$("#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal));
						});
					}
				});
			}
		});
		$("#idEmpresas").on('change',function(){
			//console.log($(this).val());
			var idEmp = $(this).val();
			if(idEmp != 0){
				var urlQuerySucursales = url + 'contabilidad/json/sucursalese/idFiscales/'+idEmp;
				console.log(urlQuerySucursales);
				$.ajax({
					url: urlQuerySucursales,
					dataType: "json",
					success: function(data){
						console.dir(data);
						$("#idSucursal").empty();
						$("#idSucursal").append($("<option></option>").attr("value","0").text("Seleccione Sucursal..."));
						$.each(data, function (i,item){
							$("#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal));
						});
					}
				});
			}
		});
		
		
		$("select#idSucursal").on('click', function(){
			var url = window.location.origin + "/General/sistema/json/proyectos/idSucursal/" + this.value;
			//console.log("$url");
			$.ajax({
				url: url,
				dataType: "json",	
				success: function(data){
					$("select#idProyecto").empty();
					$.each(data, function(i,item){	
						$("select#idProyecto").append($("<option></option>").attr("value",data[i].idProyecto).text(data[i].descripcion)); 
					});
					
				}
			});
			
		});
		function AddRow(){
			$('#detalleProyectoxfc tbody').append('<tr><td><b>Total de registros</b></td><td><input id="totalRegfc"class="form-control" style="width:120px"></input></td><td style="text-align:right"><b>Total:</b></td><td><input id="totalfc"class="form-control" style="width:120px"></input></td></tr>');
    	}
    	function calculaTotal(){
			var total = 0;
			var nFilas = $("#detalleProyectoxfc tbody tr").length -1;
			$("table#detalleProyectoxfc").find("td[id^='importe']").each(function(){
			   	console.log($(this).text());
			   	total += +$(this).text(); 
			   	console.log(total);
			   	$("#totalfc").val("$" + total.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ","));
			   	$("#totalRegfc").val(nFilas);
			 });
				
		}
		function AddRowFP(){
			$('#detalleProyectoxfp tbody').append('<tr><td><b>Total de registros</b></td><td><input id="totalRegfp"class="form-control" style="width:120px"></input></td><td style="text-align:right"><b>Total:</b></td><td><input id="totalfp"class="form-control" style="width:120px"></input></td></tr>');
    	}
    	function calculaTotalFP(){
			var total = 0;
			var nFilas = $("#detalleProyectoxfp tbody tr").length -1;
			$("table#detalleProyectoxfp").find("td[id^='importe']").each(function(){
			   	console.log($(this).text());
			   	total += +$(this).text(); 
			   	console.log(total);
			   	$("#totalfp").val("$" + total.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ","));
			   	$("#totalRegfp").val(nFilas);
			 });
				
		}
		function AddRowRE(){
			$('#detalleRemisonC tbody').append('<tr><td><b>Total de registros</b></td><td><input id="totalRegRE"class="form-control" style="width:120px"></input></td><td style="text-align:right"><b>Total:</b></td><td><input id="totalRE"class="form-control" style="width:120px"></input></td></tr>');
    	}
    	function calculaTotalRE(){
			var total = 0;
			var nFilas = $("#detalleRemisonC tbody tr").length -1;
			$("table#detalleRemisonC").find("td[id^='importe']").each(function(){
			   	console.log($(this).text());
			   	total += +$(this).text(); 
			   	console.log(total);
			   	$("#totalRE").val(total.toFixed(2));
			   	$("#totalRegRE").val(nFilas);
			 });
				
		}
		
		function AddRowRS(){
			$('#detalleRemisonP tbody').append('<tr><td><b>Total de registros</b></td><td><input id="totalRegRS"class="form-control" style="width:120px"></input></td><td style="text-align:right"><b>Total:</b></td><td><input id="totalRS"class="form-control" style="width:120px"></input></td></tr>');
    	}
    	function calculaTotalRS(){
			var total = 0;
			var nFilas = $("#detalleRemisonP tbody tr").length -1;
			$("table#detalleRemisonP").find("td[id^='importe']").each(function(){
			   	console.log($(this).text());
			   	total += +$(this).text(); 
			   	console.log(total);
			   	$("#totalRS").val("$" + total.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ","));
			   	$("#totalRegRS").val(nFilas);
			 });
				
		}
		
		function AddRowPN(){
			$('#detalleProyectoNomina tbody').append('<tr><td><b>Total de registros</b></td><td><input id="totalRegPN"class="form-control" style="width:120px"></input></td><td style="text-align:right"><b>Total:</b></td><td><input id="totalPN"class="form-control" style="width:120px"></input></td></tr>');
    	}
    	function calculaTotalPN(){
			var total = 0;
			var nFilas = $("#detalleProyectoNomina tbody tr").length -1;
			$("table#detalleProyectoNomina").find("td[id^='importe']").each(function(){
			   	console.log($(this).text());
			   	total += +$(this).text(); 
			   	console.log(total);
			   	$("#totalPN").val("$" + total.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ","));
			   	$("#totalRegPN").val(nFilas);
			 });
				
		}
		
		$("button#button").on("click", function(){
			var fechaI  = $("#fechaInicial").val();
			var fechaIn = fechaI.replace(/(\d\d)\/(\d\d)\/(\d{4})/, "$3-$2-$1");
			var fechaF  = $("#fechaFinal").val();
			var fechaFN  = fechaF.replace(/(\d\d)\/(\d\d)\/(\d{4})/, "$3-$2-$1");
			console.log(fechaIn);
			console.log(fechaFN);
		 	var idProyecto = $("select#idProyecto").val();
			var urlProyecto = window.location.origin + "/General/contabilidad/json/proyectoxfecha/idProyecto/" + idProyecto + "/fechaI/" + fechaIn + "/fechaF/" + fechaFN;
			//console.log(urlProyecto);
			$.ajax({
				url: urlProyecto,
				dataType: "json",
				success: function(data){
					console.dir(data);
					var tbody = $("table#detalleProyectoxfc").find('tbody');
					tbody.empty();
					$.each(data, function(i,item){
						var idTipoMovimiento = data[i].idTipoMovimiento;
						var tipo  =  window.location.origin + "/General/contabilidad/json/getdescripciontipomovto/idTipoMovimiento/" + idTipoMovimiento;
						console.log(tipo);
						
						if(idTipoMovimiento == 2){
							console.log("El tipo es factura Cliente");
							tbody.append($('<tr>').
							append($('<td>').append("FACTURA CLIENTE")).
							append($('<td>').append(data[i].razonSocial)).	
							append($('<td>').append(data[i].numeroFactura)).
							append($('<td>').append(data[i].total).attr("id", "importe"))
							
							);
							
						}
					});
					AddRow();
					calculaTotal();
				}
				
			});
			
		});
		$("button#button").on("click", function(){
			var fechaI  = $("#fechaInicial").val();
			var fechaIn = fechaI.replace(/(\d\d)\/(\d\d)\/(\d{4})/, "$3-$2-$1");
			var fechaF  = $("#fechaFinal").val();
			var fechaFN  = fechaF.replace(/(\d\d)\/(\d\d)\/(\d{4})/, "$3-$2-$1");
			var idProyecto = $("select#idProyecto").val();
			var urlProyectoFP = window.location.origin + "/General/contabilidad/json/proyectoprovxfecha/idProyecto/" + idProyecto + "/fechaI/" + fechaIn + "/fechaF/" + fechaFN;
			console.log(urlProyectoFP);
			//====================================================================>>Factura Proveedor
			$.ajax({
				url: urlProyectoFP,
				dataType: "json",
				success: function(data){
					console.dir(data);
					var tbody = $("table#detalleProyectoxfp").find('tbody');
					tbody.empty();
					$.each(data, function(i,item){
						var idTipoMovimiento = data[i].idTipoMovimiento;
						var tipo  =  window.location.origin + "/General/contabilidad/json/getdescripciontipomovto/idTipoMovimiento/" + idTipoMovimiento;
						console.log(tipo);
						
						if(idTipoMovimiento == 4){
							tbody.append($('<tr>').
							append($('<td>').append("FACTURA PROVEEDOR")).
							append($('<td>').append(data[i].razonSocial)).	
							append($('<td>').append(data[i].numeroFactura)).
							append($('<td>').append(data[i].total).attr("id", "importe"))
							
							);
						}
					});
					AddRowFP();
					calculaTotalFP();
				}
				
			});
		});
		$("button#button").on("click", function(){
			var fechaI  = $("#fechaInicial").val();
			var fechaIn = fechaI.replace(/(\d\d)\/(\d\d)\/(\d{4})/, "$3-$2-$1");
			var fechaF  = $("#fechaFinal").val();
			var fechaFN  = fechaF.replace(/(\d\d)\/(\d\d)\/(\d{4})/, "$3-$2-$1");
			console.log(fechaIn);
			console.log(fechaFN);
		 	var idProyecto = $("select#idProyecto").val();
			var urlProyecto = window.location.origin + "/General/contabilidad/json/proyectoxfecha/idProyecto/" + idProyecto + "/fechaI/" + fechaIn + "/fechaF/" + fechaFN;
			console.log(urlProyecto);
			//====================================================================>>Remision Cliente
			$.ajax({
				url: urlProyecto,
				dataType: "json",
				success: function(data){
					var tbody = $("table#detalleRemisonC").find('tbody');
					tbody.empty();
					$.each(data, function(i,item){
						var idTipoMovimiento = data[i].idTipoMovimiento;
						var tipo  =  window.location.origin + "/General/contabilidad/json/getdescripciontipomovto/idTipoMovimiento/" + idTipoMovimiento;
						console.log(tipo);
						
						if(idTipoMovimiento == 12){
							console.log("El tipo es factura Cliente");
							tbody.append($('<tr>').
							append($('<td>').append("REMISION SALIDA")).
							append($('<td>').append(data[i].razonSocial)).	
							append($('<td>').append(data[i].numeroFactura)).
							append($('<td>').append(data[i].total).attr("id", "importe"))
							
							);
							
						}
					});
					AddRowRE();
					calculaTotalRE();
				}
			});
		});
		
		$("button#button").on("click", function(){
			var fechaI  = $("#fechaInicial").val();
			var fechaIn = fechaI.replace(/(\d\d)\/(\d\d)\/(\d{4})/, "$3-$2-$1");
			var fechaF  = $("#fechaFinal").val();
			var fechaFN  = fechaF.replace(/(\d\d)\/(\d\d)\/(\d{4})/, "$3-$2-$1");
			var idProyecto = $("select#idProyecto").val();
			var urlProyecto = window.location.origin + "/General/contabilidad/json/proyectoxfecha/idProyecto/" + idProyecto + "/fechaI/" + fechaIn + "/fechaF/" + fechaFN;
			console.log(urlProyecto);
			//====================================================================>>Remision Cliente
			$.ajax({
				url: urlProyecto,
				dataType: "json",
				success: function(data){
					var tbody = $("table#detalleRemisonP").find('tbody');
					tbody.empty();
					$.each(data, function(i,item){
						var idTipoMovimiento = data[i].idTipoMovimiento;
						var tipo  =  window.location.origin + "/General/contabilidad/json/getdescripciontipomovto/idTipoMovimiento/" + idTipoMovimiento;
						console.log(tipo);
						
						if(idTipoMovimiento == 13 ){
							console.log("El tipo es factura Proveedor");
							tbody.append($('<tr>').
							append($('<td>').append("REMISION PROVEEDOR")).
							append($('<td>').append(data[i].razonSocial)).	
							append($('<td>').append(data[i].numeroFolio)).
							append($('<td>').append(data[i].totalImporte).attr("id", "importe"))
							);
						}
					});
					AddRowRS();
					calculaTotalRS();
				}
			});
		});
		
		$("button#button").on("click", function(){
			var fechaI  = $("#fechaInicial").val();
			var fechaIn = fechaI.replace(/(\d\d)\/(\d\d)\/(\d{4})/, "$3-$2-$1");
			var fechaF  = $("#fechaFinal").val();
			var fechaFN  = fechaF.replace(/(\d\d)\/(\d\d)\/(\d{4})/, "$3-$2-$1");
			var idProyecto = $("select#idProyecto").val();
			var urlProyecto = window.location.origin + "/General/contabilidad/json/proyectoxfecha/idProyecto/" + idProyecto + "/fechaI/" + fechaIn + "/fechaF/" + fechaFN;
			console.log(urlProyecto);
			//====================================================================>>Remision Cliente
			$.ajax({
				url: urlProyecto,
				dataType: "json",
				success: function(data){
					var tbody = $("table#detalleProyectoNomina").find('tbody');
					tbody.empty();
					$.each(data, function(i,item){
						
						var idTipoMovimiento = data[i].idTipoMovimiento;
						var tipo  =  window.location.origin + "/General/contabilidad/json/getdescripciontipomovto/idTipoMovimiento/" + idTipoMovimiento;
						console.log(tipo);
						
						if(idTipoMovimiento == 20 ){
							console.log("El tipo es factura Proveedor");
							tbody.append($('<tr>').
							append($('<td>').append("PAGO NOMINA")).
							append($('<td>').append(data[i].razonSocial)).	
							append($('<td>').append(data[i].numeroFolio)).
							append($('<td>').append(data[i].totalImporte).attr("id", "importe"))
							
							);
						}
					});
					AddRowPN();
					calculaTotalPN();
				}
			});
		});
	});//document ready
</script>