<?php 
	$clientes  = $this->clientes;
	//$proyectos = $this->proyectos;
?>
<div class="row">
	<div class="col-xs-12" >
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Busca Proyecto Por Cliente</h5>	
			</div>
			<div class="panel-body">
				<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
						<!--Clientes-->
						<div class="form-group">
							<label for="CoP" class="col-md-2 control-label">Clientes: </label>
							<div class="col-md-10">
								<select name="CoP" id="CoP" class="form-control">
									<option value="0">Seleccione Cliente...</option>
									<?php foreach ($clientes as $cliente) : ?>
									<option value="<?php echo $cliente["idFiscales"] ?>"><?php echo $cliente["razonSocial"] ?></option>
									<?php endforeach ?>
								</select>
							</div>
						</div>
						<!-- Boton consulta -->
						<div class="form-group">
							<div class="col-md-offset-2 col-md-10">
								<button id="queryProyecto" type="button" class="btn btn-success">
									<i class="fa fa-search"></i> Consultar Proyecto.
								</button>
							</div>
						</div>
					</form>
			</div>
		</div>
	</div>
</div>
<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Sucursal Cafetería Gran Café del Centro.</h4>
		</div>
		<table id="detalleProyectoCF" class="table table-striped table-condensed" >
			<thead>
				<th>Tipo Movimiento</th>
				<th>Proyecto</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>
<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Sucursal Zazil Consultores</h4>
		</div>
		<table id="detalleProyectoZA" class="table table-striped table-condensed" >
			<thead>
				<th>Tipo Movimiento</th>
				<th>Proyecto</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>
<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Sucursal Sirio Soluciones en Comercializacion SA de CV.</h4>
		</div>
		<table id="detalleProyectoxSI" class="table table-striped table-condensed" >
			<thead>
				<th>Tipo Movimiento</th>
				<th>Proyecto</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>
<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Sucursal IKAL.</h4>
		</div>
		<table id="detalleProyectoxIK" class="table table-striped table-condensed" >
			<thead>
				<th>Tipo Movimiento</th>
				<th>Proyecto</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>
<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Sucursal MINERVA.</h4>
		</div>
		<table id="detalleProyectoxMI" class="table table-striped table-condensed" >
			<thead>
				<th>Tipo Movimiento</th>
				<th>Proyecto</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>
<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Sucursal EVENTOS SOCIALES.</h4>
		</div>
		<table id="detalleProyectoxEV" class="table table-striped table-condensed" >
			<thead>
				<th>Tipo Movimiento</th>
				<th>Proyecto</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>
<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Sucursal KIIWIK.</h4>
		</div>
		<table id="detalleProyectoxKI" class="table table-striped table-condensed" >
			<thead>
				<th>Tipo Movimiento</th>
				<th>Proyecto</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>
<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Sucursal ARCA.</h4>
		</div>
		<table id="detalleProyectoxAR" class="table table-striped table-condensed" >
			<thead>
				<th>Tipo Movimiento</th>
				<th>Proyecto</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>
<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Sucursal GIHEX.</h4>
		</div>
		<table id="detalleProyectoxGX" class="table table-striped table-condensed" >
			<thead>
				<th>Tipo Movimiento</th>
				<th>Proyecto</th>
				<th>Número Factura</th>
				<th>Importe</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>

<script>
$().ready(function(){
	
	$("button#queryProyecto").on("click", function(){
		var CoP = $("select#CoP").val();
		var urlProyecto = window.location.origin + "/General/contabilidad/json/proyectocliente/CoP/" + CoP;
		console.log(urlProyecto);
		$.ajax({
			url: urlProyecto,
			dataType: "json",
			success: function(data){
				var tbody = $("table#detalleProyectoCF").find('tbody');
				tbody.empty();
				$.each(data, function(i,item){
					var sucu = data[i].idSucursal;
					if(sucu == 2 ){
						console.log("El tipo es factura Proveedor");
						tbody.append($('<tr>').
						append($('<td>').append(data[i].descripcionTipo)).
						append($('<td>').append(data[i].descripcion)).	
						append($('<td>').append(data[i].numeroFactura)).
						append($('<td>').append(data[i].total).attr("id", "importe")));
					}
				});
			//AddRowPN();
			//calculaTotalPN();
			}
		});
	});
	
	$("button#queryProyecto").on("click", function(){
		var CoP = $("select#CoP").val();
		var urlProyecto = window.location.origin + "/General/contabilidad/json/proyectocliente/CoP/" + CoP;
		console.log(urlProyecto);
		//====================================================================>>Remision Cliente
		$.ajax({
			url: urlProyecto,
			dataType: "json",
			success: function(data){
				var tbody = $("table#detalleProyectoZA").find('tbody');
				tbody.empty();
				$.each(data, function(i,item){
					var sucu = data[i].idSucursal;
					
					if(sucu == 3 ){
						console.log("El tipo es factura Proveedor");
						tbody.append($('<tr>').
						append($('<td>').append(data[i].descripcionTipo)).
						append($('<td>').append(data[i].descripcion)).	
						append($('<td>').append(data[i].numeroFactura)).
						append($('<td>').append(data[i].total).attr("id", "importe")));
					}
				});
			//AddRowPN();
			//calculaTotalPN();
			}
		});
	});
	$("button#queryProyecto").on("click", function(){
		var CoP = $("select#CoP").val();
		var urlProyecto = window.location.origin + "/General/contabilidad/json/proyectocliente/CoP/" + CoP;
		console.log(urlProyecto);
		//====================================================================>>Remision Cliente
		$.ajax({
			url: urlProyecto,
			dataType: "json",
			success: function(data){
				var tbody = $("table#detalleProyectoxSI").find('tbody');
				tbody.empty();
				$.each(data, function(i,item){
					var sucu = data[i].idSucursal;
					
					if(sucu == 4 ){
						tbody.append($('<tr>').
						append($('<td>').append(data[i].descripcionTipo)).
						append($('<td>').append(data[i].descripcion)).	
						append($('<td>').append(data[i].numeroFactura)).
						append($('<td>').append(data[i].total).attr("id", "importe")));
					}
				});
			//AddRowPN();
			//calculaTotalPN();
			}
		});
	});
	$("button#queryProyecto").on("click", function(){
		var CoP = $("select#CoP").val();
		var urlProyecto = window.location.origin + "/General/contabilidad/json/proyectocliente/CoP/" + CoP;
		console.log(urlProyecto);
		//====================================================================>>Remision Cliente
		$.ajax({
			url: urlProyecto,
			dataType: "json",
			success: function(data){
				var tbody = $("table#detalleProyectoxIK").find('tbody');
				tbody.empty();
				$.each(data, function(i,item){
					var sucu = data[i].idSucursal;
					
					if(sucu == 5 ){
						tbody.append($('<tr>').
						append($('<td>').append(data[i].descripcionTipo)).
						append($('<td>').append(data[i].descripcion)).	
						append($('<td>').append(data[i].numeroFactura)).
						append($('<td>').append(data[i].total).attr("id", "importe")));
					}
				});
			//AddRowPN();
			//calculaTotalPN();
			}
		});
	});
	$("button#queryProyecto").on("click", function(){
		var CoP = $("select#CoP").val();
		var urlProyecto = window.location.origin + "/General/contabilidad/json/proyectocliente/CoP/" + CoP;
		console.log(urlProyecto);
		//====================================================================>>Remision Cliente
		$.ajax({
			url: urlProyecto,
			dataType: "json",
			success: function(data){
				var tbody = $("table#detalleProyectoxMI").find('tbody');
				tbody.empty();
				$.each(data, function(i,item){
					var sucu = data[i].idSucursal;
					
					if(sucu == 6){
						tbody.append($('<tr>').
						append($('<td>').append(data[i].descripcionTipo)).
						append($('<td>').append(data[i].descripcion)).	
						append($('<td>').append(data[i].numeroFactura)).
						append($('<td>').append(data[i].total).attr("id", "importe")));
					}
				});
			//AddRowPN();
			//calculaTotalPN();
			}
		});
	});
	$("button#queryProyecto").on("click", function(){
		var CoP = $("select#CoP").val();
		var urlProyecto = window.location.origin + "/General/contabilidad/json/proyectocliente/CoP/" + CoP;
		console.log(urlProyecto);
		//====================================================================>>Remision Cliente
		$.ajax({
			url: urlProyecto,
			dataType: "json",
			success: function(data){
				var tbody = $("table#detalleProyectoxEV").find('tbody');
				tbody.empty();
				$.each(data, function(i,item){
					var sucu = data[i].idSucursal;
					
					if(sucu == 7){
						tbody.append($('<tr>').
						append($('<td>').append(data[i].descripcionTipo)).
						append($('<td>').append(data[i].descripcion)).	
						append($('<td>').append(data[i].numeroFactura)).
						append($('<td>').append(data[i].total).attr("id", "importe")));
					}
				});
			//AddRowPN();
			//calculaTotalPN();
			}
		});
	});
	$("button#queryProyecto").on("click", function(){
		var CoP = $("select#CoP").val();
		var urlProyecto = window.location.origin + "/General/contabilidad/json/proyectocliente/CoP/" + CoP;
		console.log(urlProyecto);
		//====================================================================>>Remision Cliente
		$.ajax({
			url: urlProyecto,
			dataType: "json",
			success: function(data){
				var tbody = $("table#detalleProyectoxKI").find('tbody');
				tbody.empty();
				$.each(data, function(i,item){
					var sucu = data[i].idSucursal;
					
					if(sucu == 8){
						tbody.append($('<tr>').
						append($('<td>').append(data[i].descripcionTipo)).
						append($('<td>').append(data[i].descripcion)).	
						append($('<td>').append(data[i].numeroFactura)).
						append($('<td>').append(data[i].total).attr("id", "importe")));
					}
				});
			//AddRowPN();
			//calculaTotalPN();
			}
		});
	});
	$("button#queryProyecto").on("click", function(){
		var CoP = $("select#CoP").val();
		var urlProyecto = window.location.origin + "/General/contabilidad/json/proyectocliente/CoP/" + CoP;
		console.log(urlProyecto);
		//====================================================================>>Remision Cliente
		$.ajax({
			url: urlProyecto,
			dataType: "json",
			success: function(data){
				var tbody = $("table#detalleProyectoxAR").find('tbody');
				tbody.empty();
				$.each(data, function(i,item){
					var sucu = data[i].idSucursal;
					
					if(sucu == 9){
						tbody.append($('<tr>').
						append($('<td>').append(data[i].descripcionTipo)).
						append($('<td>').append(data[i].descripcion)).	
						append($('<td>').append(data[i].numeroFactura)).
						append($('<td>').append(data[i].total).attr("id", "importe")));
					}
				});
			//AddRowPN();
			//calculaTotalPN();
			}
		});
	});
	$("button#queryProyecto").on("click", function(){
		var CoP = $("select#CoP").val();
		var urlProyecto = window.location.origin + "/General/contabilidad/json/proyectocliente/CoP/" + CoP;
		console.log(urlProyecto);
		//====================================================================>>Remision Cliente
		$.ajax({
			url: urlProyecto,
			dataType: "json",
			success: function(data){
				var tbody = $("table#detalleProyectoxGX").find('tbody');
				tbody.empty();
				$.each(data, function(i,item){
					var sucu = data[i].idSucursal;
					
					if(sucu == 10){
						tbody.append($('<tr>').
						append($('<td>').append(data[i].descripcionTipo)).
						append($('<td>').append(data[i].descripcion)).	
						append($('<td>').append(data[i].numeroFactura)).
						append($('<td>').append(data[i].total).attr("id", "importe")));
					}
				});
			//AddRowPN();
			//calculaTotalPN();
			}
		});
	});
	
});
	
</script>