<?php 
	$clientes  = $this->clientes;
	//$proyectos = $this->proyectos;
?>
<div class="row">
	<div class="col-xs-12" >
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Busca Proyecto Por Cliente</h5>	
			</div>
			<div class="panel-body">
				<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
					<div class="form-group">
						<label class="col-xs-2 control-label" for="CoP">Cliente: </label>
	                    <div class="col-xs-10">
	                    	<select name="CoP" id="CoP" class="form-control">
	                        	<?php  foreach($clientes as $cliente): ?>
									<option value="<?php echo $cliente["idFiscales"]; ?>"><?php echo $cliente["razonSocial"]; ?></option>
								<?php endforeach; ?>    
	                        </select>
	                    </div>
	                </div>
	                <div class="form-group">
						<div class="col-md-offset-2 col-md-10">
								<button id="queryProyecto" type="submit" class="btn btn-success">
									<i class="fa fa-search"></i> Consultar Proyecto.
								</button>
							</div>
	             	</div>
				</form>
			</div>
		</div>
	</div>
</div>