<?php 	$municipio = $this->municipio; 
		$formulario = $this->formulario;
		$formulario->setAction($this->url(array("module"=>"sistema", "controller"=>"municipios", "action" => "edita", "idMunicipio"=>$municipio->getIdMunicipio()), null, true));
		
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Detalle Municipio: <?php echo $municipio->getMunicipio(); ?>
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Municipio</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><?php echo $municipio->getMunicipio() ?></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Municipio
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $formulario; ?>
		</div>
	</div>
	
	<div class="panel panel-danger">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Municipio
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-danger" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"municipios", "action"=>"baja", "idMunicipio"=>$municipio->getIdMunicipio()), null, true) ?>">
				Eliminar Municipio
			</a>
		</div>
	</div>
	
</section>