<?php 	$estado = $this->estado;
		$municipios = $this->municipios;
		$formulario = $this->formulario;
		$formulario->setAction($this->url(array("module"=>"sistema", "controller"=>"municipios", "action" => "alta"), null, true));
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Municipios del estado: <?php echo $estado->getEstado() ?>.
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"municipios","action"=>"alta","idEstado"=>$estado->getIdEstado()),null, true) ?>">
				<span class="glyphicon glyphicon-plus"></span> Nuevo Municipio
			</a>
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Estado</th>
						<th>Municipio</th>
						<th>Administrar</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($municipios as $municipio) : ?>
					<tr>
						<td><?php echo $estado->getEstado() ?></td>
						<td><?php echo $municipio->getMunicipio() ?></td>
						<td>
							<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"sistema", "controller"=>"municipios", "action" => "admin", "idMunicipio" => $municipio->getIdMunicipio()), null, true); ?>">
								<span class="glyphicon glyphicon-cog"></span> Administrar
							</a>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</section>

