<html>
	<head>
		<title>Tabla Agregar Producto</title>
	</head>
	<body>
		<table border="1"> 
		<tr>
			
			<th>Cantidad</th>
			<th>Seleccionar Producto</th>
			<th>Seleccionar Unidad</th>
			<th>Codigo de Barras</th>
			<th>Descripcion</th>
			<th>Precio Unitario</th>
			<th>Importe</th>
		</tr>

		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
				<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
				
		</table>
	</body>
</html>
