<html>
	<head>
		<title> Agregar nueva nota de entrada</title>
	</head>
	<body>
		<div id="divContenedor">
			<h1>Productos</h1>
			<div id="divContenedorTabla">
				
				<table id="tabla">
			<thead>
				<tr>
					<th>Cantidad</th>
					<th>Seleccionar Producto</th>
					<th>Selecciones Unidad</th>
					<th>Codigo de Barras</th>
					<th>Descripcion</th>
					<th>Precio Unitario</th>
					<th>Importe</th>
				</tr>
			</thead>
			<tbody>
				
			</tbody>
			<tfoot>
				<tr>
					<td>Total</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					
					<td><span id="total">0</span></td>
				</tr>
			</tfoot>
		</table>
				</table>				
				<!-- Botón para agregar filas--> 
				<input type="button" value="agregar" onclick="AddItem()"  >
		
			</div>
		</div>
	</body>
</html>




