<?php 
	 $formulario = $this->formulario;
	 $messageFail = $this->messageFail;
	 $messageSuccess = $this->messageSuccess;
?>
<section>
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">Anticipo proveedor</h3>
		</div>
		<div class="panel-body">
			<div class="col-xs-6">
				<?php if(!is_null($messageSuccess)){ ?>
					<div class="alert alert-success" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						  <span aria-hidden="true">&times;</span>
						</button>
						<?php echo $messageSuccess; ?>
					</div>
				<?php }elseif(!is_null($messageFail)){ ?>
				<div class="alert alert-danger" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					  <span aria-hidden="true">&times;</span>
					</button>
					<?php echo $messageFail; ?>
				</div>
				<?php } ?><br />
				<?php echo $formulario; ?>
			</div>
		</div>
	</div>
</section>
<script>
$(document).ready(function (){
	
	$("select#idEmpresas").on('change', function(){
		var url = window.location.origin + "/General/sistema/json/sucursales/idFiscales/" + this.value;
		$.ajax({
			url: url,
			dataType: "json",
			success: function(data){
				$("select#idSucursal").empty();
				$.each(data, function(i,item){	
					$("select#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal)); 
				});
			}
		});	
	});
	
	$("select#idEmpresas").on('change', function(){
		$url = window.location.origin + "/General/contabilidad/json/bancosempresa/emp/" + this.value;
		console.log($url);
		$.ajax({
			url: $url,
			//console.log($ajax);
			dataType: "json",
			success: function(data){
				$("select#idBanco").empty();
				$.each(data, function(i,item){	
					$("select#idBanco").append($("<option></option>").attr("value",data[i].idBanco).text(data[i].banco));
				});
			}
		});
	});
	
});
</script>