<?php
	$formulario = $this->formulario;
	$datosFactura = $this->datosFactura;
	$proveedorFac = $this->proveedorFac;
	$sucursalFac = $this->sucursalFac;
?>

<!--Datos de factura-->
<section class="panel panel-info">
	<div class="panel-heading">
		<h3 class= "panel-title">Datos Factura</h3>
	</div>
	<div class="panel-body">
		<!--Numero de factura-->
		<div class="form-group">
			<label>Factura Seleccionada:</label>
			<div class="col-md-12">
				<input id="numeroFactura" name="numeroFactura" type="text" value="<?php echo $datosFactura["idFactura"]; ?>" class="form-control" disabled="true"/>
			</div>
		</div>	
		<!--Proveedor-->
		<label >Proveedor:</label>
		<div class="form-group">
			<div class="col-md-2">
				<input id="numeroProveedor" name="numeroProveedor" type="text" value="<?php echo $datosFactura["idCoP"];  ?>" class="form-control" disabled="true" />
			</div>
			<div class="col-md-10">
				<input id="proveedor" name="proveedor" type="text" value="<?php echo $proveedorFac["razonSocial"];  ?>" class="form-control" class="col-md-1" disabled="true"/>
			</div>	
		</div>
		<label>Sucursal:</label>
		<div class="form-group">
			<div class="col-md-2">
				<input id="numeroProveedor" name="numeroProveedor" type="text" value="<?php echo $sucursalFac["idSucursal"];  ?>" class="form-control" disabled="true" />
			</div>
			<div class="col-md-10">
				<input id="proveedor" name="proveedor" type="text" value="<?php echo $sucursalFac["nombreSucursal"];  ?>" class="form-control" class="col-md-1" disabled="true"/>
			</div>	
		</div>
		<!--idFactura-->
		<div class="form-group">
			<div class="col-md-12">
				<input id="idFactura" class="hidden" name="numeroFactura" type="text" value="<?php echo $datosFactura["idFactura"]; ?>" class="form-control" disabled="true"/>
			</div>
		</div>
		<br /><br />
		<!--Ver Pagos-->
		<div class="form-group">
			<a id="pagos" class="btn btn-info">
				<span class="glyphicon glyphicon-list"></span> Ver Pagos
			</a>
		</div>	
	</div>
</section>

<div id="relacionPagos" class="row hidden" >
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Relación de Pagos</h5>
			</div>
			<div class="panel-body">
				<div>
					<table id="detalleFacturaxp" class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Movimiento</th>
								<th>Pago</th>
								<th>Importe</th>
								<th>Divisa</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div>
			</div>
			
		</div>
	</div>
</div>
<br />
<section class="panel panel-warning">
	<div class="panel-heading">
		<h3 class="panel-title">Realizar Pago Factura</h3>
	</div>
	<div class="panel-body">
		<div class="col-md-12" >
			<?php echo $formulario; ?>
		</div>
	</div>
</section>
<script>
	$().ready(function(){
		var url = window.location.origin + "/General/"
		
		$("#pagos").on("click" ,function (){
			$("#relacionPagos").removeClass("hidden");
			var idFactura =  $("#idFactura").val();
			var urlpagos = url +'contabilidad/json/buscapagoxp/idFactura/' + idFactura;
			console.log(urlpagos);
			$.ajax({
					url: urlpagos,
					dataType: "json",
					success: function(data){
						console.dir(data);
						var tbody = $("#relacionPagos").find('tbody');
						tbody.empty();
						$.each(data, function(i,item){
							tbody.append( $('<tr>').
							append($('<td>').append("PF")).
							append($('<td>').append(data[i].secuencial)).
							append($('<td>').append(data[i].total)).
							append($('<td>').append(data[i].idDivisa))
							);
						});
					}		
			});
		});
		
	});
</script>