<?php
	$formulario = $this->formulario;
	$messageFail = $this->messageFail;
	$messageSuccess = $this->messageSuccess;
	
?>


<div id="relacionPagos" class="row hidden" >
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Relación de Pagos</h5>
			</div>
			<div class="panel-body">
				<div>
					<table id="detalleFacturaxp" class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Movimiento</th>
								<th>Pago</th>
								<th>Importe</th>
								<th>Divisa</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
						<tfoot>
   							<tr>
      							<td>Adeudo Factura:
      							<input id="total" name="total" type="text" value="<?php echo $datosFactura["total"]; ?>" class="form-control" disabled="true"/>
								</td>		
								<td>Saldo:
      							<input id="total" name="total" type="text" value="<?php echo $datosFactura["saldo"]; ?>" class="form-control" disabled="true"/>
								</td>
      							<td>Importe Pagado:
      							<input id="total" name="total" type="text" value="<?php echo $datosFactura["importePagado"]; ?>" class="form-control" disabled="true"/>
								</td>
   							 </tr>
   						</tr> 
					</table>
				</div>
			</div>
			
		</div>
	</div>
</div>
<br />
<section class="panel panel-warning">
	<div class="panel-heading">
		<h3 class="panel-title">Realizar Pago Factura</h3>
	</div>
	<div class="panel-body">
		<div class="col-md-12" >
			<?php if(!is_null($messageSuccess)){ ?>
				<div class="alert alert-success" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<?php echo $messageSuccess; ?>
				</div>
				<?php }elseif(!is_null($messageFail)){ ?>
				<div class="alert alert-danger" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					  <span aria-hidden="true">&times;</span>
					</button>
					<?php echo $messageFail; ?>
				</div>
				<?php } ?><br />
			<?php echo $formulario; ?>
		</div>
	</div>
</section>
<script>
	$().ready(function(){
		var url = window.location.origin + "/General/"
		
		$("#pagos").on("click" ,function (){
			$("#relacionPagos").removeClass("hidden");
			var idFactura =  $("#idFactura").val();
			var urlpagos = url +'contabilidad/json/buscapagoxp/idFactura/' + idFactura;
			console.log(urlpagos);
			$.ajax({
					url: urlpagos,
					dataType: "json",
					success: function(data){
						console.dir(data);
						var tbody = $("#relacionPagos").find('tbody');
						tbody.empty();
						$.each(data, function(i,item){
							tbody.append( $('<tr>').
							append($('<td>').append("PF")).
							append($('<td>').append(data[i].secuencial)).
							append($('<td>').append(data[i].total)).
							append($('<td>').append("MN"))
							);
						});
					}		
		});	
		});
		
	});
</script>