<?php
	$empresas = $this->empresas;
	$datosFacturas  =$this->datosFacturas;
?>
<section class="panel panel-success">
	<div class="panel-heading">
		<h4 class="panel-title">Búsqueda Anticipo Proveedores<strong></strong></h4>
	</div>
	<div class="panel-body">
		<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
			<div class="form-group">
				<label for="empresa" class="col-md-2 control-label">Empresas: </label>
				<div class="col-md-10">
					<select name="empresa" id="idFiscales" class="form-control">
						<option value="0">Seleccione Empresa</option>
						<?php foreach ($empresas as $empresa) : ?>
							<option value="<?php echo $empresa["idFiscales"] ?>"><?php echo $empresa["razonSocial"] ?></option>
						<?php endforeach ?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label for="sucursal" class="col-md-2 control-label">Sucursal: </label>
				<div class="col-md-10">
					<select required name="sucursal" id="idSucursal" class="form-control" >
					</select>
				</div>
			</div>
			<div class="form-group">
				<label for="prov" class="col-md-2 control-label">Proveedores: </label>
				<div class="col-md-10">
					<select required name="prov" id="idProv" class="form-control">
					</select>
				</div>
			</div>
			<!-- Boton consulta -->
			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<button id="queryCXP" type="button" class="btn btn-success">
						 <span class="glyphicon glyphicon-search"></span> Consultar
					</button>
				</div>
			</div>
		</form>
	</div>
</section>

<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Anticipo Proveedor.</h4>
		</div>
		<table id="detalleAnticipoProv" class="table table-striped table-condensed">
			<thead>
				<th>Sucursal</th>
				<th>Número Folio</th>
				<th>Fecha Pago</th>
				<th>Importe</th>
				<th>Crea Factura</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>	
</section>

<script>
$().ready(function(){
	var url = window.location.origin + "/General/";

	$("#idFiscales").on('change',function(){
		var idFiscal = $(this).val();
		if(idFiscal != 0){
			var urlQuerySucursales = url + 'contabilidad/json/sucursalese/idFiscales/'+idFiscal;
			$.ajax({
				url: urlQuerySucursales,
				dataType: "json",
				success: function(data){
					$("#idSucursal").empty();
					$("#idSucursal").append($("<option></option>").attr("value","0").text("Seleccione Sucursal..."));
					$.each(data, function (i,item){
						$("#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal));
					});
				}
			});

			var urlQueryProveedores = url + 'contabilidad/json/proveedorese/idFiscales/'+idFiscal;
			$.ajax({
				url: urlQueryProveedores,
				dataType: "json",
				success: function(data){
					$("select#idProv").empty();
					$("select#idProv").append($("<option></option>").attr("value","0").text("Seleccione Proveedor..."));
					$.each(data, function (i,item){
						$("select#idProv").append($("<option></option>").attr("value",data[i].idProveedores).text(data[i].razonSocial));
					});
				}
			});
		}
	});
		
	$("button#queryCXP").on("click", function(){
		var sucu = $("select#idSucursal").val();
		var pv = $("select#idProv").val();
		console.log(pv);
		var urlCXP = url + "contabilidad/json/buscaantprov/sucu/" + sucu +"/pv/"+pv;
		console.log(urlCXP);
		$.ajax({
			url: urlCXP,
			dataType: "json",
			success: function(data){
			var tbody = $("table#detalleAnticipoProv").find('tbody');
			tbody.empty();
					$.each(data, function(i,item){
						var botonPago = $('<button></button>').attr("id","fac").attr("class","btn btn-primary").text("Factura").attr("factura",data[i].idCoP);
						tbody.append($('<tr>').
							append($('<td>').append(data[i].idSucursal)).
							append($('<td>').append(data[i].numeroFolio)).
							append($('<td>').append(data[i].fechaPago)).
							append($('<td>').append(data[i].total).attr("id", "importe")).
							append($('<td>').append(botonPago)));
					});
				}		
			});
		});
		

		$("table#detalleAnticipoProv").on("click", "button[id^='fac']", function(){ 
		 console.log("Realizar Factura");
		 window.location = "/General/contabilidad/proveedor/enlazafactura";
		});
});
</script>
