<?php
	$formulario  = $this->formulario;
	$messageFail = $this->messageFail;
	$messageSuccess = $this->messageSuccess; 
?>
<section class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Factura Cliente.</h3>
		</div>
		<div class="panel-body">
			<?php if(!is_null($messageSuccess)){ ?>
				<div class="alert alert-success" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<?php echo $messageSuccess; ?>
				</div>
				<?php }elseif(!is_null($messageFail)){ ?>
				<div class="alert alert-danger" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					  <span aria-hidden="true">&times;</span>
					</button>
					<?php echo $messageFail; ?>
				</div>
				<?php } ?><br />
			<?php echo $formulario; ?>
		</div>
	</div>
</section>

<section class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Agregar Productos.</h3>
		</div>
		<div class="panel-body">
			<div class="form-inline">
				<button id="addRow" class="btn btn-success" >
					<span class="glyphicon glyphicon-plus" ></span> Nuevo
				</button>
				<a id="generarJsonArray" class="btn btn-primary">
					<span class="glyphicon glyphicon-cog" ></span> Cargar
				</a>
				<a class="form-inline">
					<button id="editaIva" class="btn btn-warning">
						<span class="glyphicon glyphicon-pencil"></span> Edita iva.
					</button>
				<input id="ivaPorcentaje" type="text" class="form-control" value="16" disabled="disabled" size="2"/>	
				</a>
			</div>
			<table id="productos" class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Cantidad</th>
						<th>Clave Producto</th>
						<th>Seleccione Unidad</th>
						<th>Codigo de Barras</th>
						<th>Descripción</th>
						<th>Precio Unitario</th>
						<th>Importe</th>
						<th>Eliminar</th>
					</tr>
				</thead>
				<tbody>
					<div id="empaque" align="right" class="hidden">
						<label class="radio-inline">
							<input type="radio" id="desayuno" name="1" value="desayuno"><strong>Desechable Desayuno</strong>
      					</label> 
      					<label class="radio-inline">
      						 <input type="radio" id="comida" name="1" value="comida"><strong>Desechable Comida</strong>
     				 	</label>
     				 	<label class="radio-inline">
							<input type="radio" id="traste" name="1" value="traste" checked="true"><strong>Traste</strong>
      					</label> 
     				 </div>
				</tbody>
				<tfoot>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td><strong>Subtotal:</strong></td>
						<td><input id="subTotal" class="form-control" /></td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td><strong>Descuento:</strong></td>
						<td><input id="descuento" class="form-control" value="0" /></td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td><strong>Subtotal descuento:</strong></td>
						<td><input id="descuentoGenerado" class="form-control" value="0" /></td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td><strong>Iva:</strong></td>
						<td><input id="iva" class="form-control"></td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td><strong>Total:</strong></td>
						<td><input id="total" class="form-control" /></td>
					</tr>
				</tfoot>
			</table>
		</div>
	</div>
</section>

<script>
$(document).ready(function (){
	console.log( "ready!" );
	var jsonProductos = <?php echo $this->jsonProductos; ?>;
	
    $("#addRow").on("click", function () {
    	var filasTabla = $("table#productos tbody > tr").length;
		filasTabla ++;
		var inputCantidad = $('<input />').attr({'id': 'idCantidad_' + filasTabla}).attr({'class':'form-control'}).attr({'size': '1' + filasTabla}).attr({'required:':'required'+ filasTabla});
		var inputProducto = $('<input />').attr({'id': 'idProducto_' + filasTabla}).attr({'class':'form-control'});
		var inputUnidad = $('<select required />').attr({'id': 'idUnidad_' + filasTabla}).attr({'class':'form-control'}).attr({'required':'true'});;
		// codigoBarras
		var inputCodigoBarras = $('<input />').attr({'id': 'codigoBarras_' + filasTabla}).attr({'class':'form-control'});
		// descripcion
		var selectDescripcion = $('<select />').attr({'id': 'descripcion_' + filasTabla}).attr({'class':'form-control'});
		$.each(jsonProductos,function(i,item){
			selectDescripcion.append('<option value="'+jsonProductos[i].idProducto+'">'+jsonProductos[i].producto+'</option>');
		});
		// precioUnitario
		var inputCostoUnitario = $('<input />').attr({'id': 'costoUnitario_' + filasTabla}).attr({'class':'form-control'});
		// precioImporte
		var inputCostoTotal = $('<input />').attr({'id': 'costoTotal_' + filasTabla}).attr({'class':'form-control'}).attr({'name':'costoTotal_'}).attr({'disabled':'true'});
		// botonLimpiar
		var buttonLimpiar = $('<button />').attr({'id': 'btnLimpiar_' + filasTabla}).attr({'class':'btn btn-danger'});
		buttonLimpiar.html('<span class="glyphicon glyphicon-remove-circle"></span> Eliminar Producto')

		var tbody = $("table#productos").find('tbody');
		tbody.append($('<tr>').
			append($('<td>').append(inputCantidad)).
			append($('<td>').append(inputProducto)).
			append($('<td>').append(inputUnidad)).
			append($('<td>').append(inputCodigoBarras)).
			append($('<td>').append(selectDescripcion)).
			append($('<td>').append(inputCostoUnitario)).
			append($('<td>').append(inputCostoTotal)).
			append($('<td>').append(buttonLimpiar))	
		);
  	});

    $("select#idEmpresas").on('change', function(){
		var url = window.location.origin + "/General/sistema/json/sucursales/idFiscales/" + this.value;
		//console.log(url);
		$.ajax({
			url: url,
			dataType: "json",
			success: function(data){
				//console.dir(data);
				$("select#idSucursal").empty();
				$.each(data, function(i,item){	
					$("select#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal)); 
				});	
			}
		});
		//Muestra radio button en caso de que sea Empresa Café del Centro o Eventos
		if(this.value == 6 || this.value == 9){
			$("div#empaque").removeClass("hidden");
		}else{
			$("div#empaque").addClass("hidden");
		}
		
	});

    $("select#idSucursal").on('click', function(){
		var url = window.location.origin + "/General/sistema/json/proyectos/idSucursal/" + this.value;
		//console.log(url);
		$.ajax({
			url:url,
			dataType: "json",
			success: function(data){
				//console.dir(data);
				$("select#idProyecto").empty();
				$.each(data, function(i,item){
					$("select#idProyecto").append($("<option></option>").attr("value",data[i].idProyecto).text(data[i].descripcion));
				});
			}
		});
	});

    //Funcion Eliminar #btnLimpiar_2
    $("table#productos").on("click", "button[id^='btnLimpiar_']", function(){
        if ($("table#productos tbody > tr").length >1)
    	{
    		$("table#productos  tbody > tr:last").remove();
    	}
    	calculateGrandTotal();
   	});//cierra funcion eliminar

   	//Funcion buscar descripcion del producto
   	$("table#productos").on("change", "select[id^='descripcion_']", function(){
   	   	console.log("Es idProducto");
   		var descripcion= $(this).attr("id");
		var arr = descripcion.split('_');
		var id = $(this).val();
		var numFila =  arr[1];
 		
 		$.each(jsonProductos, function(i,item){
 			if(jsonProductos[i].idProducto == id){
 				$("input#idProducto_"+numFila).val(jsonProductos[i].claveProducto);
 			}
 		});
   	});//cierra funcion buscar descripcion del producto

	//Funcion buscar Multiplo del producto
	$("table#productos").on("change", "select[id^='descripcion_']", function(){
		var descripcion= $(this).attr("id");
		var arr = descripcion.split('_');
		var id = $(this).val();
		var numFila =  arr[1];
		var $url = window.location.origin + "/General/inventario/json/multiplos/idProducto/" + id ;
		
		$.ajax({
			url: $url,
			dataType: "json",
			success: function(data){
				$("select#idUnidad_"+numFila).empty();
				$.each(data, function(i,item){
					if(data[i].idProducto == id){
						$("select#idUnidad_"+numFila).append($("<option></option>").attr("value",data[i].idUnidad).text(data[i].unidad));
					}						
				});
			}
		});
	});//cierra funcion Multiplo del producto

	$("a#generarJsonArray").on("click",function(){
    	var tabla = $("table#productos > tbody  > tr");
    	var tipoEmpaque;
 		//Array Json de productos
 		var productos = [];
 		
 		tabla.each(function(){
 			var row = $(this);
 			var cantidad = row.find("input[id^='idCantidad_']").val();
 			var claveProducto = row.find("input[id^='idProducto_']").val();
 			var unidad = row.find("select[id^='idUnidad_']").val();
 			var codigoBarras = row.find("input[id^='codigoBarras_']").val();
 			var descripcion = row.find("select[id^='descripcion_']").val();
 			var precioUnitario = row.find("input[id^='costoUnitario_']").val();
 			var importe = row.find("input[id^='costoTotal_']").val();
 		
 			if ($("#desayuno:checked").val()=="desayuno"){
 	 			tipoEmpaque  = 1;
			}else if($("#comida:checked").val()=="comida"){
				tipoEmpaque  = 2;
			}else{
				tipoEmpaque  = 0;
			}
 			productos.push(new Producto(cantidad,claveProducto, unidad, codigoBarras, descripcion, precioUnitario, importe, tipoEmpaque));

 			if(cantidad.length < 1 || claveProducto.length < 1 || unidad == null|| descripcion.length < 1 || precioUnitario.length < 1 || importe.length < 1 ) {  
        		$('input[type="submit"]').attr('disabled', 'disabled');
        	}else{ 
        		$('input[type="submit"]').removeAttr('disabled');
        	} 

 	 	});
 		//console.dir(productos);
		var myString = JSON.stringify(productos);
		//console.log(myString);
		if ($("input#productos").val(myString)){
		}
	});

	function Producto(cantidad, claveProducto, unidad, codigoBarras, descripcion, precioUnitario, importe, tipoEmpaque){
		this.cantidad = cantidad;
	 	this.claveProducto = claveProducto;
	  	this.unidad = unidad;
	  	this.codigoBarras = codigoBarras;
	  	this.descripcion = descripcion;
	  	this.precioUnitario = precioUnitario;
	  	this.importe = importe;
	 	this.tipoEmpaque = tipoEmpaque;
	}

	//Envia los valores de Impuestos a a la vista de facturaProveedor
   	$("a#generarJsonArray").on("click",function(){
   	   	var impuestos = [];
 		var subTotal = $("input#subTotal").val();
 		var descuento = $("input#descuento").val();
 		var iva = $("input#iva").val();
 		var total = $("input#total").val();
 			
 		impuestos.push(new Impuesto(subTotal, descuento, iva, total)); 

 		//console.dir(impuestos);
 		var myString = JSON.stringify(impuestos);
 		//console.log(myString);
 		if ($("input#importe").val(myString)){
 		};
 		
 		if ($("input#importe").val(myString)){
 		};
 	});

 	function Impuesto(subTotal, descuento, iva, total){
 	 	this.subTotal = subTotal;
		this.descuento = descuento;
		this.iva = iva;
		this.total = total;
	}
	$("table#productos").on("change", 'input[id^="idCantidad_"], input[id^="costoUnitario_"]', function (event) {
        calculateRow($(this).closest("tr"));
        calculateGrandTotal();
    });
 
	function calculateRow(row) {
    	var  precioUnitario= +row.find('input[id^="costoUnitario_"]').val();
    	var cantidad = +row.find('input[id^="idCantidad_"]').val();
    	row.find('input[id^="costoTotal_"]').val((cantidad * precioUnitario).toFixed(2));
	}
    
	function calculateGrandTotal() {
    	var grandTotal = 0;
    	var ivaPorcentaje;
    	var total;
    	var totalIva;
    	var descuento;
    	var totalDescuento;	    

    	$("table#productos").find('input[id^="costoTotal_"]').each(function (){
        	grandTotal += +$(this).val();
       	});
    
    	$("#grandtotal").text(grandTotal.toFixed(2));
    	$("#subTotal").val(grandTotal.toFixed(2));
    
    	//Calcula iva
   		ivaPorcentaje= $("#ivaPorcentaje").val();
   		//console.log(ivaPorcentaje);
    	totalIva = (ivaPorcentaje * grandTotal ) /100;
    	//console.log(totalIva);
    	$("input#iva").val(totalIva.toFixed(2));
    
    	//Total y pagos
    	total = grandTotal + totalIva;
    	$("input#total").val(total.toFixed(2));
    
   		descuento = $("#descuento").val();
   		if (descuento !=0){
   	   		totalIva = 0;
   			total = 0;
   			//console.log("El descuento es diferenre de cero");
   			totalDescuento = grandTotal - descuento;
   			$("input#descuentoGenerado").val(totalDescuento.toFixed(2));
   			totalIva = (ivaPorcentaje * totalDescuento ) /100;
   			//total = (totalDescuento * totalIva); console.log("Iva con descuento :" + totalIva);
   			$("input#iva").val(totalIva.toFixed(2)); 
   			total = totalDescuento + totalIva;
   			$("input#total").val(total.toFixed(2));
   		}			  
   }

  	//Habilita IvaPorcentaje
  	$("#editaIva").on("click",function(){
  	  	$("#ivaPorcentaje").removeAttr("disabled");
 		$("#ivaPorcentaje").attr({'value':'0'});

        if($("#ivaPorcentaje").val()!==0){
        	var ivaPorcentaje = parseFloat($("#ivaPorcentaje").val()) * parseFloat($("#subTotal").val()) /100;
         	var total = (parseFloat($("#subTotal").val()) + parseFloat($("#iva").val()));
         	$('input#iva').val(ivaPorcentaje);
         	$('input#total').val(total);
         }
    });

    //Edita IvaPorcentaje       
    $("#ivaPorcentaje").on("click",function(){
    	calculateGrandTotal();
    });

    //Calcula por si hay descuento       
    $("#descuento").on("click",function(){
    	calculateGrandTotal();
    });

	$("#1-pagada").on("change", function(){
		var total = $("#total").val();
		if ($("#1-pagada:checked").val()==1){
			//console.log("input desahabilitado");
			$("#1-pagos").attr('disabled', 'disabled');
			$("#1-pagos").val(total); 
			//calculateGrandTotal();
		}else{
			$("#1-pagos").removeAttr("disabled");
			$("#1-pagos").val(0);
			//console.log("input habilitado");
		}
	});
});
</script>
