<?php 
	$formulario  = $this->formulario;
	$messageFail = $this->messageFail;
	$messageSuccess = $this->messageSuccess;
	$facturasProveedorDAO = new Contabilidad_DAO_FacturaProveedor;
	$impuestoDAO = new Contabilidad_DAO_Impuesto;
	$impuestos = $impuestoDAO->obtenerImpuestos();	 
?>
<section class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Nueva Factura Proveedor.</h3>
		</div>
		<div class="panel-body">
				<?php if(!is_null($messageSuccess)){ ?>
					<div class="alert alert-success" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						  <span aria-hidden="true">&times;</span>
						</button>
						<?php echo $messageSuccess; ?>
					</div>
				<?php }elseif(!is_null($messageFail)){ ?>
				<div class="alert alert-danger" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					  <span aria-hidden="true">&times;</span>
					</button>
					<?php echo $messageFail; ?>
				</div>
				<?php } ?>
				<?php echo $formulario; ?>
		</div>
	</div>
</section>

<section class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Agregar Productos para Factura Proveedor.</h3>
		</div>
		<div class="panel-body"> 	
			<button id="addRow" class="btn btn-success" >
				<span class="glyphicon glyphicon-plus" ></span> Nuevo
			</button>
			<a id="generarJsonArray" class="btn btn-primary" data-toggle="modal" data-target="#msgConfirm">
				<span class="glyphicon glyphicon-cog" ></span> Cargar
			</a>
			<a class="form-inline">
				<button id="editarIva" class="btn btn-warning">
					<span class="glyphicon glyphicon-pencil" ></span> Editar Iva
				</button>
				<input id="ivaPorcentaje" type="text" class="form-control" value="16" disabled="disabled" size="5" >
			</a>
			
			<table id="productos" class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Cantidad</th>
						<th>Clave Producto</th>
						<th>Seleccione Unidad</th>
						<th>Codigo de Barras</th>
						<th>Descripción</th>
						<th>Precio Unitario</th>
						<th>Importe</th>
						<th>Eliminar</th>
					</tr>
				</thead>
				<tbody>	  
				</tbody>
				<tfoot>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td><strong>Subtotal:</strong></td>
						<td><input id="subTotal" class="form-control" /></td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td><strong>Descuento:</strong></td>
						<td><input id="descuento" class="form-control" value="0" /></td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td><strong>Subtotal generado despues del descuento:</strong></td>
						<td><input id="descuentoGenerado" class="form-control" value="0" /></td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td><strong>Iva:</strong></td>
						<td><input id="iva" class="form-control"></td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td><strong>Total:</strong></td>
						<td><input id="total" class="form-control" /></td>
					</tr>
				</tfoot>	
			</table>
			
			<table id="impuestos">
				<thead>
						<td  align="center" ><strong></strong></td>
					</thead>
					<tbody>
						<tr>
							<td align="center" ><strong>IEPS</strong></td>
							<td align="center"><strong>ISH</strong></td></td>
							<td align="center"><strong>ISR</strong></td>
						</tr>
						 <tr>
            				<td align="left"><input type="text" id="ieps" name="iEPS" size="15" class="form-control" value="0" ></td>
          				 	<td align="left"><input type="text" id="ish" name="ish" size="15" class="form-control" value="0"></td>
          				 	<td align="left"><input type="text" id="isr" name="isr" size="15" class="form-control" value="0"></td>	
          				 </tr>
          				 <tr>
            				
          				 </tr>
          				 <tr>
            				
          				 </tr>
					</tbody>
					<tfoot>
					</tfoot>
					
				</table>
				
		</div>
	</div>
</section>
	
<script>
$(document).ready(function () {
	var jsonProductos = <?php echo $this->jsonProductos; ?>;
	// cuando se presione el boton con id=addRow, se inserta una nueva fila en la tabla de productos
	$("button#addRow").on("click",function(){
		var filasTabla = $("table#productos tbody > tr").length;
		filasTabla ++;
		var inputCantidad = $('<input />').attr({'id': 'idCantidad_' + filasTabla}).attr({'class':'form-control'}).attr({'size': '1' + filasTabla}).attr({'required:':'required'+ filasTabla});
		var inputProducto = $('<input />').attr({'id': 'idProducto_' + filasTabla}).attr({'class':'form-control'});
		var inputUnidad = $('<select required />').attr({'id': 'idUnidad_' + filasTabla}).attr({'class':'form-control'}).attr({'required':'true'});;
		// codigoBarras
		var inputCodigoBarras = $('<input />').attr({'id': 'codigoBarras_' + filasTabla}).attr({'class':'form-control'});
		// descripcion
		var selectDescripcion = $('<select />').attr({'id': 'descripcion_' + filasTabla}).attr({'class':'form-control'});
		$.each(jsonProductos,function(i,item){
			selectDescripcion.append('<option value="'+jsonProductos[i].idProducto+'">'+jsonProductos[i].producto+'</option>');
		});
		// precioUnitario
		var inputCostoUnitario = $('<input />').attr({'id': 'costoUnitario_' + filasTabla}).attr({'class':'form-control'});
		// precioImporte
		var inputCostoTotal = $('<input />').attr({'id': 'costoTotal_' + filasTabla}).attr({'class':'form-control'}).attr({'name':'costoTotal_'}).attr({'disabled':'true'});
		// botonLimpiar
		var buttonLimpiar = $('<button />').attr({'id': 'btnLimpiar_' + filasTabla}).attr({'class':'btn btn-danger'});
		buttonLimpiar.html('<span class="glyphicon glyphicon-remove-circle"></span> Eliminar Producto')

		var tbody = $("table#productos").find('tbody');
		tbody.append($('<tr>').
			append($('<td>').append(inputCantidad)).
			append($('<td>').append(inputProducto)).
			append($('<td>').append(inputUnidad)).
			append($('<td>').append(inputCodigoBarras)).
			append($('<td>').append(selectDescripcion)).
			append($('<td>').append(inputCostoUnitario)).
			append($('<td>').append(inputCostoTotal)).
			append($('<td>').append(buttonLimpiar))	
		);
  	});
  	//Valida que la tabla este llena
    $("a#generarJsonArray").on("click",function(){
    	var tabla = $("table#productos > tbody  > tr");
 		var productos = [];
 		
 		tabla.each(function(){
 			var row = $(this);
 			var cantidad = row.find("input[id^='idCantidad_']").val();
 			var claveProducto = row.find("input[id^='idProducto_']").val();
 			var unidad = row.find("select[id^='idUnidad_']").val();
 			var codigoBarras = row.find("input[id^='codigoBarras_']").val();
 			var descripcion = row.find("select[id^='descripcion_']").val();
 			var precioUnitario = row.find("input[id^='costoUnitario_']").val();
 			var importe = row.find("input[id^='costoTotal_']").val();
 			
			if(cantidad.length < 1 || claveProducto.length < 1 || unidad == null|| descripcion.length < 1 || precioUnitario.length < 1 || importe.length < 1 ) {  
        		$('input[type="submit"]').attr('disabled', 'disabled');
        	}else{ 
        		$('input[type="submit"]').removeAttr('disabled');
        	} 
 		});
	 	//console.dir(productos);
	 	var myString = JSON.stringify(productos);
	 	//console.log(myString);
	 	if ($("input#productos").val(myString)){
	 	}
 	});
  	//Envia los valores del Producto a la vista de facturaProveedor
    $("a#generarJsonArray").on("click",function(){
    	var tabla = $("table#productos > tbody  > tr");
 		var productos = [];
 		
 		tabla.each(function(){
 			var row = $(this);
 			var cantidad = row.find("input[id^='idCantidad_']").val();
 			var claveProducto = row.find("input[id^='idProducto_']").val();
 			var unidad = row.find("select[id^='idUnidad_']").val();
 			var codigoBarras = row.find("input[id^='codigoBarras_']").val();
 			var descripcion = row.find("select[id^='descripcion_']").val();
 			var precioUnitario = row.find("input[id^='costoUnitario_']").val();
 			var importe = row.find("input[id^='costoTotal_']").val();
 						
 			productos.push(new Producto(cantidad, claveProducto, unidad, codigoBarras, descripcion, precioUnitario, importe));
 		});
	 	//console.dir(productos);
	 	var myString = JSON.stringify(productos);
	 	//console.log(myString);
	 	if ($("input#productos").val(myString)){
	 	}
 	});
 	
 	//Funcion Eliminar #btnLimpiar_2
 	 $("table#productos").on("click", "button[id^='btnLimpiar_']", function(){
 	 	if ($("table#productos tbody > tr").length >1)
 	 	{
 	 	 	$("table#productos  tbody > tr:last").remove();
  		}
  		calculateGrandTotal();
 	 });
 	 	
 	//Funcion buscar descripcion del producto
 	$("table#productos").on("change", "select[id^='descripcion_']", function(){
 		var descripcion= $(this).attr("id");
		var arr = descripcion.split('_');
		var id = $(this).val();
		var numFila =  arr[1];
 		
 		$.each(jsonProductos, function(i,item){
 			if(jsonProductos[i].idProducto == id){
 				$("input#idProducto_"+numFila).val(jsonProductos[i].claveProducto);
 			}
 		});
 	});//cierra funcion buscar descripcion del producto
 	
 	//Funcion buscar Multiplo del producto
 	$("table#productos").on("change", "select[id^='descripcion_']", function(){
 		var descripcion= $(this).attr("id");
		var arr = descripcion.split('_');
		var id = $(this).val();
		var numFila =  arr[1];
		var $url = window.location.origin + "/General/inventario/json/multiplos/idProducto/" + id ;
		
		$.ajax({
			url: $url,
			dataType: "json",
			success: function(data){
				$("select#idUnidad_"+numFila).empty();
				$.each(data, function(i,item){
					if(data[i].idProducto == id){
						$("select#idUnidad_"+numFila).append($("<option></option>").attr("value",data[i].idUnidad).text(data[i].unidad));
					}						
				});
			}
		});
 	});//cierra funcion Multiplo del producto
 		
 	//Envia los valores de Impuestos a a la vista de facturaProveedor
   	$("a#generarJsonArray").on("click",function(){
   		var impuestos = [];
 		var subTotal = $("input#subTotal").val();
 		var descuento = $("input#descuento").val();
 		var iva = $("input#iva").val();
 		var total = $("input#total").val();
 		var ieps = $("input#ieps").val();
 		var ish = $("input#ish").val();
 		var isr = $("input#isr").val();

 		impuestos.push(new Impuesto(subTotal, descuento, iva, total, ieps, ish,isr)); 
 			
 		//console.dir(impuestos);
 		var myString = JSON.stringify(impuestos);
 		//console.log(myString);
 		if ($("input#1-importes").val(myString)){
 		};
 	});
 		
 	function Producto(cantidad, producto,  unidad, codigoBarras, descripcion, precioUnitario, importe) {
		this.cantidad = cantidad;
		this.producto = producto;
		this.unidad = unidad;
		this.codigoBarras = codigoBarras;
		this.descripcion = descripcion;
		this.precioUnitario = precioUnitario;
		this.importe = importe;
	}
	
	function Impuesto(subTotal, descuento, iva, total, ieps, ish, isr) {
		this.subTotal = subTotal;
		this.descuento = descuento;
		this.iva = iva;
		this.total = total;
		this.ieps = ieps;
		this.ish = ish;
		this.isr = isr;
	}

    
    $("table#productos").on("change", 'input[id^="idCantidad_"], input[id^="costoUnitario_"]', function (event) {
        calculateRow($(this).closest("tr"));
        calculateGrandTotal();
    });
	
	function calculateRow(row) {
    	var  precioUnitario= +row.find('input[id^="costoUnitario_"]').val();
    	var cantidad = +row.find('input[id^="idCantidad_"]').val();
    	row.find('input[id^="costoTotal_"]').val((cantidad * precioUnitario).toFixed(2));
	}
    
	function calculateGrandTotal() {
    	var grandTotal = 0;
    	var ivaPorcentaje;
    	var total;
    	var totalIva;
    	var descuento;
    	var ieps;
    	var ish;
    	var totalIEPS;
    	var totalISH;
    	var totalDescuento;	    
    	$("table#productos").find('input[id^="costoTotal_"]').each(function () {
        	grandTotal += +$(this).val();  
   	 	});
    
    	//$("#grandtotal").text(grandTotal.toFixed(2));
    	$("#subTotal").val(grandTotal.toFixed(2));
    
   		//Calcula iva
   		ivaPorcentaje= $("#ivaPorcentaje").val();
   		console.log(ivaPorcentaje);
    	totalIva =  ($("#subTotal").val() * ivaPorcentaje ) /100;
    	console.log("total iva"+totalIva);
    	$("input#iva").val(totalIva.toFixed(2));
    
    	//Total
    	total = grandTotal + totalIva;
  		$("input#total").val(total.toFixed(2));
  		/*Descuento*/
   		descuento = $("#descuento").val();
	   	if (descuento !=0){
	   		totalIva = 0;
	   		total = 0;
	   		console.log("El descuento es diferenre de cero");
	   		totalDescuento = grandTotal - descuento;
	   		$("input#descuentoGenerado").val(totalDescuento.toFixed(2));
	   		totalIva = (ivaPorcentaje * totalDescuento ) /100;
	   		total = (totalDescuento * totalIva);
	   		console.log("Iva con descuento :" + totalIva);
	   		$("input#iva").val(totalIva.toFixed(2)); 
	   		total = totalDescuento + totalIva ;
	   		$("input#total").val(total.toFixed(2)); 
	   	}
	   	/*IEPS*/
   		ieps = $("#ieps").val();
   		console.log(ieps);
   		if (ieps !=0){
   	   		totalIEPS = parseFloat($("#subTotal").val()) + parseFloat($("input#iva").val()) + parseFloat( $("#ieps").val());
			console.log(totalIEPS);
			$("input#total").val(totalIEPS.toFixed(2)); 
   	   	}

   		/*ISH*/
   		ish = $("#ish").val();
   		console.log(ish);
   		if (ish !=0){
   	   		totalISH = parseFloat($("#subTotal").val()) + parseFloat($("input#iva").val()) + parseFloat( $("#ish").val());
			console.log(totalISH);
			$("input#total").val(totalISH.toFixed(2)); 
   	   	}

   		/*ISR*/
   		isr = $("#isr").val();
   		if (isr !=0){
   	   		totalISR = parseFloat($("#subTotal").val()) + parseFloat($("input#iva").val()) - parseFloat( $("#isr").val());
			console.log(totalISR);
			$("input#total").val(totalISR.toFixed(2)); 
   	   	}
   	}
   
  	//Habilita IvaPorcentaje
 	$("#editarIva").on("click",function(){
 		calculateGrandTotal();
        $("#ivaPorcentaje").removeAttr("disabled");
    });
  	//Edita IvaPorcentaje       
    $("#ivaPorcentaje").on("click",function(){
    	calculateGrandTotal();
    });
    $("#ieps").on('change',function(){
    	calculateGrandTotal();
    });
    $("#ish").on('change',function(){
    	calculateGrandTotal();
    });
    $("#isr").on('change',function(){
    	calculateGrandTotal();
    });
  	//Calcula por si hay descuento       
    $("#descuento").on("click",function(){
    	calculateGrandTotal();
     });
 		
 	$("select#idEmpresas").on('change', function(){
 		var url = window.location.origin + "/General/sistema/json/sucursales/idFiscales/" + this.value;
		$.ajax({
			url: url,
			dataType: "json",
			success: function(data){
				$("select#idSucursal").empty();
				$.each(data, function(i,item){
					$("select#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal)); 
				});
			}
		});
	});
		
	$("select#idSucursal").on('click', function(){
		var url = window.location.origin + "/General/sistema/json/proyectos/idSucursal/" + this.value;
		$.ajax({
			url:url,
			dataType: "json",
			success: function(data){
				$("select#idProyecto").empty();
				$.each(data, function(i,item){
					$("select#idProyecto").append($("<option></option>").attr("value",data[i].idProyecto).text(data[i].descripcion));
				});
			}
		});
	});
		
	$("#1-pagada").on("click", function(){
		var total = $("#total").val();
		if ($("#1-pagada:checked").val()==1){
			$("#1-pagos").attr('disabled', 'disabled');
			$("#1-pagos").val(total); 
		}else{
			$("#1-pagos").removeAttr("disabled");
			$("#1-pagos").val(0);
		}
			
	});
	
	$("table#productos").on("change", "select[id^='descripcion_']", function(){
		var descripcion= $(this).attr("id");
		var arr = descripcion.split('_');
		var id = $(this).val();
		var numFila =  arr[1];
		var $url = window.location.origin + "/General/contabilidad/json/productoimpuesto/idProducto/"+id;
		$("table#productos").on("change", "input[id^='costoUnitario_']", function(){
			//console.log("El producto contiene impuesto");
			//$("table#productos").on("change", "input[id^='costoUnitario_']", function(){
			var tabla = $("table#productos > tbody  > tr");
 			tabla.each(function(){
 				var ieps = 0; 
 				var row = $(this);
				var cantidad = row.find("input[id^='idCantidad_']").val(); 		
				var importe = row.find("input[id^='costoTotal_']").val();
 				$.ajax({
 					url: $url,
					dataType: "json",
					success: function(data){
						$.each(data, function(i,item){
							if(data[i].idProducto == id){
								$("table#productos").find('input[id^="costoTotal_"]').each(function () {
									//ieps += +parseFloat(data[i].importe * importe * cantidad);
									ieps += +$(this).val() * data[i].importe ;
									//console.log(ieps);
									$('input#ieps').val(ieps);
								});
							}else{
								console.log("El producto no contiene impuesto");
							}
						});
					}
				});
 			});
		});
		calculateGrandTotal();
	});   		
});
 
</script>