<table id="order-list" class="table table-striped table-condensed">
    <thead>
        <tr>
        	<td>Cantidad</td>
        	<td>Clave Producto</td>
        	<td>Seleccione Unidad</td>
        	<td>Codigo de Barras</td>
        	<td>Descripción</td>
        	<td>Precio Unitario</td>
        	<td>Importe</td>
        	<td>Eliminar</td>
        
        </tr>
    </thead>
    
    <tbody>
        <tr>
            <td><input  name="cantidad_" class="form-control" /></td>
            <td><input  name="idProducto_" class="form-control" /></td>
            <td><select  name="idUnidad_" class="form-control" /></td>
            <td><input  name="codigoBarras_" class="form-control" /></td>
            <td><select  name="descripcion_" class="form-control" /></td>
            <td>$<input  name="costoUnitario_" class="form-control" /></td>
            <td>$<input  name="costoTotal_" class="form-control" /></td>
            <td><a class="deleteRow"> x </a></td>
        </tr>
    </tbody>
    
    <tfoot>
    	
        <tr>
            <td >
                <input type="button" id="addrow" value="Agregar Producto" class="btn btn-success"/>
            </td>
        </tr>
        
        <tr>
            <td >
                Grand Total: $<span id="grandtotal"></span>
            </td>
        </tr>
        <tr>
    	<td>&nbsp;</td>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
							<td><strong>SubTotal:</strong></td>
							<td><input id="subtotal" class="form-control" /></td>
		</tr>
		<tr>
    	<td>&nbsp;</td>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
							<td><strong>Descuento:</strong></td>
							<td><input id="descuento" class="form-control" value="0"/></td>
		</tr>
		<tr>
    	<td>&nbsp;</td>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
							<td><strong>Subtotal generado despues del descuento:</strong></td>
							<td><input id="descuentoGenerado" class="form-control" /></td>
		</tr>
    </tfoot>
</table>

<script>
$(document).ready(function () {
    var filasTabla = 1;
    $("#addrow").on("click", function () {
        /*filasTabla ++;
        //var inputCantidad = $('<input />').attr({'id': 'idCantidad_' + filasTabla}).attr({'class':'form-control'}).attr({'required':"La cantidad no puede quedar vacia"});
        var newRow = $("<tr>");
        var cols = "";
        cols +=  var inputCantidad = $('<input />').attr({'id': 'idCantidad_' + filasTabla}).attr({'class':'form-control'}).attr({'required':"La cantidad no puede quedar vacia"});
        cols += '<td>$<input  name="price' + fila + '"/></td>';
        cols += '<td><input  name="qty' + fila + '"/></td>';
        cols += '<td>$<input name="linetotal' + fila + '" readonly="readonly"/></td>';
        cols += '<td><a class="deleteRow"> x </a></td>';
        newRow.append(cols);*/
       var newRow = $("<tr>");
       var inputCantidad = $('<input />').attr({'id': 'idCantidad_' + filasTabla}).attr({'class':'form-control'}).attr({'required':"La cantidad no puede quedar vacia"});
			// idProducto
			var inputProducto = $('<input />').attr({'id': 'idProducto_' + filasTabla}).attr({'class':'form-control'});

			// idUnidad
			var inputUnidad = $('<select />').attr({'id': 'idUnidad_' + filasTabla}).attr({'class':'form-control'});
			/*$.each(jsonUnidad,function(i,item){
				inputUnidad.append('<option value="'+jsonUnidad[i].idUnidad+'">'+jsonUnidad[i].unidad+'</option>');
			});*/
			// codigoBarras
			var inputCodigoBarras = $('<input />').attr({'id': '0' + filasTabla}).attr({'class':'form-control'});
			// descripcion
			//var inputdescripcion = $('<input />').attr({'id': 'descripcion_' + filasTabla}).attr({'class':'form-control'});
			var selectdescripcion = $('<select />').attr({'id': 'descripcion_' + filasTabla}).attr({'class':'form-control'});
			/*$.each(jsonProductos,function(i,item){
				selectdescripcion.append('<option value="'+jsonProductos[i].idProducto+'">'+jsonProductos[i].producto+'</option>');
			});*/
			// precioUnitario
			var inputCostoUnitario = $('<input />').attr({'id': 'costoUnitario_' + filasTabla}).attr({'class':'form-control'});
			// precioImporte
			var inputCostoTotal = $('<input />').attr({'id': 'costoTotal_' + filasTabla}).attr({'class': 'costoTotal' + filasTabla}).attr({'class':'form-control'}).attr({'name':'costoTotal_'});
			
			// botonLimpiar
			var buttonLimpiar = $('<button />').attr({'id': 'btnLimpiar_' + filasTabla}).attr({'class':'btn btn-danger'});
			buttonLimpiar.html('<span class="glyphicon glyphicon-remove-circle"></span> Eliminar Producto')	;
      
        $("table#order-list").append($('<tr>').
				append($('<td>').append(inputCantidad)).
				append($('<td>').append(inputProducto)).
				append($('<td>').append(inputUnidad)).
				append($('<td>').append(inputCodigoBarras)).
				append($('<td>').append(selectdescripcion)).
				append($('<td>').append(inputCostoUnitario)).
				append($('<td>').append(inputCostoTotal)).
				append($('<td>').append(buttonLimpiar))
				
			);
    });
    
    $("table#order-list").on("change", 'input[id^="idCantidad_"], input[id^="costoUnitario_"]', function (event) {
        calculateRow($(this).closest("tr"));
        calculateGrandTotal();
        descuento();
    });
    
    $("table#order-list").on("click", "a.deleteRow", function (event) {
        $(this).closest("tr").remove();
        calculateGrandTotal();
    });
});
    
function calculateRow(row) {
    var  precioUnitario= +row.find('input[id^="costoUnitario_"]').val();
    var cantidad = +row.find('input[id^="idCantidad_"]').val();
    row.find('input[id^="costoTotal_"]').val((cantidad * precioUnitario).toFixed(2));
}
    
function calculateGrandTotal() {
    var grandTotal = 0;
    
    $("table#order-list").find('input[id^="costoTotal_"]').each(function () {
        grandTotal += +$(this).val();
       
    });
    $("#grandtotal").text(grandTotal.toFixed(2));
    $("#subtotal").val(grandTotal.toFixed(2));
    /*Descuento*/
     
    /*	 */
  }
function descuento() {  
	var descuento = 0;
	var total = 0;	
	$("table#order-list ").keyup("input[id^='subtotal']", function(){
  	
    if($("#descuento").val()!== "0") {
    	console.log("El descuento es diferente de cero");
    	$("#descuentoGenerado").val(descuento);
    	descuento = parseFloat($("#subtotal").val()) - parseFloat( $("#descuento").val());
		//Realiza el total, cuando hay descuento
		total =  parseFloat( $("#descuentoGenerado").val(descuento));
    	console.log(total);
    }
    }); 
  
}

</script>