<?php 
	$formulario = $this->formulario;	
?>
<?php if(! is_null($this->formulario)) { ?>
	<header>
		<?php echo $this->mensajeFormulario; ?>
	</header>
	<div class="row">
						
	<section>	
		<article class="col-md-0">
						
			<?php echo $this->formulario; ?>
		</article>			
	</section>	
			
	</div>
			
<?php			
			
		}
		echo '<br />';
?>

<?php 
	if(($this->rowset)){
		echo $this->mensaje;
		switch ($this->tipo) {
			case '1':
				echo $this->partial('partials/tablas/FacturaProveedor.phtml', 
					array("tabla" => $this->rowset,
						"tipo" => $this->tipo,
						"empresa" => $this->empresa,
						"cliente" => $this->cliente,
						"formulario" => $this->datosForm)
				);
					
			case '2':
				
				break;
			case '3':
				
				break;
			
		}
		
	}
	
	echo '<br />';
?>