<?php if(! is_null($this->formulario)) { ?>
	<header>
		<?php echo $this->mensajeFormulario; ?>
	</header>
	<div class="row">
		<section>
				<?php echo $this->formulario; ?>
			
		</section>
			
	</div>
			
<?php			
			
		}
		echo '<br />';
?>
<?php 
	if(($this->rowset)){
		echo $this->mensaje;
		switch ($this->tipo) {
			case '1':
				
				break;
			case '2':
				
				break;
			case '3':
				
				break;
			
		}
		
	}
	
	echo '<br />';
?>