<?php
	$empresas = $this->empresas;
	
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h4 class="panel-title">Búsqueda de Factura por Pagar<strong></strong></h4>
			</div>
			<div class="panel-body">
				<div>
					
				</div>
				<hr />
				<div>
					<div class="form-horizontal">
						<!-- Empresas -->
						<div class="form-group">
							<label for="empresa" class="col-md-2">Empresas: </label>
							<div class="col-md-10">
								<select name="empresa" id="idFiscales" class="form-control">
									<option value="0">Seleccione Empresa</option>
									<?php foreach ($empresas as $empresa) : ?>
									<option value="<?php echo $empresa["idFiscales"] ?>"><?php echo $empresa["razonSocial"] ?></option>
									<?php endforeach ?>
								</select>
							</div>
						</div>
						<!-- Sucursales -->
						<div class="form-group">
							<label for="sucursal" class="col-md-2">Sucursal: </label>
							<div class="col-md-10">
								<select name="sucursal" id="idSucursal" class="form-control">
								</select>
							</div>
						</div>
						<!-- Proveedores -->
						<div class="form-group">
							<label for="proveedor" class="col-md-2">Proveedor: </label>
							<div class="col-md-10">
								<select name="proveedor" id="idProveedor" class="form-control">
								</select>
							</div>
						</div>
						<!-- Boton consulta -->
						<div class="form-group">
							<div class="col-md-offset-2 col-md-10">
								<button id="queryFacturas" type="button" class="btn btn-success">
									<i class="fa fa-search"></i> Consultar Facturas
								</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title"></h5>
			</div>
			<div class="panel-body">
				<div>
					<table class="table table-striped table-condensed">
						<thead>
							<tr>
								<th></th>
								<th></th>
								<th></th>
								<th></th>
								<th></th>
								<th></th>
								<th></th>
							</tr>
						</thead>
					</table>
				</div>
			</div>
			
		</div>
	</div>
</div>
<script>
	$().ready(function(){
		
		var url = window.location.origin + "/General/";
		
		$("#idFiscales").on('change',function(){
			//console.log($(this).val());
			var idFiscal = $(this).val();
			if(idFiscal != 0){
				// Traer sucursales de la empresa seleccionada y llenar combo de sucursales
				
				var urlQuerySucursales = url + 'contabilidad/json/sucursalese/idFiscales/'+idFiscal;
				
				$.ajax({
					url: urlQuerySucursales,
					dataType: "json",
					success: function(data){
						console.dir(data);
						
						$("#idSucursal").empty();
						$("#idSucursal").append($("<option></option>").attr("value","0").text("Seleccione Sucursal..."));
						$.each(data, function (i,item){
							$("#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal));
						});
					}
				});
				
				// Traer proveedores de la empresa seleccionada y llenar combo de proveedores
				
				var urlQueryProveedores = url + 'contabilidad/json/proveedorese/idFiscales/'+idFiscal;
				
				$.ajax({
					url: urlQueryProveedores,
					dataType: "json",
					success: function(data){
						console.dir(data);
						$("select#idProveedor").empty();
						$("select#idProveedor").append($("<option></option>").attr("value","0").text("Seleccione Proveedor..."));
						$.each(data, function (i,item){
							$("select#idProveedor").append($("<option></option>").attr("value",data[i].idProveedores).text(data[i].razonSocial));
						});
					}
				});
			}
		});
		
		$("#queryFacturas").on('click', function(){
			//Traer Id's de Empresa, Sucursal y Proveedor
			console.log($("#idFiscales").val());
			console.log($("#idSucursal").val());
			console.log($("#idProveedor").val());
			
		});
		
	});
</script>

