<?php
	$sucursalesDAO = new Sistema_DAO_Sucursal;
	$empresas = $this->empresas;
	//$sucursal = $sucursalesDAO->obtenerSucursal($idSucursal);  
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h4 class="panel-title">Búsqueda de Factura por Pagar<strong></strong></h4>
			</div>
			<div class="panel-body">
				<div>
					
				</div>
				<hr />
				<div>
					<div class="form-horizontal">
						<!-- Empresas -->
						<div class="form-group">
							<label for="empresa" class="col-md-2">Empresas: </label>
							<div class="col-md-10">
								<select name="empresa" id="idFiscales" class="form-control">
									<option value="0">Seleccione Empresa</option>
									<?php foreach ($empresas as $empresa) : ?>
									<option value="<?php echo $empresa["idFiscales"] ?>"><?php echo $empresa["razonSocial"] ?></option>
									<?php endforeach ?>
								</select>
							</div>
						</div>
						<!-- Sucursales -->
						<div class="form-group">
							<label for="sucursal" class="col-md-2">Sucursal: </label>
							<div class="col-md-10">
								<select name="sucursal" id="idSucursal" class="form-control">
								</select>
							</div>
						</div>
						<!-- Proveedores -->
						<div class="form-group">
							<label for="proveedor" class="col-md-2">Proveedor: </label>
							<div class="col-md-10">
								<select name="proveedor" id="idProveedor" class="form-control">
								</select>
							</div>
						</div>
						<!-- Boton consulta -->
						<div class="form-group">
							<div class="col-md-offset-2 col-md-10">
								<button id="queryFacturas" type="button" class="btn btn-success">
									<i class="fa fa-search"></i> Consultar Facturas
								</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Detalle de Facturas</h5>
			</div>
			<div class="panel-body">
				<div>
					<table id="detalleFacturaxp" class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Sucursal</th>
								<th>Proveedor</th>
								<th>Número Factura</th>
								<th>Fecha</th>
								<th>$total</th>
								<th>Pago</th>
								<th>Nomina</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div>
			</div>
			
		</div>
	</div>
</div>

<!-- Registra pago -->
<div id="registroPago" class="row hidden">
	<div class="col-md-12">
		<div class="panel panel-warning">
			<div class="panel-heading">
				<h5 class="panel-title">Registro de Pago Factura</h5>
			</div>
			<div class="panel-body">
				<div>
					<div class="form-horizontal">
						<!-- Fecha -->
						<div class="form-group">
							<label for="fecha" class="control-label col-md-2">Fecha de Pago: </label>
							<div class="col-md-10">
								<input id="fecha" name="fecha" type="text" class="form-control" />
							</div>
						</div>
						<!-- Pago -->
						<div class="form-group">
							<label for="pago" class="control-label col-md-2">Monto: </label>
							<div class="col-md-10">
								<input id="pago" name="pago" type="text" class="form-control" />
							</div>
						</div>
						<!-- Divisa -->
						<div class="form-group">
							<label for="divisa" class="control-label col-md-2">Divisa: </label>
							<div class="col-md-10">
								<input id="divisa" name="divisa" type="text" class="form-control" />
							</div>
						</div>
						<!-- Concepto -->
						<div class="form-group">
							<label for="concepto" class="control-label col-md-2">Concepto: </label>
							<div class="col-md-10">
								<input id="concepto" name="concepto" type="text" class="form-control" />
							</div>
						</div>
						<!-- FormaPago -->
						<div class="form-group">
							<label for="formaPago" class="control-label col-md-2">Forma de Pago</label>
							<div class="col-md-10">
								<input id="formaPago" name="formaPago" type="text" class="form-control" />
							</div>
						</div>
						<!-- Banco -->
						<div class="form-group">
							<label for="banco" class="control-label col-md-2">Banco: </label>
							<div class="col-md-10">
								<input id="banco" name="banco" type="text" class="form-control" />
							</div>
						</div>
						<!-- Referencia -->
						<div class="form-group">
							<label for="referencia" class="control-label col-md-2">Referencia: </label>
							<div class="col-md-10">
								<input id="referencia" name="referencia" type="text" class="form-control" />
							</div>
						</div>
						<!-- BotonEnvio -->
						<div class="form-group">
							<div class="col-md-offset-2 col-md-10">
								<button type="button" class="btn btn-warning" role="button">
									<i class="fa fa-save"></i> Registrar Pago
								</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Registra Nomina -->
<div id="registroNomina" class="row hidden">
	<div class="col-md-12">
		<div class="panel panel-warning">
			<div class="panel-heading">
				<h5 class="panel-title">Registrar una Nota Crédito</h5>
			</div>
			<div class="panel-body">
				<div>
					<div class="form-horizontal">
						<!-- Fecha -->
						<div class="form-group">
							<label for="fecha" class="control-label col-md-2">Fecha: </label>
							<div class="col-md-10">
								<input id="fecha" name="fecha" type="text" class="form-control" />
							</div>
						</div>
						<!-- Pago -->
						<div class="form-group">
							<label for="pago" class="control-label col-md-2">Monto: </label>
							<div class="col-md-10">
								<input id="pago" name="pago" type="text" class="form-control" />
							</div>
						</div>
						<!-- Divisa -->
						<div class="form-group">
							<label for="divisa" class="control-label col-md-2">Divisa: </label>
							<div class="col-md-10">
								<input id="divisa" name="divisa" type="text" class="form-control" />
							</div>
						</div>
						
						<!-- BotonEnvio -->
						<div class="form-group">
							<div class="col-md-offset-2 col-md-10">
								<button type="button" class="btn btn-warning" role="button">
									<i class="fa fa-save"></i> Registrar Pago
								</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
	$().ready(function(){
		
		var url = window.location.origin + "/General/";
		
		$("#idFiscales").on('change',function(){
			//console.log($(this).val());
			var idFiscal = $(this).val();
			if(idFiscal != 0){
				// Traer sucursales de la empresa seleccionada y llenar combo de sucursales
				
				var urlQuerySucursales = url + 'contabilidad/json/sucursalese/idFiscales/'+idFiscal;
				
				$.ajax({
					url: urlQuerySucursales,
					dataType: "json",
					success: function(data){
						console.dir(data);
						
						$("#idSucursal").empty();
						$("#idSucursal").append($("<option></option>").attr("value","0").text("Seleccione Sucursal..."));
						$.each(data, function (i,item){
							$("#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal));
						});
					}
				});
				
				// Traer proveedores de la empresa seleccionada y llenar combo de proveedores
				
				var urlQueryProveedores = url + 'contabilidad/json/proveedorese/idFiscales/'+idFiscal;
				
				$.ajax({
					url: urlQueryProveedores,
					dataType: "json",
					success: function(data){
						console.dir(data);
						$("select#idProveedor").empty();
						$("select#idProveedor").append($("<option></option>").attr("value","0").text("Seleccione Proveedor..."));
						$.each(data, function (i,item){
							$("select#idProveedor").append($("<option></option>").attr("value",data[i].idProveedores).text(data[i].razonSocial));
						});
					}
				});
			}
		});
		
		$("#queryFacturas").on('click', function(){
			//Traer Id's de Empresa, Sucursal y Proveedor
			var idSucursal = $("#idSucursal").val();
			var proveedor = $("#idProveedor").val();
			console.log($("#idFiscales").val());
			console.log($("#idSucursal").val());
			console.log($("#idProveedor").val());
			var urlFacturaxp = url + 'contabilidad/json/buscafacxp/idSucursal/' + idSucursal + '/pro/' + proveedor;
			console.log(urlFacturaxp);
			//Comenzamaos eventos ajax
			$.ajax({
				url: urlFacturaxp,
				dataType:"json",
				success: function (data){
					console.dir(data);
					var tbody = $("#detalleFacturaxp").find('tbody');
					tbody.empty();
					$.each(data, function(i,item){
						var botonPago = $('<button></button>').attr("tipo","pago").attr("factura",data[i].idFactura).attr("class","btn btn-link").text("Pago");
						var botonNomina = $('<button></button>').attr("tipo","nomina").attr("factura",data[i].idFactura).attr("class","btn btn-link").text("Nomina de Crédito");
						
						tbody.append( $('<tr>').
							append($('<td>').append(data[i].idSucursal)).
							append($('<td>').append(data[i].idCoP)).
							append($('<td>').append(data[i].numeroFactura)).
							append($('<td>').append(data[i].fechaFactura)).
							append($('<td>').append(data[i].total)).
							append($('<td>').append(botonPago)).
							append($('<td>').append(botonNomina))
						);
					});
				}
			});
			
		});
		
		$("#detalleFacturaxp").on('click', "button[tipo='pago']", function(){
			console.log("Si funciona!!!!");
			
				$("#registroPago").removeClass("hidden");
				if ($("#detalleFacturaxp").is('.registroPago')){
					$("#registroNomina").addClass("hidden");
				}
				
		});
		
		$("#detalleFacturaxp").on('click', "button[tipo='nomina']", function(){
			console.log("Si funciona!!!!");
			$("#registroNomina").removeClass("hidden");
		});
		
	});
</script>

