<?php
	$divisaDAO = new Contabilidad_DAO_Divisa;
	$divisas = $divisaDAO->obtenerDivisas();
	$bancosDAO = new Contabilidad_DAO_Banco;
	$bancos = $bancosDAO->obtenerBancos();
	$conceptoPagos =array("AN"=>"ANTICIPO", "LI"=>"LIQUIDADO","PA"=>"PAGO");
	$formasPago = array('CH'=>'CHEQUE','DE'=>'DEPOSITO','EF'=>'EFECTIVO','SP'=>'SPEI', 'DO'=>'DOCUMENTO');
	$sucursalesDAO = new Sistema_DAO_Sucursal;
	$empresas = $this->empresas;
	//$sucursal = $sucursalesDAO->obtenerSucursal($idSucursal);  
	$facturasxp = $this->facturasxp;
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h4 class="panel-title">Búsqueda de Factura por Pagar<strong></strong></h4>
			</div>
			<div class="panel-body">
				<div>
					
				</div>
				<hr />
				<div>
					<!--<div class="form-horizontal">-->
						<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
						<!-- Empresas -->
						<div class="form-group">
							<label for="empresa" class="col-md-2">Empresas: </label>
							<div class="col-md-10">
								<select name="empresa" id="idFiscales" class="form-control">
									<option value="0">Seleccione Empresa</option>
									<?php foreach ($empresas as $empresa) : ?>
									<option value="<?php echo $empresa["idFiscales"] ?>"><?php echo $empresa["razonSocial"] ?></option>
									<?php endforeach ?>
								</select>
							</div>
						</div>
						<!-- Sucursales -->
						<div class="form-group">
							<label for="sucursal" class="col-md-2">Sucursal: </label>
							<div class="col-md-10">
								<select name="sucursal" id="idSucursal" class="form-control">
								</select>
							</div>
						</div>
						<!-- Proveedores -->
						<div class="form-group">
							<label for="proveedor" class="col-md-2">Proveedor: </label>
							<div class="col-md-10">
								<select name="proveedor" id="idProveedor" class="form-control">
								</select>
							</div>
						</div>
						<!-- Boton consulta -->
						<div class="form-group">
							<div class="col-md-offset-2 col-md-10">
								<button id="queryFacturas" type="submit" class="btn btn-success">
									<i class="fa fa-search"></i> Consultar Facturas
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Muesta el resultado de la busqueda -->
<?php if(!is_null($facturasxp)){ ?>
	<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Detalle de Facturas</h5>
			</div>
			<div class="panel-body">
				<div>
					<table id="detalleFacturaxp" class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Sucursal</th>
								<th>Proveedor</th>
								<th>Número Factura</th>
								<th>Fecha</th>
								<th>$total</th>
								<th>Pago</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($facturasxp as $facturaxp) :?>
								<tr>
									<td><?php echo $facturaxp["idSucursal"]; ?></td>
									<td><?php echo $facturaxp["idCoP"]; ?></td>
									<td><?php echo $facturaxp["numeroFactura"]; ?></td>
									<td><?php echo $facturaxp["fecha"]; ?></td>
									<td><?php echo "$" .number_format($facturaxp["total"],2) ?></td>
									<td>	
										<a class="btn btn-success" type="submit" href="<?php echo $this->url(array("module"=>"contabilidad","controller"=>"proveedor","action"=>"aplicarpago","idFactura"=>$facturaxp["idFactura"]),null, true)?>">
											<span class="glyphicon glyphicon-pencil"></span> Pago
										</a
									</td>
								</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
			
		</div>
	</div>
</div>	
<?php } ?>
<!--Modal para realizar un  pago -->
<div class="modal fade" id="modalPago" tabindex="-1" role="dialog">
	<div class="modal-dialog" role= "document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss"modal">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title">Realiza pago:</h4>
			</div><!--heder-->
			<div class="modal-body">
				<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
					<div class="form-group">
						<label for="fecha" class="control-label col-md-2">Fecha de Pago: </label>
						<div class="col-md-10">
							<input id="fecha" name="fecha" type="text" class="form-control" />
						</div>
					</div>
						
					<div class="form-group">
						<label for="pago" class="control-label col-md-2">Monto: </label>
						<div class="col-md-10">
							<input id="pago" name="pago" type="text" class="form-control" />
						</div>
					</div>
					
						<!-- Divisa -->
						<div class="form-group">
							<label for="divisa" class="control-label col-md-2">Divisa: </label>
							<div class="col-md-10">
								<select id="idDivisa" name="divisa" class="form-control">
									<?php foreach ($divisas as $divisa) : ?>
									<option value="<?php echo $divisa->getIdDivisa(); ?>"><?php echo $divisa->getDescripcion(); ?></option>
								<?php endforeach; ?>
								</select>
							</div>
						</div>
						<!-- Concepto -->
						<div class="form-group">
							<label for="concepto" class="control-label col-md-2">Concepto: </label>
							<div class="col-md-10">
								<select id="conceptoPago" name="concepto" class="form-control">
									<?php foreach ($conceptoPagos as $key =>$value): ?>
										<option value="<?php echo $key; ?>"><?php echo $value; ?></option>
									<?php endforeach; ?>	
								</select>
							</div>
						</div>
						<!-- FormaPago -->
						<div class="form-group">
							<label for="formaPago" class="control-label col-md-2">Forma de Pago</label>
							<div class="col-md-10">
								<select id="formaPago" name="formaPago" class="form-control">
									<?php foreach ($formasPago as $key => $value): ?>
										<option value="<?php echo $key; ?>"><?php echo $value; ?></option>
									<?php endforeach ?>	
								</select>
							</div>
						</div>
						<!-- Banco -->
						<div class="form-group">
							<label for="banco" class="control-label col-md-2">Banco: </label>
							<div class="col-md-10">
								<select id="idBanco" name="banco" class="form-control">
									<?php foreach ($bancos as $banco) :?>
										<option value="<?php echo $banco->getIdBanco(); ?>"> <?php echo $banco->getBanco(); ?></option>
									<?php endforeach?>
								</select>
							</div>
						</div>
						<!-- Referencia -->
						<div class="form-group">
							<label for="referencia" class="control-label col-md-2">Referencia: </label>
							<div class="col-md-10">
								<input id="referencia" name="referencia" type="text" class="form-control" placeholder="(Opcional)..." />
							</div>
						</div>
						<!-- BotonEnvio -->
						<div class="form-group">
							<div class="col-md-offset-2 col-md-10">
								<button type="submit" class="btn btn-warning">
									<i class="fa fa-save"></i> Registrar Pago
								</button>
							</div>
						</div>		
				</form>
					
			</div><!--body-->
		</div><!--modal-content-->
	</div><!--modal-dialog-->
</div><!--modal-->

<div class="row hidden" >
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Relación de Pagos</h5>
			</div>
			<div class="panel-body">
				<div>
					<table id="detalleFacturaxp" class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Movimiento</th>
								<th>Pago</th>
								<th>Divisa</th>
								<th>Importe</th>
								<th>Fecha</th>
								<th>$total</th>
								<th>Pago</th>
								<th>Nomina</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div>
			</div>
			
		</div>
	</div>
</div>


<script>
	$().ready(function(){
		
		var url = window.location.origin + "/General/";
		
		$("select#idFiscales").on('change',function(){
			console.log($(this).val());
			var idFiscal = $(this).val();
			if(idFiscal != 0){
				// Traer sucursales de la empresa seleccionada y llenar combo de sucursales
				var urlQuerySucursales = url + 'contabilidad/json/sucursalese/idFiscales/'+idFiscal;
				
				$.ajax({
					url: urlQuerySucursales,
					dataType: "json",
					success: function(data){
						console.dir(data);
						$("#idSucursal").empty();
						$("#idSucursal").append($("<option></option>").attr("value","0").text("Seleccione Sucursal..."));
						$.each(data, function (i,item){
							$("#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal));
						});
					}
				});
			
				// Traer proveedores de la empresa seleccionada y llenar combo de proveedores
				var urlQueryProveedores = url + 'contabilidad/json/proveedorese/idFiscales/'+idFiscal;
				console.log(urlQueryProveedores);
				$.ajax({
					url: urlQueryProveedores,
					dataType: "json",
					success: function(data){
						console.dir(data);
						$("select#idProveedor").empty();
						$("select#idProveedor").append($("<option></option>").attr("value","0").text("Seleccione Proveedor..."));
						$.each(data, function (i,item){
							$("select#idProveedor").append($("<option></option>").attr("value",data[i].idProveedores).text(data[i].razonSocial));
						});
					}
				});
			}
		});
		
		$("a#pagos").on('click', function(){
			
		});
	});
</script>


