<?php 
	
	$empresas = $this->empresas;
	$proveedores = $this->proveedores;
	$pagoProveedor = $this->pagoProveedor;
?>

<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">Cuentas por Pagar</h3>
	</div>
	<div class="panel-body">
		<table class="table table-striped table-condensed">
			<thead>
			</thead>
			<tbody>
				<tr>
					<!--<?php echo $this->formulario; ?>-->
					
					<td>Empresa.</td>
					<td>
						<select id="idEmpresas" class="form-control">
							<option value="0">Buscar...</option>
							<?php foreach ($empresas as $empresa) : ?>
							<option value="<?php echo $empresa->idFiscales ?>"><?php echo $empresa->razonSocial;  ?></option>
							<?php endforeach; ?>
						</select>
					</td>
				</tr>
				<tr>
					<td>Sucursal.</td>
					<td>
						<select id="idSucursal" class="form-control">
							<option value="0">Buscar...</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>Proveedor.</td>
					<td>
						<select id="idCoP" class="form-control">
							<option value="0">Buscar...</option>
							<?php foreach ($proveedores as $proveedor) : ?>
							<option value="<?php echo $proveedor->idEmpresa ?>"><?php echo $proveedor->razonSocial; ?></option>
							<?php endforeach; ?>
						</select>
					</td>
				</tr>
				<tr>
					<td>Factura.</td>
					<td>
						<!--<input  placeholder="Número factura..."/>-->
						<input id="numeroFactura" class="form-control" onkeypress="soloNumero()">
					</td>
				</tr>
				<tr>
					<td></td>
					<td>
						<button id="btnPagosProveedor" class="btn btn-success" disabled>
							<span class="glyphicon glyphicon-search"></span> Buscar Factura
						</button>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
	<div></div>
</section>
<section class="row">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Detalle pago factura Proveedor.</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>#Factura</th>
						<th>#Proveedor</th>
						<th>#Empresa</th>
						<th>#Sucursal</th>
						<th>Fecha Captura</th>
						<th>$Total</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($pagoProveedor as $pagoProveedor) : ?>
					<!--
					<tr>
						<td><?php echo $pagoProveedor->idFactura ?></td>
						<td><?php echo $pagoProveedor->idCoP ?></td>
						<td><?php echo $pagoProveedor->idScursal ?></td>
						<td><?php echo $pagoProveedor->idScursal ?></td>
						<td><?php echo $pagoProveedor->idScursal ?></td>
						<td><?php echo $pagoProveedor->idScursal ?></td>
					</tr>
					-->
					<?php endforeach; ?>
				</tbody>
				<tbody>
					
				</tbody>
			</table>
		</div>
	</div>
	
</section>
<!-- 
<section class="panel panel-info">
	<div class="panel-heading">
		<h3 class="panel-title">Detalle pagos factura</h3>
	</div>
	<div class="panel-body">
		<table id="tableDetails" class="table table-striped table-condensed">
			<thead>
				<th>Número Factura</th>
				<th>Proveedor</th>
				<th>Empresa</th>
				<th>Detalle</th>
				<th>Saldo general de proveedor</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>

<section class="panel panel-info">
	<div class="panel-heading">
		<h3 class="panel-title">Registrar un pago</h3>
	</div>
	<div class="panel-body">
		<table id="tableDetails" class="table table-striped table-condensed">
			<thead>
				<th>Pago en</th>
				<th>Pago $</th>
				<th>Fecha pago</th>
				<th>Concepto pago</th>
				<th>Forma liquidación </th>
				<th>Número de Referencia</th>
				<th>Banco</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>
---!>
<section class="panel panel-info">
	<div class="panel-heading">
		<h3 class="panel-title">Registrar un nota de credito</h3>
	</div>
	<div class="panel-body">
		<table id="tableDetails" class="table table-striped table-condensed">
			<thead>
				<th>Pago en</th>
				<th>Pago $</th>
				<th>Fecha pago</th>
				<th>Concepto pago</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>
-->
<script>
$(document).ready(function(){
	console.log("ready");
	var url = window.location.origin + "/General/";
	$("select#idEmpresas").on('change', function(){
		var idEmpresa = $(this).val();
		if (idEmpresa !=0){
			var urlSucursal = url + "sistema/json/sucursales/idFiscales/" + this.value;
			console.log(urlSucursal);
			$.ajax({
				url: urlSucursal,
				dataType: "json",
				success: function (data){
					$("select#idSucursal").empty();
					$.each(data, function (i,item){
						$("select#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal));
					});
				}
			});
		}
	});
	
	$("select#idSucursal").on('click', function(){
		var idSucursal = $(this).val();
		console.log(idSucursal);
		if(idSucursal !=0){
			var urlConsultaFactura = url + "contabilidad/json/factura/idSucursal/"+ idSucursal;
			console.log(urlConsultaFactura);
		}
	});
	
	$("select#idProveedor").on('click', function (){
		var idProveedor = $(this).val();
		if(idProveedor != 0){
		
		}
	});
	
	$("input#numeroFactura").on('change', function(){
		$("button#btnPagosProveedor").removeAttr("disabled");
	});
	
	$("button#btnPagosProveedor").on('click', function(){
		console.log("click");
		var idSucursal = $("select#idSucursal").val();
		var idCoP = $("select#idCoP").val();
		var numFac = $("input#numeroFactura").val();
		
		console.log(idSucursal);
	
		/*var url = window.location.origin +contabilidad/impuestos/enlazarproducto/idProducto/" + producto + "/idImpuesto/" + impuesto;
	     console.log(url); sistema/json/sucursales/idFiscales/
	    var urlCuentasxp = url + "contabilidad/json/pagos/idSucursal/"+ idSucursal;*/
	    var urlCuentasxp = url + "contabilidad/json/pagos/idSucursal/" + idSucursal +"/idCoP/" + idCoP + "/numeroFactura/" + numFac;
	    console.log(urlCuentasxp); 
	});
	
});

function soloNumero()
	{
		if((event.keyCode < 48) || (event.keyCode > 57))
			event.returnValue = false;
	}	
</script>