<?php ?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title"><strong>Consulta  de libros</strong></h3>
		</div>
		<div class="panel-body">
			<form class="form-inline">
				<div class="form-group">
					<label for="titulo">Titulo:</label>
    				<input type="text" class="form-control" id="titulo" placeholder="Titulo...">
				</div>
				<div class="form-group">
					<label for="autor">Autor:</label>
    				<input type="text" class="form-control" id="autor" placeholder="Autor...">
				</div>
				<div class="form-group">
					<label for="editorial">Editorial:</label>
    				<input type="text" class="form-control" id="editorial" placeholder="Editorial...">
				</div>
				<button id="btnBusqueda" type="submit" class="btn btn-info"><span class="glyphicon glyphicon-search"></span> Consultar</button>
			</form>
			<br /><hr /><br />
			<table id="resultadoLibros" class="table table-striped table-condensed">
				<thead>
					<th>Titulo</th>
					<th>Autor</th>
					<th>Editorial</th>
					<th>Detalles</th>
				</thead>
				<tbody></tbody>
			</table>
		</div>
	</div>
</section>
<script>
	$().ready(function(){
		console.log("Javascript Activado!!");
		
		$("button#btnBusqueda").on('click', function(){
			console.log("Boton presionado!!");
			var titulo = $("input#titulo");
			var autor = $("input#autor");
			var editorial = $("input#editorial");
			
			var url = window.location.origin + "/General/public/Biblioteca/Json/consultabasica";
			
			if(autor.val() != "") url += "/autor/" + autor.val();
			if(titulo.val() != "") url += "/titulo/" + titulo.val();
			if(editorial.val() != "") url += "/editorial/" + editorial.val();
			
			//url += "autor/" + autor.val() + "/titulo/" + titulo.val() + "/editorial/" + editorial.val();
			
			console.log(encodeURI(url));
			
			$.ajax({
				url: encodeURI(url),
				dataType: "json",
				success: function(data){
					console.log("Peticion AJAX enviada");
					console.dir(data);
					var tbody = $("table#resultadoLibros").find('tbody');
					tbody.empty();
					$.each(data, function(i,item){
					
						tbody.append($('<tr>').
							append($('<td>').append(data[i]["titulo"])).
							append($('<td>').append(data[i]["autor"])).
							append($('<td>').append(data[i]["editorial"])).
							append($('<td>').append("-"))
						);
						
						
					});
				}
			});
			
		});
		
		
		
	});
</script>
