<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Capa C - Grupo 6020
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<th>Materia</th>
					<th>Profesor</th>
					<th>Evaluación</th>
				</thead>
				<tbody>
					<tr>
						<td>Filosofía</td>
						<td>Velázquez Galván Javier Arturo</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"118"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Derecho</td>
						<td>Arcos Lozano Sandra Erika</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"119"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Física</td>
						<td>Newmann Coto Guillermo Patricio</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"149"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Morfofisiología</td>
						<td>Rodriguez Alvarez Maria del Carmen</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"122"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Catequesis</td>
						<td>Gonzalez Gutierrez Juan Carlos</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"147"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</section>