<?php
	$inventario = $this->inventario;
	$formulario = $this->formulario;
	$productosDAO = new Inventario_DAO_Producto;
	$formulario->setAction($this->url(array("module"=>"inventario", "controller"=>"inventario", "action" => "admin", "idInventario"=> $inventario->getIdInventario()), null, true));	
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				<?php 
					$producto = $productosDAO->obtenerProducto($inventario->getIdProducto());
				?>
				Producto en Inventario: <strong><?php echo $producto->getProducto(); ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>No</th>
						<th>Clave</th>
						<th>Minimo</th>
						<th>Maximo</th>
						<th>Costo Unitario</th>
						<th>Porcentaje Ganancia</th>
						<th>Cantidad de Ganancia</th>
						<th>Costo Cliente</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><?php echo $inventario->getIdInventario() ?></td>
						<td><?php echo $producto->getClaveProducto() ?></td>
						<td><?php echo $inventario->getMinimo() ?></td>
						<td><?php echo $inventario->getMaximo() ?></td>
						<td><?php echo $inventario->getCostoUnitario() ?></td>
						<td><?php echo $inventario->getPorcentajeGanancia() ?></td>
						<td><?php echo $inventario->getCantidadGanancia() ?></td>
						<td><?php echo $inventario->getCostoCliente() ?></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</section>

<section class="row">
	<div class="panel panel-warning">
		<div class="panel-heading">
			Actualizando Producto
		</div>
		<div class="panel-body">
			<div class="col-xs-6">
				<?php echo $formulario; ?>
			</div>
		</div>
	</div>
</section>

<script>
	$(document).ready(function(){
		calculaCostoCliente();
		function calculaCostoCliente() {
			var costoCliente = 0;
			var porcentajeGanancia = 0;
			$("#cantidadGanancia").on("blur",function(){
				costoCliente  = parseFloat($("#costoUnitario").val()) + parseFloat($("#cantidadGanancia").val());
    			console.log(costoCliente);
    			$("input#costoCliente").val(costoCliente.toFixed(2));
			});
			
			$("#cantidadGanancia").on("blur",function(){
				console.log("El costo");
				porcentajeGanancia = ((parseFloat($("#costoCliente").val()) / parseFloat($("#costoUnitario").val()) -1) * 100);
    			console.log(porcentajeGanancia);
    			$("input#porcentajeGanancia").val(porcentajeGanancia.toFixed(2));
			});
    	
    	
 	 	  
   	}
		
	});
</script>