<?php 
	$empresas = $this->empresas;
?>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h4 class="panel-title">Búsqueda producto<strong></strong></h4>
			</div>
			<div class="panel-body">
				<div>
					<!--<div class="form-horizontal">-->
						<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
						<!-- Empresas -->
						<div class="form-group">
							<label for="empresa" class="col-md-2">Empresas: </label>
							<div class="col-md-10">
								<select name="empresa" id="idFiscales" class="form-control">
									<option value="0">Seleccione Empresa</option>
									<?php foreach ($empresas as $empresa) : ?>
									<option value="<?php echo $empresa["idFiscales"] ?>"><?php echo $empresa["razonSocial"] ?></option>
									<?php endforeach ?>
								</select>
							</div>
						</div>
						<!-- Sucursales -->
						<div class="form-group">
							<label for="sucursal" class="col-md-2">Sucursal: </label>
							<div class="col-md-10">
								<select name="sucursal" id="idSucursal" class="form-control">
								</select>
							</div>
						</div>
						<!-- Producto -->
						<div class="form-group">
							<label for="producto" class="col-md-2">Producto: </label>
							<div class="col-md-10">
								<select name="producto" id="idProducto" class="form-control">
								</select>
							</div>
						</div>
						<!-- Boton consulta -->
						<div class="form-group">
							<div class="col-md-offset-2 col-md-10">
								<button id="queryMotos" type="button" class="btn btn-success">
									<i class="fa fa-search"></i> Consultar Movimientos
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle producto por movimiento.</h4>
		</div>
		<table id="detalleProductoMovtos" class="table table-striped table-condensed">
			<thead>
				<th>Tipo Movimiento </th>
				<th>fecha</th>
				<th>CoP</th>
				<th>Cantidad</th>
				<th>Costo Unitario</th>
				<th>Total</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>
<script>
$().ready(function(){
	var url = window.location.origin + "/General/";
	$("select#idFiscales").on('change',function(){
		var idFiscal = $(this).val();
		if(idFiscal != 0){
			var urlQuerySucursales = url + 'contabilidad/json/sucursalese/idFiscales/'+idFiscal;
			$.ajax({
				url: urlQuerySucursales,
				dataType: "json",
				success: function(data){
					console.dir(data);
					$("#idSucursal").empty();
					$("#idSucursal").append($("<option></option>").attr("value","0").text("Seleccione Sucursal..."));
					$.each(data, function (i,item){
						$("#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal));
					});
				}
			});
		}
	});
	
	$("select#idSucursal").on('change',function(){
		var idSucursal = $(this).val();
		if(idSucursal != 0){
			var urlQueryMovtos = url + 'inventario/json/productoxmovimiento/idSucursal/'+idSucursal;
			console.log(urlQueryMovtos);
			$.ajax({
				url: urlQueryMovtos,
				dataType: "json",
				success: function(data){
					console.dir(data);
					$("#idProducto").empty();
					$("#idProducto").append($("<option></option>").attr("value","0").text("Seleccione Producto..."));
					$.each(data, function (i,item){
						$("#idProducto").append($("<option></option>").attr("value",data[i].idProducto).text(data[i].producto));
					});
				}
			});
		}
	});
	
	$("button#queryMotos").on("click", function(){
		 	var idProducto = $("select#idProducto").val();
			var urlProducto = window.location.origin + "/General/inventario/json/productoxsucursal/idProducto/" + idProducto ;
			console.log(urlProducto);
			$.ajax({
				url: urlProducto,
				dataType: "json",
				success: function(data){
					var tbody = $("table#detalleProductoMovtos").find('tbody');
					tbody.empty();
					$.each(data, function(i,item){
						//var botonPago = $('<button></button>').attr("id","pago").attr("class","btn btn-primary").text("Pago").attr("factura",data[i].idFactura);
						tbody.append($('<tr>').
							append($('<td>').append(data[i].idTipoMovimiento)).
							append($('<td>').append(data[i].fecha)).	
							append($('<td>').append(data[i].idCoP)).
							append($('<td>').append(data[i].cantidad)).
							append($('<td>').append(data[i].costoUnitario).attr("id", "importe")).
							append($('<td>').append(data[i].totalImporte)));
					});
					//AddRow();
					//calculaTotal();
				}
			});
			
		});
	
});
</script>