<?php 
	$empresas = $this->empresas;
?>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h4 class="panel-title">Búsqueda producto<strong></strong></h4>
			</div>
			<div class="panel-body">
				<div>
					<!--<div class="form-horizontal">-->
						<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
						<!-- Empresas -->
						<div class="form-group">
							<label for="empresa" class="col-md-2">Empresas: </label>
							<div class="col-md-10">
								<select name="empresa" id="idFiscales" class="form-control">
									<option value="0">Seleccione Empresa</option>
									<?php foreach ($empresas as $empresa) : ?>
									<option value="<?php echo $empresa["idFiscales"] ?>"><?php echo $empresa["razonSocial"] ?></option>
									<?php endforeach ?>
								</select>
							</div>
						</div>
						<!-- Sucursales -->
						<div class="form-group">
							<label for="sucursal" class="col-md-2">Sucursal: </label>
							<div class="col-md-10">
								<select name="sucursal" id="idSucursal" class="form-control">
								</select>
							</div>
						</div>
						<!-- Producto -->
						<div class="form-group">
							<label for="producto" class="col-md-2">Producto: </label>
							<div class="col-md-10">
								<select name="producto" id="idProducto" class="form-control">
								</select>
							</div>
						</div>
						<!-- Boton consulta -->
						<div class="form-group">
							<div class="col-md-offset-2 col-md-10">
								<button id="queryFacturas" type="button" class="btn btn-success">
									<i class="fa fa-search"></i> Consultar Movimientos
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
$().ready(function(){
	var url = window.location.origin + "/General/";
	$("select#idFiscales").on('change',function(){
		var idFiscal = $(this).val();
		if(idFiscal != 0){
			var urlQuerySucursales = url + 'contabilidad/json/sucursalese/idFiscales/'+idFiscal;
			$.ajax({
				url: urlQuerySucursales,
				dataType: "json",
				success: function(data){
					console.dir(data);
					$("#idSucursal").empty();
					$("#idSucursal").append($("<option></option>").attr("value","0").text("Seleccione Sucursal..."));
					$.each(data, function (i,item){
						$("#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal));
					});
				}
			});
		}
	});
	
	$("select#idSucursal").on('change',function(){
		var idSucursal = $(this).val();
		if(idSucursal != 0){
			var urlQueryProducto = url + 'Inventario/json/productomovimiento/idSucursal/'+idSucursal;
			$.ajax({
				url: urlQuerySucursales,
				dataType: "json",
				success: function(data){
					console.dir(data);
					$("#idSucursal").empty();
					$("#idSucursal").append($("<option></option>").attr("value","0").text("Seleccione Sucursal..."));
					$.each(data, function (i,item){
						$("#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal));
					});
				}
			});
		}
	});
	
});
</script>