<?php 
	$movimientos = $this->movimientos;
?>
<section class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">
				General Inventario.
			</h3>
		</div>
		<div class="panel-body">
			
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>clave Producto </th>
						<th>Descripcioón</th>
						<th>Cantidad</th>
						<th>Fecha</th>
						<th>Costo Unitario</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($movimientos as $movimiento) : ?>
					<tr>
						<td><?php echo $movimiento["claveProducto"] ?></td>
						<td><?php echo $movimiento["producto"] ?></td>
						<td><?php echo $movimiento["fecha"] ?></td>
						<td><?php echo $movimiento["existencia"] ?></td>
						<td><?php echo date_format($date, $movimiento["costoUnitario"]) ?></td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</section>