<?php
	$plan = $this->plan;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"encuesta","controller"=>"plan","action"=>"edita","idPlan"=>$plan["idPlanEducativo"]),null,true));
?>
<div class="row-fluid">
    <div class="span12 widget-box">
        <div class="widget-title">
            <h5>Detalle de Plan de Estudios: <strong><?php echo $plan["planEducativo"] ?></strong></h5>
        </div>
        <div class="widget-content">
            <div>
                <a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"plan","action"=>"index"),null,true) ?>">
                    <span class="icon icon-arrow-left"></span> Regresar a Planes de Estudio
                </a>
            </div>
            <hr />
            <div>
                <table class="table table-bordered table-striped table-condensed">
                    <thead>
                        <tr>
                            <th>Plan Educativo</th>
                            <th>Vigente</th>
                            <th>Creación</th>
                            <th>Descripción</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><?php echo $plan["planEducativo"]; ?></td>
                            <td><?php echo ($plan["vigente"] == 1) ? "Vigente" : "No Vigente" ; ?></td>
                            <td><?php echo $plan["fecha"]; ?></td>
                            <td><?php echo $plan["descripcion"]; ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12 widget-box">
        <div class="widget-title">
            <h5>Editar Plan de Estudios</h5>
        </div>
        <div class="widget-content">
            <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded"
                    action="<?php echo $this->url(array("module"=>"encuesta","controller"=>"plan","action"=>"edita","idPlan"=>$plan["idPlanEducativo"]),null,true) ?>">
                <div class="control-group">
                    <label for="planEducativo" class="control-label">Plan de Estudios: </label>
                    <div class="controls">
                        <input class="span10" type="text" name="planEducativo" placeholder="Nombre plan estudios" autofocus="" value="<?php echo $plan["planEducativo"] ?>" />
                    </div>
                </div>
                
                <div class="control-group">
                    <label for="descripcion" class="control-label">Descripción: </label>
                    <div class="controls">
                        <input class="span10" type="text" name="descripcion" placeholder="Descripción" value="<?php echo $plan["descripcion"] ?>" />
                    </div>
                </div>
                
                <div class="control-group">
                    <label class="control-label" for="vigente">Vigente?: </label>
                    <div class="controls">
                        <label>
                            <div class="checkbox">
                                <span class="cheked">
                                    <input name="vigente" type="checkbox" name="vigente" <?php echo ($plan["vigente"] == 1) ? "checked=''" : "" ;  ?> />
                                </span>
                            </div>
                        </label>
                    </div>
                </div>
                
                <div class="form-actions">
                    <div class="pull-right">
                        <button class="btn btn-warning" type="submit" >
                            <span class="icon icon-refresh"></span> Actualizar Plan
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
