<?php
	$formulario = $this->formulario;
	$messageFail = $this->messageFail;
	$messageSuccess = $this->messageSuccess;
	
?>
<div class="row-fluid">
    <div class="span12 widget-box">
        <div class="widget-title">
            <span></span>
            <h5>Nuevo Plan de Estudios</h5>
        </div>
        <div class="widget-content">
            <div>
                <a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"plan","action"=>"index"),null,true) ?>">
                    <span class="icon icon-arrow-left"></span> Regresar a Planes de Estudios
                </a>
                <?php if(!is_null($messageSuccess)){ ?>
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                    <?php echo $messageSuccess; ?>
                </div>
                <?php }elseif(!is_null($messageFail)){ ?>
                <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                    <?php echo $messageFail; ?>
                </div>
                <?php } ?>
            </div>
            <hr />
            <div>
                <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
                    <div class="control-group">
                        <label for="planEducativo" class="control-label">Plan de Estudios: </label>
                        <div class="controls">
                            <input class="span10" type="text" name="planEducativo" placeholder="Nombre plan estudios" autofocus="" />
                        </div>
                    </div>
                    
                    <div class="control-group">
                        <label for="descripcion" class="control-label">Descripción: </label>
                        <div class="controls">
                            <input class="span10" type="text" name="descripcion" placeholder="Descripción" />
                        </div>
                    </div>
                    
                    <div class="control-group">
                        <label class="control-label" for="vigente">Vigente?: </label>
                        <div class="controls">
                            <label>
                                <div class="checkbox">
                                    <span class="cheked">
                                        <input name="vigente" type="checkbox" name="vigente" />
                                    </span>
                                </div>
                            </label>
                        </div>
                    </div>
                    
                    <div class="form-actions">
                        <div class="pull-right">
                            <button type="submit" class="btn btn-success">
                                <span class="icon icon-save"></span> Guardar Plan
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
