<?php
	$planes = $this->planes;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Planes de Estudio
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"plan","action"=>"alta"),null,true) ?>">
				<span class="glyphicon glyphicon-plus"></span> Agregar Plan de Estudios 
			</a>
			<table class="table table-striped table-condensed">
				<thead>
					<th>Plan de Estudios</th>
					<th>Ciclos Escolares</th>
					<th>Vigente</th>
					<th>Descripcion</th>
				</thead>
				<tbody>
					<?php foreach ($planes as $plan) : ?>
					<tr>
						<td><?php echo $plan["plan"] ?></td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"ciclo","action"=>"index","idPlan"=>$plan["idPlanE"],),null,true) ?>">
								<span class="glyphicon glyphicon-cog"></span> Ciclos Escolares
							</a>
						</td>
						<td><?php echo $plan["vigente"] ?></td>
						<td><?php echo $plan["descripcion"] ?></td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</div>
</section>