<?php
	$parametro = $this->parametro;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"sistema", "controller"=>"parametro", "action" => "edita", "idParametro"=>$parametro->getIdParametro()), null, true));
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Detalle Parametro
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Parametro</th>
						<th>Descripcion</th>
						<th>Fecha</th>
						<th>Subparametros</th>
					</tr>
				</thead>
				<tbody>
	
					<tr>
						<td><?php echo $parametro->getParametro() ?></td>
						<td><?php echo $parametro->getDescripcion() ?></td>
						<td><?php echo $parametro->getFecha() ?></td>
						<td>
							<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"sistema", "controller"=>"subparametro", "action" => "index", "idParametro" => $parametro->getIdParametro()), null, true); ?>">
								Subparametros
							</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Parametro
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $formulario; ?>
		</div>
	</div>
	
	<div class="panel panel-danger">
		<div class="panel-heading">
			<h3 class="panel-title">
				Eliminar Parametro
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-danger" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"parametro", "action"=>"baja", "idParametro"=>$parametro->getIdParametro()), null, true) ?>">
				Eliminar Parametro
			</a>
		</div>
	</div>
</section>