<?php
	$docente = $this->docente;
	$asignaciones = $this->asignaciones;
	
	$encuestaDAO = $this->encuestaDAO;;
	$materiaDAO = $this->materiaDAO;
	$gruposDAO = $this->gruposDAO;
	$asignacionDAO = $this->asignacionDAO;
?>
<div class="row-fluid">
    <div class="span12 widget-box">
        <div class="widget-title">
            <h5>Reportes Grupales // Docente: <strong><?php echo $docente->getApellidos().", ".$docente->getNombres() ?></strong></h5>
        </div>
        <div class="widget-content">
            <table class="table table-bordered table-condensed table-striped">
                <thead>
                    <th>Grupo</th>
                    <th>Materia</th>
                    <th>Evaluación</th>
                    <th>Resultados</th>
                </thead>
                <tbody>
                    <?php foreach ($asignaciones as $asignacion) : 
                        $grupo = $gruposDAO->obtenerGrupo($asignacion["idGrupoEscolar"]);
                        $materia = $materiaDAO->obtenerMateria($asignacion["idMateriaEscolar"]);
                        $encuestasRealizadas = $encuestaDAO->obtenerEncuestasRealizadasPorAsignacion($asignacion["idAsignacionGrupo"]);
                        //$encuestaRealizada = $encuestaDAO->obtenerEncuestaRealizadaPorAsignacion($asignacion["idAsignacion"]);
                        
                        //$asignacionDAO->obtenerEvaluacionGeneralDocente($docente->getIdRegistro(), $encuesta->getIdEncuesta());
                        if(!is_null($encuestasRealizadas)){
                            foreach ($encuestasRealizadas as $erealizada) : 
                                //$encuesta = $encuestaDAO->obtenerEncuesta($erealizada["idEncuesta"]);
                                $encuesta = $encuestaDAO->getEncuestaById($erealizada["idEncuesta"]);
                                $cssDisabled = "";
                                $cssBadge = "badge-info";
                                if($erealizada["realizadas"] <= 0){
                                    $cssDisabled = "disabled";
                                    $cssBadge = "badge-warning";
                                }
                            ?>
                            <tr>
                                <td><?php echo $grupo->getGrupo() ?></td>
                                <td><?php echo $materia->getMateria() ?></td>
                                <td><?php echo $encuesta->getNombre() ?></td> 
                                <td>
                                    <a target="_blank" class="btn btn-success btn-block <?php echo $cssDisabled; ?>" 
                                       href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"resgrupal","idEncuesta"=>$encuesta->getIdEncuesta(),"idAsignacion"=>$asignacion["idAsignacionGrupo"]),null,true) ?>">
                                        <span class="icon icon-check"></span> <span class="badge <?php echo $cssBadge; ?>"><?php echo $erealizada["realizadas"] ?></span> Detalle en Web 
                                    </a>
                                </td>
                            </tr>           
                    <?php   endforeach; } ?>
                    
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12 widget-box">
        <div class="widget-title">
            <h5>Reportes Generales // Docente: <strong><?php echo $docente->getApellidos().", ".$docente->getNombres() ?></strong></h5>
        </div>
        <div class="widget-content">
            <?php
                //$encuestaDAO->obtenerObjetoEncuesta($en, $idAsignacion)
                //print_r($asignaciones);
                $lista = array();
                foreach ($asignaciones as $asignacion) {
                    //echo $asignacion["idAsignacion"] . "<br />";
                    $encuesta = array();
                    $erealizadas = $encuestaDAO->obtenerEncuestasRealizadasPorAsignacion($asignacion["idAsignacionGrupo"]);
                    
                    foreach ($erealizadas as $erealizada) {
                        //print_r($erealizada);
                        //print_r("---");
                        //$encuesta[$erealizada["idEncuesta"]][] = $erealizada;
                        $lista[$erealizada["idEncuesta"]][] = $erealizada["idAsignacionGrupo"];
                    }
                    //$lista[] = $encuesta;
                    //print_r("<br />");
                }
                
                //print_r($lista);
                /*
                foreach ($asignaciones as $asignacion) {
                    $erealizadas = $encuestaDAO->obtenerEncuestasRealizadasPorAsignacion($asignacion["idAsignacion"]);
                    foreach ($erealizadas as $erealizada) {
                        $encuestaDAO->obtenerObjetoEncuesta($erealizada["idEncuesta"], $erealizada["idAsignacion"]);
                        print_r("<br />");
                        print_r("<br />");
                    }
                }
                */
            ?>
            <table class="table table-bordered table-condensed table-striped">
                <thead>
                    <tr>
                        <th>Evaluacion</th>
                        <th>Resultados</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($lista as $idEncuesta => $asign) :
                        // $idEncuesta es el idEncuesta, $asign en un array ordenado de id's asignación.
                        $encuesta = $encuestaDAO->getEncuestaById($idEncuesta);
                        $numeroEncuestas = count($asign);
                        ?>
                    <tr>
                        <td><?php echo $encuesta->getNombre() ?></td>
                        <td>
                            <a class="btn btn-warning btn-block" target="_blank" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"repgeneral","idDocente"=>$docente->getIdRegistro(),"idEncuesta"=>$encuesta->getIdEncuesta()),null,true) ?>">
                                <span class="icon icon-search"></span> Ver en Web <span class="badge badge-important"><?php echo $numeroEncuestas ?></span> Grupos
                            </a>
                        </td>
                    </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
