<?php
	$docentes = $this->docentes;
	//$encuestasRealizadas = $this->encuestasVigentesRealizadas;
	$registroDAO = $this->registroDAO;
	//$registroDAO = new Encuesta_DAO_Registro;
	//$encuestaDAO = new Encuesta_DAO_Registro;
	
	
?>
<div class="row-fluid">
    <div class="span12 widget-box">
        <div class="widget-title">
            <h5>Evaluaciones disponibles</h5>
        </div>
        <div class="widget-content">
            <table class="table table-bordered table-striped table-condensed">
                <thead>
                    <th>Perfil</th>
                    <th>Evaluaciones</th>
                    <th>Docente</th>
                </thead>
                <tbody>
                    <?php foreach ($docentes as $docente) :
                         
                        //$docente = $registroDAO
                        //$encuesta = $encuestaDAO->obtenerEncuesta($encuesta["idEncuesta"]);
                        $dir = array("module"=>"encuesta","controller"=>"profesor","action"=>"admin","idDocente"=>$docente->getIdRegistro());
                        ?>
                    <tr>
                        <td>
                            <a class="btn btn-link" href="#">
                                <span class="icon icon-user"></span> Perfil
                            </a>
                        </td>
                        <td>
                            <a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"profesor","action"=>"encuestas","idDocente"=>$docente->getIdRegistro()),null,true) ?>">
                                <span class="icon icon-ok"></span> Evaluaciones
                            </a>
                        </td>
                        <td>
                            <?php echo $docente->getApellidos().", ".$docente->getNombres() ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
