<?php
	$docentes = $this->docentes;
	//$encuestasRealizadas = $this->encuestasVigentesRealizadas;
	
	$registroDAO = new Encuesta_DAO_Registro;
	$encuestaDAO = new Encuesta_DAO_Registro;
	
	
?>
<section class="row">
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">
				 Evaluaciones Disponibles de Docentes del <strong>Colegio Sagrado Corazon.</strong>
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<th>Perfil</th>
					<th>Evaluaciones</th>
					<th>Docente</th>
				</thead>
				<tbody>
					<?php foreach ($docentes as $docente) :
						 
						//$docente = $registroDAO
						//$encuesta = $encuestaDAO->obtenerEncuesta($encuesta["idEncuesta"]);
						$dir = array("module"=>"encuesta","controller"=>"profesor","action"=>"admin","idDocente"=>$docente->getIdRegistro());
						?>
					<tr>
						<td>
							<a class="btn btn-link" href="#">
								<span class="glyphicon glyphicon-user"></span> Perfil
							</a>
						</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"profesor","action"=>"encuestas","idDocente"=>$docente->getIdRegistro()),null,true) ?>">
								<span class="glyphicon glyphicon-ok"></span> Evaluaciones
							</a>
						</td>
						<td>
							<?php echo $docente->getApellidos().", ".$docente->getNombres() ?>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</section>