<?php 
	$seccion = $this->seccion;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"encuesta","controller"=>"seccion","action"=>"edita","idSeccion"=>$seccion->getIdSeccionEncuesta()), null, TRUE));
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Detalle Sección
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>Fecha Creacion</th>
					<th>Orden</th>
					<th>Elementos</th>
					<th>Navegar</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><?php echo $seccion->getNombre(); ?></td>
					<td><?php echo $seccion->getFecha(); ?></td>
					<td><?php echo $seccion->getOrden(); ?></td>
					<td><?php echo $seccion->getElementos(); ?></td>
					<td>
						<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"seccion","action"=>"index","idSeccion"=>$seccion->getIdSeccionEncuesta()),null,true) ?>">
							Ir a los Elementos
						</a>
					</td>
				</tr>
			</tbody>
		</table>
		</div>
	</div>
	
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Sección
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $formulario; ?>
		</div>
	</div>
	
</section>
