<?php 
	$seccion = $this->seccion;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"encuesta","controller"=>"seccion","action"=>"edita","idSeccion"=>$seccion->getIdSeccion()), null, TRUE));
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Detalle Sección
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>Fecha Creacion</th>
					<th>Orden</th>
					<th>Elementos</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><?php echo $seccion->getNombre(); ?></td>
					<td><?php echo $seccion->getFecha(); ?></td>
					<td><?php echo $seccion->getOrden(); ?></td>
					<td><?php echo $seccion->getElementos(); ?></td>
				</tr>
			</tbody>
		</table>
		</div>
	</div>
	
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Sección
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $formulario; ?>
		</div>
	</div>
	
	<div class="panel panel-danger">
		<div class="panel-heading">
			<h3 class="panel-title">
				Eliminar Sección
			</h3>
		</div>
		<div class="panel-body">
			<p>
				Una sección solo se puede eliminar si no contiene elementos dentro de si.
			</p>
			<p>
				Los elementos de una sección son los grupos y las preguntas.
			</p>
			<a class="btn btn-danger" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"seccion","action"=>"baja","idSeccion"=>$seccion->getIdSeccion(),)) ?>">
				Eliminar Sección
			</a>
		</div>
	</div>
</section>
