<?php 
	$seccion = $this->seccion;
	$elementos = $this->elementos;
	$tipo = Zend_Registry::get("tipo");
?>
<section class="row">
	<header>
		<h3>Grupos y preguntas de la sección: <?php echo $seccion->getNombre(); ?></h3>
	</header>
	<div>
		<a href="<?php echo $this->url(array("module" => "encuesta", "controller" => "grupo", "action" => "alta", "idSeccion" => $seccion->getIdSeccion()), null, true); ?>" class="btn btn-success">
			<span class="glyphicon glyphicon-plus"></span> Agregar grupo
		</a>
		<a href="<?php echo $this->url(array("module" => "encuesta", "controller" => "pregunta", "action" => "alta", "idSeccion" => $seccion->getIdSeccion()), null, true); ?>" class="btn btn-success">
			<span class="glyphicon glyphicon-plus"></span> Agregar pregunta
		</a>
	</div>
</section>

<section class="row">
	<?php if(!is_null($elementos) && count($elementos)) { ?>
	<table class="table table-condensed table-striped">
		<thead>
			<tr>
				<th>Elemento</th>
				<th>Nombre</th>
				<th>Orden</th>
				<th>Tipo Pregunta(s)</th>
				<th>Creación</th>
				<th>Administrar</th>
			</tr>
		</thead>
		<?php foreach ($elementos as $elemento) : 
			$t = ($elemento instanceof Encuesta_Model_Grupo) ? "grupo" : "pregunta";
			$id = ($elemento instanceof Encuesta_Model_Grupo) ? $elemento->getIdGrupo() : $elemento->getIdPregunta();
			$url = $this->url(array("module" => "encuesta", "controller" => $t, "action" => "admin", "id".ucfirst($t) => $id), null, true);
			?>
		<tr>
			<td><?php echo ucfirst($t); ?></td>
			<td><?php echo ($elemento instanceof Encuesta_Model_Grupo) ? $elemento->getNombre() : $elemento->getPregunta(); ?></td>
			<td><?php echo $elemento->getOrden(); ?></td>
			<td><?php echo $tipo[$elemento->getTipo()]; ?></td>
			<td><?php echo $elemento->getFecha(); ?></td>
			<td>
				<a class="btn btn-info" href="<?php echo $url; ?>">
					<span class="glyphicon glyphicon-cog"></span> Administrar
				</a>
			</td>
		</tr>
		<?php endforeach; ?>
	</table>
	<?php }else{ ?>
		<h3>Esta seccion no contiene grupos ni preguntas.</h3>
	<?php } ?>
</section>
