<?php echo $this->formulario ?>

<form name="nuevaNota">
<section class="row">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">
				Agregar Productos para Nota Entrada.
			</h3>
		</div>
		<div class="panel-body">
			<!-- -->
			<!-- Botón para agregar filas-->
			<button id="addRow" class="btn btn-success" >
				<span class="glyphicon glyphicon-plus" ></span> Nuevo
			</button>
			<!-- Botón para calcular total importe-->
			<button id="processTable" class="btn btn-warning">
				<span class="glyphicon glyphicon-cog" ></span> Calcular
			</button><br /><br />
			<table id="productosNota" class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Cantidad</th>
						<th>Clave Producto</th>
						<th>Seleccione Unidad</th>
						<th>Codigo de Barras</th>
						<th>Descripcion</th>
						<th>Precio Unitario</th>
						<th>Importe</th>
						<th>Eliminar</th>
					</tr>
				</thead>
				<tbody>
				</tbody>
				<tfoot>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td><input id="total" class="form-control" /></td>
					</tr>
				</tfoot>
			</table>
			<br />
		</div>
	</div>
</section>
<a class="btn btn-primary" href="<?php $this->url (array("module"=>"contabilidad","controller"=>"notaproveedor","action"=>"nueva")) ?>">
	<span class="glyphicon glyphicon-envelope"></span> Enviar
</a>

<script>
	$( document ).ready(function() {
		console.log( "ready!" );
		var jsonProductos = <?php echo $this->jsonProductos; ?>;
		var jsonUnidad = <?php echo $this->jsonUnidad; ?>;
		//console.dir(jsonProductos);
		
		// cuando se presione el boton con id=addRow, se inserta una nueva fila en la tabla de productos
		$("button#addRow").on("click",function(){
			var filasTabla = $("table#productosNota tbody > tr").length;
			//console.log(filasTabla);
			// si filasTabla = 0 continuar
			// si filasTabla <> 0 checar fila actual
			filasTabla ++;
			// generamos elementos de nueva fila
			// cantidad
			var inputCantidad = $('<input />').attr({'id': 'idCantidad_' + filasTabla}).attr({'class':'form-control'}).attr({'value':0});
			// idProducto
			var inputProducto = $('<input />').attr({'id': 'idProducto_' + filasTabla}).attr({'class':'form-control'});

			// idUnidad
			var inputUnidad = $('<select />').attr({'id': 'idUnidad_' + filasTabla}).attr({'class':'form-control'});
			$.each(jsonUnidad,function(i,item){
				inputUnidad.append('<option value="'+jsonUnidad[i].idUnidad+'">'+jsonUnidad[i].unidad+'</option>');
			});
			// codigoBarras
			var inputCodigoBarras = $('<input />').attr({'id': 'codigoBarras_' + filasTabla}).attr({'class':'form-control'});
			// descripcion
			//var inputDescripcion = $('<input />').attr({'id': 'descripcion_' + filasTabla}).attr({'class':'form-control'});
			var selectDescripcion = $('<select />').attr({'id': 'descripcion_' + filasTabla}).attr({'class':'form-control'});
			$.each(jsonProductos,function(i,item){
				selectDescripcion.append('<option value="'+jsonProductos[i].idProducto+'">'+jsonProductos[i].producto+'</option>');
			});	
			// precioUnitario
			var inputCostoUnitario = $('<input />').attr({'id': 'costoUnitario_' + filasTabla}).attr({'class':'form-control'});
			// precioImporte
			var inputCostoTotal = $('<input />').attr({'id': 'costoTotal_' + filasTabla}).attr({'class':'form-control'}).attr({'name':'precioImporte_'});
			
			// botonLimpiar
			var buttonLimpiar = $('<button />').attr({'id': 'btnLimpiar_' + filasTabla}).attr({'class':'btn btn-danger'});
			buttonLimpiar.html('<span class="glyphicon glyphicon-remove-circle"></span> Eliminar Producto')

			var tbody = $("table#productosNota").find('tbody');
			tbody.append($('<tr>').
				append($('<td>').append(inputCantidad)).
				append($('<td>').append(inputProducto)).
				append($('<td>').append(inputUnidad)).
				append($('<td>').append(inputCodigoBarras)).
				append($('<td>').append(selectDescripcion)).
				append($('<td>').append(inputCostoUnitario)).
				append($('<td>').append(inputCostoTotal)).
				append($('<td>').append(buttonLimpiar))
				
			);
		});//cierra el addRow
		
		//Funcion Eliminar #btnLimpiar_2
 		$("table#productosNota").on("click", "button[id^='btnLimpiar_']", function(){
 			var numero=0;
 			var tabla = document.getElementById("productosNota");
 
  			// si tenemos mas de una fila, borramos3
  			if(tabla.rows.length > 2)
  			{
  				tabla.deleteRow(tabla.rows.length-1);
  				--numero;
  			}
 		});//cierra funcion eliminar
 		
 		//Funcion buscar descripcion del producto
 		$("table#productosNota").on("change", "select[id^='descripcion_']", function(){
 			var descripcion= $(this).attr("id");
			var arr = descripcion.split('_');
			var id = $(this).val();
			//console.log(id);
			var numFila =  arr[1];
 			
 			$.each(jsonProductos,function(i,item){
 				if(jsonProductos[i].idProducto == id){
 					$("input#idProducto_"+numFila).val(jsonProductos[i].claveProducto);
 				}
 				
				//selectProducto.append('<option value="'+jsonProductos[i].idProducto+'">'+jsonProductos[i].claveProducto+'</option>');
			});
 			
 		});//cierra funcion buscar descripcion del producto

		//input  cantidad
		$("table#productosNota").on("change","input[id^='idCantidad_']" ,function() {
			var idCantidad= $(this).attr("id");
			var arr = idCantidad.split('_');
			var numFila =  arr[1];
			
			var precioUnitarioFila = $('input#costoUnitario_'+numFila);
			//console.log(precioUnitarioFila);
			var precioImporte = $(this).val() * precioUnitarioFila.val();

			$('input#costoTotal_'+numFila).val(precioImporte);
			//console.log($(this).val())	;
			
 		}); //cierra input cantidad
//input  precioImporte
		//$("table#productosNota input[id^='costoTotal_']".keyup ,function() {
		$("table#productosNota").on("click", "input[id^='costoTotal_']", function(){	
			var t;
			var total =$(this).val();
			
			console.log(total);
 		}); //cierra input cantidad
 		
 		//Funcion genera totalColumna

 	
//======================
 		//input precioUnitario
 		$("table#productosNota").on("change", "input[id^='costoUnitario_']", function(){
 			var precioUnitario = $(this).attr("id");
 			var arr = precioUnitario.split('_');
 			var numFila = arr[1];
 			
 			var cantidadFila = $('input#idCantidad_'+numFila);
 			var precioImporte = $(this).val() * cantidadFila.val();
 			
 			$('input#costoTotal_'+numFila).val(precioImporte);
 			
 		});//cierra input precioUnitario
 		
	});//cierra document ready
</script>
