<?php
	
?>
<section class="row">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">
				Agregar Productos para Nota Entrada.
			</h3>
		</div>
		<div class="panel-body">
			<!-- -->
			<!-- Botón para agregar filas-->
			<button id="addRow" class="btn btn-success" >
				<span class="glyphicon glyphicon-plus" ></span> Nuevo
			</button><br />
			<table id="productosNota" class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Cantidad</th>
						<th>Seleccionar Producto</th>
						<th>Seleccione Unidad</th>
						<th>Codigo de Barras</th>
						<th>Descripcion</th>
						<th>Precio Unitario</th>
						<th>Importe</th>
						<th>Eliminar</th>
					</tr>
				</thead>
				<tbody>
				</tbody>
				<tfoot>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td><input id="total" class="form-control" /></td>
					</tr>
				</tfoot>
			</table>
			<br />
			<a class="btn btn-primary">
				<span class="glyphicon glyphicon-envelope"></span>Enviar
			</a>
		</div>
	</div>
</section>	
<script>
	$( document ).ready(function() {
		console.log( "ready!" );
		var jsonProductos = <?php echo $this->jsonProductos; ?>;
		var jsonUnidad = <?php echo $this->jsonUnidad; ?>;
		console.dir(jsonProductos);
		
		// cuando se presione el boton con id=addRow, se inserta una nueva fila en la tabla de productos
		$("button#addRow").on("click",function(){
			var filasTabla = $("table#productosNota tbody > tr").length;
			//console.log(filasTabla);
			// si filasTabla = 0 continuar
			// si filasTabla <> 0 checar fila actual
			filasTabla ++;
			// generamos elementos de nueva fila
			// cantidad
			var inputCantidad = $('<input />').attr({'id': 'idCantidad_' + filasTabla}).attr({'class':'form-control'}).attr({'value':0});
			// idProducto
			var selectProducto = $('<select />').attr({'id': 'idProducto_' + filasTabla}).attr({'class':'form-control'});
			$.each(jsonProductos,function(i,item){
				selectProducto.append('<option value="'+jsonProductos[i].idProducto+'">'+jsonProductos[i].claveProducto+'</option>');
			});
			// idUnidad
			var inputUnidad = $('<select />').attr({'id': 'idUnidad_' + filasTabla}).attr({'class':'form-control'});
			$.each(jsonUnidad,function(i,item){
				inputUnidad.append('<option value="'+jsonUnidad[i].idUnidad+'">'+jsonUnidad[i].unidad+'</option>');
			});
			// codigoBarras
			var inputCodigoBarras = $('<input />').attr({'id': 'codigoBarras_' + filasTabla}).attr({'class':'form-control'});
			// descripcion
			var inputDescripcion = $('<input />').attr({'id': 'descripcion_' + filasTabla}).attr({'class':'form-control'});
				
			// precioUnitario
			var inputPrecioUnitario = $('<input />').attr({'id': 'precioUnitario_' + filasTabla}).attr({'class':'form-control'}).attr({'value':0});
			// precioImporte
			var inputPrecioImporte = $('<input />').attr({'id': 'precioImporte_' + filasTabla}).attr({'class':'form-control disabled'});
			
			// botonLimpiar
			var buttonLimpiar = $('<button />').attr({'id': 'btnLimpiar_' + filasTabla}).attr({'class':'btn btn-danger'});
			buttonLimpiar.html('<span class="glyphicon glyphicon-remove-circle"></span> Eliminar Producto')

			var tbody = $("table#productosNota").find('tbody');
			tbody.append($('<tr>').
				append($('<td>').append(inputCantidad)).
				append($('<td>').append(selectProducto)).
				append($('<td>').append(inputUnidad)).
				append($('<td>').append(inputCodigoBarras)).
				append($('<td>').append(inputDescripcion)).
				append($('<td>').append(inputPrecioUnitario)).
				append($('<td>').append(inputPrecioImporte)).
				append($('<td>').append(buttonLimpiar))
				
			);
		});//cierra el addRow
		
		//Funcion Eliminar #btnLimpiar_2
 		$("table#productosNota").on("click", "button[id^='btnLimpiar_']", function(){
 			var numero=0;
 			var tabla = document.getElementById("productosNota");
 
  			// si tenemos mas de una fila, borramos3
  			if(tabla.rows.length > 2)
  			{
  				tabla.deleteRow(tabla.rows.length-1);
  				--numero;
  			}
 		});//cierra funcion eliminar
 		
 		//Funcion buscar descripcion del producto
 		$("table#productosNota").on("change", "select[id^='idProducto_']", function(){
 			var idProducto= $(this).attr("id");
			var arr = idProducto.split('_');
			var id = $(this).val();
			//console.log(id);
			var numFila =  arr[1];
 			
 			$.each(jsonProductos,function(i,item){
 				if(jsonProductos[i].idProducto == id){
 					$("input#descripcion_"+numFila).val(jsonProductos[i].producto);
 				}
 				
				//selectProducto.append('<option value="'+jsonProductos[i].idProducto+'">'+jsonProductos[i].claveProducto+'</option>');
			});
 			
 		});//cierra funcion buscar descripcion del producto

		//input  cantidad
		$("table#productosNota").on("change","input[id^='idCantidad_']" ,function() {
			var idCantidad= $(this).attr("id");
			var arr = idCantidad.split('_');
			var numFila =  arr[1];
			
			var precioUnitarioFila = $('input#precioUnitario_'+numFila);
			//console.log(precioUnitarioFila);
			var precioImporte = $(this).val() * precioUnitarioFila.val();
			//console.log($(this).val());
			//console.log(precioUnitarioFila.val());
			//console.log(precioImporte);
			$('input#precioImporte_'+numFila).val(precioImporte);
			//console.log(idCantidad)	;
 		}); //cierra input cantidad
 		
 		//Funcion genera totalColumna
		$("table#productosNota").on("click","input[id^='precioImporte_']" ,function() {
			var precioImporte= $(this).attr("id");
			var arr = precioImporte.split('_');
			var numColumna =  arr[1];
			
			var total = $('input#precioImporte_'+numColumna);
			var totalColumna = total.val() + total.val();
			console.log(totalColumna);
			//console.log($(this).val());
			//totalColumna = precioImporte.val() + total;
			//console.log(totalColumna);			
 		
 		});//cierra la funcion de genera columna
 		//input precioUnitario
 		$("table#productosNota").on("change", "input[id^='precioUnitario_']", function(){
 			var precioUnitario = $(this).attr("id");
 			var arr = precioUnitario.split('_');
 			var numFila = arr[1];
 			
 			var cantidadFila = $('input#idCantidad_'+numFila);
 			var precioImporte = $(this).val() * cantidadFila.val();
 			
 			$('input#precioImporte_'+numFila).val(precioImporte);
 		});//cierra input precioUnitario
 		
	});//cierra document ready
</script>
