<?php 
	$encuesta = $this->encuesta;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"encuesta","controller"=>"generador","action"=>"alta","idEncuesta"=>$encuesta->getIdEncuesta())));
?>
<section class="row">
	<article class="col-md-12">
		<header>
			<h3>Encuesta: <?php echo $encuesta->getNombre()  ?></h3>
		</header>
		<div>
			<?php echo $formulario; ?>
		</div>
	</article>
</section>
