<?php 
	$encuesta = $this->encuesta;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"encuesta","controller"=>"generador","action"=>"alta","idEncuesta"=>$encuesta->getIdEncuesta())));
?>
<section class="row">
	<article class="col-md-12">
		<header>
			<h3>Encuesta: <?php echo $encuesta->getNombre()  ?></h3>
		</header>
	</article>
</section>
<section class="row">
	<article class="col-md-4"></article>
	<article class="col-md-4"><img src="<?php echo $this->baseUrl() . "/images/Logo.png" ?>" /></article>
	<article class="col-md-4"></article>
</section>
<section class="row">
	<article class="col-md-12">
		<?php echo $formulario; ?>
	</article>
</section>
<br /><br /><br />
