<?php 
	$formulario = $this->formulario;
	$fiscales = $this->fiscales;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Empresa
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<th>Empresa</th>
					<th>Domicilio</th>
					<th>Telefonos</th>
					<th>Emails</th>
				</thead>
				<tbody>
					<tr>
						<td><?php echo $fiscales->getRazonSocial(); ?></td>
						<td>
							<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"domicilio","action"=>"fiscal","idFiscales"=>$fiscales->getIdFiscales()),null,true) ?>">
								<span class="glyphicon glyphicon-cog"></span> Administrar
							</a>
						</td>
						<td>
							<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"telefono","action"=>"fiscal","idFiscales"=>$fiscales->getIdFiscales()),null,true) ?>">
								<span class="glyphicon glyphicon-cog"></span> Administrar
							</a>
						</td>
						<td>
							<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"email","action"=>"fiscal","idFiscales"=>$fiscales->getIdFiscales()),null,true) ?>">
								<span class="glyphicon glyphicon-cog"></span> Administrar
							</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Empresa
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $formulario; ?>
		</div>
	</div>
</section>