<?php 
	$fiscales = $this->fiscales;
	$empresaDAO = new Sistema_DAO_Empresa;
?>
<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Empresas en el Sistema
		</h3>
	</div>
	<div class="panel-body">
		<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"empresas","action"=>"alta",),null,true) ?>">
			<span class="glyphicon glyphicon-plus"></span> Nueva Empresa
		</a>
		<br /><br />
		<table class="table table-striped table-condensed">
			<thead>
				<th>R.F.C.</th>
				<th>Razon Social</th>
				<th>Creación</th>
				<th>Es Cliente</th>
				<th>Es Proveedor</th>
				<th>Datos</th>
			</thead>
			<tbody>
				<?php foreach ($fiscales as $fiscal) : 
					$empresa = $empresaDAO->obtenerEmpresaIdFiscales($fiscal->getIdFiscales());
					
					?>
				<tr>
					<td><?php echo $fiscal->getRfc() ?></td>
					<td><?php echo $fiscal->getRazonSocial() ?></td>
					<td><?php echo $fiscal->getFecha() ?></td>
					<td><?php echo $cliente = ($empresa->getEsCliente()) == "S" ? "Si" : "No" ; ?></td>
					<td><?php echo $proveedor = ($empresa->getEsProveedor()) == "S" ? "Si" : "No" ; ?></td>
					<td>
						<button class="btn btn-info" fiscales="<?php echo $fiscal->getIdFiscales() ?>">
							<span class="glyphicon glyphicon-cog"></span> Domicilio, Telefonos, e Emails
						</button>
					</td>
				</tr>
				<?php endforeach ?>
			</tbody>
		</table>
	</div>
</section>
<section class="panel panel-info">
	<div class="panel-heading">
		<h3 class="panel-title">
			Domicilio
		</h3>
	</div>
	<div class="panel-body domicilio">
		
	</div>
</section>
<section class="panel panel-info">
	<div class="panel-heading">
		<h3 class="panel-title">
			Telefonos
		</h3>
	</div>
	<div class="panel-body telefonos">
		
	</div>
</section>
<section class="panel panel-info">
	<div class="panel-heading">
		<h3 class="panel-title">
			Emails
		</h3>
	</div>
	<div class="panel-body emails">
		
	</div>
</section>
<script>
	$(document).ready(function() {
		//===================================================================================
	    $('table.table').dataTable( {
	       "pagingType": "full_numbers",
	        "language": {
	        	"url": "//cdn.datatables.net/plug-ins/1.10.10/i18n/Spanish.json"
	        }
	    } );
	    //===================================================================================
	    $("button.btn-info").on('click', function() {
			//console.log(this.value);
			$idFiscal = $(this).attr("fiscales");
			console.log($idFiscal);
			//Obtengo los municipios del estado
			
			$url = "/General/public/sistema/html/domicilio/idFiscales/" + $idFiscal;
			console.log($url);
			
			$.ajax({
				url: $url,
				dataType: "html",
				success: function(data){
					console.log($url);
					//console.dir(data);
					$("div.domicilio").html(data);
					
				}
			});
			
			$url = "/General/public/sistema/html/telefonos/idFiscales/" + $idFiscal;
			console.log($url);
			
			$.ajax({
				url: $url,
				dataType: "html",
				success: function(data){
					console.log($url);
					//console.dir(data);
					$("div.telefonos").html(data);
					
				}
			});
			
			$url = "/General/public/sistema/html/emails/idFiscales/" + $idFiscal;
			console.log($url);
			
			$.ajax({
				url: $url,
				dataType: "html",
				success: function(data){
					console.log($url);
					//console.dir(data);
					$("div.emails").html(data);
					
				}
			});
			
		});
	    
	} );
</script>