<?php
	$formulario = $this->formulario;
?>
<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Saldo Banco Por Mes.
		</h3>
	</div>
	<div class="panel-body">
		<div class="container">
			<div class="col-md-6">
				<?php echo $formulario; ?>
			</div>
		</div>
	</div>
</section>
<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Saldo Empresa.</h4>
		</div>
		<table id="detalleSaldoBancoMes" class="table table-striped table-condensed">
			<thead>
				<th>Mes</th>
				<th>Entrada</th>
				<th>Salida</th>
				<th>Saldo Inicial</th>
				<th>Saldo Final</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>
<script>
	$().ready(function(){
		var url = window.location.origin + "/General/";
			
		$("#idEmpresas").on('change',function(){
			//console.log($(this).val());
			var idEmp = $(this).val();
			if(idEmp != 0){
				var urlQuerySucursales = url + 'sistema/json/sucursales/idFiscales/'+idEmp;
				console.log(urlQuerySucursales);
				$.ajax({
					url: urlQuerySucursales,
					dataType: "json",
					success: function(data){
						console.dir(data);
						$("#idSucursal").empty();
						$("#idSucursal").append($("<option></option>").attr("value","0").text("Seleccione Sucursal..."));
						$.each(data, function (i,item){
							$("#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal));
						});
					}
				});
			}
		});
		
		$("select#idEmpresas").on('change', function(){
			$url = url + "contabilidad/json/bancosempresa/emp/" + this.value;
			console.log($url);
			$.ajax({
				url: $url,
				//console.log($ajax);
				dataType: "json",
				success: function(data){
					$("select#idBanco").empty();
					$.each(data, function(i,item){	
						$("select#idBanco").append($("<option></option>").attr("value",data[i].idBanco).text(data[i].banco));
						
					});
				}
			});
		});
		
		
		$("button#button").on("click", function(){
			console.log("BUSCA");
			
		});
		
		
		
	});//document ready
</script>