<?php
	$formulario = $this->formulario;
?>
<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Saldo Banco Por Mes.
		</h3>
	</div>
	<div class="panel-body">
		<div class="container">
			<div class="col-md-6">
				<?php echo $formulario; ?>
			</div>
		</div>
	</div>
</section>
<section>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle Saldo Empresa.</h4>
		</div>
		<table id="detalleSaldoBancoMes" class="table table-striped table-condensed">
			<thead>
				<th>Mes</th>
				<th>Año</th>
				<th>Entrada</th>
				<th>Salida</th>
				<th>Saldo Inicial</th>
				<th>Saldo Final</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>

<script>
$().ready(function(){
	var url = window.location.origin + "/General/";

	$("#idEmpresas").on('change',function(){
		var idEmp = $(this).val();
		if(idEmp != 0){
			var urlQuerySucursales = url + 'sistema/json/sucursales/idFiscales/'+idEmp;
			$.ajax({
				url: urlQuerySucursales,
				dataType: "json",
				success: function(data){
					$("#idSucursal").empty();
    				$("#idSucursal").append($("<option></option>").attr("value","0").text("Seleccione Sucursal..."));
    				$.each(data, function (i,item){
    					$("#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal));
    				});
				}
			});
		}
	});
		
	$("select#idEmpresas").on('change', function(){
		$url = url + "contabilidad/json/bancosempresa/emp/" + this.value;
		$.ajax({
			url: $url,
			dataType: "json",
			success: function(data){
				$("select#idBanco").empty();
				$.each(data, function(i,item){	
					$("select#idBanco").append($("<option></option>").attr("value",data[i].idBanco).text(data[i].banco));
				});
			}
		});
	});

	$("#button").on("click", function (){
		var em = $("select#idEmpresas").val();
		var ban = $("select#idBanco").val();
		var urlSBanco = window.location.origin + "/General/sistema/json/saldobanco/em/"+ em + "/ban/" + ban;
		$.ajax({
			url: urlSBanco,
			dataType: "json",
			success: function(data){
			var tbody = $("table#detalleSaldoBancoMes").find('tbody');
			tbody.empty();
			$.each(data, function(i,item){
				var mm ;
				if(data[i].mes == 01){
					mm= 'Enero';
				}else if(data[i].mes == 02){
					mm= 'Febrero';
				}else if(data[i].mes == 03){
					mm= 'Marzo';
				}else if(data[i].mes == 04){
					mm= 'Abril';
				}else if(data[i].mes == 05){
					mm= 'Mayo';
				}else if(data[i].mes == 06){
					mm= 'Junio';
				}else if(data[i].mes == 07){
					mm= 'Julio';
				}else if(data[i].mes == 08){
					mm= 'Agosto';
				}else if(data[i].mes == 09){
					mm= 'Septiembre';
				}else if(data[i].mes == 10){
					mm= 'Octubre';
				}else if(data[i].mes == 11){
					mm= 'Noviembre';
				}else if(data[i].mes == 12){
					mm= 'Diciembre';
				}
				
				tbody.append($('<tr>').
					  append($('<td>').append(mm)).
					  append($('<td>').append(data[i].anio)).
					  append($('<td>').append(parseFloat(data[i].entradas).toFixed(3)).attr('id','totalEntradas')).
					  append($('<td>').append(parseFloat(data[i].salidas).toFixed(3)).attr('id','totalSalidas')).
					  append($('<td>').append(parseFloat(data[i].saldoIniMes).toFixed(3).replace(/\B(?=(\d{3})+(?!\d))/g, ","))).
					  append($('<td>').append(parseFloat(data[i].saldoFinMes).toFixed(3).replace(/\B(?=(\d{3})+(?!\d))/g, ",")))
					  );	
				});
			    AddRow();
				calculaTotal();
			}
		});
	});

	function AddRow(){
		$('#detalleSaldoBancoMes tbody').append('<tr><td></td><td><b>Total:</b></td><td><input id="saldoE"class="form-control" style="width:120px"></input></td><td><input id="saldoS"class="form-control" style="width:120px"></input></td><td></td><td></td></tr>');
    }

	function calculaTotal(){
		var total = 0;
		var totalS = 0;

		$("table#detalleSaldoBancoMes").find("td[id^='totalEntradas']").each(function(){
			total += +$(this).text();
			$("#saldoE").val("$" + total.toFixed(3).replace(/\B(?=(\d{3})+(?!\d))/g, ","));
		});

		$("table#detalleSaldoBancoMes").find("td[id^='totalSalidas']").each(function(){
			totalS += +$(this).text();
			$("#saldoS").val("$" + totalS.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ","));
		});
				
	}		
});//document ready
</script>

