<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
		Contabilidad <span class="caret"></span>
	</a>
	<ul class="dropdown-menu multi-level" role="menu">
		<li class="dropdown-submenu">
			<a class="test" tabindex="-1" href="<?php echo $this->url(array("module"=>"contabilidad","controller"=>"empresas","action"=>"index"), null, true) ?>">
				Empresas
			</a>
			<ul class="dropdown-menu">
				<li>
					<a href="<?php echo $this->url(array("module"=>"contabilidad","controller"=>"empresas","action"=>"clientes"),null,true) ?>">
						Clientes
					</a>
				</li>
				<li>
					<a href="<?php echo $this->url(array("module"=>"contabilidad","controller"=>"empresas","action"=>"proveedores"),null,true) ?>">
						Proveedores
					</a>
				</li>
			</ul>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'impuestos', 'action' => 'index'), null, true); ?>">
				Impuestos
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'banco', 'action' => 'index'), null, true); ?>">
				Bancos
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'divisa', 'action' => 'index'), null, true); ?>">
				Divisa
			</a>
		</li>
		<li class="dropdown-submenu">
			<a class="test" tabindex="-1" href="#">
				Clientes
			</a>
			<ul class="dropdown-menu">
				<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'clientes', 'action' => 'consecutivofactura'), null, true); ?>">Editar Número Factura</a></li>
				<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'clientes', 'action' => 'factura'), null, true); ?>">Factura</a></li>
				<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'clientes', 'action' => 'nota'), null, true); ?>">Nota</a></li>
				<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'clientes', 'action' => 'remision'), null, true); ?>">Remision</a></li>
				<li class="dropdown-submenu">
					<a class="test" tabindex="-1" href="#">
						Cobros
					</a>
					<ul class="dropdown-menu">
						<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'clientes', 'action' => 'cobros'), null, true); ?>">Cobro de Factura</a></li>	
						<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'clientes', 'action' => ''), null, true); ?>">Cancelar Pagos</a></li>
						<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'clientes', 'action' => ''), null, true); ?>">Cancelar Remisiones</a></li>
					</ul>
				</li>
			</ul>
		</li>
		<li class="dropdown-submenu">
			<a class="test" tabindex="-1" href="#">
				Proveedores
			</a>
			<ul class="dropdown-menu">
				<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'proveedor', 'action' => 'factura'), null, true); ?>">Factura</a></li>
				<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'proveedor', 'action' => 'nota'), null, true); ?>">Nota</a></li>
				<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'proveedor', 'action' => 'remision'), null, true); ?>">Remision</a></li>
				<li class="dropdown-submenu">
					<a class="test" tabindex="-1" href="#">
						Pagos
					</a>
					<ul class="dropdown-menu">
						<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'proveedor', 'action' => 'pagos'), null, true); ?>">Pago de Factura</a></li>	
						<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'proveedor', 'action' => ''), null, true); ?>">Cancelar Pagos</a></li>
						<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'proveedor', 'action' => ''), null, true); ?>">Cancelar Remisiones</a></li>
					</ul>
				</li>
			</ul>
		</li>
		<li class="dropdown-submenu">
			<a class="test" tabindex="-1" href="#">
				Tesoreria
			</a>
			<ul class="dropdown-menu">
				<li><a tabindex="-1" href="<?php echo $this->url(array('module'=>'contabilidad', 'controller'=>'tesoreria','action'=>'nomina'), null, true); ?>">Nomina</a></li>
				
			</ul>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'proyectos', 'action' => 'index'), null, true); ?>">
				Proyectos
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'poliza', 'action' => 'index'), null, true); ?>">
				Poliza
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'guiacontable', 'action' => 'index'), null, true); ?>">
				Guia Contable
			</a>
		</li>
	</ul>
</li>