<!-- Menú de operaciones de consulta -->
<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
		Encuesta
		<span class="caret"></span>
	</a>
	<ul class="dropdown-menu">
		<li>
			<a href="<?php echo $this->url(array('module' => 'encuesta', 'controller' => 'consulta', 'action' => 'index'), null, true); ?>">
				<span class="glyphicon glyphicon-search"></span> Encuestas Realizadas 
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'encuesta', 'controller' => 'plan', 'action' => 'index'), null, true); ?>">
				Planes de Estudio 
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'encuesta', 'controller' => 'nivel', 'action' => 'index'), null, true); ?>">
				Niveles Escolares 
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'encuesta', 'controller' => 'profesor', 'action' => 'index'), null, true); ?>">
				Profesores 
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'encuesta', 'controller' => 'registro', 'action' => 'index'), null, true); ?>">
				Usuarios
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'encuesta', 'controller' => 'categoria', 'action' => 'index'), null, true); ?>">
				Categorias 
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'encuesta', 'controller' => 'index', 'action' => 'index'), null, true); ?>">
				Encuestas Activas 
			</a>
		</li>
	</ul>
</li>