<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-target="#">
		Inventario <span class="caret"></span>
	</a>
	<ul class="dropdown-menu">
		<li class="dropdown-submenu">
			<a tabindex="-1" href="<?php echo $this->url(array('module' => 'inventario', 'controller' => 'inventario', 'action' => 'index'),null,true) ?>">
				Inventario
			</a>
			<ul class="dropdown-menu">
				<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'inventario', 'controller' => 'inventario', 'action' => 'general'), null, true); ?>">General</a></li>
				<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'inventario', 'controller' => 'inventario', 'action' => 'producto'), null, true); ?>">Búsqueda por producto</a></li>
			</ul>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'inventario', 'controller' => 'unidad', 'action' => 'index'), null, true); ?>">
				Unidad
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'inventario', 'controller' => 'producto', 'action' => 'index'), null, true); ?>">
				Productos
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'inventario', 'controller' => 'productoterminado', 'action' => 'index'), null, true); ?>">
				Producto Terminado
			</a>
		</li>
	</ul>
</li>