<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
		Inventario
		<span class="caret"></span>
	</a>
	<ul class="dropdown-menu">
		<li>
			<a href="<?php echo $this->url(array('module' => 'inventario', 'controller' => 'unidad', 'action' => 'index'), null, true); ?>">
				Unidad
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'inventario', 'controller' => 'producto', 'action' => 'index'), null, true); ?>">
				Productos
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'inventario', 'controller' => 'inventario', 'action' => 'index'), null, true); ?>">
				Inventario
			</a>
		</li>
	</ul>
</li>