<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-target="#">
		Sistema <span class="caret"></span>
	</a>
	<ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
		<li class="dropdown-submenu">
			<a class="test" tabindex="-1" href="#">
				Informacion General
			</a>
			<ul class="dropdown-menu">
				<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'rol', 'action' => 'index'), null, true); ?>">Roles & Usuarios</a></li>
				<li class="divider"></li>
				<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'estados', 'action' => 'index'), null, true); ?>">Estados & Municipios</a></li>
			</ul>
		</li>
		<li class="dropdown-submenu">
			<a class="test" tabindex="-1" href="#">
				Inventario
			</a>
			<ul class="dropdown-menu">
				<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'parametro', 'action' => 'index'), null, true); ?>">Parametros & Subparametros</a></li>
			</ul>
		</li>
		<li class="dropdown-submenu">
			<a class="test" tabindex="-1" href="#">
				Contabilidad
			</a>
			<ul class="dropdown-menu">
				<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'empresa', 'action' => 'empresas'), null, true); ?>">Empresas</a></li>
				<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'empresa', 'action' => 'clientes'), null, true); ?>">Clientes</a></li>
				<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'empresa', 'action' => 'proveedores'), null, true); ?>">Proveedores</a></li>
			</ul>
		</li>
	</ul>
</li>