<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-target="#">
		Sistema <span class="caret"></span>
	</a>
	<ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
		<li class="dropdown-submenu">
			<a class="test" tabindex="-1" href="#">
				Informacion General
			</a>
			<ul class="dropdown-menu">
				<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'rol', 'action' => 'index'), null, true); ?>">Roles & Usuarios</a></li>
				<li class="divider"></li>
				<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'estados', 'action' => 'index'), null, true); ?>">Estados & Municipios</a></li>
			</ul>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'parametro', 'action' => 'index'), null, true); ?>">
				Parametros & Subparametros
			</a>
		</li>
		<li class="dropdown-submenu">
			<a class="test" tabindex="-1" href="#">
				Fiscales
			</a>
			<ul class="dropdown-menu">
				<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'empresa', 'action' => 'clientes'), null, true); ?>">Clientes</a></li>
				<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'empresa', 'action' => 'proveedores'), null, true); ?>">Proveedores</a></li>
				<li class="dropdown-submenu">
				<a class="test" tabindex="-1" href="#">
					Empresas
				</a>
					<ul class="dropdown-menu">
						<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'empresa', 'action' => 'empresas'), null, true); ?>">Empresas & Sucursales</a></li>
						<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'empresas', 'action' => 'clientes'), null, true); ?>">Enlaza Cliente</a></li>
						<li><a tabindex="-1" href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'empresas', 'action' => 'proveedores'), null, true); ?>">Enlaza Proveedor</a></li>
					</ul>
				</li>
			</ul>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'vendedores', 'action' => 'index'), null, true); ?>">
				Vendedores
			</a>
			
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'contabilidad', 'controller' => 'guiacontable', 'action' => 'index'), null, true); ?>">
				Guia Contable
			</a>
		</li>
	</ul>
</li>