<?php 
	$emails = $this->emails;
?>
<table class="table table-condensed table-striped">
	<thead>
		<th>Email</th>
		<th>Creación</th>
		<th>Descripción</th>
	</thead>
	<tbody>
		<?php foreach ($emails as $email) : ?>
		<tr>
			<td><?php echo $email->getEmail() ?></td>
			<td><?php echo $email->getFecha() ?></td>
			<td><?php echo $email->getDescripcion() ?></td>
		</tr>
		<?php endforeach ?>
	</tbody>
</table>