<?php 
	$emails = $this->emails;
?>
<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"email","action"=>"alta"),null,true) ?>">
	<span class="glyphicon glyphicon-plus"></span> Agregar Email
</a>
<table class="table table-condensed table-striped">
	<thead>
		<th>Email</th>
		<th>Creación</th>
		<th>Descripción</th>
	</thead>
	<tbody>
		<?php foreach ($emails as $email) : ?>
		<tr>
			<td><?php echo $email->getEmail() ?></td>
			<td><?php echo $email->getFecha() ?></td>
			<td><?php echo $email->getDescripcion() ?></td>
		</tr>
		<?php endforeach ?>
	</tbody>
</table>