<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="description" content="">
        <meta name="author" content="Hector Rodriguez">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <title>Encuesta</title>
        
        <!-- Replace favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
        <link rel="shortcut icon" href="<?php echo $this->baseUrl() ?>/public/ext/modules/encuesta/images/icono.png">
        <link rel="apple-touch-icon" href="<?php echo $this->baseUrl() ?>/public/ext/modules/encuesta/images/engranes.jpg">
        <!-- jQuery -->
        <script src="<?php echo $this->baseUrl() ?>/public/lib/jquery/jquery.min.js"></script>
        <!-- Bootstrap -->
        <link rel="stylesheet" charset="UTF-8" href="<?php echo $this->baseUrl() ?>/public/lib/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" charset="UTF-8" href="<?php echo $this->baseUrl() ?>/public/lib/bootstrap/css/bootstrap-theme.min.css" />
        <script src="<?php echo $this->baseUrl() ?>/public/lib/jquery/jquery.min.js"></script>
        <!-- Font-Awesome -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/public/lib/font-awesome/css/font-awesome.min.css" />
        <!-- Otros -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/public/ext/site/css/buttons.css" />
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>
        <!-- Otros -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/public/ext/modules/encuesta/css/fullcalendar.css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/public/ext/modules/encuesta/css/matrix-style.css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/public/ext/modules/encuesta/css/matrix-media.css" />
        
        
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/mencuesta/css/bootstrap.min.css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/mencuesta/css/bootstrap-responsive.min.css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/mencuesta/css/fullcalendar.css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/mencuesta/css/matrix-style.css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/mencuesta/css/matrix-media.css" />
        <link href="<?php echo $this->baseUrl() ?>/css/mencuesta/font-awesome/css/font-awesome.css" rel="stylesheet" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/mencuesta/css/jquery.gritter.css" />
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/jquery.min.js"></script>
        
        
    </head>
    <body>
    <?php 
        $urlModuleEncuesta = array('module'=>'encuesta', 'controller'=>'index', 'action'=>'index');
        
        function reloadUrl($arrayOpts, $urlBase) {
            $newUrl = $urlBase;
            foreach ($arrayOpts as $key => $value) {
                $newUrl[$key] = $value;
            }
            return $newUrl;
        }
    ?>
    
    <!--Header-part-->
    <div id="header">
    	<h1><a href="dashboard.html">Matrix Admin</a></h1>
    </div>
    <!--close-Header-part-->
    
    
    <!--top-Header-menu-->
    <div id="user-nav" class="navbar navbar-inverse">
      <ul class="nav">
        <li  class="dropdown" id="profile-messages" ><a title="" href="#" data-toggle="dropdown" data-target="#profile-messages" class="dropdown-toggle"><i class="icon icon-user"></i>  <span class="text">Bienvenido <strong>Usuario</strong> </span><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#"><i class="icon-user"></i> Mi Perfil</a></li>
            <li class="divider"></li>
            <li><a href="#"><i class="icon-check"></i> Mis Tareas</a></li>
            <li class="divider"></li>
            <li><a href="login.html"><i class="icon-key"></i> Salir</a></li>
          </ul>
        </li>
        <li class="dropdown" id="menu-messages"><a href="#" data-toggle="dropdown" data-target="#menu-messages" class="dropdown-toggle"><i class="icon icon-envelope"></i>
    			<span class="text">Mensajes</span> <span class="label label-important">5</span> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a class="sAdd" title="" href="#"><i class="icon-plus"></i> Nuevo Mensaje</a></li>
            <li class="divider"></li>
            <li><a class="sInbox" title="" href="#"><i class="icon-envelope"></i> Inbox</a></li>
            <li class="divider"></li>
            <li><a class="sOutbox" title="" href="#"><i class="icon-arrow-up"></i> Outbox</a></li>
            <li class="divider"></li>
            <li><a class="sTrash" title="" href="#"><i class="icon-trash"></i> Trash</a></li>
          </ul>
        </li>
        <li class=""><a title="" href="#"><i class="icon icon-cog"></i> <span class="text">Settings</span></a></li>
        <li class=""><a title="" href="login.html"><i class="icon icon-share-alt"></i> <span class="text">Logout</span></a></li>
      </ul>
    </div>
    <!--close-top-Header-menu-->
    <!--start-top-serch-->
    <div id="search">
      <input type="text" placeholder="Search here..."/>
      <button type="submit" class="tip-bottom" title="Search"><i class="icon-search icon-white"></i></button>
    </div>
    <!--close-top-serch-->
    <!--sidebar-menu-->
    <div id="sidebar"><a href="<?php echo $this->url(reloadUrl(array('module'=>'dashboard','action'=>'index'), $urlModuleEncuesta), null, true) ?>" class="visible-phone"><i class="icon icon-home"></i> Dashboard</a>
      <ul>
        <li><a href="<?php echo $this->url(reloadUrl(array('controller'=>'dashboard','action'=>'index'), $urlModuleEncuesta), null, true) ?>"><i class="icon icon-home"></i> <span>Dashboard</span></a> </li>
        <li class="submenu"> <a href="#"><i class="icon icon-th-list"></i> <span>Encuesta</span> <span class="label label-important">2</span></a>
          <ul>
            <li><a href="<?php echo $this->url($urlModuleEncuesta, null, true) ?>">Consultar Encuestas</a></li>
            <li><a href="<?php echo $this->url(reloadUrl(array('action'=>'alta'), $urlModuleEncuesta), null, true) ?>">Nueva Encuesta</a></li>
          </ul>
        </li>
        <li> <a href="charts.html"><i class="icon icon-signal"></i> <span>Charts &amp; graphs</span></a> </li>
        <li> <a href="widgets.html"><i class="icon icon-inbox"></i> <span>Widgets</span></a> </li>
        <li><a href="tables.html"><i class="icon icon-th"></i> <span>Tables</span></a></li>
        <li><a href="grid.html"><i class="icon icon-fullscreen"></i> <span>Full width</span></a></li>
        <li class="submenu"> <a href="#"><i class="icon icon-th-list"></i> <span>Forms</span> <span class="label label-important">3</span></a>
          <ul>
            <li><a href="form-common.html">Basic Form</a></li>
            <li><a href="form-validation.html">Form with Validation</a></li>
            <li><a href="form-wizard.html">Form with Wizard</a></li>
          </ul>
        </li>
        <li><a href="buttons.html"><i class="icon icon-tint"></i> <span>Buttons &amp; icons</span></a></li>
        <li><a href="interface.html"><i class="icon icon-pencil"></i> <span>Eelements</span></a></li>
        <li class="submenu"> <a href="#"><i class="icon icon-file"></i> <span>Addons</span> <span class="label label-important">5</span></a>
          <ul>
            <li><a href="index2.html">Dashboard2</a></li>
            <li><a href="gallery.html">Gallery</a></li>
            <li><a href="calendar.html">Calendar</a></li>
            <li><a href="invoice.html">Invoice</a></li>
            <li><a href="chat.html">Chat option</a></li>
          </ul>
        </li>
        <li class="submenu"> <a href="#"><i class="icon icon-info-sign"></i> <span>Error</span> <span class="label label-important">4</span></a>
          <ul>
            <li><a href="error403.html">Error 403</a></li>
            <li><a href="error404.html">Error 404</a></li>
            <li><a href="error405.html">Error 405</a></li>
            <li><a href="error500.html">Error 500</a></li>
          </ul>
        </li>
        <li class="content"> <span>Monthly Bandwidth Transfer</span>
          <div class="progress progress-mini progress-danger active progress-striped">
            <div style="width: 77%;" class="bar"></div>
          </div>
          <span class="percent">77%</span>
          <div class="stat">21419.94 / 14000 MB</div>
        </li>
        <li class="content"> <span>Disk Space Usage</span>
          <div class="progress progress-mini active progress-striped">
            <div style="width: 87%;" class="bar"></div>
          </div>
          <span class="percent">87%</span>
          <div class="stat">604.44 / 4000 MB</div>
        </li>
      </ul>
    </div>
    <!--sidebar-menu-->
    
    <!--main-container-part-->
        <div id="content">
        <!--breadcrumbs-->
            <div id="content-header">
              <div id="breadcrumb"> <a href="<?php echo $this->url(reloadUrl(array('controller'=>'dashboard','action'=>'index'), $urlModuleEncuesta), null, true) ?>" title="Go Dashboard" class="tip-bottom"><i class="icon-home"></i> Dashboard</a></div>
            </div>
            <!--End-breadcrumbs-->
            <!--Action boxes-->
            <div class="container-fluid">
            <!--End-Action boxes-->
            <!--Chart-box-->
            <!--End-Chart-box-->
            <?php echo $this->layout()->content; ?>
            <hr/>
            </div>
        </div>
        <!--end-main-container-part-->
        
        <!--Footer-part-->
        
        <div class="row-fluid">
          <div id="footer" class="span12"> 2013 &copy; Matrix Admin. Brought to you by <a href="http://themedesigner.in">Themedesigner.in</a> </div>
        </div>
        
        <!--end-Footer-part-->
        
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/excanvas.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/jquery.ui.custom.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/bootstrap.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/jquery.flot.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/jquery.flot.resize.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/jquery.peity.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/fullcalendar.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/matrix.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/matrix.dashboard.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/jquery.gritter.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/matrix.interface.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/matrix.chat.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/jquery.validate.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/matrix.form_validation.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/jquery.wizard.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/jquery.uniform.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/select2.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/matrix.popover.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/jquery.dataTables.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/mencuesta/js/matrix.tables.js"></script>
    
        <script type="text/javascript">
          // This function is called from the pop-up menus to transfer to
          // a different page. Ignore if the value returned is a null string:
          function goPage (newURL) {
        
              // if url is empty, skip the menu dividers and reset the menu selection to default
              if (newURL != "") {
        
                  // if url is "-", it is this page -- reset the menu:
                  if (newURL == "-" ) {
                      resetMenu();
                  }
                  // else, send page to designated URL
                  else {
                    document.location.href = newURL;
                  }
              }
          }
        
        // resets the menu selection upon entry to this page:
          function resetMenu() {
             document.gomenu.selector.selectedIndex = 2;
          }
        </script>
    </body>
</html>
