<div id="loginbox">
    <form id="loginform" class="form-vertical" action="#">
        <div class="control-group">
            <div class="controls">
                <div class="main_input_box">
                    <span class="add-on bg_lg"><span class="icon-user"></span></span>
                    <input type="text" placeholder="Usuario" autofocus="" />
                </div>
            </div>
        </div>
        
        <div class="control-group">
            <div class="controls">
                <div class="main_input_box">
                    <span class="add-on bg_ly"><span class="icon-lock"></span></span>
                    <input type="password" placeholder="Password" />
                </div>
            </div>
        </div>
    </form>
</div>