<?php
    $auth = Zend_Auth::getInstance();
    $identity = $auth->getIdentity();
?>
<div class="row-fluid nopadding">
    <div class="span3">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-user"></i>
                </span>
                <h5>Logo or Photo</h5>
            </div>
        </div>
    </div>
    <div class="span9">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-user"></i>
                </span>
                <h5>Details</h5>
            </div>
            <div class="widget-content">
                <?php //print_r($identity) ?>
                <strong>Usuario: </strong><i><?php echo $identity["user"]["nickname"]; ?></i><br />
                <strong>Rol: </strong><br />
                
            </div>
        </div>
    </div>
</div>