<div class="container-fluid">
<header>
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar1">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				
				<a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index'), null, true); ?>" class="navbar-brand">
					Applicacion General
				</a>
			</div>
			
			<div class="collapse navbar-collapse" id="navbar1">
				<ul class="nav navbar-nav">
					<!-- Menú de operaciones de sistema -->
					<?php echo $this->partial('menus/submenus/sistema.phtml'); ?>
					<!-- Menú de operaciones de contabilidad -->
					<?php echo $this->partial('menus/submenus/contabilidad.phtml'); ?>
					<!-- Menú de operaciones de inventario -->
					<?php echo $this->partial('menus/submenus/inventario.phtml'); ?>
					<!-- Menú de operaciones de consulta -->
					<?php echo $this->partial('menus/submenus/consulta.phtml'); ?>
					<!-- Menú de operaciones de soporte -->
					<?php echo $this->partial('menus/submenus/soporte.phtml'); ?>
					<!-- Menú de operaciones de encuesta -->
					<?php echo $this->partial('menus/submenus/encuesta.phtml'); ?>
				</ul>
			</div>
		</div>
	</nav>
</header>
</div>