<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Primaria :: Segundo Grado :: Grupo B :: Capa A 
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<th>Materia</th>
					<th>Profesor</th>
					<th>Evaluación</th>
				</thead>
				<tbody>
					<tr>
						<td>Español</td>
						<td>Juárez Salas, Gizeh</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"1","idAsignacion"=>"506"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Arte</td>
						<td>Mijares Fernández, María</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"1","idAsignacion"=>"508"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Danza</td>
						<td>Gonzalez Cid, Carlos Augusto</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"1","idAsignacion"=>"509"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Computación</td>
						<td>Valery Lobo, Sonia Josefina</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"1","idAsignacion"=>"510"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Deportes</td>
						<td>Rodríguez Dávila, Patricia</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"1","idAsignacion"=>"511"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</section>