<?php 
	$grado = $this->grado;	
	$formulario = $this->formulario;
	$messageFail = $this->messageFail;
	$messageSuccess = $this->messageSuccess;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Alta de Grupos en Grado: <strong><?php echo $grado->getGrado() ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grado","action"=>"admin","idGrado"=>$grado->getIdGrado()), null, true); ?>">
				<span class="glyphicon glyphicon-chevron-left"></span> Regresar Grado: <strong><?php echo $grado->getGrado() ?></strong>
			</a><br /><br />
			<?php if(!is_null($messageSuccess)){ ?>
			<div class="alert alert-success" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				  <span aria-hidden="true">&times;</span>
				</button>
				<?php echo $messageSuccess; ?>
			</div>
			<?php }elseif(!is_null($messageFail)){ ?>
			<div class="alert alert-danger" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				  <span aria-hidden="true">&times;</span>
				</button>
				<?php echo $messageFail; ?>
			</div>
			<?php } ?>
			<div>
				<?php echo $this->formulario; ?>
			</div>
			<br /><br />
		</div>
	</div>
</section>