<?php
	$formulario = $this->formulario;
	$grupo = $this->grupo;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Asociando Materia con Profesor
			</h3>
		</div>
		<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grupos","action"=>"index","idGrupo"=>$grupo->getIdGrupo()),null,true) ?>">
			<span class="glyphicon glyphicon-chevron-left"></span> Regresar al Grupo
		</a>
		<?php echo $formulario; ?>
	</div>
</section>