<?php 
	$ciclo = $this->ciclo;
	$nivel = $this->nivel;
	$grado = $this->grado;
	$grupos = $this->grupos;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Busqueda de Grupos en Nivel: <strong><?php echo $nivel->getNivel() ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grado","action"=>"admin","idGrado"=>$grado->getIdGrado()), null, true); ?>">
				<span class="glyphicon glyphicon-chevron-left"></span> Regresar al Grado: <strong><?php echo $grado->getGrado() ?></strong>.
			</a><br /><br />
			<?php echo $this->formulario; ?>
			
			<table class="table table-striped table-condensed">
				<thead>
					<th>Ciclo</th>
					<th>Nivel</th>
					<th>Grado</th>
					<th>Consulta</th>
				</thead>
				<tbody>
					<?php foreach ($grupos as $grupo) : ?>
					<tr>
						<td><?php echo $ciclo->getCiclo() ?></td>
						<td><?php echo $nivel->getNivel() ?></td>
						<td><?php echo $grado->getGrado() ?></td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grupos","action"=>"index","idGrupo"=>$grupo->getIdGrupo()),null,true) ?>">
								<span class="glyphicon glyphicon-search"></span> Grupo: <strong><?php echo $grupo->getGrupo() ?></strong>
							</a>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
			<br />
		</div>
	</div>
	
</section>
<script>
	$().ready(function(){
		$("select#nivel").on('change', function(){
			console.log(this.value);
			//Borro el contenido del select municipio
			//Obtengo los municipios del estado
			$url = "/General/public/encuesta/json/grados/idNivel/" + this.value;
			console.log($url);
			$.ajax({
				url: $url,
				dataType: "json",
				success: function(data){
					console.log($url);
					console.dir(data);
					$("select#1-grado").empty();
					$.each(data, function(i,item){//function(key,value)		
						$("select#1-grado").append($("<option></option>").attr("value",data[i].idGrado).text(data[i].grado));
						//$("select#1-idMunicipio").append($("<option></option>").attr("value",key).text(value)); 
					});
					
				}
			});
		});
		
	});
</script>