<?php
	$grupo = $this->grupo;
	$materia = $this->materia;
	$docente = $this->docente;
	$encuestas = $this->encuestas;
	$encuestaDAO = new Encuesta_DAO_Encuesta;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Encuestas del Docente: <strong><?php echo $docente->getApellidos().", ".$docente->getNombres() ?></strong> de la materia:<strong><?php echo $materia->getMateria() ?></strong> en el grupo: <strong><?php echo $grupo->getGrupo() ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grupos","action"=>"index","idGrupo"=>$grupo->getIdGrupo()), null, true); ?>">
				<span class="glyphicon glyphicon-chevron-left"></span> Regresar al Grupo: <strong><?php echo $grupo->getGrupo() ?></strong>
			</a>
			<br />
			<table class="table table-striped table-condensed">
				<thead>
					<th>Encuesta</th>
					<th>Evaluar</th>
					<th>Resultados</th>
				</thead>
				<tbody>
					<?php foreach ($encuestas as $encuesta) : ?>
					<tr>
						<td><?php echo $encuesta->getNombre() ?></td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>$encuesta->getIdEncuesta(),"idGrupo"=>$grupo->getIdGrupo(),"idDocente"=>$docente->getIdRegistro(),"idMateria"=>$materia->getIdMateria()),null,true) ?>">
								Evaluar
							</a>
						</td>
						<td>
							<?php $registro = array("idEncuesta"=>$encuesta->getIdEncuesta(),"idGrupo"=>$grupo->getIdGrupo(),"idRegistro"=>$docente->getIdRegistro()); ?>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"resultado","idEncuesta"=>$encuesta->getIdEncuesta(),),null,true) ?>">
								<span class="glyphicon glyphicon-search"></span> <?php echo $encuestaDAO->obtenerEncuestasRealizadas($registro) ?> Encuestas contestadas
							</a>
							
						</td>
					</tr>
					<?php endforeach ?>
				</tbody>
		</table>
		</div>
	</div>
</section>