<?php
	$nivel = $this->nivel;
	$grado = $this->grado;
	$grupo = $this->grupo;
	$materias = $this->materias;
	$profesores = $this->profesores;
	
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Nivel: <strong><?php echo $nivel->getNivel() ?></strong> >> Grado: <strong><?php echo $grado->getGrado() ?></strong> >> Grupo: <strong><?php echo $grupo->getGrupo() ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grado","action"=>"admin","idGrado"=>$grupo->getIdGrado()), null, true); ?>">
				<span class="glyphicon glyphicon-chevron-left"></span> Regresar al Grado: <strong><?php echo $grado->getGrado() ?></strong>
			</a>
			<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"altae","idGrupo"=>$grupo->getIdGrupo()), null, true); ?>">
				<span class="glyphicon glyphicon-plus"></span> Registrar Encuesta Evaluativa
			</a>
			<br />
			<table class="table table-striped table-condensed">
				<thead>
					<th>Materia</th>
					<th>Profesor</th>
					<th>Evaluación</th>
					<th>Resultado</th>
				</thead>
				<tbody>
					<?php foreach ($materias as $materia) : ?>
					<tr>
						<td><?php echo $materia->getMateria(); ?></td>
						<td>
							<?php
								if(!empty($profesores)){
									if(key_exists($materia->getIdMateria(), $profesores)){
										$profesor = $profesores[$materia->getIdMateria()];
										$docente = $profesor["profesor"]; 
										echo $docente->getApellidos() . ", " . $docente->getNombres();
									}else{?>
											<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grupos","action"=>"asociarp","idGrupo"=>$grupo->getIdGrupo(),"idMateria"=>$materia->getIdMateria()),null,true) ?>">
												<span class="glyphicon glyphicon-plus"></span> Asignar profesor
											</a>
							<?php	}
								}
							?>
						</td>
						<td></td>
						<td></td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</div>
</section>