<?php 
	$grupo = $this->grupo;
	$nivel = $this->nivel;
	$grado = $this->grado;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Opciones del Grupo: <strong><?php echo $grupo->getGrupo() ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grado","action"=>"index","idNivel"=>$nivel->getIdNivel()), null, true); ?>">
				<span class="glyphicon glyphicon-chevron-left"></span> Regresar al Grupo: <strong><?php echo $grupo->getGrupo() ?></strong>.
			</a><br /><br />
			<table class="table table-striped table-condensed">
				<thead>
					<th>Materia</th>
					<th>Clave Materia</th>
					<th>Profesor</th>
				</thead>
				<tbody>
					<?php foreach ($profesores as $profesor) : ?>
					<tr>
						<td><?php echo $ciclo->getCiclo() ?></td>
						<td><?php echo $nivel->getNivel() ?></td>
						<td><?php echo $grado->getGrado() ?></td>
						<td><?php echo $grupo->getGrupo() ?></td>
						<td>
							<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grupos","action"=>"opciones","idGrupo"=>$grupo->getIdGrupo()),null,true) ?>">
								Opciones del Grupo
							</a>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
			<br /><br />
		</div>
	</div>
</section>