<?php 
	$grupo = $this->grupo;
	$nivel = $this->nivel;
	$grado = $this->grado;
	$ciclo = $this->ciclo;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Ciclo: <strong><?php echo $ciclo->getCiclo() ?></strong> || Nivel: <strong><?php echo $nivel->getNivel() ?></strong> || Grado: <strong><?php echo $grado->getGrado() ?></strong> || Grupo: <strong><?php echo $grupo->getGrupo() ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grado","action"=>"index","idNivel"=>$nivel->getIdNivel()), null, true); ?>">
				<span class="glyphicon glyphicon-chevron-left"></span> Regresar al Grupo: <strong><?php echo $grupo->getGrupo() ?></strong>.
			</a><br /><br />
			<table class="table table-striped table-condensed">
				<thead>
					<th>Materia</th>
					<th>Docente</th>
					<th>Evaluación</th>
					<th>Resultado</th>
				</thead>
				<tbody>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				</tbody>
			</table>
			<br /><br />
		</div>
	</div>
</section>