<?php
	$formulario = $this->formulario;
?>
<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Alta impuesto.
		</h3>
	</div>
	<div class="panel-body">
		<div class="container">
			<div class="col-md-6">
				<?php echo $formulario; ?>
			</div>
		</div>
	</div>
</section>
<script>
$(function(){
	$('#impuestos').validate({
		rules:{
			abreviatura:{
				required: true,
			},
			descripcion:{
				required: true,
			},
			estatus:{
				required: true,
				rangelength: [0, 1],
				lettersonly:true,
			}
		},
		messages: {
			abreviatura:{
				required: "Debe ingresar abrevitura"
			},
			descripcion:{
				required: "Debe ingresar descripción ",
			},
			estatus:{
				required: "Debe ingresar el estatus",
                rangelength: "El estatus debe tener máximo 1 caracter",                 
                lettersonly: "Ingrese A: Activo o C: Cancelado "
			}
		}	
	});
});
$(document).ready(function() {
	$('#abreviatura').keyup(function(e){
		$(this).val($(this).val().toUpperCase());
	});
});
</script>