<?php
	$formulario = $this->formulario;
	//echo $formulario;
	$messageSuccess = $this->messageSuccess;
	$messageFail =$this->messageFail;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">Nuevo Impuesto</h3>
		</div>
		<div class="panel-body">
			<div class="col-xs-6">
				<?php if(!is_null($messageSuccess)){?>
					<div class="alert alert-info" role="alert">
						<button type="button" class="close">
							<span aria-hidden="true">&times;</span>
						</button>
						<?php echo $messageSuccess; ?>
					</div>
				<?php }elseif(!is_null($messageFail)){ ?>
					<div class="alert alert-danger" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="close">
							<span aria-hidden="true">&times;</span>
						</button>
						<?php echo $messageFail; ?>
					</div>	
					<?php } ?>
					<?php echo $formulario; ?>
			</div>
		</div>
	</div>
</section>