<?php
$productoImpuestos = $this->productoImpuesto;
?>
<section class="row">
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">Asociar Producto a Impuesto</h3>
		</div>
		<div class="panel-body">
			<div class="col-xs-12">
				<table class="table table-condensed">
					<tbody>
						<tr>
							<td>Seleccione Producto</td>
							<td>
								<select id="idProducto" class="form-control">
									<?php foreach ($productoImpuestos as $producto) : ?>
										<option value="<?php echo $producto["idProducto"]; ?>"><?php echo $producto["producto"]; ?></option>
									<?php endforeach; ?>
								</select>
							</td>
						</tr>
						<tr>
							<td>
								<button id="idImpuesto" class="btn btn-warning" type="button" data-toggle="modal" data-target="#msgConfirm">
									<span class="glyphicon glyphicon-random"></span> Asociar Impuesto
								</button>
							</td>
							<td>
								<select id="selectIdClientes" class="form-control">
								</select>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<br /><hr /><br />
			<div class="col-xs-12">
				<table id="clientesEmpresa" class="table table-striped table-condensed">
					<thead>
						<th>Producto</th>
						<th>Impuesto</th>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</section>
<script>
	$().ready(function(){
		var idProductos = $("select#idProducto").val();
		var url = window.location.origin + "/General/public/contabilidad/json/productos/idProducto/"+idProducto;
		
	});
</script>