<?php
	$impuestos = $this->impuestos;
	$impuestosDAO =  new Contabilidad_DAO_Impuesto;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">Impuestos</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"contabilidad","controlle"=>"impuestos","action"=>"alta"))?>">
				<span class="glyphicon glyphicon-plus"></span>Nuevo Impuesto	
			</a>
		<table class="table table-striped table-condensed">
		<thead>
			<tr>
				<th>Configurar	</th>
				<th>Abreviatura</th>
				<th>Descripción</th>
				<th>Estatus</th>
				<th>Fecha Alta</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($impuestos as $impuesto): 
				$impuesto = $impuestosDAO->obtenerImpuestos();
			?>
			<tr>
				<td>
					<a class="btn btn-warning" href="<?php echo $this->url(array ("module"=>"contabilidad","controller"=>"impuestos","action"=>"editar","idImpuesto"=>$impuesto->getIdImpuesto()), null, true);?>">
						<span class="glyphicon glyphicon-cog"></span> Editar
					</a>	
				</td>
				<td><?php echo $impuesto->getAbreviatura() ?></td>
				<td><?php echo $impuesto->getDescripcion() ?></td>
				<td><?php echo $impuesto.abreviatura ?></td>
				<td><?php echo $impuesto.abreviatura ?></td>
				<td>
					<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"contabilidad","controller"=>"impuestos","action"=>"enlazar")) ?>">
						<span class="glyphicon glyphicon-equalizer"></span>Enlazar Impuesto
					</a>
				</td>
			</tr>
			<?php endforeach; ?>
			
		</tbody>
		</table>
	</div>
</section>