<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
		Usuario <span class="caret"></span>
	</a>
	<ul class="dropdown-menu">
		<li>
			<a id="login" href="<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'login'),null,true) ?>">
				<span class="glyphicon glyphicon-user"></span>  
				Login
			</a>
		</li>
		<li>
			<a id="profile" href="<?php echo $this->url(array('module'=>'default','controller'=>'usuario','action'=>'perfil'),null,true) ?>">
				<span class="glyphicon glyphicon-home"></span>  Perfil
			</a>
		</li>
		<li>
			<a id="logout" href="<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'logout'),null,true) ?>">
				<span class="glyphicon glyphicon-off"></span> Logout
			</a>
		</li>
	</ul>
</li>