<?php
	$categoria = $this->categoria;
	$opcion = $this->opcion;
	$formulario = $this->formulario;	
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Categoria: <strong><?php echo $categoria->getCategoria() ?></strong> || Opcion: <strong><?php echo $opcion->getOpcion() ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<h3>Agregando Valor a la Opcion: <strong><?php echo $opcion->getOpcion(); ?></strong></h3>
			<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"categoria","action"=>"opciones","idCategoria"=>$categoria->getIdCategoria()),null,true) ?>">
				<span class="glyphicon glyphicon-chevron-left"></span> Regresar a Opciones
			</a>
			<br /><br />
			<?php echo $formulario ?>
		</div>
	</div>
</section>