<?php
	$categoria = $this->categoria;
	$opciones = $this->opciones;
	$formulario = $this->formulario; 
	$formulario->setAction($this->url(array("module"=>"encuesta", "controller"=>"categoria", "action" => "edita", "idCategoria"=>$categoria["idCategoriasRespuesta"]), null, true));
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Detalle Categoría
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"categoria","action"=>"index"),null,true) ?>">
				<span class="glyphicon glyphicon-chevron-left"></span> Regresar a Categorias
			</a><br />
			<table class="table table-striped table-condensed">
				<thead>
					<th>Categoría</th>
					<th>Creación</th>
					<th>Descripción</th>
					<th>Opciones</th>
				</thead>
				<tbody>
					<tr>
						<td><?php echo $categoria["categoria"]; ?></td>
						<td><?php echo $categoria["fecha"]; ?></td>
						<td><?php echo $categoria["descripcion"]; ?></td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"categoria","action"=>"opciones","idCategoria"=>$categoria["idCategoriasRespuesta"])) ?>">
								<span class="glyphicon glyphicon-cog"></span> Opciones
							</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Categoría
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $this->formulario; ?>
		</div>
	</div>
</section>
