<?php
	$categoria = $this->categoria;
	$opciones = $this->opciones;
	$formulario = $this->formulario; 
	$formulario->setAction($this->url(array("module"=>"encuesta", "controller"=>"categoria", "action" => "edita", "idCategoria"=>$categoria->getIdCategoria()), null, true));
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Detalle Categoría
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<th>Categoría</th>
					<th>Creación</th>
					<th>Descripción</th>
					<th>Opciones</th>
				</thead>
				<tbody>
					<tr>
						<td><?php echo $categoria->getCategoria(); ?></td>
						<td><?php echo $categoria->getFecha(); ?></td>
						<td><?php echo $categoria->getDescripcion(); ?></td>
						<td>
							<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"categoria","action"=>"opciones","idCategoria"=>$categoria->getIdCategoria())) ?>">
								Opciones
							</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Categoría
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $this->formulario; ?>
		</div>
	</div>
	
	<div class="panel panel-danger">
		<div class="panel-heading">
			<h3 class="panel-title">
				Eliminar Categoría
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-danger" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"categoria","action"=>"baja","idCategoria"=>$categoria->getIdCategoria()), null, TRUE); ?>">
				Eliminar Categoría
			</a>
		</div>
	</div>
</section>
