<?php
	$categoria = $this->categoria;
	$opciones = $this->opciones;
	$formulario = $this->formulario; 
	$formulario->setAction($this->url(array("module"=>"encuesta", "controller"=>"categoria", "action" => "edita", "idCategoria"=>$categoria["idCategoriasRespuesta"]), null, true));
?>
<div class="row-fluid">
    <div class="span12 widget-box">
        <div class="widget-title">
            <h5>Detalle Categoría</h5>
        </div>
        <div class="widget-content">
            <div>
                <a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"categoria","action"=>"index"),null,true) ?>">
                    <span class="icon icon-arrow-left"></span> Regresar a Categorias
                </a>
            </div>
            <hr />
            <table class="table table-bordered table-striped table-condensed">
                <thead>
                    <th>Categoría</th>
                    <th>Creación</th>
                    <th>Descripción</th>
                    <th>Opciones</th>
                </thead>
                <tbody>
                    <tr>
                        <td><?php echo $categoria["categoria"]; ?></td>
                        <td><?php echo $categoria["fecha"]; ?></td>
                        <td><?php echo $categoria["descripcion"]; ?></td>
                        <td>
                            <a class="btn btn-info btn-block" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"categoria","action"=>"opciones","idCategoria"=>$categoria["idCategoriasRespuesta"])) ?>">
                                <span class="icon icon-cog"></span> Opciones
                            </a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12 widget-box">
        <div class="widget-title">
            <h5>Editar Categoría</h5>
        </div>
        <div class="widget-content">
            <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
                <div class="control-group">
                    <label class="control-label">Categoría: </label>
                    <div class="controls">
                        <input class="span10" name="nombre" type="text" value="<?php echo $categoria["categoria"]; ?>" />
                    </div>
                </div>
                
                <div class="control-group">
                    <label class="control-label">Descripción: </label>
                    <div class="controls">
                        <input class="span10" name="descripcion" type="text" value="<?php echo $categoria["descripcion"]; ?>" />
                    </div>
                </div>
                
                <div class="form-actions">
                    <div class="pull-right">
                        <button type="submit" class="btn btn-warning">
                            <span class="icon icon-refresh"></span> Actualizar Categoría
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
