<?php 
	//$categoria = $this->categoria;
	$formulario = $this->formulario;
	$messageSuccess = $this->messageSuccess;
	$messageFail = $this->messageFail;
?>
<div class="row-fluid">
    <div class="span12 widget-box">
        <div class="widget-title">
            <h5>Alta de Categoria</h5>
        </div>
        <div class="widget-content">
            <div>
                <a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta", "controller"=>"categoria", "action"=>"index")) ?>">
                    <span class="glyphicon glyphicon-chevron-left"></span> Regresar a Categorias
                </a><br />
                <?php if(!is_null($messageSuccess)){ ?>
                <br />
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                    <?php echo $messageSuccess; ?>
                </div>
                <?php }elseif(!is_null($messageFail)){ ?>
                <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                    <?php echo $messageFail; ?>
                </div>
                <?php } ?>
            </div>
            <div>
                <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
                    <div class="control-group">
                        <label class="control-label" for="categoria">Categoria: </label>
                        <div class="controls">
                            <input class="span10" name="categoria" type="text" placeholder="Nombre Categoría ..." autofocus="" />
                        </div>
                    </div>
                    
                    <div class="control-group">
                        <label class="control-label" for="descripcion">Descripcion: </label>
                        <div class="controls">
                            <input class="span10" type="text" name="descripcion" placeholder="Descripción ..." />
                        </div>
                    </div>
                    
                    <div class="form-actions">
                        <div class="pull-right">
                            <button class="btn btn-success">
                                <span class="icon icon-save"></span> Guardar Categoría
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
