<?php 
	$categorias = $this->categorias;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Categorias en el Módulo de Encuestas:
			</h3>
		</div>
		<div class="panel-body">
			<p>
				Al crear preguntas que sean de opcion, ya sean simple o múltiple, se necesita al menos contar con una categoría 
				que contenga opciones seleccionables para la pregunta.
			</p>
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"categoria","action"=>"alta"), null, true) ?>">
				<span class="glyphicon glyphicon-plus"></span> Categoria
			</a>
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Nombre</th>
						<th>Creación</th>
						<th>Descripción</th>
						<th>Configuración</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($categorias as $categoria) : ?>
					<tr>
						<td><?php echo $categoria["categoria"]; ?></td>
						<td><?php echo $categoria["fecha"]; ?></td>
						<td><?php echo $categoria["descripcion"]; ?></td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"categoria","action"=>"admin","idCategoria"=>$categoria["idCategoriasRespuesta"] ), null, true) ?>">
								<span class="glyphicon glyphicon-cog"></span> Configuracion
							</a>
						</td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</div>
</section>