<?php 
	$categorias = $this->categorias;
?>
<div class="row-fluid">
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-list-ol"></i>
                </span>
                <h5>Categorias disponibles</h5>
            </div>
            <div class="widget-content">
                <div>
                    <a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"categoria","action"=>"alta"), null, true) ?>">
                        <span class="icon icon-plus"></span> Nueva Categoría
                    </a>
                </div>
                <hr />
                <table class="table table-bordered table-condensed">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Creación</th>
                            <th>Descripción</th>
                            <th>Configuración</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($categorias as $categoria) : ?>
                        <tr>
                            <td><?php echo $categoria["categoria"] ?></td>
                            <td><?php echo $categoria["fecha"] ?></td>
                            <td><?php echo $categoria["descripcion"] ?></td>
                            <td>
                                <a class="btn btn-warning btn-block" 
                                    href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"categoria","action"=>"admin","idCategoria"=>$categoria["idCategoriasRespuesta"] ), null, true) ?>">
                                    <span class="icon icon-cogs"></span> Configuracion
                                </a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
