<?php 
	$categorias = $this->categorias;
?>
<section class="row">
	<article>
		<header>
			<h3>Categorias en el Módulo de Encuestas:</h3>
		</header>
		<div>
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"categoria","action"=>"alta"), null, true) ?>">
				<span class="glyphicon glyphicon-plus"></span> Categoria
			</a>
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Nombre</th>
						<th>Creacion</th>
						<th>Descripcion</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($categorias as $categoria) : ?>
					<tr>
						<td><?php echo $categoria->getCategoria() ?></td>
						<td><?php echo $categoria->getFecha() ?></td>
						<td><?php echo $categoria->getDescripcion() ?></td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</article>
</section>