<?php 
	$opciones = $this->opciones;
	$categoria = $this->categoria;
?>
<section class="row">
	<article class="col-md-12">
		<header>
			<h3>Opciones de la Categoría: <?php echo $categoria->getCategoria(); ?></h3>
		</header>
		<div>
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"opcion","action"=>"alta","idCategoria"=>$categoria->getIdCategoria()), null, true) ?>">
				<span class="glyphicon glyphicon-plus"></span> Agregar Opción
			</a>
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Nombre</th>
						<th>Creación</th>
						<th>Orden</th>
						<th>Configuración</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($opciones as $opcion) : ?>
					<tr>
						<td><?php echo $opcion->getOpcion(); ?></td>
						<td><?php echo $opcion->getFecha(); ?></td>
						<td><?php echo $opcion->getOrden(); ?></td>
						<td>
							<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"opcion","action"=>"admin","idOpcion"=>$opcion->getIdOpcion() ), null, true) ?>">
								<span class="glyphicon glyphicon-cog"></span> Configuración
							</a>
						</td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</article>
</section>