<?php 
	$opciones = $this->opciones;
	$categoria = $this->categoria;
	
	$opcionDAO = new Encuesta_DAO_Opcion;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Opciones de la Categoría: <strong><?php echo $categoria->getCategoria(); ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"categoria","action"=>"admin","idCategoria"=>$categoria->getIdCategoria(),),null,true) ?>">
				<span class="glyphicon glyphicon-chevron-left"></span> Regresar a Categoria: <strong><?php echo $categoria->getCategoria() ?></strong>
			</a>
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"opcion","action"=>"alta","idCategoria"=>$categoria->getIdCategoria()), null, true) ?>">
				<span class="glyphicon glyphicon-plus"></span> Agregar Opción
			</a>
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Orden</th>
						<th>Nombre</th>
						<th>Valor</th>
						<th>Creación</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($opciones as $opcion) : ?>
					<tr>
						<td><?php echo $opcion->getOrden(); ?></td>
						<td><?php echo $opcion->getOpcion(); ?></td>
						<td><?php echo $opcion->getVreal(); ?></td>
						<td><?php echo $opcion->getFecha(); ?></td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</div>
</section>