<?php $formulario = $this->formulario ?>

<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">Registrar Nómina.</h3>
		</div>
		<div class="panel-body">
			<?php echo $formulario; ?>
		</div>
	</div>
</section>

<script>
$(document).ready(function(){
	$("#pagada:checked").val()=="true";
	$("select#idEmpresas").on('change', function(){
		console.log("Bancos por empresa");
		$url = "/General/contabilidad/json/bancosempresa/emp/" + this.value;
		console.log($url);
		$.ajax({
			url: $url,
			//console.log($ajax);
			dataType: "json",
			success: function(data){
				$("select#idBanco").empty();
				$.each(data, function(i,item){	
					$("select#idBanco").append($("<option></option>").attr("value",data[i].idBanco).text(data[i].banco));
				});
			}
		});	
	});
	
	$("select#idEmpresas").on('change', function(){
			var url = window.location.origin + "/General/sistema/json/sucursales/idFiscales/" + this.value;
			console.log(url);
			$.ajax({
				url: url,
				dataType: "json",
				success: function(data){
					console.dir(data);
					$("select#idSucursal").empty();
					$.each(data, function(i,item){	
						$("select#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal)); 
					});
					
				}
			});
	});
		
	$("select#idSucursal").on('click', function(){
			var url = window.location.origin + "/General/sistema/json/proyectos/idSucursal/" + this.value;
			console.log(url);
			$.ajax({
				url:url,
				dataType: "json",
				success: function(data){
				console.dir(data);
				$("select#idProyecto").empty();
						$.each(data, function(i,item){
							$("select#idProyecto").append($("<option></option>").attr("value",data[i].idProyecto).text(data[i].descripcion));
						});
					}
				});
	});
	
	$("#pagada").on("change", function(){
		if($("#pagada:checked").val()=="1"){
			//$("#formaLiquidar").removeAttr("disabled");
			$("#idBanco").removeAttr("disabled");
			$("#numeroReferencia").removeAttr("disabled");
			
		}else{
			$("#pagada:checked").val()=="0"
			//$("#formaLiquidar").attr("disabled", true);
			$("#idBanco").attr("disabled", true);
			$("#numeroReferencia").attr("disabled", true);
		}
	});
	$("#numFolio").on('keypress' , function(){
		if((event.keyCode < 48 ) || (event.keyCode > 57))
		event.returnValue = false;
	});
	
	$("#1-sueldo").on("change", function (){
		calculaNomina();
	});
	$("#1-subsidio").on("change", function (event){
		calculaNomina();
	});
	$("#1-IMSS").on("click", function (event){
		calculaNomina();
	});
	$("#1-ISPT").on("change", function (event){
		calculaNomina();
	});
	
	function calculaNomina(){
		var total;  
		total = parseFloat($("input#1-sueldo").val()) + parseFloat($("input#1-subsidio").val())-$("input#1-IMSS").val()-$("input#1-ISPT").val();
		console.log("El total:"+ total);
		$("#1-nominaxpagar").val(total.toFixed(2));
	}
});
</script>