<?php
	echo $this->formulario;	
	$messageFail = $this->messageFail;
	$messageSuccess = $this->messageSuccess;	
?>
<section class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Agregar Productos para Nota Salida.</h3>
		</div>
		<div class="panel-body">
			<?php if (!is_null($messageSuccess)){?>
			<div class="alert-success" role="alert">
				<button type="button" class="close" data-dismiss="alert" arial-label="Close">
					<span arial-hidden="true">&times;</span>
				</button>
				<?php echo $messageSuccess; ?>
			</div>
			<?php }elseif(!is_null($messageFail)){ ?>
			<div class="alert alert-danger" role="alert">
				<button type="button" class="close" data-dismiss="alert" arial-label="close">
					<span aria-hidden="true">&times;</span>
				</button>
				<?php echo $messageFail; ?>
			</div>
			<?php }?><br />
			<button id="addRow" class="btn btn-success" >
				<span class="glyphicon glyphicon-plus" ></span> Nuevo
			</button>
			<a id="generarJsonArray" class="btn btn-warning">
				<span class="glyphicon glyphicon-cog" ></span> Cargar
			</a>
			<table id="productos" class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Cantidad</th>
						<th>Clave Producto</th>
						<th>Seleccione Unidad</th>
						<th>Codigo de Barras</th>
						<th>Descripcion</th>
						<th>Precio Unitario</th>
						<th>Importe</th>
						<th>Eliminar</th>
					</tr>
				</thead>
				<tbody>
				</tbody>
				<tfoot>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td><strong>Subtotal:</strong></td>
						<td><input id="subTotal" class="form-control" /></td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td><strong>Descuento:</strong></td>
						<td><input id="descuento" class="form-control" value="0" /></td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td><strong>Subtotal descuento:</strong></td>
						<td><input id="descuentoGenerado" class="form-control" value="0" /></td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td><strong>Iva:</strong></td>
						<td><input id="iva" class="form-control"></td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td><strong>Total:</strong></td>
						<td><input id="total" class="form-control" /></td>
					</tr>
				</tfoot>
			</table>
		</div>
	</div>
</section>
<script>

$(document).ready(function () {
	var jsonProductos = <?php echo $this->jsonProductos; ?>;
	
		$("button#addRow").on("click",function(){
			var filasTabla = $("table#productos tbody > tr").length;
			//console.log(filasTabla);
			filasTabla ++;
			// generamos elementos de nueva fila
			// cantidad
			var inputCantidad = $('<input />').attr({'id': 'idCantidad_' + filasTabla}).attr({'class':'form-control'}).attr({'size': '1' + filasTabla});
			// idProductocto
			/*var selectProducto = $('<select />').attr({'id': 'idProducto_' + filasTabla}).attr({'class':'form-control'});
			$.each(jsonProductos,function(i,item){
				selectProducto.append('<option value="'+jsonProductos[i].idProducto+'">'+jsonProductos[i].claveProducto+'</option>');
			});*/
			var inputProducto = $('<input />').attr({'id': 'idProducto_' + filasTabla}).attr({'class':'form-control'});
			// idUnidad
			var inputUnidad = $('<select required />').attr({'id': 'idUnidad_' + filasTabla}).attr({'class':'form-control'}).attr({'required':'true'});;
			/*$.each(jsonUnidad,function(i,item){
				inputUnidad.append('<option value="'+jsonUnidad[i].idUnidad+'">'+jsonUnidad[i].unidad+'</option>');
			});*/
			// codigoBarras
			var inputCodigoBarras = $('<input />').attr({'id': 'codigoBarras_' + filasTabla}).attr({'class':'form-control'});
			// descripcion
			//var inputDescripcion = $('<input />').attr({'id': 'descripcion_' + filasTabla}).attr({'class':'form-control'});
			//var inputDescripcion = $('<input />').attr({'id': 'descripcion_' + filasTabla}).attr({'class':'form-control'});
			var selectDescripcion = $('<select />').attr({'id': 'descripcion_' + filasTabla}).attr({'class':'form-control'});
			$.each(jsonProductos,function(i,item){
				selectDescripcion.append('<option value="'+jsonProductos[i].idProducto+'">'+jsonProductos[i].producto+'</option>');
			});
			// precioUnitario
			var inputCostoUnitario = $('<input />').attr({'id': 'costoUnitario_' + filasTabla}).attr({'class':'form-control'});
			// precioImporte
			var inputCostoTotal = $('<input />').attr({'id': 'costoTotal_' + filasTabla}).attr({'class':'form-control'}).attr({'name':'costoTotal_'}).attr({'disabled':'true'});
			// botonLimpiar
			var buttonLimpiar = $('<button />').attr({'id': 'btnLimpiar_' + filasTabla}).attr({'class':'btn btn-danger'});
			buttonLimpiar.html('<span class="glyphicon glyphicon-remove-circle"></span> Eliminar Producto')

			var tbody = $("table#productos").find('tbody');
			tbody.append($('<tr>').
				append($('<td>').append(inputCantidad)).
				append($('<td>').append(inputProducto)).
				append($('<td>').append(inputUnidad)).
				append($('<td>').append(inputCodigoBarras)).
				append($('<td>').append(selectDescripcion)).
				append($('<td>').append(inputCostoUnitario)).
				append($('<td>').append(inputCostoTotal)).
				append($('<td>').append(buttonLimpiar))
				
			);
  });
    //Envia los valores del Producto a la vista de facturaProveedor
    $("a#generarJsonArray").on("click",function(){
    	var tabla = $("table#productos > tbody  > tr");
 		//Array Json de productos
 		var productos = [];
 		tabla.each(function(){
 			var row = $(this);
 			var cantidad = row.find("input[id^='idCantidad_']").val();
 			var claveProducto = row.find("input[id^='idProducto_']").val();
 			var unidad = row.find("select[id^='idUnidad_']").val();
 			var codigoBarras = row.find("input[id^='codigoBarras_']").val();
 			var descripcion = row.find("select[id^='descripcion_']").val();
 			var precioUnitario = row.find("input[id^='costoUnitario_']").val();
 			var importe = row.find("input[id^='costoTotal_']").val();
 			
 			console.log("Cantidad:"+cantidad);
 			console.log("Producto:"+claveProducto);
 			console.log("unidad:"+unidad);
 			console.log("codigoBarras:"+codigoBarras);
 			console.log("descripcion:"+descripcion);
 			console.log("precioUnitario:"+precioUnitario);
 			console.log("costoTotal:"+importe);
 				
 						
 			productos.push(new Producto(cantidad, claveProducto, unidad, codigoBarras, descripcion, precioUnitario, importe)); 
 		});
 			console.dir(productos);
 			var myString = JSON.stringify(productos);
 			
 			console.log(myString);
 			if ($("input#productos").val(myString)){
 				
 			};
 	});
 		
 	//Funcion Eliminar #btnLimpiar_2
  	$("table#productos").on("click", "button[id^='btnLimpiar_']", function(){
  		if ($("table#productos tbody > tr").length >1)
  		{
  			$("table#productos  tbody > tr:last").remove();
  		}
  		calculateGrandTotal();
  	});	
 	
 	//Funcion buscar descripcion del producto
 	$("table#productos").on("change", "select[id^='descripcion_']", function(){
 		var descripcion= $(this).attr("id");
		var arr = descripcion.split('_');
		var id = $(this).val();
		var numFila =  arr[1];
 		
 		$.each(jsonProductos,function(i,item){
 			if(jsonProductos[i].idProducto == id){
 				$("input#idProducto_"+numFila).val(jsonProductos[i].claveProducto);
 			}
 				
		});
 	});
 	
 	//Funcion buscar Multiplo del producto
 	$("table#productos").on("change", "select[id^='descripcion_']", function(){
 		var descripcion= $(this).attr("id");
		var arr = descripcion.split('_');
		var id = $(this).val();
		var numFila =  arr[1];

		var $url = window.location.origin + "/General/inventario/json/multiplos/idProducto/" + id ;
		console.log($url);
		$.ajax({
			url: $url,
			dataType: "json",
			success: function(data){
			console.log($url);
			console.dir(data);
			$("select#idUnidad_"+numFila).empty();
			$.each(data, function(i,item){
				if(data[i].idProducto == id){
					$("select#idUnidad_"+numFila).append($("<option></option>").attr("value",data[i].idUnidad).text(data[i].unidad));
				}else{
					//console.log("No existe unidad");
				}	
			});
			}
		});
 	});//cierra funcion Multiplo del producto
 	
 	//Envia los valores de Impuestos a a la vista de facturaProveedor
   	$("a#generarJsonArray").on("click",function(){
 		var impuestos = [];
 		var subTotal = $("input#subTotal").val();
 		var descuento = $("input#descuento").val();
 		var iva = $("input#iva").val();
 		var total = $("input#total").val();
 		var ieps = $("input#ieps").val();
 		var ish = $("input#ish").val();
 		var isr = $("input#isr").val();
 			
 		console.log("subTotal:"+subTotal);
 		console.log("descuento:"+descuento);
 		console.log("iva:"+iva);
 		console.log("total:"+total);
 		console.log("ieps:"+ieps);
 		console.log("ish:"+ish);
 		console.log("isr:"+isr);
 			
 		impuestos.push(new Impuesto(subTotal, descuento, iva, total, ieps, ish,isr)); 
 			
 		console.dir(impuestos);
 		var myString = JSON.stringify(impuestos);
 		console.log(myString);
 		if ($("input#1-importes").val(myString)){};
 	});
 		
 	function Producto(cantidad, producto,  unidad, codigoBarras, descripcion, precioUnitario, importe) {
 		this.cantidad = cantidad;
		this.producto = producto;
		this.unidad = unidad;
		this.codigoBarras = codigoBarras;
		this.descripcion = descripcion;
		this.precioUnitario = precioUnitario;
		this.importe = importe;
	}
		
	function Impuesto(subTotal, descuento, iva, total, ieps, ish, isr) {
		this.subTotal = subTotal;
		this.descuento = descuento;
		this.iva = iva;
		this.total = total;
		this.ieps = ieps;
		this.ish = ish;
		this.isr = isr;
	}
	
    $("table#productos").on("change", 'input[id^="idCantidad_"], input[id^="costoUnitario_"]', function (event) {
        calculateRow($(this).closest("tr"));
        calculateGrandTotal();
    });
   	});
    
	function calculateRow(row) {
		var  precioUnitario= +row.find('input[id^="costoUnitario_"]').val();
    	var cantidad = +row.find('input[id^="idCantidad_"]').val();
    	row.find('input[id^="costoTotal_"]').val((cantidad * precioUnitario).toFixed(2));
	}
    
	function calculateGrandTotal() {
		var grandTotal = 0;
    	var ivaPorcentaje;
    	var total;
    	var totalIva;
    	var descuento;
    	var totalDescuento;	    
    
    	$("table#productos").find('input[id^="costoTotal_"]').each(function () {
        	grandTotal += +$(this).val();
       	});
    
    	$("#grandtotal").text(grandTotal.toFixed(2));
    	$("#subTotal").val(grandTotal.toFixed(2));
    
    	//Calcula iva
   		ivaPorcentaje= $("#ivaPorcentaje").val();
   		console.log(ivaPorcentaje);
    	totalIva =  ($("#subTotal").val() * ivaPorcentaje ) /100;
    	console.log("total iva"+totalIva);
    	$("input#iva").val(totalIva.toFixed(2));
    
    	//Total
    	total = grandTotal + totalIva;
  		ieps = $('input#ieps').val();
   		if (ieps != 0){
   			iepsIva = $("#subTotal").val() - ieps;
   			ivaIeps = iepsIva * 0.16
   			$("input#iva").val(ivaIeps);
   
   		}
    	$("input#total").val(total.toFixed(2));
    	descuento = $("#descuento").val();
   		if (descuento !=0){
   			totalIva = 0;
   			total = 0;
 			totalDescuento = grandTotal - descuento;
   			$("input#descuentoGenerado").val(totalDescuento.toFixed(2));
   			totalIva = (ivaPorcentaje * totalDescuento ) /100;
   			total = (totalDescuento * totalIva);
   			console.log("Iva con descuento :" + totalIva);
   			$("input#iva").val(totalIva.toFixed(2)); 
   			total = totalDescuento + totalIva;
   			$("input#total").val(total.toFixed(2)); 
   		}
   	}
  	//Habilita IvaPorcentaje
 		 $("#editarIva").on("click",function(){
 		 	calculateGrandTotal();
         	$("#ivaPorcentaje").removeAttr("disabled");
         	
         });
  //Edita IvaPorcentaje       
          $("#ivaPorcentaje").on("click",function(){
          	calculateGrandTotal();
          });
  //Calcula por si hay descuento       
          $("#descuento").on("click",function(){
          	calculateGrandTotal();
          });
 		
 $("select#idEmpresas").on('change', function(){
			var url = window.location.origin + "/General/sistema/json/sucursales/idFiscales/" + this.value;
			console.log(url);
			$.ajax({
				url: url,
				dataType: "json",
				success: function(data){
					console.dir(data);
					$("select#idSucursal").empty();
					$.each(data, function(i,item){	
						$("select#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal)); 
					});
					
				}
			});
		});
		
		$("select#idSucursal").on('click', function(){
			var url = window.location.origin + "/General/sistema/json/proyectos/idSucursal/" + this.value;
			console.log(url);
			$.ajax({
				url:url,
				dataType: "json",
				success: function(data){
				console.dir(data);
				$("select#idProyecto").empty();
						$.each(data, function(i,item){
							$("select#idProyecto").append($("<option></option>").attr("value",data[i].idProyecto).text(data[i].descripcion));
						});
					}
				});
		});
		
		$("#1-pagada").on("click", function(){
			var total = $("#total").val();
			console.log(total);
			if ($("#1-pagada:checked").val()==1){
				console.log("input desahabilitado");
				$("#1-pagos").attr('disabled', 'disabled');
				$("#1-pagos").val(total); 
				//calculateGrandTotal();
			}else{
				$("#1-pagos").removeAttr("disabled");
				$("#1-pagos").val(0);
				console.log("input habilitado");
			}
			
		});		
});
</script>
