<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="description" content="">
        <meta name="author" content="Hector Rodriguez">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>General Application</title>
        
        <!-- Replace favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
        <link rel="shortcut icon" href="<?php echo $this->baseUrl() ?>/public/ext/modules/encuesta/images/icono.png">
        <link rel="apple-touch-icon" href="<?php echo $this->baseUrl() ?>/public/ext/modules/encuesta/images/engranes.jpg">
        <!-- Matrix Admin Template -->
        <link rel="stylesheet" charset="UTF-8" href="<?php echo $this->baseUrl() ?>/public/ext/modules/encuesta/matrix-template/css/bootstrap.min.css" />
        <link rel="stylesheet" charset="UTF-8" href="<?php echo $this->baseUrl() ?>/public/ext/modules/encuesta/matrix-template/css/bootstrap-responsive.min.css" />
        <link rel="stylesheet" charset="UTF-8" href="<?php echo $this->baseUrl() ?>/public/ext/modules/encuesta/matrix-template/css/matrix-login.css" />
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>

    </head>
    <body>
        <?php echo $this->layout()->content; ?>
    </body>
    <script src="<?php echo $this->baseUrl() ?>/public/ext/modules/encuesta/matrix-template/js/jquery.min.js"></script>
    <script src="<?php echo $this->baseUrl() ?>/public/ext/modules/encuesta/matrix-template/js/matrix.login.js"></script>
        
</html>