<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="author" content="Hector Rodriguez">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>Sistema Encuesta</title>
        
        <!-- Replace favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
        <link rel="shortcut icon" href="<?php echo $this->baseUrl() ?>/public/ext/modules/encuesta/images/icono.png">
        <link rel="apple-touch-icon" href="<?php echo $this->baseUrl() ?>/public/ext/modules/encuesta/images/favicon.png">
        <!-- jQuery -->
        <script src="<?php echo $this->baseUrl() ?>/public/lib/jquery/jquery.min.js"></script>
        <!-- Bootstrap -->
        <link rel="stylesheet" charset="UTF-8" href="<?php echo $this->baseUrl() ?>/public/lib/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" charset="UTF-8" href="<?php echo $this->baseUrl() ?>/public/lib/bootstrap/css/bootstrap-theme.min.css" />
        <script src="<?php echo $this->baseUrl() ?>/public/lib/jquery/jquery.min.js"></script>
        <!-- Font-Awesome -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/public/lib/font-awesome/4.6.3/css/font-awesome.min.css" />
        <!-- Otros -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/public/ext/site/css/buttons.css" />
        
    </head>
    <body>
        <div class="container">
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>
