<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="Hector Rodriguez">
        
        
        <?php $public = $this->baseUrl()."/public" ?>
        <?php $creative = $this->baseUrl()."/public/lib/creative/"; ?>
        
        <link rel="shortcut icon" href="<?php echo $public; ?>/images/favicon.ico">
        <link rel="apple-touch-icon" href="<?php echo $public; ?>/images/icono.png">
        <title>PyMES</title>
        <!-- Bootstrap Core CSS -->
        <link href="<?php echo $creative; ?>vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <!-- Custom Fonts -->
        <link href="<?php echo $creative; ?>vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
        <!-- Plugin CSS -->
        <link href="<?php echo $creative; ?>vendor/magnific-popup/magnific-popup.css" rel="stylesheet">
        <!-- Theme CSS -->
        <link href="<?php echo $creative; ?>css/creative.min.css" rel="stylesheet">
        <!-- jQuery -->
        <script src="<?php echo $creative; ?>vendor/jquery/jquery.min.js"></script>
    </head>
    <body id="page-top">
        <?php echo $this->layout()->content; ?>
    </body>
    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $creative; ?>vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="<?php echo $creative; ?>vendor/scrollreveal/scrollreveal.min.js"></script>
    <script src="<?php echo $creative; ?>vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

    <!-- Theme JavaScript -->
    <script src="<?php echo $creative; ?>js/creative.min.js"></script>
</html>