<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">

		<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
		Remove this if you use the .htaccess -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

		<title>General</title>
		<meta name="description" content="">
		<meta name="author" content="Hector Rodriguez">

		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<!-- Replace favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
		<link rel="shortcut icon" href="/favicon.ico">
		<link rel="apple-touch-icon" href="/apple-touch-icon.png">
		<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/graficas.css" />
		<script src="<?php echo $this->baseUrl(); ?>/js/Chart.js"></script>
		
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/jquery.dataTables.css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/bootstrap.css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/bootstrap-theme.css" />
		
		<script src="<?php echo $this->baseUrl(); ?>/js/jquery-1.11.2.js"></script>
		<script src="<?php echo $this->baseUrl(); ?>/js/bootstrap.js"></script>
		<script src="<?php echo $this->baseUrl(); ?>/js/jquery.dataTables.min.js"></script>
		

	</head>

	<body>
		<!-- Menu principal -->
		<?php echo $this->partial("menus/principal.phtml"); ?>
		
		<div class="container">
			<?php echo $this->layout()->content; ?>
		</div>
		<script src="<?php echo $this->baseUrl(); ?>/js/panel.js"></script>
	</body>
</html>

