<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

		<title>General Application</title>
		<meta name="description" content="">
		<meta name="author" content="Hector Rodriguez">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<!-- Replace favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
		<link rel="shortcut icon" href="<?php echo $this->baseUrl() ?>/images/icono.png">
		<link rel="apple-touch-icon" href="<?php echo $this->baseUrl() ?>/images/engranes.jpg">
		
			
		<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/graficas.css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/jquery-ui.css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/jquery-ui.structure.css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/jquery-ui.theme.css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/bootstrap.min.css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/bootstrap-theme.min.css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/jquery.dataTables.min.css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/responsive.bootstrap.min.css" />
	
		<script src="<?php echo $this->baseUrl(); ?>/js/jquery-1.11.2.js"></script>
		<script src="<?php echo $this->baseUrl(); ?>/js/jquery.validate.js"></script>
		<script src="<?php echo $this->baseUrl(); ?>/js/additional-methods.js"></script>
		<script src="<?php echo $this->baseUrl(); ?>/js/jquery-ui.min.js"></script>
		<script src="<?php echo $this->baseUrl(); ?>/js/datepicker-es.js"></script>
		<script src="<?php echo $this->baseUrl(); ?>/js/bootstrap.min.js"></script>
		<script src="<?php echo $this->baseUrl(); ?>/js/jquery.dataTables.min.js"></script>
		<script src="<?php echo $this->baseUrl(); ?>/js/dataTables.bootstrap.min.js"></script>
		<script src="<?php echo $this->baseUrl(); ?>/js/dataTables.responsive.min.js"></script>
		<script src="<?php echo $this->baseUrl(); ?>/js/responsive.bootstrap.min.js"></script>
		<script src="<?php echo $this->baseUrl(); ?>/js/generartabla.js"></script>
		<script src="<?php echo $this->baseUrl(); ?>/js/Chart.js"></script>
	
		
		<style>
			body{
				padding-top: 50px;
			}
			textarea{
				resize: none;
			}
			.error{
				color: #FF7F00;
				font-family: monospace;
			}
			.optional{
				font-family: monospace;
				color: #005580;
			}
		</style>
		<script>
			$().ready(function(){
				// Opciones default de jQuery Validator
				jQuery.validator.setDefaults({
					wrapper: "div",
					errorElement: "label"
				});
				// Opciones default de ChartJS
				//Chart.defaults.global.responsive = true;
				
			});
		</script>
	</head>

	<body>
		<!-- Menu principal -->
		<?php echo $this->partial("partials/menus/principal.phtml"); ?>
		<?php
			$anchoLateral = "col-md-2";
			$anchoPrincipal = "col-md-10";
			$anchoTotal = "col-md-12";
		 ?>
		<!--Prueba -->
		<br />
		<div class="container">
			<section class="main row">
				<aside class="<?php echo $clase = (is_null($this->links)) ? "hidden" : $anchoLateral ; ?>">
					<header>
						<h3></h3>
					</header>
					<?php if (!is_null($this->links)){?>
						<?php echo $this->partial("partials/menus/menuAside.phtml", array("links" => $this->links)); ?>
					<?php } ?>
				</aside>
				<!-- Contenido Web -->
				<article class="<?php echo $clase = (is_null($this->links)) ? $anchoTotal : $anchoPrincipal ; ?>">
					<?php echo $this->layout()->content; ?>
				</article>
			</section>
		</div>
		
		<!--datepickeer-->
					<script>
			$(document).ready(function() {
			    $('#table').dataTable( {
			        "pagingType": "full_numbers"
			    } );
			} );
			$(function() { 
				$( "#fecha" ).datepicker({
					changeMonth: true,
					changeYear: true
				});
			});
			$(function() { 
				$( "#fechaInicial" ).datepicker({
					changeMonth: true,
					changeYear: true
				});
			});
			
			$(function() { 
				$( "#fechaFinal" ).datepicker({
					changeMonth: true,
					changeYear: true
				});
			});
		</script>
		<!--datepickeer-->

	</body>
</html>

