<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">

		<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
		Remove this if you use the .htaccess -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

		<title>General</title>
		<meta name="description" content="">
		<meta name="author" content="Hector Rodriguez">

		<meta name="viewport" content="width=device-width; initial-scale=1.0">

		<!-- Replace favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
		<link rel="shortcut icon" href="/favicon.ico">
		<link rel="apple-touch-icon" href="/apple-touch-icon.png">
		
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" 
		integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
		
		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" 
		integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
		
		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" 
		integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

	</head>

	<body>
		<!-- Menu principal -->
		<header style="height: 51px;">
			<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main">
							<span class="sr-only">Desplegar / Ocultar Menu</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a href="<?php echo $this->url(array("action" => "index", "controller" => "index"), null, true); ?>" class="navbar-brand">
							Applicacion General
						</a>
						
					</div>
					<div id="main" class="collapse navbar-collapse">
						<ul class="nav navbar-nav">
							<li>
								<a href="<?php echo $this->url(array("module" => "sistema", "controller" => "index", "action" => "index"), null, true) ?>">
									Sistema
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module" => "contabilidad", "controller" => "index", "action" => "index"), null, true) ?>">
									Contabilidad
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module" => "inventario", "controller" => "index", "action" => "index"), null, true) ?>">
									Inventario
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module" => "soporte", "controller" => "index", "action" => "index"), null, true) ?>">
									Soporte
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module" => "encuesta", "controller" => "index", "action" => "index"), null, true) ?>">
									Encuesta
								</a>
							</li>
						</ul>
					</div>
				</div>
			</nav>
		</header>
		<div class="container">
			<?php echo $this->layout()->content; ?>
		</div>
	</body>
</html>

