<?php echo $this->doctype(); ?>

<html>
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="description" content="">
        <meta name="author" content="Hector Rodriguez">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Pymes</title>
		
		<!-- Replace favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
		<link rel="shortcut icon" href="<?php echo $this->baseUrl() ?>/public/ext/modules/pymes/images/favicon.png">
		<link rel="apple-touch-icon" href="<?php echo $this->baseUrl() ?>/public/ext/modules/pymes/images/favicon.png">
		
		<link rel="stylesheet" charset="UTF-8" href="<?php echo $this->baseUrl() ?>/public/lib/bootstrap/css/bootstrap.min.css" />
		<link rel="stylesheet" charset="UTF-8" href="<?php echo $this->baseUrl() ?>/public/lib/bootstrap/css/bootstrap-theme.min.css" />
		
	</head>
	<?php 
	   $data = null;
	   $auth = Zend_Auth::getInstance();
       
       if($auth->hasIdentity()) $data = $auth->getIdentity();
	?>
	
	<body>
	    <div class="container-fluid">
	        <?php echo $this->layout()->content; ?>
	    </div>
	</body>
	<script charset="UTF-8" type="text/javascript" src="<?php echo $this->baseUrl() ?>/public/lib/jquery/jquery.min.js"></script>
	<script charset="UTF-8" type="text/javascript" src="<?php echo $this->baseUrl() ?>/public/lib/bootstrap/js/bootstrap.min.js"></script>
</html>

