<?php 
	$rol = $this->rol;
	$usuarios = $this->usuarios;
?>
<section class="row">
	<article>
		<header>
			<h3>
				Usuarios con el rol: <?php echo $rol->getRol(); ?>
			</h3>
		</header>
		<div>
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"usuario","action"=>"alta","idRol"=>$rol->getIdRol(),)); ?>">
				<span class="glyphicon glyphicon-plus"></span> Nuevo Usuario
			</a>
			<table class="table table-striped table-condensed">
				<tbody>
					<thead>
						<th>Usuario</th>
						<th>Creación</th>
						<th>Nombres</th>
						<th>Apellidos</th>
					</thead>
					<?php foreach ($usuarios as $usuario) : ?>
					<tr>
						<td><?php echo $usuario->getUsuario(); ?></td>
						<td><?php echo $usuario->getFecha(); ?></td>
						<td><?php echo $usuario->getNombres(); ?></td>
						<td><?php echo $usuario->getApellidos(); ?></td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</article>
</section>