<?php 
	$rol = $this->rol;
	$usuarios = $this->usuarios;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Usuarios con el rol: <strong><?php echo $rol->getRol(); ?></strong> 
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<tbody>
					<thead>
						<th>Usuario</th>
						<th>Creación</th>
						<th>Nombres</th>
						<th>Apellidos</th>
					</thead>
					<?php foreach ($usuarios as $usuario) : ?>
					<tr>
						<td><?php echo $usuario->getUsuario(); ?></td>
						<td><?php echo $usuario->getFecha(); ?></td>
						<td><?php echo $usuario->getNombres(); ?></td>
						<td><?php echo $usuario->getApellidos(); ?></td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</div>
	
</section>