<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Capa C - Grupo 6030
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<th>Materia</th>
					<th>Profesor</th>
					<th>Evaluación</th>
				</thead>
				<tbody>
					<tr>
						<td>Introducción al estudio de la economía</td>
						<td>Khalil Jalil, Ricardo</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"180"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Geografía económica</td>
						<td>Soto Hernandez, María Dolores</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"130"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Derecho</td>
						<td>Arcos Lozano, Sandra Erika	 Encuestas</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"129"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Inglés A</td>
						<td>Guerra Rosete, Claudia Virginia</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"176"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Inglés B</td>
						<td>Fortoul Blanca</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"179"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</section>