<?php
	$fiscalesEmpresas = $this->fiscalesEmpresas;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">Consulta de Clientes</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-info" href="">
				<span></span> Agregar Cliente
			</a>
			<div>
				<p>
					Seleccione Empresa
				</p>
				<select id="selectIdFiscales" class="form-control">
					<?php foreach ($fiscalesEmpresas as $fiscales) : ?>
						<option value="<?php echo $fiscales["idFiscales"]; ?>"><?php echo $fiscales["razonSocial"]; ?></option>
					<?php endforeach; ?>
				</select>
			</div><br />
			<div id="containerClientesEmpresa" class="col-xs-6">
				<ul id="clientesEmpresa" class="connectedSortable">
					<li class="ui-state-default">Item 1</li>
					<li class="ui-state-default">Item 2</li>
					<li class="ui-state-default">Item 3</li>
					<li class="ui-state-default">Item 4</li>
					<li class="ui-state-default">Item 5</li>
				</ul>
			</div>
			<div id="containerEmpresasSistema" class="col-xs-6">
				<ul id="empresasSistema" class="connectedSortable">
					<li class="ui-state-highlight">Item 1</li>
					<li class="ui-state-highlight">Item 2</li>
					<li class="ui-state-highlight">Item 3</li>
					<li class="ui-state-highlight">Item 4</li>
					<li class="ui-state-highlight">Item 5</li>
				</ul>
			</div>
		</div>
	</div>
</section>
<style>
	/* Estilos de los contenedores */
	#clientesEmpresa, #empresasSistema {
		border: 1px solid #eee;
		width: 142px;
		min-height: 20px;
		list-style-type: disc;
		margin: 0;
		padding: 5px 0 0 0;
		float: left;
		margin-right: 10px;
	}
	
	#clientesEmpresa li, #empresasSistema li {
		margin: 0 5px 5px 5px;
		padding: 5px;
		font-size: 1.2em;
		width: 120px;
	}
</style>
<script>
	$().ready(function(){
		var module = "";
		var controller = "";
		var action = "";
		console.log("Cargado!");
		
		$("select#selectIdFiscales").on('change',function(){
			
			module = "contabilidad";
			controller = "json";
			action = "clientese";
			
			console.log("Valor: " + $(this).val());
			
			$url = window.location.origin + "/General/public/"+module+"/"+controller+"/"+action+"/idFiscales/"+$(this).val();
			
			console.log($url);
		});
		
		$("table#tablaClientes");
		
		$(function(){
			$("#clientesEmpresa, #empresasSistema").sortable({
				connectWith: ".connectedSortable"
			}).disableSelection();
		});
	});
</script>