<?php
	$fiscalesDAO = new Sistema_DAO_Fiscales;
	$fiscalesEmpresas = $fiscalesDAO->getFiscalesEmpresas();
	$fiscalesProveedores = $fiscalesDAO->getFiscalesProveedores();
?>
<section class="row">
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">Asociacion de Proveedores a Empresa</h3>
		</div>
		<div class="panel-body">
			<div class="col-xs-12">
				<table class="table table-condensed table-striped">
					<tbody>
						<tr>
							<td>Seleccione Empresa</td>
							<td>
								<select id="selectIdEmpresas" class="form-control">
									<?php foreach ($fiscalesEmpresas as $fiscales) : ?>
										<option value="<?php echo $fiscales["idFiscales"]; ?>"><?php echo $fiscales["razonSocial"] ?></option>
									<?php endforeach; ?>
								</select>
							</td>
						</tr>
						<tr>
							<td>
								<button id="btnProveedor" class="btn btn-warning">
									<span class="glyphicon glyphicon-random"></span> Asociar Proveedor
								</button>
							</td>
							<td>
								<select id="selectIdProveedores" class="form-control"></select>
							</td>
						</tr>
					</tbody>
				</table><br	/><hr /><br />
				<div class="col-xs-12">
					<table id="proveedoresEmpresa" class="table table-striped table-condensed">
						<thead>
							<th>R.F.C.</th>
							<th>Razón Social</th>
						</thead>
						<tbody></tbody>
					</table>
				</div>
				
			</div>
		</div>
	</div>
</section>
<!-- Message Config -->
<div class="modal fade" id="msgConfirm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title">Confirmar Asociación.</h4>
			</div>
			
			<div class="modal-body">
				¿Esta seguro de asociar el cliente: <strong><span id="cliente"></span></strong> a la empresa: <strong><span id="empresa"></span></strong> ? 
			</div>
			
			<div class="modal-footer">
				<button id="asociarProveedorEmpresa" type="button" class="btn btn-success" data-dismiss="modal">
					<span class="glyphicon glyphicon-random"></span> Asociar
				</button>
				<button type="button" class="btn btn-danger" data-dismiss="modal">
					<span class="glyphicon glyphicon-close"></span> Cancelar
				</button>
			</div>
		</div>
	</div>
</div>
<script>
	$().ready(function(){
		
		var fiscales = <?php echo Zend_Json::encode($fiscalesDAO->getFiscalesProveedores()); ?>
		$.each(fiscales, function(i,item) {
			$("select#selectIdProveedores").append($("<option></option>").attr("value",fiscales[i].idFiscales).text(fiscales[i].razonSocial));
		});
		
		var idFiscales = $("select#selectIdFiscales").val();
		var url = window.location.origin + "/General/public/contabilidad/json/proveedorese/idFiscales/"+idFiscales;
		
		$.ajax({
			url: url,
			dataType: "json",
			success: function(data){
				//console.log(url);
				//console.dir(data);
				
				var tbody = $("table#proveedoresEmpresa").find('tbody');
				tbody.empty();
				$.each(data, function(i,item){
					tbody.append($('<tr>').
						append($('<td>').append(data[i].rfc)).
						append($('<td>').append(data[i].razonSocial))
					);
				});
			}
		});
		
		$("button#asociarCliente").on('click',function() {
			//console.log($("select#selectIdClientes option:selected ").text());
			//console.log($("select#selectIdFiscales option:selected ").text());
			$("span#proveedor").text($("select#selectIdProveedores option:selected ").text());
			$("span#empresa").text($("select#selectIdFiscales option:selected ").text());
		});
		
		$("button#asociarProveedorEmpresa").on('click',function() {
			
			var selectEmpresa = $("select#selectIdFiscales");
			var selectCliente = $("select#selectIdProveedor");
			
			module = "contabilidad";
			controller = "opera";
			action = "asocproveedore";
			
			var fempresa = selectEmpresa.val();
			var fproveedor = selectProveedor.val();
			
			//console.log(selectEmpresa.val());
			//console.log(selectCliente.val());
			
			var url = window.location.origin + "/General/public/"+ module + "/" + controller + "/" + action + "/idFiscalesEmpresa/" + fempresa + "/idFiscalesCliente/" + fcliente;
			
			console.log(url);
			
			$.ajax({
				url: url,
			});
			
		});
		
	});
</script>