<?php
	$banco = $this->banco;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"contabilidad", "controller"=>"banco", "action" => "edita", "idBanco"=>$banco->getIdBanco()), null, true));
	$tipoBanco = Zend_Registry::get("tipoBanco");
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Detalle Banco
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Cuenta</th>
						<th>Descripcion</th>
						<th>Cuenta Contable</th>
						<th>Tipo</th>
						<th>Saldo</th>
					</tr>
				</thead>
				<tbody>
	
					<tr>
						<td><?php echo $banco->getCuenta() ?></td>
						<td><?php echo $banco->getBanco() ?></td>
						<td><?php echo $banco->getCuentaContable() ?></td>
						<td><?php echo $tipoBanco[$banco->getTipo()] ?></td>
						<td><?php echo $banco->getSaldo() ?></td>
											
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Banco
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $formulario; ?>
		</div>
	</div>
	
	<div class="panel panel-danger">
		<div class="panel-heading">
			<h3 class="panel-title">
				Eliminar Banco
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-danger" href="<?php echo $this->url(array("module"=>"contabilidad","controller"=>"banco", "action"=>"baja", "idBanco"=>$banco->getIdBanco()), null, true) ?>">
				Eliminar Banco
			</a>
		</div>
	</div>
</section>