<?php
	$formulario = $this->formulario;
?>

<section class="row">	
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Asociar Banco a Empresa.</h3>
		</div>
		<div class="panel-body">
			<div class="col-xs-12">
				<?php echo $formulario; ?>
			</div>
		</div>
	</div>
	<br />
</section>
<section class="row">
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle.</h4>
		</div>
		<table id="impuestosProductos" class="table table-striped table-condensed">
			<thead>
				<th>Impuesto</th>
				<th>Producto</th>
				<th>Importe</th>
				<th>Porcentaje</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>
<script>
$(document).ready(function () {
		
		$("select#idEmpresas").on('change', function(){
			var url = window.location.origin + "/General/sistema/json/sucursales/idFiscales/" + this.value;
			console.log(url);
			$.ajax({
				url: url,
				dataType: "json",
				success: function(data){
					console.dir(data);
					$("select#idSucursal").empty();
					$.each(data, function(i,item){	
						$("select#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal)); 
					});
					
				}
			});
		});
		
		//Obtiene el valor empresa
		var idEmpresas = $("select#idEmpresas").val();
		var url = window.location.origin + "/General/contabilidad/json/bancosEmpresa/idEmpresa/"+idEmpresas;
		console.log(url);
		$.ajax({
			url: url,
			dataType: "json",
			success: function(data){
				console.log(url);
				console.dir(data);
				
				var tbody = $("table#impuestosProductos").find('tbody');
				tbody.empty();
				$.each(data, function(i,item){
					tbody.append($('<tr>').
					append($('<td>').append(data[i].descripcion)).
					append($('<td>').append(data[i].producto)).
					append($('<td>').append(data[i].importe)).
					append($('<td>').append(data[i].porcentaje))
					);
				});
			}
		});
});
</script>
