<?php
	$formulario = $this->formulario;
?>

<section class="row">	
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Asociar Banco a Empresa.</h3>
		</div>
		<div class="panel-body">
			<div class="col-xs-12">
				<?php echo $formulario; ?>
			</div>
		</div>
	</div>
	<br />
</section>
<section class="row">
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="panel-title">Detalle </h4>
		</div>
		<table id="bancosEmpresa" class="table table-striped table-condensed">
			<thead>
				<th>Empresa</th>
				<th>Sucursal</th>
				<th>Banco</th>
				
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>
<script>
$(document).ready(function () {
		
		$("select#idEmpresa").on('change', function(){
			var url = window.location.origin + "/General/sistema/json/sucursales/idFiscales/" + this.value;
			console.log(url);
			$.ajax({
				url: url,
				dataType: "json",
				success: function(data){
					console.dir(data);
					$("select#idSucursal").empty();
					$.each(data, function(i,item){	
						$("select#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal)); 
					});
					
				}
			});
			
			//Obtiene el valor empresa
			var url = window.location.origin + "/General/contabilidad/json/bancosempresa/emp/"+ this.value;
			console.log(url);
			$.ajax({
				url: url,
				dataType: "json",
				success: function(data){
				console.log(url);
				console.dir(data);
				
				var tbody = $("table#bancosEmpresa").find('tbody');
				tbody.empty();
				$.each(data, function(i,item){
					tbody.append($('<tr>').
					append($('<td>').append(data[i].banco)).
					append($('<td>').append(data[i].banco)).
					append($('<td>').append(data[i].banco))
					);
				});
			}
		});
			
		});
		
		
});
</script>
