<?php 	$bancos = $this->bancos; 
		$formulario = $this->formulario;
		$formulario->setAction($this->url(array("module"=>"contabilidad", "controller"=>"banco", "action" => "alta"), null, true));
		$tipoBanco = Zend_Registry::get("tipoBanco");
?>

<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Bancos.
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"contabilidad","controller"=>"banco","action"=>"alta")) ?>">
				<span class="glyphicon glyphicon-plus"></span> Nuevo Banco
			</a>
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Numero Banco</th>
						<th>Cuenta</th>
						<th>Banco</th>
						<th>CuentaContable</th>
						<th>Tipo</th>
						<th>Fecha</th>
						<th>Saldo</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($bancos as $banco) : ?>
					<tr>
						<td><?php echo $banco->getIdBanco() ?></td>
						<td><?php echo $banco->getCuenta() ?></td>
						<td><?php echo $banco->getBanco() ?></td>
						<td><?php echo $banco->getCuentaContable() ?></td>
						<td><?php echo $tipoBanco[$banco->getTipo()] ?></td>
							
						<td><?php echo $banco->getFecha() ?></td>
						<td><?php echo $banco->getSaldo() ?></td>
						<td>
							<a class="btn btn-warning" href="<?php echo $this->url(array("module"=>"contabilidad", "controller"=>"banco", "action" => "admin", "idBanco" => $banco->getIdBanco()), null, true); ?>">
								<span class="glyphicon glyphicon-cog"></span> Administrar
							</a>
						</td>
						<td>
							<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"contabilidad", "controller"=>"banco", "action" => "admin", "idBanco" => $banco->getIdBanco()), null, true); ?>">
								<span class="glyphicon glyphicon-cog"></span> Enlazar Empresa
							</a>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</section>




