<?php 
	$nivel = $this->nivel;
	$grado = $this->grado;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"encuesta","controller"=>"grado","action"=>"edita","idGrado"=>$grado->getIdGradoEducativo()),null,true));
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Nivel: <strong><?php echo $nivel->getNivel(); ?></strong> >> Grado: <strong><?php echo $grado->getGradoEducativo(); ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grado","action"=>"index","idNivel"=>$grado->getIdNivelEducativo()),null,true) ?>">
				<span class="glyphicon glyphicon-chevron-left"></span> Regresar al Nivel
			</a>
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"materia","action"=>"alta","idGrado"=>$grado->getIdGradoEducativo()),null,true) ?>">
				<span class="glyphicon glyphicon-plus"></span> Nueva Materia
			</a>
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grupos","action"=>"alta","idGrado"=>$grado->getIdGradoEducativo()),null,true) ?>">
				<span class="glyphicon glyphicon-plus"></span> Nuevo Grupo
			</a>
			<table class="table table-condensed table-striped">
				<thead>
					<th>Nivel</th>
					<th>Grado</th>
					<th>Materias</th>
					<th>Grupos</th>
					<th>Descripción</th>
				</thead>
				<tbody>
					<tr>
						<td><?php echo $nivel->getNivel(); ?></td>
						<td><?php echo $grado->getGradoEducativo(); ?></td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grado","action"=>"materias","idGrado"=>$grado->getIdGradoEducativo()),null,true) ?>">
								<span class="glyphicon glyphicon-search"></span> Materias
							</a>
						</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grupos","action"=>"consulta","idGrado"=>$grado->getIdGradoEducativo()),null,true) ?>">
								<span class="glyphicon glyphicon-search"></span> Grupos
							</a>
						</td>
						<td><?php echo $grado->getDescripcion(); ?></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Grado: <strong><?php echo $grado->getGradoEducativo(); ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $this->formulario; ?>
		</div>
	</div>
</section>