<?php 
	$nivel = $this->nivel;
	$messageSuccess = $this->messageSuccess;
	$messageFail = $this->messageFail;
?>
<div class="row-fluid">
    <div class="span12 widget-box">
        <div class="widget-title">
            <h5>Alta de Grado Escolar al Nivel: <strong><?php echo $nivel->getNivel() ?></strong></h5>
        </div>
        <div class="widget-content">
            <div>
                <a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grado","action"=>"index","idNivel"=>$nivel->getIdNivel()),null,true) ?>">
                    <span class="icon icon-arrow-left"></span> Regresar al Nivel <strong><?php echo $nivel->getNivel(); ?></strong>
                </a><br />
                <?php if(!is_null($messageSuccess)){ ?>
                <br />
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                    <?php echo $messageSuccess; ?>
                </div>
                <?php }elseif(!is_null($messageFail)){ ?>
                <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                    <?php echo $messageFail; ?>
                </div>
                <br />
                <?php } ?>
            </div>
            <hr />
            <div>
                <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
                    <div class="control-group">
                        <label class="control-label" for="gradoEducativo">Grado: </label>
                        <div class="controls">
                            <input class="span10" type="text" name="gradoEducativo" placeholder="Primero, Segundo, Tercero, Etc..." autofocus="" />
                        </div>
                    </div>
                    
                    <div class="control-group">
                        <label class="control-label" for="abreviatura">Simbolo: </label>
                        <div class="controls">
                            <select name="abreviatura" class="span10">
                                <?php for ($cont=1; $cont < 13; $cont++) { ?>
                                <option value="<?php echo $cont; ?>"><?php echo $cont." °"; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    
                    <div class="control-group">
                        <label class="control-label" for="descripcion">Descripción: </label>
                        <div class="controls">
                            <input class="span10" type="text" name="descripcion" placeholder="Agregue una descripción al grado" />
                        </div>
                    </div>
                    
                    <div class="form-actions">
                        <div class="pull-right">
                            <button class="btn btn-success">
                                <span class="icon icon-save"></span> Guardar
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
