<?php 
	$nivel = $this->nivel;
	$grados = $this->grados;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Grados Escolares del Nivel: <strong><?php echo $nivel->getNivel() ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"nivel","action"=>"index"),null,true) ?>">
				<span class="glyphicon glyphicon-chevron-left"></span> Regresar a los Niveles
			</a>
			
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grado","action"=>"alta","idNivel"=>$nivel->getIdNivel()),null,true) ?>">
				<span class="glyphicon glyphicon-plus"></span> Agregar Grado
			</a><br /><br />
			<table class="table table-condensed table-striped">
				<thead>
					<th>Nivel</th>
					<th>Grado</th>
					<th>Descripción</th>
					<th>Configuración</th>
				</thead>
				<tbody>
					<?php foreach ($grados as $grado) : ?>
					<tr>
						<td><?php echo $nivel->getNivel() ?></td>
						<td><?php echo $grado->getGrado() ?></td>
						<td><?php echo $grado->getDescripcion() ?></td>
						<td>
							<a class="btn btn-warning" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grado","action"=>"admin","idGrado"=>$grado->getIdGrado()),null,true) ?>">
								<span class="glyphicon glyphicon-cog"></span> Administrar
							</a>
						</td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>
			<br /><br />
		</div>
	</div>
</section>