<?php
	$grado = $this->grado;
	$materias = $this->materias;
	$formulario = $this->formulario;
	
?>
<section class="row">
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">
				Materias del Grado: <strong><?php echo $grado->getGrado(); ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grado","action"=>"admin","idGrado"=>$grado->getIdGrado()),null,true) ?>">
				<span class="glyphicon glyphicon-chevron-left"></span> Regresar al Grado: <strong><?php echo $grado->getGrado(); ?></strong>
			</a>
			<table class="table table-striped table-condensed">
				<thead>
					<th>Grado</th>
					<th>Materia</th>
				</thead>
				<tbody>
					<?php foreach ($materias as $materia) : ?>
					<tr>
						<td><?php echo $grado->getGrado() ?></td>
						<td><?php echo $materia->getMateria() ?></td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</div>
</section>