<?php
	$nivel = $this->nivel;
	$grado = $this->grado;
	$materias = $this->materias;
	$formulario = $this->formulario;
	
?>
<section class="row">
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">
				Nivel: <strong><?php echo $nivel["nivelEducativo"] ?></strong> >> Materias del Grado: <strong><?php echo $grado["gradoEducativo"]; ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grado","action"=>"admin","idGrado"=>$grado["idGradoEducativo"]),null,true) ?>">
				<span class="glyphicon glyphicon-chevron-left"></span> Regresar al Grado: <strong><?php echo $grado["gradoEducativo"]; ?></strong>
			</a>
			<table class="table table-striped table-condensed">
				<thead>
					<th>Nivel</th>
					<th>Grado</th>
					<th>Materia</th>
					<th>Créditos</th>
					<th>Fecha Creación</th>
				</thead>
				<tbody>
					<?php foreach ($materias as $materia) : ?>
					<tr>
						<td><?php echo $nivel["nivelEducativo"]; ?></td>
						<td><?php echo $grado["gradoEducativo"]; ?></td>
						<td><?php echo $materia["materiaEscolar"]; ?></td>
						<td><?php echo $materia["creditos"] ?></td>
						<td><?php echo $materia["fecha"] ?></td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</div>
</section>