<?php
	$grado = $this->grado;
	$formulario = $this->formulario;
	$materias = $this->materias;
?>
<section class="row">
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">
				Materia del Grado: <strong><?php echo $grado->getGrado(); ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $this->formulario; ?>
			
			<table class="table table-striped table-condensed">
				<thead>
					<th>Grado</th>
					<th>Materia</th>
					<th>Profesor</th>
				</thead>
				<tbody>
					<?php foreach ($materias as $materia) : ?>
					<tr>
						<td><?php echo $grado->getGrado() ?></td>
						<td><?php echo $materia->getGrado() ?></td>
						<td></td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</div>
</section>