<?php
	$libro = $this->libro;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"Biblioteca","controller"=>"libro","action"=>"edita","idLibro"=>$libro->getIdLibro(),),null,true));
?>
<!-- Consulta -->
<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">Libro: <strong><?php echo $libro->getTitulo() ?></strong></h3>
	</div>
	<div class="panel-body">
		<table class="table table-condensed table-striped">
			<thead>
				<th>Titulo</th>
				<th>Autor</th>
				<th>Editorial</th>
				<th>Número de paginas</th>
				<th>Año publicación</th>
			</thead>
			<tbody>
				<tr>
					<td><?php echo $libro->getTitulo() ?></td>
					<td><?php echo $libro->getAutor() ?></td>
					<td><?php echo $libro->getEditorial() ?></td>
					<td><?php echo $libro->getPaginas() ?></td>
					<td><?php echo $libro->getPublicado() ?></td>
				</tr>
			</tbody>
		</table>
	</div>
</section>
<!-- Edicion -->
<section class="panel panel-warning">
	<div class="panel-heading">
		<h3 class="panel-title">Editar libro: <strong><?php echo $libro->getTitulo() ?></strong></h3>
	</div>
	<div class="panel-body">
		<div>
			
		</div>
		<div>
			<?php echo $formulario; ?>
		</div>
	</div>
</section>