<?php ?>
<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title"><strong>Consulta  de libros</strong></h3>
	</div>
	<div class="panel-body">
		<div class="form-horizontal">
			<div class="form-group">
				<label for="titulo" class="control-label col-xs-2">Titulo:</label>
				<div class="col-xs-10">
					<input type="text" class="form-control"  id="titulo" placeholder="Titulo...">
				</div>
			</div>
			
			<div class="form-group">
				<label for="autor" class="control-label col-xs-2">Autor:</label>
				<div class="col-xs-10">
					<input type="text" class="form-control" id="autor" placeholder="Autor...">
				</div>
			</div>
			
			<div class="form-group">
				<label for="editorial" class="control-label col-xs-2">Editorial:</label>
				<div class="col-xs-10">
					<input type="text" class="form-control" id="editorial" placeholder="Editorial...">
				</div>
			</div>
			
			<div class="form-group">
				<div class="col-xs-offset-2 col-xs-12">
					<button id="btnBusqueda" type="button" class="btn btn-info" >
						<span class="glyphicon glyphicon-search"></span> Consultar
					</button>
				</div>
			</div>
		</div>
	</div>
</section>
<section class="panel panel-info">
	<div class="panel-heading">
		<h3 class="panel-title">Libros Encontrados</h3>
	</div>
	<div class="panel-body">
		<table id="resultadoLibros" class="table table-striped table-condensed">
			<thead>
				<th>Titulo</th>
				<th>Autor</th>
				<th>Editorial</th>
				<th>Detalles</th>
			</thead>
			<tbody></tbody>
		</table>
	</div>
</section>
<!-- Message Config -->
<div class="modal fade" id="msgDetalle" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title">Detalles de Libro</h4>
			</div>
			<div class="modal-body">
				<table class="table table-striped table-condensed" id="detalleLibro">
					<tr><td>Titulo:</td><td><strong><span id="titulo"></span></strong></td></tr>
					<tr><td>Autor:</td><td><strong><span id="autor"></span></strong>  </td></tr>
					<tr><td>Editorial:</td><td><strong><span id="editorial"></span></strong> </td></tr>
					<tr><td>Paginas:</td><td><strong><span id="paginas"></span></strong></td></tr>
					<tr><td>Año-Publicación:</td><td><strong><span id="publicacion"></span></strong> </td></tr>
				</table>
			</div>
			<div class="modal-footer">
				<a id="aConfigLibro" class="btn btn-info" href="">
					<span class="glyphicon glyphicon-cog"></span> Configurar
				</a>
				<button type="button" class="btn btn-danger" data-dismiss="modal">
					<span class="glyphicon glyphicon-close"></span> Cerrar
				</button>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/biblioteca/consultaLibro.js"></script>
