<!-- Menú de operaciones de consulta -->
<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
		Consulta
		<span class="caret"></span>
	</a>
	<ul class="dropdown-menu">
		<li>
			<a href="<?php echo $this->url(array('module' => 'consulta', 'controller' => 'movtos', 'action' => 'index'), null, true); ?>">
				Movimientos: Facturas/Remisiones
			</a>
		</li>
	</ul>
</li>