<li class="dropdown">
	<a role="button" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		Sistema
		<span class="caret"></span>
	</a>
	<ul class="dropdown-menu">
		<li>
			<a href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'rol', 'action' => 'index'), null, true); ?>">
				Roles y Usuarios
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'parametro', 'action' => 'index'), null, true); ?>">
				Parametros y Subparametros
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'estados', 'action' => 'index'), null, true); ?>">
				Estados
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'empresa', 'action' => 'alta'), null, true); ?>">
				Datos Fiscales
			</a>
		</li>
	</ul>
</li>