<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
		Sistema
		<span class="caret"></span>
	</a>
	<ul class="dropdown-menu">
		<li>
			<a href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'parametro', 'action' => 'index'), null, true); ?>">
				Parametros
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'subparametro', 'action' => 'index'), null, true); ?>">
				Subparametros
			</a>
		</li>
		
	</ul>
</li>