<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
		Sistema
		<span class="caret"></span>
	</a>
	<ul class="dropdown-menu">
		<li>
			<a href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'estados', 'action' => 'index'), null, true); ?>">
				Estados
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'empresa', 'action' => 'alta'), null, true); ?>">
				Datos Fiscales
			</a>
		</li>
	</ul>
</li>