<?php echo $this->formulario; ?>
<script>
	$(document).ready(function(){
		$("select#idEmpresas").on('change', function (){
			var url = window.location.origin + "/General/";
			console.log();
			var idEmpresa = $(this).val();
			var urlSucursal = url + "sistema/json/sucursales/idFiscales/" +this.value;
			$.ajax({
				url: urlSucursal,
				dataType: "json",
				success: function (data){
					$("select#idSucursal").empty();
					$.each(data, function (i,item){
						$("select#idSucursal").append($("<option></option>").attr("value",data[i].idSucursal).text(data[i].nombreSucursal));
					});
				}
			});
		});
		
		$("#fechaFinal").on('change', function (){
			var fechaInicio = $("#fechaInicial").val();
			if(fechaInicio > $(this).val()){
				//console.log("");
				alert('[ERROR] Fecha inicio no puede ser mayor que la fecha final');
			};		
		});
	});
</script>