<?php 
	$grupo = $this->grupo;
	$seccion = $this->seccion;
	$opciones = $this->opciones;
	$tipoOpcion = Zend_Registry::get("tiposValores");
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"encuesta", "controller"=>"grupo", "action" => "edita", "idGrupo"=>$grupo->getIdGrupoSeccion()), null, true));
	
	$t = Zend_Registry::get("tipo");
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Detalle Grupo
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-condensed">
				<thead>
					<th>Nombre</th>
					<th>Creación</th>
					<th>Orden</th>
					<th>Tipo Preguntas</th>
					<th>Preguntas</th>
				</thead>
				<tbody>
					<tr>
						<td><?php echo $grupo->getNombre(); ?></td>
						<td><?php echo $grupo->getFecha(); ?></td>
						<td><?php echo $grupo->getOrden(); ?></td>
						<td><?php echo $t[$grupo->getTipo()]; ?></td>
						<td>
							<a href="<?php echo $this->url(array("module"=>"encuesta","controller" => "grupo", "action" => "index", "idGrupo" => $grupo->getIdGrupoSeccion()), null, true) ?>" class="btn btn-info">
								<span class="glyphicon glyphicon-cog"></span>  Preguntas
							</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Grupo
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $this->formulario; ?>
		</div>
	</div>
	
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">
				Opciones del Grupo
			</h3>
		</div>
		<div class="panel-body">
			<?php 
						if(is_null($opciones)){ ?>
							Error en encuesta, este grupo no tiene opciones asociadas, no se podra generar la encuesta.
					<?php }else{ ?>
			<table class="table table-striped table-condensed">
				<thead>
					<th>Opción</th>
					<th>Tipo Valor</th>
					<th>Valor</th>
					<th>Creación</th>
				</thead>
				<tbody>
					
					<?php foreach ($opciones as $opcion) : ?>
						<tr>
							<td><?php echo $opcion->getNombreOpcion() ?></td>
							<td><?php echo $tipoOpcion[$opcion->getTipoValor()];  ?></td>
							<td><?php
								switch ($opcion->getTipoValor()) {
									case 'EN':
										echo $opcion->getValorEntero();
										break;
									case 'TX':
										echo $opcion->getValorTexto();
										break;
									case 'DC':
										echo $opcion->getValorDecimal();
										break;
								}
							?>
							</td>
							<td><?php echo $opcion->getFecha() ?></td>
						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
			<?php } ?>
		</div>
	</div>
</section>