<?php 
	$grupo = $this->grupo;
	$seccion = $this->seccion;
	//$preguntas = $this->preguntas;
	$opciones = $this->opciones;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"encuesta", "controller"=>"grupo", "action" => "edita", "idGrupo"=>$grupo->getIdGrupo()), null, true));
	
	$t = Zend_Registry::get("tipo");
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Detalle Grupo
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-condensed">
				<thead>
					<th>Nombre</th>
					<th>Creación</th>
					<th>Orden</th>
					<th>Tipo Preguntas</th>
					<th>Preguntas</th>
				</thead>
				<tbody>
					<tr>
						<td><?php echo $grupo->getNombre(); ?></td>
						<td><?php echo $grupo->getFecha(); ?></td>
						<td><?php echo $grupo->getOrden(); ?></td>
						<td><?php echo $t[$grupo->getTipo()]; ?></td>
						<td>
							<a href="<?php echo $this->url(array("module"=>"encuesta","controller" => "grupo", "action" => "index", "idGrupo" => $grupo->getIdGrupo()), null, true) ?>" class="btn btn-info">
								<span class="glyphicon glyphicon-cog"></span>  Preguntas
							</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Grupo
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $this->formulario; ?>
		</div>
	</div>
	
	<div class="panel panel-danger">
		<div class="panel-heading">
			<h3 class="panel-title">Eliminar Grupo</h3>
		</div>
		<div class="panel-body">
			<p>
				Un grupo solo se puede eliminar si esta vacío.
			</p>
			<a class="btn btn-danger" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"seccion","action"=>"baja","idGrupo"=>$grupo->getIdGrupo(),)) ?>">
				Eliminar Grupo
			</a>
			<br /><br />
		</div>
	</div>
	
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">
				Opciones del Grupo
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-success">
				Agregar Opciones
			</a>
			<a class="btn btn-warning">
				Editar Opciones
			</a>
			<a class="btn btn-danger">
				Eliminar Opciones
			</a>
			<table class="table table-striped table-condensed">
				<thead>
					<th>Opción</th>
					<th>Creación</th>
				</thead>
				<tbody>
					<?php foreach ($opciones as $opcion) : ?>
					<tr>
						<td><?php echo $opcion->getOpcion() ?></td>
						<td><?php echo $opcion->getFecha() ?></td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</div>
</section>