<?php
    $seccion = $this->seccion;
    $tiposPregunta = Zend_Registry::get("tipo");
?>
<div class="row-fluid">
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <h5>Alta de Nuevo Grupo en la Sección: <strong><?php echo $seccion->getNombre(); ?></strong></h5>
            </div>
            <div class="widget-content">
                <div>
                    <a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"seccion","action"=>"admin","id"=>$seccion->getIdSeccionEncuesta()),null,true) ?>">
                        <span class="icon icon-arrow-left"></span> Regresar a Sección
                    </a>
                </div>
                <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
                    <div class="control-group">
                        <label class="control-label" for="nombre">Nombre del grupo: </label>
                        <div class="controls">
                            <input class="span10" name="nombre" placeholder="Nombre de Grupo" />
                        </div>
                    </div>
                    
                    <div class="control-group">
                        <label class="control-label" for="tipoGrupo">Tipo de Preguntas del grupo: </label>
                        <div class="controls">
                            <select class="span10" name="tipoGrupo">
                                <?php foreach ($tiposPregunta as $key => $value) : ?>
                                <option value="<?php echo $key ?>"><?php echo $value ?></option>
                                <?php endforeach; ?>
                            </select>
                            
                        </div>
                    </div>
                    
                    <div class="form-actions">
                        <div class="pull-right">
                            <button class="btn btn-success" type="submit">
                                <span class="icon icon-plus"></span> Agregar Grupo
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
