<?php
	$subParametro = $this->subParametro;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"sistema", "controller"=>"Subparametro", "action" => "edita", "idSubparametro"=>$subParametro->getIdSubparametro()),null,true));
	
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Detalle Subpararametro: <?php echo $subParametro->getSubparametro() ?>.
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Suparametro</th>
						<th>Clave Subparametro</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><?php echo $subParametro->getSubparametro() ?></td>
						<td><?php echo $subParametro->getClaveSubparametro() ?></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Subparametro
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $formulario; ?>
		</div>
	</div>
	
	