<?php
	$producto= $this->producto;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"inventario", "controller"=>"Producto", "action" => "edita", "idProducto"=> $producto->getIdProducto()), null, true));
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Detalle Producto
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Clave Producto</th>
						<th>Descripcion</th>
						<th>Codigo de Barras</th>
					</tr>
				</thead>
				<tbody>
	
					<tr>
						<td><?php echo $producto->getclaveProducto() ?></td>
						<td><?php echo $producto->getProducto() ?></td>
						<td><?php echo $producto->getCodigoBarras() ?></td>
						
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Producto
		</div>
		<div class="panel-body">
			<?php echo $formulario; ?>
		</div>
	</div>
	
	<div class="panel panel-danger">
		<div class="panel-heading">
			<h3 class="panel-title">
				Eliminar Producto
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-danger" href="<?php echo $this->url(array("module"=>"inventario","controller"=>"producto", "action"=>"baja", "idProducto"=>$producto->getIdProducto()), null, true) ?>">
				Eliminar Producto
			</a>
		</div>
	</div>
</section>