<section class="row">
	<div>
		<?php echo $this->formulario ?>
	</div>
</section>

<script>
	$().ready(function(){
		$("select#2-unidad").on('change', function(){
			console.log(this.value);
			//Borro 
			//Obtengo las Abreviatura 
			$url = "/General/public/inventario/json/unidades/idUnidad/" + this.value;
			console.log($url);
			
			$.ajax({
				url: $url,
				dataType: "json",
				success: function(data){
					console.log($url);
					console.dir(data);
					$("select#1-abreviatura").empty();
					$.each(data, function(i,item){		
						$("select#1-abreviatura").append($("<option></option>").attr("value",data[i].idUnidad).text(data[i].unidad));
						 
					});
					
				}
			});
		});
		
	});
</script>
