<?php 
	$productos = $this->productos;
?>
<section class="row">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">
				Productos.
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"inventario","controller"=>"producto","action"=>"alta")) ?>">
				<span class="glyphicon glyphicon-plus"></span> Nuevo Producto
			</a>
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Configurar</th>
						<th>Clave Producto</th>
						<th>Descripción</th>
						<th>Codigo de Barras</th>
						<th>Multiplos</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($productos as $producto) : ?>
					<tr>
						<td>
							<a class="btn btn-warning" type="submit" href="<?php echo $this->url(array("module"=>"inventario", "controller"=>"producto", "action" => "edita", "idProducto" => $producto->getIdProducto()), null, true); ?>">
								<span class="glyphicon glyphicon-cog"></span> Configurar
							</a>
						</td>
						<td><?php echo $producto->getclaveProducto() ?></td>
						<td><?php echo $producto->getProducto() ?></td>
						<td><?php echo $producto->getCodigoBarras() ?></td>
						
						<td>
							<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"inventario", "controller"=>"multiplos", "action" => "index", "idProducto" => $producto->getIdProducto()), null, true); ?>">
								<span class="glyphicon glyphicon-equalizer"></span> Multiplos
							</a>
						</td>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</section>

<script>
	$(document).ready(function() {
		//===================================================================================
	    $('table.table').dataTable( {
	       "pagingType": "full_numbers",
	        "language": {
	        	"url": "//cdn.datatables.net/plug-ins/1.10.10/i18n/Spanish.json"
	        }
	    } );
	});
</script>
