<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Capa C - Grupo 6010
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<th>Materia</th>
					<th>Profesor</th>
					<th>Evaluación</th>
				</thead>
				<tbody>
					<tr>
						<td>Derecho</td>
						<td>Arcos Lozano Sandra Erika</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"110"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Física</td>
						<td>Newmann Coto Guillermo Patricio</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"174"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Informatica aplicada a la ciencia y la industria</td>
						<td>Ibarra Gonzalez, Tomas Alberto</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"111"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
					<tr>
						<td>Inglés A</td>
						<td>Olvera Dulce</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"encuesta","idEncuesta"=>"3","idAsignacion"=>"170"),null,true) ?>">
								<span class="glyphicon glyphicon-check"></span> Evaluar Profesor
							</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</section>