<?php 
	$modulos = $this->modulos
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Modulos.
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"contabilidad","controller"=>"guiacontable","action"=>"altamodulo")) ?>">
				<span class="glyphicon glyphicon-plus"></span> Nuevo Módulo
			</a>
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>No. Módulo</th>
						<th>Descripción</th>
						<th>Administrar</th>
						
					</tr>
				</thead>
				<tbody>
					<?php foreach ($modulos as $modulo) : ?>
					<tr>
						<td><?php echo $modulo->getIdModulo() ?></td>
						<td><?php echo $modulo->getDescripcion() ?></td>
						<td>
							<a class="btn btn-warning" href="<?php echo $this->url(array("module"=>"contabilidad", "controller"=>"guiacontable", "action" => "editamodulo", "idModulo" => $modulo->getIdModulo()), null, true); ?>">
								<span class="glyphicon glyphicon-cog"></span> Administrar
							</a>
						</td>
						
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</section>
<script>
	$(document).ready(function() {
		//===================================================================================
	    $('table.table').dataTable( {
	       "pagingType": "full_numbers",
	        "language": {
	        	"url": "//cdn.datatables.net/plug-ins/1.10.10/i18n/Spanish.json"
	        }
	    } );
	});
	
</script>
