<?php 
	$guiaContable = $this->guiaContable;
	$tiposDAO = new Sistema_DAO_Empresa;
	$moduloDAO = new Contabilidad_DAO_GuiaContable;
?>
<section class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">
				Guia Contable.
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"contabilidad","controller"=>"guiacontable","action"=>"alta")) ?>">
				<span class="glyphicon glyphicon-plus"></span> Nueva Cuenta Contable
			</a>
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"contabilidad","controller"=>"guiacontable","action"=>"adminmodulos")) ?>">
				<span class="glyphicon glyphicon-th-list"></span> Módulo
			</a>
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"contabilidad","controller"=>"guiacontable","action"=>"admintipos")) ?>">
				<span class="glyphicon glyphicon-th-list" ></span> Tipo
			</a>
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Modulo</th>
						<th>Tipo Proveedor</th>
						<th>Cuenta</th>
						<th>Descripción</th>
						<th>Configurar</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($guiaContable as $guiaCon) :
						$tipo = $tiposDAO->obtenerTipoProveedorIdTipoProveedor($guiaCon->getIdTipoProveedor());
						$modulo = $moduloDAO->obtenerModulo($guiaCon->getIdModulo());
					?>	
					<tr>
						<td><?php echo $modulo["descripcion"]; ?></td>
						<td><?php echo $tipo->getDescripcion(); ?></td>
						<td><?php echo $guiaCon->getCta(); ?></td>
						<td><?php echo $guiaCon->getDescripcion(); ?></td>
						<td>
							<a class="btn btn-warning" href="<?php echo $this->url(array("module"=>"contabilidad", "controller"=>"guiacontable", "action" => "editar","idGuiaContable"=>$guiaCon->getIdGuiaContable()), null, true); ?>">
								<span class="glyphicon glyphicon-cog"></span> Configurar
							</a>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</section>
<script>
	$(document).ready(function() {
		//===================================================================================
	    $('table.table').dataTable( {
	       "pagingType": "full_numbers",
	        "language": {
	        	"url": "//cdn.datatables.net/plug-ins/1.10.10/i18n/Spanish.json"
	        }
	    } );
	});
</script>
