<?php
    $auth = $this->auth;
    $ubicaciones = $this->ubicaciones;
    $usuarios = $this->usuarios;
?>
<?php if (!is_null($auth) && $auth->hasIdentity()) { 
    $identity = $auth->getIdentity();
    
    ?>
<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-info">
          <div class="panel-heading">
              <h5 class="panel-title">Consulta Rápida de Soporte</h5>
          </div>
          <div class="panel-body">
              <a class="btn btn-danger" href="<?php echo $this->url(array("module"=>"soporte","controller"=>"home","action"=>"logout"),null,true) ?>">
                  <span class="glyphicon glyphicon-off"></span> Terminar Consultas
              </a>
              <hr />
              <div class="form-horizontal">
                  
                  <div class="form-group">
                      <label class="col-xs-2 control-label" for="ubicacion">Ubicación: </label>
                      <div class="col-xs-10">
                          <select id="ubicacion" class="form-control" name="ubicacion">
                              <option value="0">Seleccione ubicación...</option>
                              <?php foreach ($ubicaciones as $ubicacion) : ?>
                              <option value="<?php echo $ubicacion["ubicacion"] ?>"><?php echo utf8_encode($ubicacion["ubicacion"]) ?></option>
                              <?php endforeach ?>
                          </select>
                      </div>
                  </div>
                  
                  <div class="form-group">
                      <label class="col-xs-2 control-label" for="usuario">Usuario: </label>
                      <div class="col-xs-10">
                          <select id="usuario" class="form-control" name="usuario">
                              <option value="0">Usuario...</option>
                              <?php foreach ($usuarios as $usuario) : ?>
                              <option value="<?php echo $usuario["Usuario"] ?>"><?php echo utf8_encode($usuario["Usuario"]) ?></option>
                              <?php endforeach ?>
                          </select>
                      </div>
                  </div>
                  
                  <div class="form-group">
                      <div class="col-xs-offset-2 col-xs-10">
                          <button id="btnConsult" type="button" class="btn btn-success">
                              <span class="glyphicon glyphicon-flash"></span> Consultar
                          </button>
                      </div>
                  </div>
              </div>
          </div>
        </div>
        <!-- Resultados -->
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h5 class="panel-title">Resultados de la búsqueda</h5>
            </div>
            <div class="panel-body">
                <table id="tResults" class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>Equipo</th>
                            <th>Detalles A</th>
                            <th>Detalles B</th>
                            <th>Detalles C</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<?php } else { ?>
    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h5 class="panel-title"> Consulta Rapida de Soporte </h5>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
                        <div class="form-group">
                            <label class="col-xs-2 control-label">Clave Organización:</label>
                            <div class="col-xs-10">
                                <input name="claveOrganizacion" class="form-control" type="text" placeholder="Clave_Organizacion..." required="required" autofocus="" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-offset-2 col-xs-10">
                                <button type="submit" class="btn btn-success">
                                    <span class="glyphicon glyphicon-flash"></span> Acceso
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
<?php } ?>

<script>
    $().ready(function(){
        var url = window.location.origin + "/General/";
       console.log(url); 
       
       $("button#btnConsult").on('click',function(){
           var ubicacion = $("#ubicacion").val();
           var usuario = $("#usuario").val();
           
           var pieceUbicacion = "";
           var pieceUsuario = "";
           
           if(ubicacion != "0") pieceUbicacion = "ubicacion/"+ubicacion+"/";
           if(usuario != "0") pieceUsuario = "usuario/"+usuario+"/";
           
           var urlModule = url+"soporte/json/consultaequipo/";
           var params = pieceUbicacion+pieceUsuario;
           
           //var urlQuery = urlModule+params;
           //console.log(urlQuery);
           
           if(params != ""){
               var urlQuery = urlModule+params;
               console.log(urlQuery);
               
               $.ajax({
                    url: urlQuery,
                    dataType: "json",
                    success: function(data){
                        //console.log("Respuesta del server");
                        console.dir(data);
                        var tbody = $("table#tResults").find('tbody');
                        tbody.empty();
                        $.each(data, function(i, item){
                           console.log(item);
                           
                           tbody.append($('<tr>').
                                append($('<td>').append(item["equipo"] +
                                " - " + item["noSerie"])).
                                append($('<td>').append(item["sisOperativo"])).
                                append($('<td>').append(item["procesador"])).
                                append($('<td>').append(item["versionOffice"]))
                           );
                           
                        });
                    }
                });
               
           }else{
               console.log("No se ejecuta query!!");
           }
       });
    });
</script>