<?php	
	$encuesta = $this->encuesta;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"encuesta", "controller"=>"index", "action" => "edita", "idEncuesta"=>$encuesta->getIdEncuesta()), null, true));
	//$secciones = $this->secciones;
	$seccionDAO = new Encuesta_DAO_Seccion;
	$tipo = Zend_Registry::get("tipo");
	$estatus = Zend_Registry::get("estatus");
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Detalle Encuesta
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-condensed">
				<thead>
					<th>Nombre</th>
					<th>Inicio Encuesta</th>
					<th>Término Encuesta</th>
					<th>Estatus</th>
					<th>Secciones</th>
				</thead>
				<tbody>
					<tr>
						<td><?php echo $encuesta->getNombre(); ?></td>
						<td><?php echo $encuesta->getFechaInicio(); ?></td>
						<td><?php echo $encuesta->getFechaFin(); ?></td>
						<td><?php echo $estatus[$encuesta->getEstatus()]; ?></td>
						<td>
							<a href="<?php echo $this->url(array("module"=>"encuesta","controller" => "index", "action" => "secciones", "idEncuesta" => $encuesta->getIdEncuesta()), null, true) ?>" class="btn btn-info">
								<span class="glyphicon glyphicon-cog"></span>  Secciones
							</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Encuesta
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $this->formulario; ?>
		</div>
	</div>
	
	<div class="panel panel-danger">
		<div class="panel-heading">
			<h3 class="panel-title">Finalizar Encuesta</h3>
		</div>
		<div class="panel-body">
			<p>
				Una encuesta jamás se elimina, por ejemplo, 
				usted necesita reutilizar esta encuesta cada cierto periodo, 
				lo unico que hace usted es activarla y des-activarla.
			</p>
			<p>
				Al final de su vida útil usted puede extraer una copia de los datos
				de la encuesta antes de desactivarla nuevamente.
			</p>
			<a class="btn btn-danger" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"baja","idEncuesta"=>$encuesta->getIdEncuesta(),)) ?>">
				Finalizar
			</a>
		</div>
	</div>
</section>
