<?php	
	$encuesta = $this->encuesta;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"encuesta", "controller"=>"index", "action" => "edita", "idEncuesta"=>$encuesta->getIdEncuesta()), null, true));
	//$secciones = $this->secciones;
	$seccionDAO = new Encuesta_DAO_Seccion;
	$tipo = Zend_Registry::get("tipo");
	$estatus = Zend_Registry::get("estatus");
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Detalle Encuesta: <strong><?php echo $encuesta->getNombre(); ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-condensed">
				<thead>
					<th>Nombre Clave</th>
					<th>Creación</th>
					<th>Estatus</th>
					<th>Secciones</th>
				</thead>
				<tbody>
					<tr>
						<td><?php echo $encuesta->getNombreClave(); ?></td>
						<td><?php echo $encuesta->getFecha(); ?></td>
						<td><?php echo $estatus[$encuesta->getEstatus()]; ?></td>
						<td>
							<a href="<?php echo $this->url(array("module"=>"encuesta","controller" => "index", "action" => "secciones", "idEncuesta" => $encuesta->getIdEncuesta()), null, true) ?>" class="btn btn-info">
								<span class="glyphicon glyphicon-cog"></span>  Secciones
							</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title">
				Editar Encuesta: <strong><?php echo $encuesta->getNombre(); ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<?php echo $this->formulario; ?>
		</div>
	</div>
</section>
