<?php $formulario = $this->formulario; ?>
<section class="row"><section>
	<article class="col-md-6">
		<header>
			<h3>Alta de nueva Encuesta</h3>
		</header>
		<?php echo $this->formulario; ?>
	</article>
</section>
<script>
	$().ready(function(){
		
		$("input.fechaInicio").datepicker({
			minDate: 0
		});
		
		$("input.fechaFin").datepicker({
			minDate: +1
		});
		
		jQuery.validator.setDefaults({
			debug: true,
			success: "valido",
			//animation: true,
			//placement: 'right',
			
		});
		
		var form = $("#altaEncuesta");
		form.validate({
			//errorClass: "error",
			//focusCleanup: true,
			//focusInvalid: true,
			//onkeyup: true,
			//animation: true,
			rules: {
				nombre: "required",
				nombreClave: {
					required: true,
					rangelength: [15,20],
				},
				descripcion: "required",
				fechaInicio: "required",
				fechaFin: "required"
			},
			messages: {
				nombre: "Nombre de la encuesta requerido",
				nombreClave: {
					required: "Nombre Clave de encuesta requerido",
					rangelength: "Este campo debe tener entre 15 y 20 caracteres"
				},
				descripcion: "Agregue una descripcion acerca de esta encuesta",
				fechaInicio: {
					required: "Especifique la fecha de inicio de aplicacion de esta Encuesta"
				},
				fechaFin: {
					required: "Especifique la fecha de fin de aplicacion de esta Encuesta"
				}
			}
		});
		
		//form.validate();
		
		$("#submit").click(function(){
			console.log("" + form.valid());
		});
		
		//$("form#altaEncuesta").validate();
		
	});
</script>