<?php 
	$formulario = $this->formulario;
?>
<section class="row">
	<div>
		<div>
			<?php echo $formulario ?>
		</div>
	</div>
</section>
<script>
	$().ready(function(){
		//Cambio en nivel educativo
		$("select#1-idNivel").on('change', function(){
			console.log(this.value);
			$url = "/General/public/encuesta/json/grados/idNivel/" + this.value;
			//console.log($url);
			//Actualizamos combo de grados escolares
			$.ajax({
				url: $url,
				dataType: "json",
				success: function(data){
					console.log($url);
					console.dir(data);
					$("select#1-idGrado").empty();
					$.each(data, function(i,item){//function(key,value)		
						$("select#1-idGrado").append($("<option></option>").attr("value",data[i].idGrado).text(data[i].grado)); 
					});
					//Actualizamos combo de grupos escolares
					$idCiclo = $("select#1-idCiclo").val();
					$idGrado = $("select#1-idGrado").val();
					$url = "/General/public/encuesta/json/grupos/idCiclo/" + $idCiclo + "/idGrado/" + $idGrado;
					console.log($url);
					$.ajax({
						url: $url,
						dataType: "json",
						success: function(data){
							console.log($url);
							console.dir(data);
							$("select#1-idGrupo").empty();
							$.each(data, function(i,item){//function(key,value)		
								$("select#1-idGrupo").append($("<option></option>").attr("value",data[i].idGrupo).text(data[i].grupo)); 
							});
							
						}
					});
					//==============================================>
				}
			});
			//Actualizamos combo de grupos escolares
			/*
			$idCiclo = $("select#1-idCiclo").val();
			$idGrado = $("select#1-idGrado").val();
			$url = "/General/public/encuesta/json/grupos/idCiclo/" + $idCiclo + "/idGrado/" + $idGrado;
			console.log($url);
			$.ajax({
				url: $url,
				dataType: "json",
				success: function(data){
					console.log($url);
					console.dir(data);
					$("select#1-idGrupo").empty();
					$.each(data, function(i,item){//function(key,value)		
						$("select#1-idGrupo").append($("<option></option>").attr("value",data[i].idGrupo).text(data[i].grupo)); 
					});
					
				}
			});
			*/
		});
		
		$("select#1-idGrado").on('change', function(){
			console.log(this.value);
			//Borro el contenido del select municipio
			//Obtengo los municipios del estado
			$idCiclo = $("select#1-idCiclo").val();
			console.log($idCiclo);
			$url = "/General/public/encuesta/json/grupos/idCiclo/" + $idCiclo + "/idGrado/" + this.value;
			console.log($url);
			$.ajax({
				url: $url,
				dataType: "json",
				success: function(data){
					console.log($url);
					console.dir(data);
					$("select#1-idGrupo").empty();
					$.each(data, function(i,item){//function(key,value)		
						$("select#1-idGrupo").append($("<option></option>").attr("value",data[i].idGrupo).text(data[i].grupo));
						//$("select#1-idMunicipio").append($("<option></option>").attr("value",key).text(value)); 
					});
					
				}
			});
		});
	});
</script>