<?php $formulario = $this->formulario; ?>
<section class="row"><section>
	<article class="col-md-8">
		<header>
			<h3>Alta de nueva Encuesta</h3>
		</header>
		<div id="errorContainerGeneral"></div>
		<div class="errorContainerLabel"></div>
		<?php echo $this->formulario; ?>
	</article>
</section>
<script>
	$().ready(function(){
		
		var form = $("#altaEncuesta");
		form.validate({
			rules: {
				nombre: "required",
				nombreClave: {
					required: true,
					rangelength: [15,20],
				},
				descripcion: "required",
			},
			messages: {
				nombre: "Nombre de la encuesta requerido",
				nombreClave: {
					required: "Nombre Clave de encuesta requerido",
					rangelength: "Este campo debe tener entre 15 y 20 caracteres"
				},
				descripcion: "Agregue una descripcion acerca de esta encuesta"
			}
		});
		
		$("#submit").click(function(){
			console.log("" + form.valid());
		});
		
	});
</script>