<?php $encuestas = $this->encuestas; ?>
<section class="row">
	<article class="col-xs-3 col-sm-3 col-md-3 ">
		<header>
			<h4>
				Encuestas
			</h4>
		</header>
		<div id="contenedorEncuestas">
			<table class="table table-condensed">
				<tbody>
					<tr>
						<td>
							<a type="button" class="btn btn-block btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index", "action"=>"alta"), null, true) ?>" data-toggle="modal">
								<span class="glyphicon glyphicon-plus"></span> Nueva
							</a>
						</td>
					</tr>
					<?php foreach ($encuestas as $encuesta) : ?>
					<tr>
						<td>
							<button type="button" class="btn btn-block btn-default" tipo="encuesta" claveEncuesta="<?php echo $encuesta->getIdEncuesta(); ?>">
								<span class="glyphicon glyphicon-list-alt"></span> <?php echo $encuesta->getNombreClave(); ?>
							</button>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
		
	</article>
	
	<article class="col-xs-3 col-sm-3 col-md-3">
		<header>
			<h4>Secciones</h4>
		</header>
		<div id="contenedorSecciones">
			
		</div>
	</article>
	
	<article class="col-xs-3 col-sm-3 col-md-3">
		<header>
			<h4>Grupos</h4>
		</header>
		<div id="contenedorGrupos">
			
		</div>
	</article>
	
	<article class="col-xs-3 col-sm-3 col-md-3">
		<header>
			<h4>Preguntas</h4>
		</header>
		<div id="contenedorPreguntas">
			
		</div>
	</article>
</section>

<section class="row">
	<div id="contentDet" class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">Detalles Elemento</h3>
		</div>
		<div id="detalles" class="panel-body" tipo="" claveContenedor="">
		</div>
	</div>
</section>

<script>
	$().ready(function() {
		//$urlEncuesta = "/General/public/encuesta/";
		var url = window.location.origin + "/General/public/";
		
		$("button[tipo='encuesta']").click(function() {
			console.log($(this).attr("claveEncuesta"));
			var claveEncuesta = $(this).attr("claveEncuesta");
			var claveContenedor = $("div#detalles").attr("claveContenedor");
			//$hashContainer = $("div#detalles").attr("hash");
			var tipo = "encuesta";
			var tipoContenedor = $("div#detalles").attr("tipo");
			
			if((tipo != tipoContenedor) && (claveEncuesta != claveContenedor) ){
				// Peticion AJAX para actualizar contenedor de detalles
				var urlQueryEncuesta = url + "encuesta/html/encuestadet/claveEncuesta/"+claveEncuesta; 
				$.ajax({
					url: urlQueryEncuesta,
					dataType: "html",
					success: function(data){
						$("div#detalles").html(data);
						$("div#detalles").attr("claveContenedor", claveEncuesta);
						$("div#detalles").attr("tipo", tipo);
					}
				});
				// Peticion AJAX para actualizar secciones
				var urlQuerySecciones = url + "encuesta/html/secciones/claveEncuesta/"+claveEncuesta;
				$.ajax({
					url: urlQuerySecciones,
					dataType: "html",
					success: function(data){
						$("div#contenedorSecciones").html(data);
						$("div#contenedorGrupos").html("");
						$("div#contenedorPreguntas").html("");
					}
				});
				
				
			}
			
		});
	
		$("div#contenedorSecciones").on("click", "button[tipo='seccion']", function(event) {
			console.log("En secciones");
			
			var claveSeccion = $(this).attr("claveSeccion");
			var claveContenedor = $("div#detalles").attr("claveContenedor");
			
			var tipo = "seccion";
			var tipoContenedor = $("div#detalles").attr("tipo");
			//console.log($tipo);
			//console.log($tipoContainer);
			
			if((tipo != tipoContenedor) && (claveSeccion != claveContenedor) ){
				//============================================================================================== Detalles Seccion
				//$urlDetallesSeccion = $urlEncuesta + "html/secciondet/hash/" + $hash;
				var urlQuerySeccion = url + "encuesta/html/secciondet/claveSeccion/"+claveSeccion;
				$.ajax({
					url: urlQuerySeccion,
					dataType: "html",
					success: function(data){
						$("div#detalles").html(data);
						$("div#detalles").attr("tipo", "seccion");
						$("div#detalles").attr("claveContenedor", claveSeccion);
						$("div#detalles").attr("tipo", tipo);
					}
				});
				//============================================================================================== Grupos
				//console.log("Lanzando peticion de grupos");
				//$urlGrupos = $urlEncuesta + "html/grupos/hash/" + $hash;
				//console.log($urlGrupos);
				var urlQueryGrupos = url + "encuesta/html/grupos/claveSeccion/"+claveSeccion;
				$.ajax({
					url: urlQueryGrupos,
					dataType: "html",
					success: function(data){
						$("div#contenedorGrupos").html(data);
					}
				});
				//============================================================================================== Preguntas
				//console.log("Lanzando peticion de preguntas");
				//$urlPreguntas = $urlEncuesta + "html/preguntas/hashSeccion/" + $hash;
				var urlQueryPreguntas = url + "encuesta/html/preguntas/claveSeccion/"+claveSeccion;
				$.ajax({
					url: urlQueryPreguntas,
					dataType: "html",
					success: function(data){
						$("div#contenedorPreguntas").html(data);
					}
				});
			}
			
		});
	
		$("div#contenedorGrupos").on("click", "button[tipo='grupo']", function(event) {
			console.log("En grupos");
			var claveGrupo = $(this).attr("claveGrupo");
			var claveContenedor = $("div#detalles").attr("claveContenedor");
			
			var tipo = "grupo";
			var tipoContenedor = $("div#detalles").attr("tipo");
			
			if((tipo != tipoContenedor) && (claveGrupo != claveContenedor)){
				//============================================================================================== Detalles Grupo
				$urlDetallesGrupo = $urlEncuesta + "html/grupodet/hash/" + $hash;
				var urlQueryGrupo = url + "encuesta/html/grupodet/claveGrupo/"+claveGrupo;
				$.ajax({
					url: urlQueryGrupo,
					dataType: "html",
					success: function(data){
						$("div#detalles").html(data);
						$("div#detalles").attr("claveGrupo", claveGrupo);
						$("div#detalles").attr("tipo", tipo);
					}
				});
				//============================================================================================== Preguntas
				//console.log("Lanzando peticion de preguntas");
				//$urlPreguntas = $urlEncuesta + "html/preguntas/hashGrupo/" + $hash;
				var urlPreguntasGrupo = url + "encuesta/html/preguntas/claveGrupo/" + claveGrupo;
				$.ajax({
					url: urlPreguntasGrupo,
					dataType: "html",
					success: function(data){
						$("div#contenedorPreguntas").html(data);
					}
				});
			}
		});
	
		$("div#contenedorPreguntas").on("click", "button[tipo='pregunta']", function(event) {
			console.log("En preguntas");
			var clavePregunta = $(this).attr("clavePregunta");
			var clavePadre = $(this).attr("padre");
			//$tipo = $(this).attr("tipo");
			//console.log($hash);
			
			var claveContenedor = $("div#detalles").attr("claveContenedor");
			var tipo = "grupo";
			var tipoContenedor = $("div#detalles").attr("tipo");
			
			if((tipo != tipoContenedor) && (clavePregunta != claveContenedor) ){
				//$urlDetallesPregunta = $urlEncuesta + "html/preguntadet/idPadre/"+ $hashPadre+"/tipo/"+$tipo+"/hash/"+$hash;
				var urlDetallesPregunta = url + "encuesta/html/preguntadet/idPadre/"+clavePadre+"/tipo/"+tipo+"/clavePregunta/"+clavePregunta;
				console.log(urlDetallesPregunta);
				$.ajax({
					url: urlDetallesPregunta,
					dataType: "html",
					success: function(data){
						$("div#detalles").html(data);
						//$("div#detalles").attr("tipo", "pregunta");
						$("div#detalles").attr("claveContenedor", clavePregunta);
						$("div#detalles").attr("tipo", tipo);
					}
				});
				
				
			}
			
		});
	
	});

</script>