<?php $encuestas = $this->encuestas; ?>
<section class="row">
	<article class="col-xs-3 col-sm-3 col-md-3 ">
		<header>
			<h4>
				Encuestas
			</h4>
		</header>
		<div id="contenedorEncuestas">
			<table class="table table-condensed">
				<tbody>
					<tr>
						<td>
							<a type="button" class="btn btn-block btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index", "action"=>"alta"), null, true) ?>">
								<span class="glyphicon glyphicon-plus"></span> Nueva
							</a>
						</td>
					</tr>
					<?php foreach ($encuestas as $encuesta) : ?>
					<tr>
						<td>
							<button type="button" class="btn btn-block btn-default" tipo="encuesta" claveEncuesta="<?php echo $encuesta->getIdEncuesta(); ?>" data-toggle="modal" data-target="#msgDetails">
								<?php echo $encuesta->getNombreClave(); ?>
							</button>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
		
	</article>
	
	<article class="col-xs-3 col-sm-3 col-md-3">
		<header>
			<h4>Secciones</h4>
		</header>
		<div id="contenedorSecciones">
			
		</div>
	</article>
	
	<article class="col-xs-3 col-sm-3 col-md-3">
		<header>
			<h4>Grupos</h4>
		</header>
		<div id="contenedorGrupos">
			
		</div>
	</article>
	
	<article class="col-xs-3 col-sm-3 col-md-3">
		<header>
			<h4>Preguntas</h4>
		</header>
		<div id="contenedorPreguntas">
			
		</div>
	</article>
</section>

<section class="row">
	<div id="contentDet" class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">Detalles Elemento</h3>
		</div>
		<div id="detalles" class="panel-body" tipo="" claveContenedor="">
		</div>
	</div>
</section>
<!-- Detalles -->
<div class="modal fade" id="msgDetails" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title">Detalles del elemento</h4>
			</div>
			<div class="modal-body">
				<div class="row">
					<div id="dynamicContent" class="col-xs-12" ></div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-danger" data-dismiss="modal">
					<span class="glyphicon glyphicon-close"></span> Cerrar
				</button>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/mencuesta/mainEncuesta.js"></script>