<?php
	//Reutilizamos los DAO del controller en vez de instanciar nuevos
	$encuestaDAO = $this->encuestaDAO;				//  -----> De aqui obtenemos la encuesta
	$seccionDAO = $this->seccionDAO;				//  -----> De aqui obtenemos las categorias
	$grupoDAO = $this->grupoDAO;
	$gruposDAO = $this->gruposDAO;					//  -----> De aqui obtenemos las asignaciones del docente
	$registroDAO = $this->registroDAO; 
	$asignacionDAO = new Encuesta_DAO_AsignacionGrupo;
	$preferenciaDAO = new Encuesta_DAO_Preferencia;
	$reporteDAO = new Encuesta_DAO_Reporte;
	 
	$idEncuesta = $this->idEncuesta;
	$idDocente = $this->idDocente;
	
	$page = $this->page;
	$pdf = $this->pdf;
	//===========================================================
	$encuesta = $encuestaDAO->obtenerEncuesta($idEncuesta);
	$docente = $registroDAO->obtenerRegistro($idDocente);
	
	$asignaciones = $asignacionDAO->obtenerAsignacionesDocente($idDocente);
	$secciones = $encuestaDAO->obtenerSecciones($idEncuesta);
	$categorias = array();
	foreach ($secciones as $seccion) {
		$grupos = $seccionDAO->obtenerGrupos($seccion->getIdSeccion());
		foreach ($grupos as $grupo) {
			$categorias[] = $grupo;
		}
	}
	
	//===========================================================
	$totalAlumnas = 0;
	$totalCategorias = array();
	$promedioGeneral = 0;
	
	$idReporte = $reporteDAO->agregarReporte($this->nombreArchivo);
	$imgEncabezado = Zend_Pdf_Image::imageWithPath(IMAGES_PATH . '/EncabezadoVertical_2015-2016.png');
	$page->drawImage($imgEncabezado, 50, 20, 580, 121);
	$page->drawText("Resultados de Encuesta: ".$encuesta->getNombre(), 165, 160);
	$page->drawText("Docente: ".$docente->getApellidos().", ".$docente->getNombres(), 165, 175);
	//$page->drawText("Grupo: ".$grupo->getGrupo(), 165, 190);
	$font = $this->font;
?>
<section class="row">
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">
				Resultado General de la Evaluacion: <strong><?php echo $encuesta->getNombre() ?></strong> con el docente: <strong><?php echo $docente->getApellidos().", ".$docente->getNombres() ?></strong> 
			</h3>
		</div>
		<div class="panel-body">
			<?php
				//Numero de columnas de la tabla en el reporte pdf
				$numColumnas = 2 + count($categorias);
				//Instanciamos la tabla
				$tablaPdf = new My_Pdf_Table($numColumnas);
				$encabezados = array();
				$encabezados[] = "Grupo";
				$encabezados[] = "Alumnas";
				//$encabezados = new My_Pdf_Table_HeaderRow();
			?>
			<table class="table table-striped table-condensed">
				<thead>
					<th>Grupo</th>
					<th>Alumnas</th>
					<?php foreach ($categorias as $categoria) : ?>
					<th>
						<?php 
							$encabezados[] = $categoria->getNombre();
							echo $categoria->getNombre(); ?>
					</th>
					<?php endforeach; 
						$encabezadoTabla = new My_Pdf_Table_HeaderRow($encabezados);
						$encabezadoTabla->setFont($font,10);
						$tablaPdf->addRow($encabezadoTabla);
					?>
				</thead>
				<tbody>
				<?php foreach ($asignaciones as $asignacion) : 
					//
					$erealizada = $encuestaDAO->obtenerEncuestaRealizadaPorAsignacion($asignacion["idAsignacion"]);
					$grupoEscolar = $gruposDAO->obtenerGrupo($asignacion["idGrupo"]);
					$rowTabla = new My_Pdf_Table_Row();
					$columnas = array();
					$colGrupo = new My_Pdf_Table_Column();
					$colGrupo->setText($grupoEscolar->getGrupo());
					$columnas[] = $colGrupo;
					$colAlumnas = new My_Pdf_Table_Column();
					$colAlumnas->setText($erealizada["realizadas"]);
					$columnas[] = $colAlumnas;
					?>
					<tr>
						<td><?php echo $grupoEscolar->getGrupo() ?></td>
						<td>
							<?php 
								$totalAlumnas += $erealizada["realizadas"];
								echo $erealizada["realizadas"]; 
							?>
						</td>
						<?php foreach ($categorias as $categoria) : ?>
						<td>
							<?php
								$valorMayor = $grupoDAO->obtenerValorMayorOpcion($categoria->getIdGrupo());
								$numeroPreguntas = count($grupoDAO->obtenerPreguntas($categoria->getIdGrupo()));
								$maximo = $erealizada["realizadas"] * $numeroPreguntas * $valorMayor["valor"];
								//$vMayor = $erealizada["realizadas"] * $valorMayor["valor"];
								$puntaje = $preferenciaDAO->obtenerTotalPreferenciaGrupo($categoria->getIdGrupo(), $asignacion["idAsignacion"]);
								//$puntaje = $puntaje / $erealizada["realizadas"];
								$calificacion = (10 * $puntaje) / $maximo; 
								//$calificacion = 
								echo sprintf('%.2f', $calificacion);
								//echo $puntaje;
								$totalCategorias[$categoria->getIdGrupo()][] = sprintf('%.2f', $calificacion);
								$colCategoria = new My_Pdf_Table_Column();
								$colCategoria->setText(sprintf('%.2f', $calificacion));
								$columnas[] = $colCategoria;
							?>
						</td>
						<?php endforeach; 
							$rowTabla->setColumns($columnas);
							$rowTabla->setFont($font, 8);
							$rowTabla->setBorder(My_Pdf::TOP, new Zend_Pdf_Style());
							$rowTabla->setBorder(My_Pdf::RIGHT, new Zend_Pdf_Style());
							$rowTabla->setBorder(My_Pdf::BOTTOM, new Zend_Pdf_Style());
							$rowTabla->setBorder(My_Pdf::LEFT, new Zend_Pdf_Style());
							$rowTabla->setCellPaddings(array(5, 5, 5, 5));
							
							$tablaPdf->addRow($rowTabla);
						?>
					</tr>
					
				<?php endforeach; ?>
				<?php
					$rowPromedios = new My_Pdf_Table_Row();
					$celdas = array();
					$colVacia =  new My_Pdf_Table_Column();
					$colVacia->setText("");
					$celdas[] = $colVacia;
					$colAlumnas = new My_Pdf_Table_Column();
					$colAlumnas->setText($totalAlumnas);
					$colAlumnas->setBorder(My_Pdf::TOP, new Zend_Pdf_Style());
					$colAlumnas->setBorder(My_Pdf::RIGHT, new Zend_Pdf_Style());
					$colAlumnas->setBorder(My_Pdf::BOTTOM, new Zend_Pdf_Style());
					$colAlumnas->setBorder(My_Pdf::LEFT, new Zend_Pdf_Style());
					//$colAlumnas->setCellPaddings(array(5, 5, 5, 5));
					$celdas[] = $colAlumnas;
				?>
					<tr>
						<td></td>
						<td>
							<strong>
								<?php echo $totalAlumnas; ?>
							</strong>
						</td>
						<?php foreach ($categorias as $categoria) : ?>
							<td>
								<strong>
									<?php
										$totales = $totalCategorias[$categoria->getIdGrupo()];
										$promedio = 0;
										foreach ($totales as $total) {
											$promedio +=$total;
										}
										$promedio = $promedio / count($asignaciones);
										$promedioGeneral += $promedio;
										echo sprintf('%.2f', $promedio);
										
										$colCategoria = new My_Pdf_Table_Column();
										$colCategoria->setText(sprintf('%.2f', $promedio));
										$colCategoria->setBorder(My_Pdf::TOP, new Zend_Pdf_Style());
										$colCategoria->setBorder(My_Pdf::RIGHT, new Zend_Pdf_Style());
										$colCategoria->setBorder(My_Pdf::BOTTOM, new Zend_Pdf_Style());
										$colCategoria->setBorder(My_Pdf::LEFT, new Zend_Pdf_Style());
										//$colCategoria->setCellPaddings(array(5, 5, 5, 5));
										$celdas[] = $colCategoria;
									?>
								</strong>
							</td>
						<?php endforeach;
							//print_r($celdas);
							$rowPromedios->setColumns($celdas);
							//$rowPromedios->setColumns($cols);
							$rowPromedios->setFont($font, 9);
							//$rowPromedios->setBorder(My_Pdf::TOP, new Zend_Pdf_Style());
							//$rowPromedios->setBorder(My_Pdf::RIGHT, new Zend_Pdf_Style());
							//$rowPromedios->setBorder(My_Pdf::BOTTOM, new Zend_Pdf_Style());
							//$rowPromedios->setBorder(My_Pdf::LEFT, new Zend_Pdf_Style());
							$rowPromedios->setCellPaddings(array(5, 5, 5, 5));
							$tablaPdf->addRow($rowPromedios);
						 ?>
					</tr>
				</tbody>
			</table>
			<br />
			<?php $promedioGeneral = $promedioGeneral / count($categorias) ?>
			<h4>PROMEDIO: <strong><?php echo sprintf('%.2f', $promedioGeneral) ; ?></strong> - Leyenda</h4>
			<?php 
				$page->drawText("PROMEDIO: ". sprintf('%.2f', $promedioGeneral), 165, 190);
				$page->addTable($tablaPdf, 0, 200);
				$pdf->addPage($page);
				$pdf->save();
			?>
		</div>
	</div>
</section>