<?php
	//Reutilizamos los DAO del controller en vez de instanciar nuevos
	$encuestaDAO = $this->encuestaDAO;				//  -----> De aqui obtenemos la encuesta
	$seccionDAO = $this->seccionDAO;				//  -----> De aqui obtenemos las categorias
	$grupoDAO = $this->grupoDAO;					
	$gruposDAO = $this->gruposDAO;					//  -----> De aqui obtenemos las asignaciones del docente
	$registroDAO = $this->registroDAO; 
	$asignacionDAO = new Encuesta_DAO_AsignacionGrupo;
	$preferenciaDAO = new Encuesta_DAO_Preferencia;
	$reporteDAO = new Encuesta_DAO_Reporte;
	
	$reporter = new Encuesta_Util_Reporter;
	
	$idEncuesta = $this->idEncuesta;
	$idDocente = $this->idDocente;
	
	$reporter->generarReporteGeneralEvaluacionDocente($idDocente, $idEncuesta);
	
	//===========================================================
	$encuesta = $encuestaDAO->obtenerEncuesta($idEncuesta);
	$docente = $registroDAO->obtenerRegistro($idDocente);
	
	$asignaciones = $asignacionDAO->obtenerAsignacionesDocente($idDocente);
	$secciones = $encuestaDAO->obtenerSecciones($idEncuesta);
	$categorias = array();
	foreach ($secciones as $seccion) {
		$grupos = $seccionDAO->obtenerGrupos($seccion->getIdSeccion());
		foreach ($grupos as $grupo) {
			$categorias[] = $grupo;
		}
	}
	
	//===========================================================
	$totalAlumnas = 0;
	$totalCategorias = array();
	$promedioGeneral = 0;
?>
<section class="row">
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">
				Resultado General de la Evaluacion: <strong><?php echo $encuesta->getNombre() ?></strong> con el docente: <strong><?php echo $docente->getApellidos().", ".$docente->getNombres() ?></strong> 
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<th>Grupo</th>
					<th>Alumnas</th>
					<?php foreach ($categorias as $categoria) : ?>
					<th>
						<?php 
							$encabezados[] = $categoria->getNombre();
							echo $categoria->getNombre(); ?>
					</th>
					<?php endforeach; ?>
				</thead>
				<tbody>
				<?php foreach ($asignaciones as $asignacion) : 
					$erealizada = $encuestaDAO->obtenerEncuestaRealizadaPorAsignacion($asignacion["idAsignacion"]);
					$grupoEscolar = $gruposDAO->obtenerGrupo($asignacion["idGrupo"]);
				?>
					<tr>
						<td><?php echo $grupoEscolar->getGrupo() ?></td>
						<td>
							<?php 
								$totalAlumnas += $erealizada["realizadas"];
								echo $erealizada["realizadas"]; 
							?>
						</td>
						<?php foreach ($categorias as $categoria) : ?>
						<td>
							<?php
								$valorMayor = $grupoDAO->obtenerValorMayorOpcion($categoria->getIdGrupo());
								$numeroPreguntas = count($grupoDAO->obtenerPreguntas($categoria->getIdGrupo()));
								//print_r("N.P: ".$numeroPreguntas);
								//print_r("<br />");
								//print_r("E.R: ".$erealizada["realizadas"]);
								//print_r("<br />");
								$maximo = $erealizada["realizadas"] * $numeroPreguntas * $valorMayor["valor"];
								//print_r("NoPreguntas: ".$numeroPreguntas);
								//print_r("Maximo: ".$maximo);
								//print_r("<br />");
								//$vMayor = $erealizada["realizadas"] * $valorMayor["valor"];
								$puntaje = $preferenciaDAO->obtenerTotalPreferenciaGrupo($categoria->getIdGrupo(), $asignacion["idAsignacion"]);
								//print_r("P.M: ".$maximo);
								//print_r("<br />");
								//print_r("P.O: ".$puntaje);
								//print_r("<br />");
								//$puntaje = $puntaje / $erealizada["realizadas"];
								
								if($maximo == 0){
									$calificacion = 0;
								}else{
									$calificacion = (10 * $puntaje) / $maximo;
								}
								 
								//print_r("Calif: ".sprintf('%.2f', $calificacion));
								echo sprintf('%.2f', $calificacion);
								$totalCategorias[$categoria->getIdGrupo()][] = sprintf('%.2f', $calificacion);
								$colCategoria = new My_Pdf_Table_Column();
								$colCategoria->setText(sprintf('%.2f', $calificacion));
								$columnas[] = $colCategoria;
							?>
						</td>
						<?php endforeach; ?>
					</tr>
					
				<?php endforeach; ?>
					<tr>
						<td></td>
						<td>
							<strong>
								<?php echo $totalAlumnas; ?>
							</strong>
						</td>
						<?php foreach ($categorias as $categoria) : ?>
							<td>
								<strong>
									<?php
										$totales = $totalCategorias[$categoria->getIdGrupo()];
										$promedio = 0;
										foreach ($totales as $total) {
											$promedio +=$total;
										}
										$promedio = $promedio / count($asignaciones);
										$promedioGeneral += $promedio;
										echo sprintf('%.2f', $promedio);
									?>
								</strong>
							</td>
						<?php endforeach; ?>
					</tr>
				</tbody>
			</table>
			<br />
			<?php 
				$promedioGeneral = $promedioGeneral / count($categorias);
				$resultado = ""; 
				
				if($promedioGeneral > 10){
					$resultado = "ERROR, RANGO SOBREPASADO";
				}elseif($promedioGeneral >= 8.5){
					$resultado = "EXCELENTE";
				}elseif($promedioGeneral >= 7.0){
					$resultado = "ADECUADO";
				}elseif($promedioGeneral >= 5.0){
					$resultado = "INSUFICIENTE";
				}elseif($promedioGeneral >= 4.0){
					$resultado = "DEFICIENTE";
				}
			?>
			<h4>PROMEDIO: <strong><?php echo sprintf('%.2f', $promedioGeneral) ; ?></strong> - <?php echo $resultado ?></h4>
		</div>
	</div>
</section>