<?php
	$preguntasAbiertas = $this->preguntasAbiertas;
	
	$encuesta = $this->encuesta;
	$asignacion = $this->asignacion;
	$registro = $this->registro;
	$grupo = $this->grupo;
	
	$page = $this->page;
	$pdf = $this->pdf;
	
	$encuestaDAO = new Encuesta_DAO_Encuesta;
	$seccionDAO = new Encuesta_DAO_Seccion;
	$grupoDAO = new Encuesta_DAO_Grupo;
	$preguntaDAO = new Encuesta_DAO_Pregunta;
	$reporteDAO = new Encuesta_DAO_Reporte;
	
	$preferenciaDAO = new Encuesta_DAO_Preferencia;
	
	$realizadas = $encuestaDAO->obtenerNumeroEncuestasRealizadas($encuesta->getIdEncuesta(), $asignacion["idAsignacion"]); 
	$secciones = $seccionDAO->obtenerSecciones($encuesta->getIdEncuesta());
	
	$idReporte = $reporteDAO->agregarReporte($this->nombreArchivo);
	$imgEncabezado = Zend_Pdf_Image::imageWithPath(IMAGES_PATH . '/EncabezadoVertical_2015-2016.png');
	$page->drawImage($imgEncabezado, 50, 20, 580, 121);
	$page->drawText("Resultados de Encuesta: ".$encuesta->getNombre(), 165, 160);
	$page->drawText("Docente: ".$registro->getApellidos().", ".$registro->getNombres(), 165, 175);
	$page->drawText("Grupo: ".$grupo->getGrupo(), 165, 190);
?>
<section class="row">
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">
				<strong>Preguntas Abiertas de Encuesta.</strong> 
			</h3>
		</div>
		<div class="panel-body">
			<h4>Resultados de la Encuesta: <strong><?php echo $encuesta->getNombre() ?></strong></h4>
			<h4>Grupo: <strong><?php echo $grupo->getGrupo() ?></strong></h4>
			<h4>Docente: <strong><?php echo $registro->getApellidos().", ".$registro->getNombres() ?></strong></h4>
			<h4>Alumnas: <strong><?php echo $realizadas ?></strong></h4>
			<a class="btn btn-info" target="_blank" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"reporte","idReporte"=>$idReporte),null,true) ?>">
				<span class="glyphicon glyphicon-search"></span> Informe en PDF
			</a>
			<hr />
			<h4>Preguntas Abiertas</h4>
			<?php	foreach ($preguntasAbiertas as $preguntaAbierta) : ?>
					
			<?php	endforeach; ?>
			<table class="table table-striped table-condensed">
				<th>Pregunta</th>
				<tbody>
					
				</tbody>
			</table>
			<?php 
				$promedio = 0;
				$categorias = 0;
				$cY = 0;
				foreach ($secciones as $seccion) :
					$gruposSeccion = $seccionDAO->obtenerGrupos($seccion->getIdSeccion());
					$espacio = 10;
					$eX = 60; // espacio en X
					$eY = 210; // espacio en Y
					$aY = 15;
					$tY = $eY; // total en Y
					foreach ($gruposSeccion as $grupoSeccion) :
						$categorias++;
						//$aY += 10;
						$preguntasGrupo = $grupoDAO->obtenerPreguntas($grupoSeccion->getIdGrupo());
						$opcionValorMayor = $grupoDAO->obtenerValorMayorOpcion($grupoSeccion->getIdGrupo());
						$valor = 0;
						foreach ($preguntasGrupo as $preguntaGrupo) {
							$preferencias = $preferenciaDAO->obtenerPreferenciaPregunta($preguntaGrupo->getIdPregunta(), $asignacion["idAsignacion"]);
							foreach ($preferencias as $preferencia) {
								$valor += $preferencia["total"];
							}
						}
						
						$maximo = $opcionValorMayor["valor"] * $grupoSeccion->getElementos() * $realizadas;
						$calificacion = ($valor * 10) / $maximo;
						//$total = $realizadas * $valor * $opcionValorMayor["valor"];
						print_r("Categoria: <strong>".$grupoSeccion->getNombre()."</strong><br />");
						print_r("Puntaje Máximo: <strong>".$maximo."</strong>   ");
						print_r("Puntaje Obtenido: <strong>".$valor."</strong>   ");
						print_r("Calificación: <strong>".sprintf('%.2f', $calificacion)."</strong> <br />");
						$tY += $aY;
						$page->drawText("Categoría: ".$grupoSeccion->getNombre(), $eX, $tY);
						$tY += $aY;
						$page->drawText("Puntaje Máximo: ".$maximo, $eX, $tY);
						$tY += $aY;
						$page->drawText("Puntaje Obtenido: ".$valor, $eX, $tY);
						$tY += $aY;
						$page->drawText("Calificación Categoría: ".sprintf('%.2f', $calificacion), $eX, $tY);
						$tY += 2*$aY;
						$promedio += $calificacion; 
						$cY = $tY;
						
						//$preferenciaDAO->obtenerPreferenciaGrupo($grupoSeccion->getIdGrupo());
						/*
						//$opciones = explode(",", $grupoSeccion->getOpciones());
						$opcionValorMayor = $grupoDAO->obtenerValorMayorOpcion($grupoSeccion->getIdGrupo());
						//puntaje maximo = opcion de valor mas alto * numero de preguntas * encuestas realizadas
						$maximo = $opcionValorMayor["valor"] * $grupoSeccion->getElementos() * $realizadas;
						//print_r($maximo);
						echo "<h4>".$grupoSeccion->getNombre()." >> </h4> Puntaje Máximo: " . $maximo;
						//print_r($opciones);
						echo "<br />";
						$preferenciaDAO->obtenerTotalCategoria($encuesta->getIdEncuesta(), $grupo->getIdGrupo(), $grupoSeccion->getIdGrupo());
						*/
					endforeach;
				endforeach;
				// Agregamos el promedio
				$promedio /= $categorias;
				$resultado = ""; 
				
				if($promedio > 8.5){
					$resultado = "EXCELENTE";
				}elseif($promedio > 7.0){
					$resultado = "ADECUADO";
				}elseif($promedio > 5.0){
					$resultado = "INSUFICIENTE";
				}elseif($promedio > 4.0){
					$resultado = "DEFICIENTE";
				}
				
				$page->drawText("PROMEDIO: ".sprintf('%.2f', $promedio) . " - " . $resultado, 165, $cY + 30);
				
				$pdf->addPage($page);
				$pdf->save();
				
				
				?>
				
		</div>
	</div>
</section>