<?php
	// Obtenemos la asignacion del controller
	$asignacionE = $this->asignacion;	// Array de la BD
	//print_r($asignacionE);
    //print_r("<br />");
	$encuesta = $this->encuesta;		// Objeto, viene de un DAO
	
	//print_r($asignacionE);
	//print_r("<br />");
	//print_r($encuesta);
	//print_r("<br />");
	
	$encuestaDAO = $this->encuestaDAO;
	$seccionDAO = $this->seccionDAO;
	$grupoDAO = $this->grupoDAO;
	$preguntaDAO = $this->preguntaDAO;
	
	$registroDAO = $this->registroDAO;			// Obtendremos datos del Docente a evaluar
	
	$reporteDAO = $this->reporteDAO;
	$materiaDAO = $this->materiaDAO;;		//Obtenemos datos de la materia evaluada
	$gruposDAO = $this->gruposDAO;
	
	$preferenciaDAO = $this->preferenciaDAO;
	$reporteador = $this->reporter;
	$idReporte = null;
	// ========================================================================= Obtenemos los datos de el reporte en general
	$registro = $registroDAO->obtenerRegistro($asignacionE["idRegistro"]);		// Docente
	//print_r("<br />Uno <br />");
	$materia = $materiaDAO->obtenerMateria($asignacionE["idMateriaEscolar"]);
	
	$grupoE = $gruposDAO->obtenerGrupo($asignacionE["idGrupoEscolar"]);
	$encuestasRealizadas = $encuestaDAO->obtenerEncuestaRealizadaPorAsignacion($asignacionE["idAsignacionGrupo"]);
	//$page = $this->page;
	//$pdf = $this->pdf;
	
	//print_r("<br />Dos <br />");
	//$realizadas = $encuestaDAO->obtenerNumeroEncuestasRealizadas($encuesta->getIdEncuesta(), $asignacion["idAsignacion"]);
	//$secciones = $seccionDAO->obtenerSecciones($encuesta->getIdEncuesta());
	
	$secciones = $encuestaDAO->obtenerSecciones($encuesta->getIdEncuesta());
	//print_r($secciones);
	$categorias = array();
	foreach ($secciones as $seccion) {
		$grupos = $seccionDAO->getGruposByIdSeccion($seccion->getIdSeccionEncuesta());//->obtenerGrupos($seccion->getIdSeccion());
		foreach ($grupos as $grupo) {
			$categorias[] = $grupo;
		}
	}
    $idReporte = $reporteador->generarReporteGrupalEvaluacionAsignacion($encuesta->getIdEncuesta(), $asignacionE["idAsignacionGrupo"]);
    /*
	try{
		//print_r($encuesta);
		//print_r("<br />");
		//print_r($asignacion);
		//print_r("<br />");
		$idReporte = $reporteador->generarReporteGrupalEvaluacionAsignacion($encuesta->getIdEncuesta(), $asignacionE["idAsignacionGrupo"]);
		//print_r("<br />");
		//print_r("FIN");
	}catch(Exception $ex){
		//print_r($ex);
	}
	*/
	$promedioGeneral = 0;
    //print_r("<br />Tres <br />");
?>
<div class="row-fluid">
    <div class="span12 widget-box">
        <div class="widget-title">
            <h5>Resultado Grupal de Encuesta</h5>
        </div>
        <div class="widget-content">
            <div>
                <a class="btn btn-info" target="_blank" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"repgrupal","idReporte"=>$idReporte),null,true) ?>">
                    <span class="icon icon-copy"></span> Reporte en PDF
                </a>
            </div>
            <hr />
            <div>
                <table class="table table-bordered table-striped table-condensed">
                    <thead>
                        <th>Grupo</th>
                        <th>Alumnas</th>
                        <?php foreach ($categorias as $categoria) : ?>
                        <th>
                            <?php 
                                $encabezados[] = $categoria->getNombre();
                                echo $categoria->getNombre(); ?>
                        </th>
                        <?php endforeach; ?>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <?php echo $grupoE->getGrupo() ?>
                            </td>
                            <td>
                                <?php 
                                //$totalAlumnas += $encuestasRealizadas["realizadas"];
                                echo $encuestasRealizadas["realizadas"] ?>
                            </td>
                            <?php foreach ($categorias as $categoria) : ?>
                            <td>
                                <?php
                                    $valorMayor = $grupoDAO->obtenerValorMayorOpcion($categoria->getIdGrupoSeccion());
                                    $numeroPreguntas = count($grupoDAO->getPreguntasByIdGrupo($categoria->getIdGrupoSeccion()));//->obtenerPreguntas($categoria->getIdGrupoSeccion()));
                                    //print_r("N.P: ".$numeroPreguntas);
                                    //print_r("<br />");
                                    //print_r("E.R: ".$encuestasRealizadas["realizadas"]);
                                    //print_r("<br />");
                                    $maximo = $encuestasRealizadas["realizadas"] * $numeroPreguntas * $valorMayor["valor"];
                                    //print_r("NoPreguntas: ".$numeroPreguntas);
                                    //print_r("Maximo: ".$maximo);
                                    //print_r("<br />");
                                    //$vMayor = $erealizada["realizadas"] * $valorMayor["valor"];
                                    $puntaje = $preferenciaDAO->obtenerTotalPreferenciaGrupo($categoria->getIdGrupoSeccion(), $asignacionE["idAsignacionGrupo"]);
                                    //print_r("P.M: ".$maximo);
                                    //print_r("<br />");
                                    //print_r("P.O: ".$puntaje);
                                    //print_r("<br />");
                                    //$puntaje = $puntaje / $erealizada["realizadas"];
                                    
                                    if($maximo == 0){
                                        $calificacion = 0;
                                    }else{
                                        $calificacion = (10 * $puntaje) / $maximo;
                                    }
                                    $promedioGeneral += $calificacion; 
                                    //print_r("Calif: ".sprintf('%.2f', $calificacion));
                                    echo sprintf('%.2f', $calificacion);
                                    $totalCategorias[$categoria->getIdGrupoSeccion()][] = sprintf('%.2f', $calificacion);
                                    $colCategoria = new My_Pdf_Table_Column();
                                    $colCategoria->setText(sprintf('%.2f', $calificacion));
                                    $columnas[] = $colCategoria;
                                ?>
                            </td>
                            <?php endforeach; ?>
                        </tr>
                    </tbody>
                </table>
            </div>
            <hr />
            <div>
                <?php 
                    $promedioGeneral = $promedioGeneral / count($categorias);
                    $resultado = ""; 
                    
                    if($promedioGeneral > 10){
                        $resultado = "ERROR, RANGO SOBREPASADO";
                    }elseif($promedioGeneral >= 8.5){
                        $resultado = "EXCELENTE";
                    }elseif($promedioGeneral >= 7.0){
                        $resultado = "ADECUADO";
                    }elseif($promedioGeneral >= 5.0){
                        $resultado = "INSUFICIENTE";
                    }elseif($promedioGeneral >= 4.0){
                        $resultado = "DEFICIENTE";
                    }
                ?>
                <h4>PROMEDIO: <strong><?php echo sprintf('%.2f', $promedioGeneral) ; ?></strong> - <?php echo $resultado ?></h4>
            </div>
        </div>
    </div>
</div>
<section class="row">
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">
				Resultado Grupal de Encuesta  
			</h3>
		</div>
		<div class="panel-body">
			<h4>Encuesta: <strong><?php echo $encuesta->getNombre() ?></strong></h4>
			<h5>Docente: <strong><?php echo $registro->getApellidos().", " .$registro->getNombres() ?></strong></h5>
			
			<a class="btn btn-info" target="_blank" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"repgrupal","idReporte"=>$idReporte),null,true) ?>">
				<span class="icon icon-copy"></span> Reporte en PDF
			</a>
			
			<table class="table table-bordered table-striped table-condensed">
				<thead>
					<th>Grupo</th>
					<th>Alumnas</th>
					<?php foreach ($categorias as $categoria) : ?>
					<th>
						<?php 
							$encabezados[] = $categoria->getNombre();
							echo $categoria->getNombre(); ?>
					</th>
					<?php endforeach; ?>
				</thead>
				<tbody>
					<tr>
						<td>
							<?php echo $grupoE->getGrupo() ?>
						</td>
						<td>
							<?php 
							//$totalAlumnas += $encuestasRealizadas["realizadas"];
							echo $encuestasRealizadas["realizadas"] ?>
						</td>
						<?php foreach ($categorias as $categoria) : ?>
						<td>
							<?php
								$valorMayor = $grupoDAO->obtenerValorMayorOpcion($categoria->getIdGrupoSeccion());
								$numeroPreguntas = count($grupoDAO->getPreguntasByIdGrupo($categoria->getIdGrupoSeccion()));//->obtenerPreguntas($categoria->getIdGrupoSeccion()));
								//print_r("N.P: ".$numeroPreguntas);
								//print_r("<br />");
								//print_r("E.R: ".$encuestasRealizadas["realizadas"]);
								//print_r("<br />");
								$maximo = $encuestasRealizadas["realizadas"] * $numeroPreguntas * $valorMayor["valor"];
								//print_r("NoPreguntas: ".$numeroPreguntas);
								//print_r("Maximo: ".$maximo);
								//print_r("<br />");
								//$vMayor = $erealizada["realizadas"] * $valorMayor["valor"];
								$puntaje = $preferenciaDAO->obtenerTotalPreferenciaGrupo($categoria->getIdGrupoSeccion(), $asignacionE["idAsignacionGrupo"]);
								//print_r("P.M: ".$maximo);
								//print_r("<br />");
								//print_r("P.O: ".$puntaje);
								//print_r("<br />");
								//$puntaje = $puntaje / $erealizada["realizadas"];
								
								if($maximo == 0){
									$calificacion = 0;
								}else{
									$calificacion = (10 * $puntaje) / $maximo;
								}
								$promedioGeneral += $calificacion; 
								//print_r("Calif: ".sprintf('%.2f', $calificacion));
								echo sprintf('%.2f', $calificacion);
								$totalCategorias[$categoria->getIdGrupoSeccion()][] = sprintf('%.2f', $calificacion);
								$colCategoria = new My_Pdf_Table_Column();
								$colCategoria->setText(sprintf('%.2f', $calificacion));
								$columnas[] = $colCategoria;
							?>
						</td>
						<?php endforeach; ?>
					</tr>
				</tbody>
			</table>
			<br />
			<?php 
				$promedioGeneral = $promedioGeneral / count($categorias);
				$resultado = ""; 
				
				if($promedioGeneral > 10){
					$resultado = "ERROR, RANGO SOBREPASADO";
				}elseif($promedioGeneral >= 8.5){
					$resultado = "EXCELENTE";
				}elseif($promedioGeneral >= 7.0){
					$resultado = "ADECUADO";
				}elseif($promedioGeneral >= 5.0){
					$resultado = "INSUFICIENTE";
				}elseif($promedioGeneral >= 4.0){
					$resultado = "DEFICIENTE";
				}
			?>
			<h4>PROMEDIO: <strong><?php echo sprintf('%.2f', $promedioGeneral) ; ?></strong> - <?php echo $resultado ?></h4>
		</div>
	</div>
</section>