<?php
	$asignacion = $this->asignacion;
	$encuesta = $this->encuesta;
	//$registro = $this->registro;
	//$grupo = $this->grupo;
	//$materia = $this->materia;
	//$page = $this->page;
	//$pdf = $this->pdf;
	
	$encuestaDAO = $this->encuestaDAO;
	$seccionDAO = $this->seccionDAO;
	$grupoDAO = $this->grupoDAO;
	$preguntaDAO = $this->preguntaDAO;
	$reporteDAO = new Encuesta_DAO_Reporte;
	
	$preferenciaDAO = new Encuesta_DAO_Preferencia;
	$reporteador = new Encuesta_Util_Reporter;
	$idReporte = null;
	
	$realizadas = $encuestaDAO->obtenerNumeroEncuestasRealizadas($encuesta->getIdEncuesta(), $asignacion["idAsignacion"]);
	$secciones = $seccionDAO->obtenerSecciones($encuesta->getIdEncuesta());
	try{
		//print_r($encuesta);
		//print_r("<br />");
		//print_r($asignacion);
		//print_r("<br />");
		$idReporte = $reporteador->generarReporteGrupalEvaluacionAsignacion($encuesta->getIdEncuesta(), $asignacion["idAsignacion"]);
		//print_r("<br />");
		//print_r("FIN");
	}catch(Exception $ex){
		print_r($ex);
	}
?>
<section class="row">
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">
				<strong>Resultados Grupales de Encuesta.</strong> 
			</h3>
		</div>
		<div class="panel-body">
			
		</div>
	</div>
</section>