<?php
	$asignacion = $this->asignacion;
	$preguntas = $this->preguntas;
	$encuesta = $this->encuesta;
	$docente = $this->docente;
	$grupo = $this->grupo;
	
	$grupoDAO = new Encuesta_DAO_Grupo;
	$seccionDAO = new Encuesta_DAO_Seccion;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Resultados de la Encuesta: <strong><?php echo $encuesta->getNombre() ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<h4>Grupo: <?php echo $grupo->getGrupo() ?></h4>
			<h4>Docente: <?php echo $docente->getApellidos().", ".$docente->getNombres() ?></h4>
			<br />
			<a class="btn btn-info">
				<span class="glyphicon glyphicon-cog"></span> Informe de Grupo
			</a><br />
			<table class="table table-striped table-condensed">
				<thead>
					<th>Categoria</th>
					<th>Pregunta</th>
					<th>Preferencia</th>
				</thead>
				<tbody>
					<?php foreach ($preguntas as $pregunta) : ?>
					<tr>
						<td>
							<?php if ($pregunta->getOrigen() == "G") echo $grupoDAO->getGrupoById($pregunta->getIdOrigen())->getNombre() ?>
							<?php if ($pregunta->getTipo() == "AB") echo "Pregunta Abierta" ?>
						</td>
						<td><?php echo $pregunta->getNombre() ?></td>
						<td>
							<?php if ($pregunta->getTipo() != "AB"){  ?>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"pregunta","action"=>"grafica","idPregunta"=>$pregunta->getIdPregunta(),"idAsignacion"=>$asignacion["idAsignacion"]),null,true) ?>">
								<span class="glyphicon glyphicon-stats"></span> Gráfico
							</a>
							<?php }else{ ?>
							<a class="btn btn-link" href="<?php echo $this->url(array(),null,true) ?>">
								Lista Respuestas
							</a>
							<?php } ?>
						</td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</div>
</section>