<?php 
	$encuesta = $this->encuesta;
	$secciones = $this->secciones;
	$formulario = $this->formulario;
?>
<section class="row">
	<article>
		<header>
			<h3>Secciones de la Encuesta: <?php echo $encuesta->getNombre() ?></h3>
		</header>
		<div>
			<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"index"), null, true) ?>">
				<span class="glyphicon glyphicon-chevron-left"></span> Regresar a Encuestas
			</a>
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"seccion","action"=>"alta","idEncuesta"=>$encuesta->getIdEncuesta(),), null, true) ?>">
				<span class="glyphicon glyphicon-plus"></span> Nueva Sección
			</a>
			<table class="table table-striped table-condensed">
				<thead>
					<th>Sección</th>
					<th>Creación</th>
					<th>Orden</th>
					<th>Elementos</th>
				</thead>
				<tbody>
					<?php foreach ($secciones as $seccion) : ?>
					<tr>
						<td><?php echo $seccion->getNombre() ?></td>
						<td><?php echo $seccion->getFecha() ?></td>
						<td><?php echo $seccion->getOrden() ?></td>
						<td>
							<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"seccion","action"=>"index","idSeccion"=>$seccion->getIdSeccion(),), null, true); ?>">
								<span class="glyphicon glyphicon-th"></span> Elementos
							</a>
						</td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</article>
</section>