<section class="row">
	<div>
		<div>
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"alta",),null,true) ?>">
				Alta Encuesta Simple
			</a>
			<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"altae",),null,true) ?>">
				Alta Encuesta Evaluativa
			</a>
		</div>
	</div>
</section>