<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Tipos de Encuestas
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<th>Tipo Encuesta.</th>
					<th>Descripción</th>
				</thead>
				<tbody>
					<tr>
						<td>
							<a class="btn btn-block btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"alta",),null,true) ?>">
								Alta Encuesta Simple.
							</a>
						</td>
						<td>
							Crear una Encuesta Simple.
						</td>
					</tr>
					<tr>
						<td>
							<a class="btn btn-block btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"altae",),null,true) ?>">
								Alta Encuesta Evaluativa.
							</a>
						</td>
						<td>
							Crear una Encuesta Evaluativa de Grupo.
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</section>