<?php 	$email= $this->email; 
		$formulario = $this->formulario;
		$formulario->setAction($this->url(array("module"=>"sistema", "controller"=>"email", "action" => "edita", "idEmail"=>$email->getIdEmail()), null, true));
?>
<section class="row">
	<article>
		<header>
			<h3>
				Detalle Email: <?php echo $email->getEmail(); ?>
			</h3>
		</header>
		
		<table class="table table-striped table-condensed">
			<thead>
				<tr>
					<th>Numero Email</th>
					<th>Email</th>
				</tr>
			</thead>
			<tbody>

				<tr>
					<td><?php echo $email->getIdEmail() ?></td>
					<td><?php echo $email->getEmail() ?></td>
				</tr>
			</tbody>
		</table>
	</article>
</section>
<section class="row">
	<article class="col-md-6" style="background-color: #87CEEB">
		<header>
			<h3>Editar</h3>
		</header>
		<?php echo $formulario; ?>
	</article>
	<article class="col-md-6" style="background-color: #FF6347">
		<header>
			<h3>Eliminar</h3>
		</header>
		<a class="btn btn-danger" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"email", "action"=>"baja", "idEmail"=>$email->getIdEmail()), null, true) ?>">
			Eliminar Email
		</a>
		<br /><br />
	</article>
</section>