<?php
	$fiscales = $this->fiscales;
	$formulario = $this->formulario;
	$emails = $this->emails;
	$tipoTelefono = Zend_Registry::get("tipoTelefono");
?>
<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"empresas","action"=>"admin","idFiscales"=>$fiscales->getIdFiscales())) ?>">
	<span class="glyphicon glyphicon-chevron-left"></span> Regresar a Empresa
</a>
<br /><br />
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Emails de: <strong><?php echo $fiscales->getRazonSocial() ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped table-condensed">
				<thead>
					<th>Email</th>
					<th>Creación</th>
					<th>Descripción</th>
					<th>Configuración</th>
				</thead>
				<tbody>
					<?php foreach ($emails as $email) : ?>
					<tr>
						<td><?php echo $email->getEmail(); ?></td>
						<td><?php echo $email->getFecha(); ?></td>
						<td><?php echo $email->getDescripcion(); ?></td>
						<td>
							<a class="btn btn-warning" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"email","action"=>"admin","idEmail"=>$email->getIdEmail())) ?>">
								<span></span> Administrar
							</a>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
	
</section>
