<?php 	$emails = $this->emails; 
		$formulario = $this->formulario;
		$formulario->setAction($this->url(array("module"=>"sistema", "controller"=>"email", "action" => "alta"), null, true));
?>
<section class="row">
	<article>
		<header>
			<h3>
				Email  de alta en el sistema.
			</h3>
		</header>
		<?php echo $formulario; ?>
		<table class="table table-striped table-condensed">
			<thead>
				<tr>
					<th>Numero Email</th>
					<th>Email</th>
				</tr>
			</thead>
			<tbody>
					<?php foreach ($emails as $email): ?>
				<tr>
					<td><?php echo $email->getIdEmail() ?></td>
					<td><?php echo $email->getEmail() ?></td>
					<td>
						<a class="btn btn-block btn-warning" href="<?php echo $this->url(array("module"=>"sistema", "controller"=>"email", "action" => "admin", "idEmail" => $email->getIdEmail()), null, true); ?>">
							Administrar
						</a>
					</td>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</article>
</section>



	
