<?php
	$empresas = $this->empresas;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Empresas
			</h3>
		</div>
		<div class="panel-body">
			<table class="table table-condensed table-striped">
				<thead>
					<th>RFC</th>
					<th>Razon social</th>
					<th>Inventario</th>
				</thead>
				<tbody>
					<?php foreach ($empresas as $empresa) : ?>
						<tr>
							<td><?php echo $empresa["rfc"]; ?></td>
							<td><?php echo $empresa["razonSocial"] ?></td>
							<td>
								<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"inventario","controller"=>"inventario","action"=>"iempresa", "idFiscales"=>$empresa["idFiscales"]),null,true) ?>">
									<span class="glyphicon glyphicon-cog"></span> Inventario
								</a>
							</td>
						</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</div>
</section>