<?php 
	$formulario = $this->formulario;
	$fiscal = $this->fiscal;
	$messageFail = $this->messageFail;
	$messageSuccess = $this->messageSuccess;
?>
<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Alta de Sucursal en Empresa: <strong><?php echo $fiscal->getRazonSocial() ?></strong> 
		</h3>
	</div>
	<div class="panel-body">
		<a class="btn btn-info" href="<?php echo $this->url(array(""=>"",""=>"",""=>"",""=>"",),null,true) ?>">
			<span class="glyphicon glyphicon-chevron-left"></span> Regresar a Sucursales de la Empresa
		</a>
		<?php echo $formulario; ?>
	</div>
</section>
<script>
	$().ready(function(){
		$("select#1-idEstado").on('change', function(){
			console.log(this.value);
			//Borro el contenido del select municipio
			//Obtengo los municipios del estado
			$url = "/General/public/sistema/json/municipios/idEstado/" + this.value;
			console.log($url);
			$.ajax({
				url: $url,
				dataType: "json",
				success: function(data){
					console.log($url);
					console.dir(data);
					$("select#1-idMunicipio").empty();
					$.each(data, function(i,item){//function(key,value)		
						$("select#1-idMunicipio").append($("<option></option>").attr("value",data[i].idMunicipio).text(data[i].municipio));
						//$("select#1-idMunicipio").append($("<option></option>").attr("value",key).text(value)); 
					});
					
				}
			});
		});
		
	});
</script>