<?php 
	$vendedores = $this->vendedores;
	$empresaDAO = new Sistema_DAO_Empresa;
?>
<section class="panel panel-success">
	<div class="panel-heading">
		<h3 class="panel-title">
			Vendedores
		</h3>
	</div>
	<div class="panel-body">
		<a class="btn btn-success" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"vendedores","action"=>"alta",),null,true) ?>">
			<span class="glyphicon glyphicon-plus"></span> Nuevo Vendedor
		</a>
		<br /><br />
		<table class="table table-striped table-condensed">
			<thead>
				<th>Clave Vendedor</th>
				<th>Nombre</th>
				<th>Estatus</th>
				<th>Fecha Alta</th>
				<th>Administrar</th>
			</thead>
			<tbody>
				<?php foreach ($vendedores as $vendedor) : ?>
				<tr>
					<td><?php echo $vendedor->getClaveVendedor() ?></td>
					<td><?php echo $vendedor->getNombre() ?></td>
					<td><?php echo $vendedor->getEstatus() ?></td>
					<td><?php echo $vendedor->getFechaAlta() ?></td>
					<td>
						<a class="btn btn-warning" href="<?php echo $this->url(array("module"=>"sistema","controller"=>"Vendedores","action"=>"editar","idVendedor"=>$vendedor->getIdVendedor()),null,true) ?>">
							<span class="glyphicon glyphicon-cog"></span> Administrar Vendedor
						</a>
					</td>
				</tr>
				<?php endforeach ?>
			</tbody>
		</table>
	</div>
</section>
<script>
	$(document).ready(function() {
		//===================================================================================
	    $('table.table').dataTable( {
	       "pagingType": "full_numbers",
	        "language": {
	        	"url": "//cdn.datatables.net/plug-ins/1.10.10/i18n/Spanish.json"
	        }
	    } );
	} );
</script>